-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import Mathlib
import SigGolfCandidate.Packed.Radix12Bundle04

-- BEGIN Radix12SplitSearchFirst from /tmp/Radix12SplitSearchFirst.lean
section

namespace Radix12SplitSearchFirst
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImage
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 28)),
   (15 + 28, (expandTail.drop 28).take 9),
   (15 + 37, expandTail.drop 37)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel

theorem codeAt_search9 :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
      ((expandTail.drop 28).take 9) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)

sym_block search9 := symRun {} ((expandTail.drop 28).take 9)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 28))) 15

theorem search9_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
    (ho : search9.res.obligs s) :
    Steps expandImage s search9.res.steps search9.res.cycles
      (search9.res.toState s) :=
  symRun_sound search9 codeAt_search9 s hpc ho

#print axioms search9_steps
end Radix12SplitSearchFirst
end
-- END Radix12SplitSearchFirst

-- BEGIN Radix12SplitSearchMid from /tmp/Radix12SplitSearchMid.lean
section

namespace Radix12SplitSearchMid
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchFirst

theorem search9_midpoint (s : MachineState) (lo hi : Nat)
    (hlo : s.getReg .x14 = BitVec.ofNat 64 lo)
    (hhi : s.getReg .x13 = BitVec.ofNat 64 hi)
    (hbound : lo + hi < 2 ^ 64) :
    (search9.res.toState s).getReg .x15 =
      BitVec.ofNat 64 ((lo + hi) / 2) := by
  simp only [Result.toState_getReg, search9.res, rv_simp]
  rw [hlo, hhi]
  apply BitVec.eq_of_toNat_eq
  simp only [BitVec.toNat_ushiftRight, Nat.shiftRight_eq_div_pow,
    BitVec.toNat_add, BitVec.toNat_ofNat]
  have hlo64 : lo < 2 ^ 64 := by omega
  have hhi64 : hi < 2 ^ 64 := by omega
  simp only [Nat.mod_eq_of_lt hlo64, Nat.mod_eq_of_lt hhi64,
    Nat.mod_eq_of_lt hbound]
  norm_num
  omega

#print axioms search9_midpoint
end Radix12SplitSearchMid
end
-- END Radix12SplitSearchMid

-- BEGIN Radix12SplitTableAddr from /tmp/Radix12SplitTableAddr.lean
section

namespace Radix12SplitTableAddr

theorem table_addr_arith (k mid : Nat)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hm : mid < 385) :
    (((BitVec.ofNat 64 k - 1#64) *
        BitVec.ofNat 64 385 + BitVec.ofNat 64 mid) <<< 3) +
        BitVec.ofNat 64 0xffc3d0 =
      BitVec.ofNat 64 (0xffc3d0 + 8 * ((k - 1) * 385 + mid)) := by
  rw [BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk,
    BitVec.shiftLeft_eq_mul_twoPow]
  have hpow : BitVec.twoPow 64 3 = BitVec.ofNat 64 8 := by decide
  rw [hpow]
  simp only [← BitVec.ofNat_mul, ← BitVec.ofNat_add]
  congr 1
  omega

#print axioms table_addr_arith
end Radix12SplitTableAddr
end
-- END Radix12SplitTableAddr

-- BEGIN Radix12ChooseBound64 from /tmp/Radix12ChooseBound64.lean
section

namespace Radix12ChooseBound64

theorem choose_lt64 (n k : Nat) (hn : n < 385) (hk : k ≤ 5) :
    n.choose k < 2 ^ 64 := by
  have hpow : n ^ k ≤ 384 ^ 5 := by
    gcongr <;> omega
  exact lt_of_le_of_lt ((Nat.choose_le_pow n k).trans hpow) (by norm_num)

#print axioms choose_lt64
end Radix12ChooseBound64
end
-- END Radix12ChooseBound64

-- BEGIN Radix12SplitSearchAddr from /tmp/Radix12SplitSearchAddr.lean
section

namespace Radix12SplitSearchAddr
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchFirst
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem search9_addr (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    (search9.res.toState s).getReg .x25 =
      BitVec.ofNat 64 (0xffc3d0 + 8 * ((k - 1) * 385 + (lo + hi) / 2)) := by
  have hbound : lo + hi < 2 ^ 64 := by omega
  have hmid := Radix12SplitSearchMid.search9_midpoint s lo hi h14 h13 hbound
  simp only [Result.toState_getReg, search9.res, rv_simp] at hmid ⊢
  rw [h11, h27, h13, h14, h2]
  rw [h13, h14] at hmid
  rw [hmid]
  simpa only [show ((3#64).toNat % 64) = 3 by decide] using
    (Radix12SplitTableAddr.table_addr_arith k ((lo + hi) / 2)
      hk hk5 (by omega))

theorem search9_x20_mem (s : MachineState) :
    (search9.res.toState s).getReg .x20 =
      s.getMem ((search9.res.toState s).getReg .x25) := by
  simp only [Result.toState_getReg, search9.res, rv_simp]

theorem search9_choose (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hmem : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    (search9.res.toState s).getReg .x20 =
      BitVec.ofNat 64 (Nat.choose ((lo + hi) / 2) k) := by
  let mid := (lo + hi) / 2
  let i := (k - 1) * 385 + mid
  have hmid : mid < 385 := by dsimp [mid]; omega
  have hi' : i < 5 * 385 := by dsimp [i]; omega
  have himod : i % 385 = mid := by dsimp [i]; omega
  have hidiv : i / 385 + 1 = k := by dsimp [i]; omega
  rw [search9_x20_mem,
    search9_addr s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi]
  change s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) = _
  rw [hmem i hi', himod, hidiv]

theorem search9_pc (s : MachineState) :
    (search9.res.toState s).pc =
      if BitVec.ult (s.getReg .x10) ((search9.res.toState s).getReg .x20) then
        BitVec.ofNat 64 4312 else BitVec.ofNat 64 4304 := by
  simp only [Result.toState_pc, Result.toState_getReg, search9.res, rv_simp]

theorem search9_pc_nat (s : MachineState) (k lo hi rank : Nat)
    (h10 : s.getReg .x10 = BitVec.ofNat 64 rank)
    (hrank : rank < 2 ^ 64)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hmem : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    (search9.res.toState s).pc =
      if rank < Nat.choose ((lo + hi) / 2) k then
        BitVec.ofNat 64 4312 else BitVec.ofNat 64 4304 := by
  have hmid : (lo + hi) / 2 < 385 := by omega
  have hchoose : Nat.choose ((lo + hi) / 2) k < 2 ^ 64 :=
    Radix12ChooseBound64.choose_lt64 _ _ hmid hk5
  rw [search9_pc, h10,
    search9_choose s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi hmem]
  simp only [BitVec.ult_eq_decide_lt]
  have hiff : (BitVec.ofNat 64 rank <
      BitVec.ofNat 64 (Nat.choose ((lo + hi) / 2) k)) ↔
      rank < Nat.choose ((lo + hi) / 2) k := by
    simp only [BitVec.lt_def, BitVec.toNat_ofNat,
      Nat.mod_eq_of_lt hrank, Nat.mod_eq_of_lt hchoose]
  simp only [hiff, decide_eq_true_eq]

theorem search9_obligs (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    search9.res.obligs s := by
  simp only [Result.obligs, search9.res, rv_simp]
  have hadd := search9_addr s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi
  simp only [Result.toState_getReg, search9.res, rv_simp] at hadd
  rw [hadd]
  apply (accessValid_iff _ _).2
  have hmid : (lo + hi) / 2 < 385 := by omega
  have hi' : (k - 1) * 385 + (lo + hi) / 2 < 5 * 385 := by omega
  have haddr : 0xffc3d0 + 8 * ((k - 1) * 385 + (lo + hi) / 2) < 2 ^ 64 := by omega
  rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt haddr]
  simp only [MEMORY_BYTES]
  constructor <;> omega

theorem search9_steps_bounded (s : MachineState) (k lo hi : Nat)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    Steps Radix12SplitExpandImage.expandImage s search9.res.steps search9.res.cycles
      (search9.res.toState s) :=
  search9_steps s hpc
    (search9_obligs s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi)

theorem search9_frame (s : MachineState) :
    (search9.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (search9.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (search9.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (search9.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (search9.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (search9.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (search9.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (search9.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_getReg, Result.toState_getMem,
    search9.res, rv_simp, memEval]
  simp

#print axioms search9_addr
#print axioms search9_choose
#print axioms search9_pc
#print axioms search9_pc_nat
#print axioms search9_obligs
#print axioms search9_steps_bounded
#print axioms search9_frame
end Radix12SplitSearchAddr
end
-- END Radix12SplitSearchAddr

-- BEGIN Radix12SplitSearchBranch from /tmp/Radix12SplitSearchBranch.lean
section

namespace Radix12SplitSearchBranch
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImage
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 37)),
   (15 + 37, (expandTail.drop 37).take 2),
   (15 + 39, (expandTail.drop 39).take 1),
   (15 + 40, (expandTail.drop 40).take 2),
   (15 + 42, expandTail.drop 42)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel

theorem codeAt_false : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 37)))
    ((expandTail.drop 37).take 2) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_true : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 39)))
    ((expandTail.drop 39).take 1) :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_bottom : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 40)))
    ((expandTail.drop 40).take 2) :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)

sym_block falseBlock := symRun {} ((expandTail.drop 37).take 2)
  (BitVec.ofNat 64 4304) 5
sym_block trueBlock := symRun {} ((expandTail.drop 39).take 1)
  (BitVec.ofNat 64 4312) 3
sym_block bottomBlock := symRun {} ((expandTail.drop 40).take 2)
  (BitVec.ofNat 64 4316) 4

theorem false_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4304) :
    Steps expandImage s falseBlock.res.steps falseBlock.res.cycles
      (falseBlock.res.toState s) := by
  have ho : falseBlock.res.obligs s := by simp only [falseBlock.res, rv_simp]
  exact symRun_sound falseBlock codeAt_false s hpc ho

theorem true_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4312) :
    Steps expandImage s trueBlock.res.steps trueBlock.res.cycles
      (trueBlock.res.toState s) := by
  have ho : trueBlock.res.obligs s := by simp only [trueBlock.res, rv_simp]
  exact symRun_sound trueBlock codeAt_true s hpc ho

theorem bottom_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4316) :
    Steps expandImage s bottomBlock.res.steps bottomBlock.res.cycles
      (bottomBlock.res.toState s) := by
  have ho : bottomBlock.res.obligs s := by simp only [bottomBlock.res, rv_simp]
  exact symRun_sound bottomBlock codeAt_bottom s hpc ho

#print axioms false_steps
#print axioms true_steps
#print axioms bottom_steps
end Radix12SplitSearchBranch
end
-- END Radix12SplitSearchBranch

-- BEGIN Radix12SplitSearchBranchProps from /tmp/Radix12SplitSearchBranchProps.lean
section

namespace Radix12SplitSearchBranchProps
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchBranch

theorem false_sem (s : MachineState) :
    (falseBlock.res.toState s).pc = BitVec.ofNat 64 4316 ∧
    (falseBlock.res.toState s).getReg .x14 = s.getReg .x15 ∧
    (falseBlock.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (falseBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (falseBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (falseBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (falseBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (falseBlock.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (falseBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_pc, Result.toState_getReg,
    Result.toState_getMem, falseBlock.res, rv_simp, memEval]
  simp

theorem true_sem (s : MachineState) :
    (trueBlock.res.toState s).pc = BitVec.ofNat 64 4316 ∧
    (trueBlock.res.toState s).getReg .x13 = s.getReg .x15 ∧
    (trueBlock.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (trueBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (trueBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (trueBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (trueBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (trueBlock.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (trueBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_pc, Result.toState_getReg,
    Result.toState_getMem, trueBlock.res, rv_simp, memEval]
  simp

theorem bottom_sem (s : MachineState) :
    (bottomBlock.res.toState s).getReg .x30 = s.getReg .x30 - 1#64 ∧
    (bottomBlock.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (bottomBlock.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (bottomBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (bottomBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (bottomBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (bottomBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (∀ a, (bottomBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_getReg, Result.toState_getMem,
    bottomBlock.res, rv_simp, memEval]
  simp

theorem bottom_pc (s : MachineState) (fuel : Nat)
    (h30 : s.getReg .x30 = BitVec.ofNat 64 fuel)
    (hfuel : 1 ≤ fuel) (hfuel9 : fuel ≤ 9) :
    (bottomBlock.res.toState s).pc =
      if 1 < fuel then BitVec.ofNat 64 4268 else BitVec.ofNat 64 4324 := by
  simp only [Result.toState_pc, bottomBlock.res, rv_simp]
  rw [h30]
  rw [BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel]
  by_cases h : fuel = 1
  · subst fuel
    decide
  · have hp : 0 < fuel - 1 := by omega
    have hp64 : fuel - 1 < 2 ^ 64 := by omega
    have hne : BitVec.ofNat 64 (fuel - 1) ≠ (0#64) := by
      intro hz
      have hzN := congrArg BitVec.toNat hz
      simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt hp64] at hzN
      norm_num at hzN
      omega
    have hb : (BitVec.ofNat 64 (fuel - 1) != 0#64) = true := by
      simpa using hne
    simp [hb, show 1 < fuel by omega]

#print axioms false_sem
#print axioms true_sem
#print axioms bottom_sem
#print axioms bottom_pc
end Radix12SplitSearchBranchProps
end
-- END Radix12SplitSearchBranchProps

-- BEGIN Radix12SplitSearchRound from /tmp/Radix12SplitSearchRound.lean
section

namespace Radix12SplitSearchRound
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImage
  Radix12SplitSearchFirst Radix12SplitSearchAddr
  Radix12SplitSearchBranch Radix12SplitSearchBranchProps
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

structure Core (s : MachineState) (k rank lo hi fuel : Nat) : Prop where
  x10 : s.getReg .x10 = BitVec.ofNat 64 rank
  x11 : s.getReg .x11 = BitVec.ofNat 64 k
  x13 : s.getReg .x13 = BitVec.ofNat 64 hi
  x14 : s.getReg .x14 = BitVec.ofNat 64 lo
  x27 : s.getReg .x27 = BitVec.ofNat 64 385
  x2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0
  x30 : s.getReg .x30 = BitVec.ofNat 64 fuel
  table : ∀ i < 5 * 385,
    s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
      BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))

theorem search_round (s : MachineState) (k rank lo hi fuel : Nat)
    (hpc : s.pc = BitVec.ofNat 64 4268)
    (hs : Core s k rank lo hi fuel)
    (hk : 1 ≤ k) (hk5 : k ≤ 5)
    (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hfuel : 1 ≤ fuel) (hfuel9 : fuel ≤ 9)
    (hrank : rank < 2 ^ 64) :
    let mid := (lo + hi) / 2
    let test := rank < Nat.choose mid k
    ∃ t n c, Steps expandImage s n c t ∧ n ≤ 13 ∧ c ≤ 16 ∧
      Core t k rank (if test then lo else mid) (if test then mid else hi) (fuel - 1) ∧
      t.pc = if 1 < fuel then BitVec.ofNat 64 4268 else BitVec.ofNat 64 4324 := by
  let mid := (lo + hi) / 2
  have hqsteps := search9_steps_bounded s k lo hi hpc hs.x11 hs.x27 hs.x13
    hs.x14 hs.x2 hk hk5 hlohi hhi
  let q := search9.res.toState s
  have hqmid : q.getReg .x15 = BitVec.ofNat 64 mid :=
    Radix12SplitSearchMid.search9_midpoint s lo hi hs.x14 hs.x13 (by omega)
  have hqpc := search9_pc_nat s k lo hi rank hs.x10 hrank hs.x11 hs.x27
    hs.x13 hs.x14 hs.x2 hk hk5 hlohi hhi hs.table
  obtain ⟨hq13, hq14, hq10, hq11, hq27, hq2, hq30, hqmem⟩ := search9_frame s
  by_cases htest : rank < Nat.choose mid k
  · let r := trueBlock.res.toState q
    have hrpc : q.pc = BitVec.ofNat 64 4312 := by
      change (search9.res.toState s).pc = _
      simpa [mid, htest] using hqpc
    have hrsteps := true_steps q hrpc
    obtain ⟨hrpc', hr13, hr14, hr10, hr11, hr27, hr2, hr30, hrmem⟩ := true_sem q
    have hr30' : r.getReg .x30 = BitVec.ofNat 64 fuel := by
      rw [hr30, hq30, hs.x30]
    let t := bottomBlock.res.toState r
    have htsteps := bottom_steps r hrpc'
    obtain ⟨ht30, ht13, ht14, ht10, ht11, ht27, ht2, htmem⟩ := bottom_sem r
    have htpc := bottom_pc r fuel hr30' hfuel hfuel9
    refine ⟨t, 12, 15, ?_, ?_, ?_, ?_, ?_⟩
    · exact Steps.of_eq (hqsteps.trans (hrsteps.trans htsteps))
        (by decide) (by decide)
    · decide
    · decide
    · have htest' : rank < Nat.choose ((lo + hi) / 2) k := by
        simpa only [mid] using htest
      simp only [htest', ↓reduceIte]
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · exact ht10.trans (hr10.trans (hq10.trans hs.x10))
      · exact ht11.trans (hr11.trans (hq11.trans hs.x11))
      · exact ht13.trans (hr13.trans hqmid)
      · exact ht14.trans (hr14.trans (hq14.trans hs.x14))
      · exact ht27.trans (hr27.trans (hq27.trans hs.x27))
      · exact ht2.trans (hr2.trans (hq2.trans hs.x2))
      · calc
          t.getReg .x30 = r.getReg .x30 - 1#64 := ht30
          _ = BitVec.ofNat 64 fuel - 1#64 := by rw [hr30']
          _ = BitVec.ofNat 64 (fuel - 1) :=
            BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel
      · intro i hi'
        rw [htmem, hrmem, hqmem]
        exact hs.table i hi'
    · exact htpc
  · let r := falseBlock.res.toState q
    have hrpc : q.pc = BitVec.ofNat 64 4304 := by
      change (search9.res.toState s).pc = _
      simpa [mid, htest] using hqpc
    have hrsteps := false_steps q hrpc
    obtain ⟨hrpc', hr14, hr13, hr10, hr11, hr27, hr2, hr30, hrmem⟩ := false_sem q
    have hr30' : r.getReg .x30 = BitVec.ofNat 64 fuel := by
      rw [hr30, hq30, hs.x30]
    let t := bottomBlock.res.toState r
    have htsteps := bottom_steps r hrpc'
    obtain ⟨ht30, ht13, ht14, ht10, ht11, ht27, ht2, htmem⟩ := bottom_sem r
    have htpc := bottom_pc r fuel hr30' hfuel hfuel9
    refine ⟨t, 13, 16, ?_, ?_, ?_, ?_, ?_⟩
    · exact Steps.of_eq (hqsteps.trans (hrsteps.trans htsteps))
        (by decide) (by decide)
    · decide
    · decide
    · have htest' : ¬rank < Nat.choose ((lo + hi) / 2) k := by
        simpa only [mid] using htest
      simp only [htest', ↓reduceIte]
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · exact ht10.trans (hr10.trans (hq10.trans hs.x10))
      · exact ht11.trans (hr11.trans (hq11.trans hs.x11))
      · exact ht13.trans (hr13.trans (hq13.trans hs.x13))
      · exact ht14.trans (hr14.trans hqmid)
      · exact ht27.trans (hr27.trans (hq27.trans hs.x27))
      · exact ht2.trans (hr2.trans (hq2.trans hs.x2))
      · calc
          t.getReg .x30 = r.getReg .x30 - 1#64 := ht30
          _ = BitVec.ofNat 64 fuel - 1#64 := by rw [hr30']
          _ = BitVec.ofNat 64 (fuel - 1) :=
            BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel
      · intro i hi'
        rw [htmem, hrmem, hqmem]
        exact hs.table i hi'
    · exact htpc

#print axioms search_round
end Radix12SplitSearchRound
end
-- END Radix12SplitSearchRound

-- BEGIN Radix12MachineBisect from /tmp/Radix12MachineBisect.lean
section

namespace Radix12MachineBisect
open Radix12

/-- The RV64 loop executes all nine comparisons even after the bracket has width one. -/
def fixedBisect (k code lo hi : Nat) : Nat → Nat
  | 0 => lo
  | fuel + 1 =>
      let mid := (lo + hi) / 2
      if mid.choose k ≤ code then fixedBisect k code mid hi fuel
      else fixedBisect k code lo mid fuel

theorem fixedBisect_unit (k code lo fuel : Nat)
    (hlo : lo.choose k ≤ code) :
    fixedBisect k code lo (lo + 1) fuel = lo := by
  induction fuel with
  | zero => rfl
  | succ fuel ih =>
      have hmid : (lo + (lo + 1)) / 2 = lo := by omega
      simp only [fixedBisect, hmid, if_pos hlo, ih]

theorem fixedBisect_eq (k code fuel : Nat) :
    ∀ lo hi : Nat, lo.choose k ≤ code → lo < hi →
      fixedBisect k code lo hi fuel = bisectChoose k code lo hi fuel := by
  induction fuel with
  | zero => intro lo hi hlo hlt; rfl
  | succ fuel ih =>
      intro lo hi hlo hlt
      by_cases hwide : lo + 1 < hi
      · let mid := (lo + hi) / 2
        have hloMid : lo < mid := by dsimp [mid]; omega
        have hmidHi : mid < hi := by dsimp [mid]; omega
        by_cases hcomp : mid.choose k ≤ code
        · simpa [fixedBisect, bisectChoose, hwide, mid, hcomp] using
            ih mid hi hcomp hmidHi
        · simpa [fixedBisect, bisectChoose, hwide, mid, hcomp] using
            ih lo mid hlo hloMid
      · have hunit : hi = lo + 1 := by omega
        subst hi
        rw [fixedBisect_unit k code lo (fuel + 1) hlo]
        simp [bisectChoose]

theorem fixed9_spec (k code lo hi : Nat)
    (hlo : lo.choose k ≤ code) (hhi : code < hi.choose k)
    (hlt : lo < hi) (hgap : hi - lo ≤ 2 ^ 9) :
    let n := fixedBisect k code lo hi 9
    n.choose k ≤ code ∧ code < (n + 1).choose k ∧ lo ≤ n ∧ n < hi := by
  rw [fixedBisect_eq k code 9 lo hi hlo hlt]
  exact bisectChoose_spec k code 9 lo hi hlo hhi hlt hgap

#print axioms fixedBisect_eq
#print axioms fixed9_spec
end Radix12MachineBisect
end
-- END Radix12MachineBisect

-- BEGIN Radix12FixedPair from /tmp/Radix12FixedPair.lean
section

namespace Radix12FixedPair
open Radix12MachineBisect

def fixedPair (k code lo hi : Nat) : Nat → Nat × Nat
  | 0 => (lo, hi)
  | fuel + 1 =>
      let mid := (lo + hi) / 2
      if code < mid.choose k then fixedPair k code lo mid fuel
      else fixedPair k code mid hi fuel

theorem fixedPair_step (k code lo hi fuel : Nat) :
    fixedPair k code lo hi (fuel + 1) =
      fixedPair k code
        (if code < ((lo + hi) / 2).choose k then lo else (lo + hi) / 2)
        (if code < ((lo + hi) / 2).choose k then (lo + hi) / 2 else hi) fuel := by
  conv_lhs => rw [fixedPair]
  split_ifs <;> rfl

theorem round_bracket (k code lo hi : Nat)
    (hlohi : lo < hi) (hlo : lo.choose k ≤ code)
    (hhi : code < hi.choose k) :
    let mid := (lo + hi) / 2
    let lo' := if code < mid.choose k then lo else mid
    let hi' := if code < mid.choose k then mid else hi
    lo' < hi' ∧ lo'.choose k ≤ code ∧ code < hi'.choose k ∧ hi' ≤ hi := by
  let mid := (lo + hi) / 2
  have hmidlo : lo ≤ mid := by dsimp [mid]; omega
  have hmidhi : mid < hi := by dsimp [mid]; omega
  by_cases hc : code < mid.choose k
  · have hstrict : lo < mid := by
      by_contra h
      have heq : mid = lo := by omega
      rw [heq] at hc
      omega
    have hc' : code < ((lo + hi) / 2).choose k := by simpa only [mid] using hc
    simp only [hc', ↓reduceIte]
    exact ⟨hstrict, hlo, trivial, Nat.le_of_lt hmidhi⟩
  · have hc' : ¬code < ((lo + hi) / 2).choose k := by simpa only [mid] using hc
    simp only [hc', ↓reduceIte]
    exact ⟨hmidhi, Nat.le_of_not_lt hc, hhi, Nat.le_refl hi⟩

theorem fixedPair_fst (k code fuel : Nat) :
    ∀ lo hi : Nat, (fixedPair k code lo hi fuel).1 =
      fixedBisect k code lo hi fuel := by
  induction fuel with
  | zero => intro lo hi; rfl
  | succ fuel ih =>
      intro lo hi
      by_cases hc : code < ((lo + hi) / 2).choose k
      · have hc' : ¬((lo + hi) / 2).choose k ≤ code := by omega
        simp only [fixedPair, fixedBisect, hc, if_neg hc', ↓reduceIte]
        exact ih lo ((lo + hi) / 2)
      · simp only [fixedPair, fixedBisect, hc, ↓reduceIte]
        have hc' : ((lo + hi) / 2).choose k ≤ code := Nat.le_of_not_lt hc
        rw [if_pos hc']
        exact ih ((lo + hi) / 2) hi

#print axioms round_bracket
#print axioms fixedPair_step
#print axioms fixedPair_fst
end Radix12FixedPair
end
-- END Radix12FixedPair

-- BEGIN Radix12SplitSearchLoop from /tmp/Radix12SplitSearchLoop.lean
section

namespace Radix12SplitSearchLoop
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImage
  Radix12SplitSearchRound Radix12FixedPair Radix12MachineBisect
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem search_loop : ∀ fuel : Nat, ∀ (s : MachineState) (k rank lo hi : Nat),
    s.pc = BitVec.ofNat 64 4268 →
    Core s k rank lo hi fuel →
    1 ≤ k → k ≤ 5 → lo < hi → hi ≤ 385 →
    lo.choose k ≤ rank → rank < hi.choose k →
    1 ≤ fuel → fuel ≤ 9 → rank < 2 ^ 64 →
    ∃ t n c, Steps expandImage s n c t ∧
      n ≤ 13 * fuel ∧ c ≤ 16 * fuel ∧
      Core t k rank (fixedPair k rank lo hi fuel).1
        (fixedPair k rank lo hi fuel).2 0 ∧
      t.pc = BitVec.ofNat 64 4324 := by
  intro fuel
  induction fuel with
  | zero =>
      intro s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi hfuel hfuel9 hrank
      omega
  | succ f ih =>
      intro s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi hfuel hfuel9 hrank
      let mid := (lo + hi) / 2
      let test := rank < Nat.choose mid k
      let lo' := if test then lo else mid
      let hi' := if test then mid else hi
      obtain ⟨t, n, c, hsteps, hn, hc, htcore, htpc⟩ :=
        search_round s k rank lo hi (f + 1) hpc hs hk hk5 hlohi hhi
          hfuel hfuel9 hrank
      have hb := Radix12FixedPair.round_bracket k rank lo hi hlohi hlo hrhi
      have hnew : lo' < hi' ∧ lo'.choose k ≤ rank ∧
          rank < hi'.choose k ∧ hi' ≤ hi := by
        simpa only [lo', hi', test, mid] using hb
      have hpair : fixedPair k rank lo hi (f + 1) =
          fixedPair k rank lo' hi' f := by
        simpa only [lo', hi', test, mid] using
          (Radix12FixedPair.fixedPair_step k rank lo hi f)
      have htcore' : Core t k rank lo' hi' f := by
        simpa only [lo', hi', test, mid, Nat.add_sub_cancel] using htcore
      by_cases hf0 : f = 0
      · subst f
        have hpc' : t.pc = BitVec.ofNat 64 4324 := by simpa using htpc
        have hp0 : fixedPair k rank lo hi 1 = (lo', hi') := by
          simpa only [fixedPair] using hpair
        refine ⟨t, n, c, hsteps, ?_, ?_, ?_, hpc'⟩
        · simpa using hn
        · simpa using hc
        · simpa only [hp0, Prod.fst, Prod.snd] using htcore'
      · have hfpos : 1 ≤ f := by omega
        have hpc' : t.pc = BitVec.ofNat 64 4268 := by
          simpa [show 1 < f + 1 by omega] using htpc
        obtain ⟨u, n', c', htail, hn', hc', hucore, hupc⟩ :=
          ih t k rank lo' hi' hpc' htcore' hk hk5 hnew.1
            (le_trans hnew.2.2.2 hhi) hnew.2.1 hnew.2.2.1
            hfpos (by omega) hrank
        refine ⟨u, n + n', c + c', hsteps.trans htail, ?_, ?_, ?_, hupc⟩
        · omega
        · omega
        · simpa only [hpair] using hucore

theorem search9_bar (s : MachineState) (k rank lo hi : Nat)
    (hpc : s.pc = BitVec.ofNat 64 4268)
    (hs : Core s k rank lo hi 9)
    (hk : 1 ≤ k) (hk5 : k ≤ 5)
    (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hlo : lo.choose k ≤ rank) (hrhi : rank < hi.choose k)
    (hrank : rank < 2 ^ 64) :
    ∃ t n c, Steps expandImage s n c t ∧ n ≤ 117 ∧ c ≤ 144 ∧
      Core t k rank (fixedPair k rank lo hi 9).1
        (fixedPair k rank lo hi 9).2 0 ∧
      t.pc = BitVec.ofNat 64 4324 ∧
      t.getReg .x14 = BitVec.ofNat 64 (Radix12.bisectChoose k rank lo hi 9) := by
  obtain ⟨t, n, c, hsteps, hn, hc, hcore, hpc'⟩ :=
    search_loop 9 s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi
      (by decide) (by decide) hrank
  refine ⟨t, n, c, hsteps, ?_, ?_, hcore, hpc', ?_⟩
  · simpa using hn
  · simpa using hc
  · calc
      t.getReg .x14 = BitVec.ofNat 64 (fixedPair k rank lo hi 9).1 := hcore.x14
      _ = BitVec.ofNat 64 (fixedBisect k rank lo hi 9) := by
        rw [fixedPair_fst]
      _ = BitVec.ofNat 64 (Radix12.bisectChoose k rank lo hi 9) := by
        rw [fixedBisect_eq k rank 9 lo hi hlo hlohi]

#print axioms search_loop
#print axioms search9_bar
end Radix12SplitSearchLoop
end
-- END Radix12SplitSearchLoop

-- BEGIN Radix12SplitStagePostSD from /tmp/Radix12SplitStagePostSD.lean
section

namespace Radix12SplitStagePostSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 42)),
   (15 + 42, (expandTail.drop 42).take 14),
   (15 + 56, expandTail.drop 56)]
theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel
theorem codeAt_post :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 42)))
      ((expandTail.drop 42).take 14) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)

sym_block post := symRun {noAlias := true} ((expandTail.drop 42).take 14)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 42))) 20

theorem post_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 4324)
    (ho : post.res.obligs s) :
    Steps expandImage s post.res.steps post.res.cycles
      (post.res.toState s) :=
  symRun_sound post codeAt_post s hpc ho

#print axioms post_steps
end Radix12SplitStagePostSD
end
-- END Radix12SplitStagePostSD

-- BEGIN Radix12SplitStagePostSDOblig from /tmp/Radix12SplitStagePostSDOblig.lean
section
namespace Radix12SplitStagePostSDOblig
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitStagePostSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem post_obligs (s : MachineState) (k bar : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 bar)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hbar : bar < 385) :
    post.res.obligs s := by
  have htable :
      (((s.getReg .x11 - 1#64) * s.getReg .x27 + s.getReg .x14) <<< 3) +
          s.getReg .x2 =
        BitVec.ofNat 64 (0xffc3d0 + 8 * ((k - 1) * 385 + bar)) := by
    rw [h11, h27, h14, h2]
    exact Radix12SplitTableAddr.table_addr_arith k bar hk hk5 hbar
  have hscratch :
      ((s.getReg .x11 - 1#64) <<< 3) + s.getReg .x28 =
        BitVec.ofNat 64 (0x4000 + 8 * (k - 1)) := by
    rw [h11, h28, BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk,
      BitVec.shiftLeft_eq_mul_twoPow]
    have hpow : BitVec.twoPow 64 3 = BitVec.ofNat 64 8 := by decide
    rw [hpow]
    simp only [← BitVec.ofNat_mul, ← BitVec.ofNat_add]
    congr 1
    omega
  simp only [Result.obligs, post.res, rv_simp]
  simp only [show ((3#64).toNat % 64) = 3 by decide]
  rw [htable, hscratch]
  have haddrT : 0xffc3d0 + 8 * ((k - 1) * 385 + bar) < 2 ^ 64 := by omega
  have haddrS : 0x4000 + 8 * (k - 1) < 2 ^ 64 := by omega
  constructor
  · intro heq
    have hn := congrArg BitVec.toNat heq
    simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt haddrT,
      Nat.mod_eq_of_lt haddrS] at hn
    omega
  constructor
  · apply (accessValid_iff _ _).2
    rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt haddrT]
    simp only [MEMORY_BYTES]
    constructor <;> omega
  · apply (accessValid_iff _ _).2
    rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt haddrS]
    simp only [MEMORY_BYTES]
    constructor <;> omega

theorem post_steps_bounded (s : MachineState) (k bar : Nat)
    (hpc : s.pc = BitVec.ofNat 64 4324)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 bar)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hbar : bar < 385) :
    SigGolfCandidate.Rv.Steps Radix12SplitExpandImageSD.expandImage s
      post.res.steps post.res.cycles (post.res.toState s) :=
  Radix12SplitStagePostSD.post_steps s hpc
    (post_obligs s k bar h11 h14 h28 h27 h2 hk hk5 hbar)

#print axioms post_obligs
#print axioms post_steps_bounded
end Radix12SplitStagePostSDOblig
end
-- END Radix12SplitStagePostSDOblig

-- BEGIN Radix12SplitStagePostSDProps from /tmp/Radix12SplitStagePostSDProps.lean
section
namespace Radix12SplitStagePostSDProps
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitStagePostSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem post_regs (s : MachineState) :
    (post.res.toState s).getReg .x11 = s.getReg .x11 - 1#64 ∧
    (post.res.toState s).getReg .x12 = s.getReg .x14 ∧
    (post.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (post.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (post.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (post.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (post.res.toState s).getReg .x2 = s.getReg .x2 := by
  simp only [Result.toState_getReg, post.res, rv_simp]
  simp

theorem post_mem (s : MachineState) (a : Word) :
    (post.res.toState s).getMem a =
      if a = ((s.getReg .x11 - 1#64) <<< 3) + s.getReg .x28 then
        s.getReg .x14 else s.getMem a := by
  simp only [Result.toState_getMem, post.res, memEval, rv_simp]
  simp only [show ((3#64).toNat % 64) = 3 by decide]

theorem post_rank_raw (s : MachineState) :
    (post.res.toState s).getReg .x10 =
      s.getReg .x10 -
        s.getMem ((((s.getReg .x11 - 1#64) * s.getReg .x27 +
          s.getReg .x14) <<< 3) + s.getReg .x2) := by
  simp only [Result.toState_getReg, post.res, rv_simp]
  simp only [show ((3#64).toNat % 64) = 3 by decide]

theorem post_pc_raw (s : MachineState) :
    (post.res.toState s).pc =
      if s.getReg .x11 - 1#64 != 0#64 then
        BitVec.ofNat 64 4252 else BitVec.ofNat 64 4380 := by
  simp only [Result.toState_pc, post.res, rv_simp]

theorem post_pc (s : MachineState) (k : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) :
    (post.res.toState s).pc =
      if 1 < k then BitVec.ofNat 64 4252 else BitVec.ofNat 64 4380 := by
  rw [post_pc_raw, h11, BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk]
  by_cases hk1 : k = 1
  · subst k
    decide
  · have hpos : 0 < k - 1 := by omega
    have hlt : k - 1 < 2 ^ 64 := by omega
    have hne : BitVec.ofNat 64 (k - 1) != 0#64 := by
      simp only [bne_iff_ne]
      intro heq
      have hn := congrArg BitVec.toNat heq
      simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt hlt] at hn
      norm_num at hn
      omega
    simp [hne, show 1 < k by omega]

theorem post_rank (s : MachineState) (k bar rank : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 bar)
    (h10 : s.getReg .x10 = BitVec.ofNat 64 rank)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hbar : bar < 385)
    (hchoose : Nat.choose bar k ≤ rank)
    (htable : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    (post.res.toState s).getReg .x10 =
      BitVec.ofNat 64 (rank - Nat.choose bar k) := by
  let i := (k - 1) * 385 + bar
  have hi : i < 5 * 385 := by dsimp [i]; omega
  have himod : i % 385 = bar := by dsimp [i]; omega
  have hidiv : i / 385 + 1 = k := by dsimp [i]; omega
  rw [post_rank_raw, h10, h11, h14, h27, h2,
    Radix12SplitTableAddr.table_addr_arith k bar hk hk5 hbar]
  change BitVec.ofNat 64 rank - s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) = _
  rw [htable i hi, himod, hidiv]
  exact BitVec.ofNat_sub_ofNat_of_le rank (Nat.choose bar k)
    (Radix12ChooseBound64.choose_lt64 bar k hbar hk5) hchoose

theorem scratch_addr (s : MachineState) (k : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) :
    ((s.getReg .x11 - 1#64) <<< 3) + s.getReg .x28 =
      BitVec.ofNat 64 (0x4000 + 8 * (k - 1)) := by
  rw [h11, h28, BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk,
    BitVec.shiftLeft_eq_mul_twoPow]
  have hpow : BitVec.twoPow 64 3 = BitVec.ofNat 64 8 := by decide
  rw [hpow]
  simp only [← BitVec.ofNat_mul, ← BitVec.ofNat_add]
  congr 1
  omega

theorem post_scratch (s : MachineState) (k : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) :
    (post.res.toState s).getMem (BitVec.ofNat 64 (0x4000 + 8 * (k - 1))) =
      s.getReg .x14 := by
  rw [post_mem, scratch_addr s k h11 h28 hk hk5]
  simp

theorem post_table_frame (s : MachineState) (k i : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hi : i < 5 * 385) :
    (post.res.toState s).getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) := by
  rw [post_mem, scratch_addr s k h11 h28 hk hk5]
  have hneq : BitVec.ofNat 64 (0xffc3d0 + 8 * i) ≠
      BitVec.ofNat 64 (0x4000 + 8 * (k - 1)) := by
    intro heq
    have hn := congrArg BitVec.toNat heq
    have ht : 0xffc3d0 + 8 * i < 2 ^ 64 := by omega
    have hs : 0x4000 + 8 * (k - 1) < 2 ^ 64 := by omega
    simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt ht,
      Nat.mod_eq_of_lt hs] at hn
    omega
  simp [hneq]

#print axioms post_regs
#print axioms post_mem
#print axioms post_rank_raw
#print axioms post_pc
#print axioms post_rank
#print axioms post_scratch
#print axioms post_table_frame
end Radix12SplitStagePostSDProps
end
-- END Radix12SplitStagePostSDProps

-- BEGIN Radix12SplitStageStartSD from /tmp/Radix12SplitStageStartSD.lean
section
namespace Radix12SplitStageStartSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 24)),
   (15 + 24, (expandTail.drop 24).take 4),
   (15 + 28, expandTail.drop 28)]
theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel
theorem codeAt_stage :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 24)))
      ((expandTail.drop 24).take 4) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)

sym_block stage := symRun {} ((expandTail.drop 24).take 4)
  (BitVec.ofNat 64 4252) 10

theorem stage_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 4252) :
    Steps expandImage s stage.res.steps stage.res.cycles
      (stage.res.toState s) := by
  have ho : stage.res.obligs s := by simp only [stage.res, rv_simp]
  exact symRun_sound stage codeAt_stage s hpc ho

theorem stage_regs (s : MachineState) :
    (stage.res.toState s).getReg .x13 = s.getReg .x12 + 1#64 ∧
    (stage.res.toState s).getReg .x14 = s.getReg .x11 - 1#64 ∧
    (stage.res.toState s).getReg .x30 = BitVec.ofNat 64 9 ∧
    (stage.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (stage.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (stage.res.toState s).getReg .x12 = s.getReg .x12 ∧
    (stage.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (stage.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (stage.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (stage.res.toState s).getReg .x2 = s.getReg .x2 := by
  simp only [Result.toState_getReg, stage.res, rv_simp]
  simp

theorem stage_pc (s : MachineState) :
    (stage.res.toState s).pc = BitVec.ofNat 64 4268 := by
  simp only [Result.toState_pc, stage.res, rv_simp]

theorem stage_mem (s : MachineState) (a : Word) :
    (stage.res.toState s).getMem a = s.getMem a := by
  simp only [Result.toState_getMem, stage.res, memEval]

#print axioms stage_steps
#print axioms stage_regs
#print axioms stage_pc
#print axioms stage_mem
end Radix12SplitStageStartSD
end
-- END Radix12SplitStageStartSD
