-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import SigGolfCandidate.Packed.Radix12Bundle04
import SigGolfCandidate.Packed.Radix12Bundle08
import SigGolfCandidate.Packed.Radix12Bundle10
import SigGolfCandidate.Packed.SignRun
import SigGolfCandidate.Rv.Api

-- BEGIN Radix12SignPrefix from /tmp/sig-radix12-sign/Radix12SignPrefix.lean
section

namespace Radix12SignPrefix
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv SigGolfCandidate.Mem SigGolfCandidate.Packed
set_option maxRecDepth 100000

abbrev image : Image := Radix12SignImage.signImage

def L : SigGolfCandidate.Rv.Layout :=
  [(0, SigGolfCandidate.Images.signCode.take 2800),
   (2800, SigGolfCandidate.Expand.pre0), (2805, SigGolfCandidate.Expand.loopCode),
   (2811, SigGolfCandidate.Expand.pre1), (2815, SigGolfCandidate.Expand.loopCode),
   (2821, SigGolfCandidate.Expand.pre2), (2826, SigGolfCandidate.Expand.loopCode),
   (2832, SigGolfCandidate.Expand.pre3), (2837, SigGolfCandidate.Expand.loopCode),
   (2843, SigGolfCandidate.Expand.pre4), (2848, SigGolfCandidate.Expand.loopCode),
   (2854, SigGolfCandidate.Expand.pre5), (2859, SigGolfCandidate.Expand.loopCode),
   (2865, SigGolfCandidate.Expand.pre6), (2870, SigGolfCandidate.Expand.loopCode),
   (2876, SigGolfCandidate.Expand.pre7), (2881, SigGolfCandidate.Expand.loopCode),
   (2887, SigGolfCandidate.Expand.pre8), (2892, SigGolfCandidate.Expand.loopCode),
   (2898, SigGolfCandidate.Expand.pre9), (2903, SigGolfCandidate.Expand.loopCode),
   (2909, SigGolfCandidate.Expand.pre10), (2914, SigGolfCandidate.Expand.loopCode),
   (2920, SigGolfCandidate.Packed.Images.signBodyPrelude), (2925, SigGolfCandidate.Expand.loopCode),
   (2931, SigGolfCandidate.Packed.Images.signCounterPrelude),
   (2935, Radix12SignImage.signTail)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_pre0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2800)) SigGolfCandidate.Expand.pre0 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_loop0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2805)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)

theorem codeAt_pre1 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2811)) SigGolfCandidate.Expand.pre1 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_loop1 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2815)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)

theorem codeAt_pre2 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2821)) SigGolfCandidate.Expand.pre2 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_loop2 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2826)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)

theorem codeAt_pre3 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2832)) SigGolfCandidate.Expand.pre3 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_loop3 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2837)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)

theorem codeAt_pre4 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2843)) SigGolfCandidate.Expand.pre4 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_loop4 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2848)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)

theorem codeAt_pre5 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2854)) SigGolfCandidate.Expand.pre5 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_loop5 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2859)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)

theorem codeAt_pre6 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2865)) SigGolfCandidate.Expand.pre6 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_loop6 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2870)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)

theorem codeAt_pre7 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2876)) SigGolfCandidate.Expand.pre7 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_loop7 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2881)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)

theorem codeAt_pre8 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2887)) SigGolfCandidate.Expand.pre8 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_loop8 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2892)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)

theorem codeAt_pre9 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2898)) SigGolfCandidate.Expand.pre9 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_loop9 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2903)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)

theorem codeAt_pre10 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2909)) SigGolfCandidate.Expand.pre10 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_loop10 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2914)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)

theorem codeAt_bodyPre : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2920)) SigGolfCandidate.Packed.Images.signBodyPrelude :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_bodyLoop : CodeAt image (BitVec.ofNat 64 (0x1000 + 4 * 2925)) SigGolfCandidate.Expand.loopCode :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
sym_block run0 := symRun {} SigGolfCandidate.Expand.pre0 (BitVec.ofNat 64 (0x1000 + 4 * 2800)) 10
sym_block run1 := symRun {} SigGolfCandidate.Expand.pre1 (BitVec.ofNat 64 (0x1000 + 4 * 2811)) 10
sym_block run2 := symRun {} SigGolfCandidate.Expand.pre2 (BitVec.ofNat 64 (0x1000 + 4 * 2821)) 10
sym_block run3 := symRun {} SigGolfCandidate.Expand.pre3 (BitVec.ofNat 64 (0x1000 + 4 * 2832)) 10
sym_block run4 := symRun {} SigGolfCandidate.Expand.pre4 (BitVec.ofNat 64 (0x1000 + 4 * 2843)) 10
sym_block run5 := symRun {} SigGolfCandidate.Expand.pre5 (BitVec.ofNat 64 (0x1000 + 4 * 2854)) 10
sym_block run6 := symRun {} SigGolfCandidate.Expand.pre6 (BitVec.ofNat 64 (0x1000 + 4 * 2865)) 10
sym_block run7 := symRun {} SigGolfCandidate.Expand.pre7 (BitVec.ofNat 64 (0x1000 + 4 * 2876)) 10
sym_block run8 := symRun {} SigGolfCandidate.Expand.pre8 (BitVec.ofNat 64 (0x1000 + 4 * 2887)) 10
sym_block run9 := symRun {} SigGolfCandidate.Expand.pre9 (BitVec.ofNat 64 (0x1000 + 4 * 2898)) 10
sym_block run10 := symRun {} SigGolfCandidate.Expand.pre10 (BitVec.ofNat 64 (0x1000 + 4 * 2909)) 10
sym_block runBody := symRun {} SigGolfCandidate.Packed.Images.signBodyPrelude (BitVec.ofNat 64 (0x1000 + 4 * 2920)) 10
theorem stage0 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2800))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run0.res.steps + 620 * 6) (run0.res.cycles + 620 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2805) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (9808, 2048, 620) f) :=
  SigGolfCandidate.Expand.stage run0 codeAt_pre0 rfl rfl rfl rfl rfl rfl codeAt_loop0
    (by decide) t htpc f hf

theorem stage1 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2811))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run1.res.steps + 1 * 6) (run1.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2815) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (12288, 8432, 1) f) :=
  SigGolfCandidate.Expand.stage run1 codeAt_pre1 rfl rfl rfl rfl rfl rfl codeAt_loop1
    (by decide) t htpc f hf

theorem stage2 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2821))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run2.res.steps + 212 * 6) (run2.res.cycles + 212 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2826) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (12292, 4528, 212) f) :=
  SigGolfCandidate.Expand.stage run2 codeAt_pre2 rfl rfl rfl rfl rfl rfl codeAt_loop2
    (by decide) t htpc f hf

theorem stage3 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2832))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run3.res.steps + 1 * 6) (run3.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2837) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (13140, 8436, 1) f) :=
  SigGolfCandidate.Expand.stage run3 codeAt_pre3 rfl rfl rfl rfl rfl rfl codeAt_loop3
    (by decide) t htpc f hf

theorem stage4 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2843))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run4.res.steps + 192 * 6) (run4.res.cycles + 192 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2848) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (13144, 5376, 192) f) :=
  SigGolfCandidate.Expand.stage run4 codeAt_pre4 rfl rfl rfl rfl rfl rfl codeAt_loop4
    (by decide) t htpc f hf

theorem stage5 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2854))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run5.res.steps + 1 * 6) (run5.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2859) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (13912, 8440, 1) f) :=
  SigGolfCandidate.Expand.stage run5 codeAt_pre5 rfl rfl rfl rfl rfl rfl codeAt_loop5
    (by decide) t htpc f hf

theorem stage6 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2865))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run6.res.steps + 192 * 6) (run6.res.cycles + 192 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2870) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (13916, 6144, 192) f) :=
  SigGolfCandidate.Expand.stage run6 codeAt_pre6 rfl rfl rfl rfl rfl rfl codeAt_loop6
    (by decide) t htpc f hf

theorem stage7 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2876))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run7.res.steps + 1 * 6) (run7.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2881) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (14684, 8444, 1) f) :=
  SigGolfCandidate.Expand.stage run7 codeAt_pre7 rfl rfl rfl rfl rfl rfl codeAt_loop7
    (by decide) t htpc f hf

theorem stage8 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2887))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run8.res.steps + 192 * 6) (run8.res.cycles + 192 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2892) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (14688, 6912, 192) f) :=
  SigGolfCandidate.Expand.stage run8 codeAt_pre8 rfl rfl rfl rfl rfl rfl codeAt_loop8
    (by decide) t htpc f hf

theorem stage9 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2898))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run9.res.steps + 1 * 6) (run9.res.cycles + 1 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2903) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (15456, 8448, 1) f) :=
  SigGolfCandidate.Expand.stage run9 codeAt_pre9 rfl rfl rfl rfl rfl rfl codeAt_loop9
    (by decide) t htpc f hf

theorem stage10 (t : MachineState) (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2909))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (run10.res.steps + 188 * 6) (run10.res.cycles + 188 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2914) + 24 ∧
      SigGolfCandidate.Expand.BytesEq u (SigGolfCandidate.Expand.applyCopy (15460, 7680, 188) f) :=
  SigGolfCandidate.Expand.stage run10 codeAt_pre10 rfl rfl rfl rfl rfl rfl codeAt_loop10
    (by decide) t htpc f hf

theorem permute_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * 2800)) :
    ∃ u, Steps image s 9660 9660 u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2920) ∧
      SigGolfCandidate.Expand.BytesEq u
        (SigGolfCandidate.Expand.applyCopies SigGolfCandidate.Expand.copies
          (fun a => s.getByte (BitVec.ofNat 64 a))) := by
  obtain ⟨u0, st0, pc0, b0⟩ := stage0 s hpc _ (fun a _ => rfl)
  obtain ⟨u1, st1, pc1, b1⟩ := stage1 u0 (by rw [pc0]; decide) _ b0
  obtain ⟨u2, st2, pc2, b2⟩ := stage2 u1 (by rw [pc1]; decide) _ b1
  obtain ⟨u3, st3, pc3, b3⟩ := stage3 u2 (by rw [pc2]; decide) _ b2
  obtain ⟨u4, st4, pc4, b4⟩ := stage4 u3 (by rw [pc3]; decide) _ b3
  obtain ⟨u5, st5, pc5, b5⟩ := stage5 u4 (by rw [pc4]; decide) _ b4
  obtain ⟨u6, st6, pc6, b6⟩ := stage6 u5 (by rw [pc5]; decide) _ b5
  obtain ⟨u7, st7, pc7, b7⟩ := stage7 u6 (by rw [pc6]; decide) _ b6
  obtain ⟨u8, st8, pc8, b8⟩ := stage8 u7 (by rw [pc7]; decide) _ b7
  obtain ⟨u9, st9, pc9, b9⟩ := stage9 u8 (by rw [pc8]; decide) _ b8
  obtain ⟨u10, st10, pc10, b10⟩ := stage10 u9 (by rw [pc9]; decide) _ b9
  exact ⟨u10, Steps.of_eq ((((((((((st0.trans st1).trans st2).trans st3).trans st4).trans st5).trans st6).trans st7).trans st8).trans st9).trans st10) rfl rfl, by rw [pc10]; decide, b10⟩

theorem permute_readBuffer (s u : MachineState)
    (hu : SigGolfCandidate.Expand.BytesEq u
      (SigGolfCandidate.Expand.applyCopies SigGolfCandidate.Expand.copies
        (fun a => s.getByte (BitVec.ofNat 64 a)))) :
    readBuffer u 0x800 6404 = SigGolfCandidate.Ref.expandRef
      (readBuffer s 0x2650 6404) := by
  rw [readBuffer_eq, SigGolfCandidate.Ref.expandRef,
    SigGolfCandidate.Ref.ofList, SigGolfCandidate.Ref.toWitness]
  apply congrArg (BitVec.ofNat (8 * 6404))
  apply congrArg SigGolfCandidate.Ref.leNat
  apply List.map_congr_left
  intro i hi
  rw [List.mem_range] at hi
  obtain ⟨c, hc, h1, h2, h3⟩ := SigGolfCandidate.Expand.copies_cover i hi
  rw [hu _ (by omega), SigGolfCandidate.Expand.applyCopies_hit
    SigGolfCandidate.Expand.copies _ (by decide) (by decide) c hc _ h1 h2, h3,
    readBuffer_byte s 0x2650 6404 _ (SigGolfCandidate.Ref.witnessSrc_lt i hi)]

theorem body_stage (t : MachineState)
    (htpc : t.pc = BitVec.ofNat 64 (0x1000 + 4 * 2920))
    (f : Nat → Byte) (hf : SigGolfCandidate.Expand.BytesEq t f) :
    ∃ u, Steps image t (runBody.res.steps + 1596 * 6)
        (runBody.res.cycles + 1596 * 6) u ∧
      u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2931) ∧
      SigGolfCandidate.Expand.BytesEq u
        (SigGolfCandidate.Expand.applyCopy (0x800, 0x2650, 1596) f) := by
  obtain ⟨u, hst, hpc, hmem⟩ :=
    SigGolfCandidate.Expand.stage runBody codeAt_bodyPre rfl rfl rfl rfl rfl rfl
      codeAt_bodyLoop (by decide) t htpc f hf
  exact ⟨u, hst, by simpa using hpc, hmem⟩


#print axioms permute_steps
#print axioms body_stage
end Radix12SignPrefix
end
-- END Radix12SignPrefix

-- BEGIN Radix12SignPrelude from /tmp/sig-radix12-sign/Radix12SignPrelude.lean
section

namespace Radix12SignPrelude
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  Radix12SignImage SigGolfCandidate.Rv
  SigGolfCandidate.Mem SigGolfCandidate.Packed

abbrev image := Radix12SignPrefix.image

theorem codeAt_counter : CodeAt image
    (BitVec.ofNat 64 (0x1000 + 4*2931))
    SigGolfCandidate.Packed.Images.signCounterPrelude :=
  codeAt_layout Radix12SignPrefix.code_eq Radix12SignPrefix.layout_ok
    (i := 25) (by kernel_rfl) (by decide)

sym_block runCounter := symRun {}
  SigGolfCandidate.Packed.Images.signCounterPrelude
  (BitVec.ofNat 64 (0x1000 + 4*2931)) 10

def after (s : MachineState) := runCounter.res.toState s

theorem steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2931)) :
    Steps image s runCounter.res.steps runCounter.res.cycles (after s) := by
  have ho : runCounter.res.obligs s := by
    simp only [runCounter.res, rv_simp]
  exact symRun_sound runCounter codeAt_counter s hpc ho

theorem pc (s : MachineState) :
    (after s).pc = BitVec.ofNat 64 (0x1000 + 4*2935) := by
  simp only [after, Result.toState_pc, runCounter.res, rv_simp]

theorem x6 (s : MachineState) :
    (after s).getReg .x6 = BitVec.ofNat 64 0x20F0 := by
  simp only [after, Result.toState_getReg, runCounter.res, rv_simp]

theorem x7 (s : MachineState) :
    (after s).getReg .x7 = BitVec.ofNat 64 0x3F40 := by
  simp only [after, Result.toState_getReg, runCounter.res, rv_simp]

theorem mem (s : MachineState) (a : Word) :
    (after s).getMem a = s.getMem a := by
  simp only [after, Result.toState_getMem, runCounter.res, rv_simp]

theorem byte (s : MachineState) (a : Word) :
    (after s).getByte a = s.getByte a := by
  simp only [MachineState.getByte, mem]

theorem buffer (s : MachineState) (a n : Nat) :
    readBuffer (after s) a n = readBuffer s a n := by
  apply readBuffer_eq_of_bytes
  intro i hi
  rw [readBuffer_byte s a n i hi]
  exact byte s (BitVec.ofNat 64 (a+i))

theorem sourceCounters (s : MachineState) :
    SigGolfCandidate.Packed.SignRun.sourceCounters (after s) =
      SigGolfCandidate.Packed.SignRun.sourceCounters s := by
  rw [SigGolfCandidate.Packed.SignRun.sourceCounters_readBuffer,
    SigGolfCandidate.Packed.SignRun.sourceCounters_readBuffer, buffer]

#print axioms steps
#print axioms buffer
end Radix12SignPrelude
end
-- END Radix12SignPrelude

-- BEGIN Radix12SignSym from /tmp/sig-radix12-sign/Radix12SignSym.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

namespace Radix12SignSym
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SignImage

abbrev image : Image := signImage

def L : SigGolfCandidate.Rv.Layout :=
  [(0, signCode.take 2935),
   (2935, signTail.take 18),
   (2953, (signTail.drop 18).take 7),
   (2960, (signTail.drop 25).take 9),
   (2969, (signTail.drop 34).take 11),
   (2980, (signTail.drop 45).take 13),
   (2993, (signTail.drop 58).take 15),
   (3008, (signTail.drop 73).take 27),
   (3035, (signTail.drop 100).take 3),
   (3038, (signTail.drop 103).take 3)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_first : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2935)) (signTail.take 18) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_term0 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2953)) ((signTail.drop 18).take 7) :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_term1 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2960)) ((signTail.drop 25).take 9) :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_term2 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2969)) ((signTail.drop 34).take 11) :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_term3 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2980)) ((signTail.drop 45).take 13) :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_term4 : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*2993)) ((signTail.drop 58).take 15) :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_pack : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*3008)) ((signTail.drop 73).take 27) :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_fallback : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*3035)) ((signTail.drop 100).take 3) :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_done : CodeAt image (BitVec.ofNat 64 (0x1000 + 4*3038)) ((signTail.drop 103).take 3) :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)

sym_block first := symRun {} (signTail.take 18) (BitVec.ofNat 64 (0x1000 + 4*2935)) 100
sym_block term0 := symRun {} ((signTail.drop 18).take 7) (BitVec.ofNat 64 (0x1000 + 4*2953)) 100
sym_block term1 := symRun {} ((signTail.drop 25).take 9) (BitVec.ofNat 64 (0x1000 + 4*2960)) 100
sym_block term2 := symRun {} ((signTail.drop 34).take 11) (BitVec.ofNat 64 (0x1000 + 4*2969)) 100
sym_block term3 := symRun {} ((signTail.drop 45).take 13) (BitVec.ofNat 64 (0x1000 + 4*2980)) 100
sym_block term4 := symRun {} ((signTail.drop 58).take 15) (BitVec.ofNat 64 (0x1000 + 4*2993)) 100
sym_block pack := symRun {} ((signTail.drop 73).take 27) (BitVec.ofNat 64 (0x1000 + 4*3008)) 100
sym_block fallback := symRun {} ((signTail.drop 100).take 3) (BitVec.ofNat 64 (0x1000 + 4*3035)) 100
sym_block done := symRun {} ((signTail.drop 103).take 3) (BitVec.ofNat 64 (0x1000 + 4*3038)) 100

example : first.res.steps = 18 := by decide
example : term0.res.steps = 7 := by decide
example : term1.res.steps = 9 := by decide
example : term2.res.steps = 11 := by decide
example : term3.res.steps = 13 := by decide
example : term4.res.steps = 15 := by decide
example : pack.res.steps = 27 := by decide
example : fallback.res.steps = 3 := by decide
example : done.res.steps = 2 := by decide

#print axioms codeAt_first
#print axioms first
#print axioms term4
end Radix12SignSym
end
-- END Radix12SignSym

-- BEGIN Radix12SignSteps from /tmp/sig-radix12-sign/Radix12SignSteps.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

namespace Radix12SignSteps
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SignImage Radix12SignSym

theorem first_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2935))
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    Steps signImage s first.res.steps first.res.cycles (first.res.toState s) := by
  have ho : first.res.obligs s := by
    simp only [first.res, rv_simp]
    rw [h6]
    decide
  exact symRun_sound first codeAt_first s hpc ho

theorem term0_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2953)) :
    Steps signImage s term0.res.steps term0.res.cycles (term0.res.toState s) := by
  have ho : term0.res.obligs s := by simp only [term0.res, rv_simp]
  exact symRun_sound term0 codeAt_term0 s hpc ho

theorem term1_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2960)) :
    Steps signImage s term1.res.steps term1.res.cycles (term1.res.toState s) := by
  have ho : term1.res.obligs s := by simp only [term1.res, rv_simp]
  exact symRun_sound term1 codeAt_term1 s hpc ho

theorem term2_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2969)) :
    Steps signImage s term2.res.steps term2.res.cycles (term2.res.toState s) := by
  have ho : term2.res.obligs s := by simp only [term2.res, rv_simp]
  exact symRun_sound term2 codeAt_term2 s hpc ho

theorem term3_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2980)) :
    Steps signImage s term3.res.steps term3.res.cycles (term3.res.toState s) := by
  have ho : term3.res.obligs s := by simp only [term3.res, rv_simp]
  exact symRun_sound term3 codeAt_term3 s hpc ho

theorem term4_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2993)) :
    Steps signImage s term4.res.steps term4.res.cycles (term4.res.toState s) := by
  have ho : term4.res.obligs s := by simp only [term4.res, rv_simp]
  exact symRun_sound term4 codeAt_term4 s hpc ho

theorem pack_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*3008))
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x3F40) :
    Steps signImage s pack.res.steps pack.res.cycles (pack.res.toState s) := by
  have ho : pack.res.obligs s := by
    simp only [pack.res, rv_simp]
    rw [h7]
    decide
  exact symRun_sound pack codeAt_pack s hpc ho

theorem fallback_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*3035))
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x3F40) :
    Steps signImage s fallback.res.steps fallback.res.cycles (fallback.res.toState s) := by
  have ho : fallback.res.obligs s := by
    simp only [fallback.res, rv_simp]
    rw [h7]
    decide
  exact symRun_sound fallback codeAt_fallback s hpc ho

theorem done_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*3038)) :
    Steps signImage s done.res.steps done.res.cycles (done.res.toState s) := by
  have ho : done.res.obligs s := by simp only [done.res, rv_simp]
  exact symRun_sound done codeAt_done s hpc ho

example : first.res.cycles = 18 := by decide
example : term0.res.cycles = 7 := by decide
example : pack.res.cycles = 27 := by decide
example : fallback.res.cycles = 3 := by decide
example : done.res.cycles = 2 := by decide

#print axioms first_steps
#print axioms pack_steps
end Radix12SignSteps
#eval (Radix12SignSym.term0.res.cycles, Radix12SignSym.term1.res.cycles,
  Radix12SignSym.term2.res.cycles, Radix12SignSym.term3.res.cycles,
  Radix12SignSym.term4.res.cycles)
end
-- END Radix12SignSteps

-- BEGIN Radix12SignLoaded from /tmp/sig-radix12-sign/Radix12SignLoaded.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12SignLoaded
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Rv Radix27
abbrev q := Radix27SignLoaded.q

theorem first_x9 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x9 =
      ((word (q s) 0).zeroExtend 64) := by
  rw [Radix27SignLoaded.qword0]
  simp only [Result.toState_getReg, Radix12SignSym.first.res,
    rv_simp, h6]

theorem first_x10 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x10 =
      ((word (q s) 1).zeroExtend 64) := by
  rw [Radix27SignLoaded.qword1]
  simp only [Result.toState_getReg, Radix12SignSym.first.res,
    rv_simp, h6]

theorem first_x11 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x11 =
      ((word (q s) 2).zeroExtend 64) := by
  rw [Radix27SignLoaded.qword2]
  simp only [Result.toState_getReg, Radix12SignSym.first.res,
    rv_simp, h6]
  rw [show (8432#64) + (8#64) = 8440#64 by decide]

theorem first_x12 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x12 =
      ((word (q s) 3).zeroExtend 64) := by
  rw [Radix27SignLoaded.qword3]
  simp only [Result.toState_getReg, Radix12SignSym.first.res,
    rv_simp, h6]
  rw [show (8432#64) + (8#64) = 8440#64 by decide]

theorem first_x13 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x13 =
      ((word (q s) 4).zeroExtend 64) := by
  rw [Radix27SignLoaded.qword4]
  simp only [Result.toState_getReg, Radix12SignSym.first.res,
    rv_simp, h6]
  rw [show (8432#64) + (16#64) = 8448#64 by decide]

#print axioms first_x9
#print axioms first_x13
end Radix12SignLoaded
end
-- END Radix12SignLoaded

-- BEGIN Radix12ChooseWord from /tmp/sig-radix12-sign/Radix12ChooseWord.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

namespace Radix12ChooseWord
open RiscvZkvm.Rv64

theorem subNat (n : Word) (j : Nat)
    (hj : j ≤ n.toNat) (hj64 : j < 2^64) :
    (n - BitVec.ofNat 64 j).toNat = n.toNat - j := by
  have hle : BitVec.ofNat 64 j ≤ n := by
    simpa only [BitVec.le_def, BitVec.toNat_ofNat,
      Nat.mod_eq_of_lt hj64] using hj
  rw [BitVec.toNat_sub_of_le hle]
  simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt hj64]

theorem mulNat (a b : Word) (h : a.toNat * b.toNat < 2^64) :
    (a*b).toNat = a.toNat*b.toNat := BitVec.toNat_mul_of_lt h

private theorem choose5_desc (n : Nat) :
    n.choose 5 = (((n*(n-1))*(n-2))*(n-3))*(n-4) / 120 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  simp only [Nat.descFactorial, Nat.factorial, Nat.sub_zero]
  congr 1
  ring

private def numerator5 (n : Word) : Word :=
  ((((n * (n - 1#64)) * (n - 2#64)) * (n - 3#64)) * (n - 4#64))

theorem choose5_word_nat (n : Word) (hlo : 4 ≤ n.toNat) (hhi : n.toNat ≤ 384) :
    (rv64_divu ((((n * (n - 1#64)) * (n - 2#64)) *
      (n - 3#64)) * (n - 4#64)) (120#64)).toNat = n.toNat.choose 5 := by
  change (rv64_divu (numerator5 n) (120#64)).toNat = n.toNat.choose 5
  have hs1 : (n - 1#64).toNat = n.toNat - 1 := subNat n 1 (by omega) (by decide)
  have hs2 : (n - 2#64).toNat = n.toNat - 2 := subNat n 2 (by omega) (by decide)
  have hs3 : (n - 3#64).toNat = n.toNat - 3 := subNat n 3 (by omega) (by decide)
  have hs4 : (n - 4#64).toNat = n.toNat - 4 := subNat n 4 (by omega) (by decide)
  have h1 : n.toNat * (n.toNat - 1) ≤ 384^2 := by
    exact Nat.mul_le_mul hhi (by omega)
  have h2 : (n.toNat * (n.toNat - 1)) * (n.toNat - 2) ≤ 384^3 := by
    calc
      _ ≤ (384^2)*(384) := Nat.mul_le_mul h1 (by omega)
      _ = 384^3 := by norm_num
  have h3 : ((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3) ≤ 384^4 := by
    calc
      _ ≤ (384^3)*(384) := Nat.mul_le_mul h2 (by omega)
      _ = 384^4 := by norm_num
  have h4 : (((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3)) * (n.toNat - 4) ≤ 384^5 := by
    calc
      _ ≤ (384^4)*(384) := Nat.mul_le_mul h3 (by omega)
      _ = 384^5 := by norm_num
  have hp1 : (n * (n - 1#64)).toNat = n.toNat * (n.toNat - 1) := by
    rw [mulNat _ _ (by rw [hs1]; omega), hs1]
  have hp2 : ((n * (n - 1#64)) * (n - 2#64)).toNat =
      (n.toNat * (n.toNat - 1)) * (n.toNat - 2) := by
    rw [mulNat _ _ (by rw [hp1, hs2]; omega), hp1, hs2]
  have hp3 : (((n * (n - 1#64)) * (n - 2#64)) * (n - 3#64)).toNat =
      ((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3) := by
    rw [mulNat _ _ (by rw [hp2, hs3]; omega), hp2, hs3]
  have hp4 : (numerator5 n).toNat =
      (((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3)) * (n.toNat - 4) := by
    unfold numerator5
    rw [mulNat _ _ (by rw [hp3, hs4]; omega), hp3, hs4]
  rw [choose5_desc]
  simpa [rv64_divu, BitVec.toNat_udiv, hp4]

private theorem choose2_desc (n : Nat) :
    n.choose 2 = n * (n-1) / 2 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  simp only [Nat.descFactorial, Nat.factorial, Nat.sub_zero]
  congr 1
  ring

theorem choose2_word_nat (n : Word) (hlo : 1 ≤ n.toNat) (hhi : n.toNat ≤ 384) :
    (rv64_divu (n * (n - 1#64)) (2#64)).toNat = n.toNat.choose 2 := by
  have hs1 : (n - 1#64).toNat = n.toNat - 1 := subNat n 1 (by omega) (by decide)
  have h1 : n.toNat * (n.toNat - 1) ≤ 384^2 :=
    Nat.mul_le_mul hhi (by omega)
  have hp1 : (n * (n - 1#64)).toNat = n.toNat * (n.toNat - 1) := by
    rw [mulNat _ _ (by rw [hs1]; omega), hs1]
  rw [choose2_desc]
  simpa [rv64_divu, BitVec.toNat_udiv, hp1]

private theorem choose3_desc (n : Nat) :
    n.choose 3 = (n * (n-1)) * (n-2) / 6 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  simp only [Nat.descFactorial, Nat.factorial, Nat.sub_zero]
  congr 1
  ring

theorem choose3_word_nat (n : Word) (hlo : 2 ≤ n.toNat) (hhi : n.toNat ≤ 384) :
    (rv64_divu ((n * (n - 1#64)) * (n - 2#64)) (6#64)).toNat =
      n.toNat.choose 3 := by
  have hs1 : (n - 1#64).toNat = n.toNat - 1 := subNat n 1 (by omega) (by decide)
  have hs2 : (n - 2#64).toNat = n.toNat - 2 := subNat n 2 (by omega) (by decide)
  have h1 : n.toNat * (n.toNat - 1) ≤ 384^2 :=
    Nat.mul_le_mul hhi (by omega)
  have h2 : (n.toNat * (n.toNat - 1)) * (n.toNat - 2) ≤ 384^3 := by
    calc
      _ ≤ (384^2)*384 := Nat.mul_le_mul h1 (by omega)
      _ = 384^3 := by norm_num
  have hp1 : (n * (n - 1#64)).toNat = n.toNat * (n.toNat - 1) := by
    rw [mulNat _ _ (by rw [hs1]; omega), hs1]
  have hp2 : ((n * (n - 1#64)) * (n - 2#64)).toNat =
      (n.toNat * (n.toNat - 1)) * (n.toNat - 2) := by
    rw [mulNat _ _ (by rw [hp1, hs2]; omega), hp1, hs2]
  rw [choose3_desc]
  simpa [rv64_divu, BitVec.toNat_udiv, hp2]

private theorem choose4_desc (n : Nat) :
    n.choose 4 = ((n * (n-1)) * (n-2)) * (n-3) / 24 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  simp only [Nat.descFactorial, Nat.factorial, Nat.sub_zero]
  congr 1
  ring

theorem choose4_word_nat (n : Word) (hlo : 3 ≤ n.toNat) (hhi : n.toNat ≤ 384) :
    (rv64_divu (((n * (n - 1#64)) * (n - 2#64)) * (n - 3#64)) (24#64)).toNat =
      n.toNat.choose 4 := by
  have hs1 : (n - 1#64).toNat = n.toNat - 1 := subNat n 1 (by omega) (by decide)
  have hs2 : (n - 2#64).toNat = n.toNat - 2 := subNat n 2 (by omega) (by decide)
  have hs3 : (n - 3#64).toNat = n.toNat - 3 := subNat n 3 (by omega) (by decide)
  have h1 : n.toNat * (n.toNat - 1) ≤ 384^2 :=
    Nat.mul_le_mul hhi (by omega)
  have h2 : (n.toNat * (n.toNat - 1)) * (n.toNat - 2) ≤ 384^3 := by
    calc
      _ ≤ (384^2)*384 := Nat.mul_le_mul h1 (by omega)
      _ = 384^3 := by norm_num
  have h3 : ((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3) ≤ 384^4 := by
    calc
      _ ≤ (384^3)*384 := Nat.mul_le_mul h2 (by omega)
      _ = 384^4 := by norm_num
  have hp1 : (n * (n - 1#64)).toNat = n.toNat * (n.toNat - 1) := by
    rw [mulNat _ _ (by rw [hs1]; omega), hs1]
  have hp2 : ((n * (n - 1#64)) * (n - 2#64)).toNat =
      (n.toNat * (n.toNat - 1)) * (n.toNat - 2) := by
    rw [mulNat _ _ (by rw [hp1, hs2]; omega), hp1, hs2]
  have hp3 : (((n * (n - 1#64)) * (n - 2#64)) * (n - 3#64)).toNat =
      ((n.toNat * (n.toNat - 1)) * (n.toNat - 2)) * (n.toNat - 3) := by
    rw [mulNat _ _ (by rw [hp2, hs3]; omega), hp2, hs3]
  rw [choose4_desc]
  simpa [rv64_divu, BitVec.toNat_udiv, hp3]

#print axioms choose2_word_nat
#print axioms choose3_word_nat
#print axioms choose4_word_nat
#print axioms choose5_word_nat
end Radix12ChooseWord
end
-- END Radix12ChooseWord

-- BEGIN Radix12SignBranchTry from /tmp/sig-radix12-sign/Radix12SignBranchTry.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12SignBranchTry
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SignImage Radix12SignSym

theorem first_pc (s : MachineState) :
    (first.res.toState s).pc =
      if 381 ≤ ((first.res.toState s).getReg .x14).toNat then
        BitVec.ofNat 64 (0x1000+4*3035)
      else BitVec.ofNat 64 (0x1000+4*2953) := by
  simp only [Result.toState_pc, Result.toState_getReg, first.res, rv_simp]
  simp [BitVec.ult_eq_decide, not_lt]

#print axioms first_pc
end Radix12SignBranchTry
end
-- END Radix12SignBranchTry

-- BEGIN Radix12HighSumTry from /tmp/sig-radix12-sign/Radix12HighSumTry.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12HighSumTry
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix27

def highWord (q : BitVec 160) (i : Nat) : Word :=
  ((word q i).zeroExtend 64) >>> 12

def highSumWord (q : BitVec 160) : Word :=
  highWord q 0 + highWord q 1 + highWord q 2 +
  highWord q 3 + highWord q 4

theorem first_x14 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).getReg .x14 =
      highSumWord (Radix12SignLoaded.q s) := by
  simp only [Result.toState_getReg, Radix12SignSym.first.res, rv_simp,
    h6, highSumWord, highWord]
  rw [Radix27SignLoaded.qword0, Radix27SignLoaded.qword1,
    Radix27SignLoaded.qword2, Radix27SignLoaded.qword3,
    Radix27SignLoaded.qword4]
  rw [show (8432#64) + (8#64) = (8440#64) by decide,
    show (8432#64) + (16#64) = (8448#64) by decide]
  norm_num


theorem highWord_nat (q : BitVec 160) (i : Nat) :
    (highWord q i).toNat = (word q i).toNat / 4096 := by
  unfold highWord
  simp only [BitVec.toNat_ushiftRight, BitVec.zeroExtend_eq_setWidth,
    BitVec.toNat_setWidth, Nat.shiftRight_eq_div_pow]
  have hw := BitVec.isLt (word q i)
  rw [Nat.mod_eq_of_lt (by omega : (word q i).toNat < 2^64)]

theorem highWord_lt (q : BitVec 160) (i : Nat) :
    (highWord q i).toNat < 2^20 := by
  rw [highWord_nat]
  have hw := BitVec.isLt (word q i)
  omega

private theorem sum5_word_nat (a b c d e : Word)
    (ha : a.toNat < 2^20) (hb : b.toNat < 2^20)
    (hc : c.toNat < 2^20) (hd : d.toNat < 2^20)
    (he : e.toNat < 2^20) :
    (a+b+c+d+e).toNat = a.toNat+b.toNat+c.toNat+d.toNat+e.toNat := by
  simp only [BitVec.toNat_add]
  omega

theorem highSumWord_nat (q : BitVec 160) :
    (highSumWord q).toNat =
      Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) := by
  unfold highSumWord
  rw [sum5_word_nat _ _ _ _ _
    (highWord_lt q 0) (highWord_lt q 1) (highWord_lt q 2)
    (highWord_lt q 3) (highWord_lt q 4)]
  simp only [Radix12.counterSum, Radix12Split.highWords,
    Radix12Split.hi, Radix12Split.B, Radix12.countersQ,
    highWord_nat]

#print axioms highWord_nat
#print axioms highSumWord_nat


theorem first_pc_q (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12SignSym.first.res.toState s).pc =
      if 381 ≤ Radix12.counterSum
          (Radix12Split.highWords (Radix12.countersQ (Radix12SignLoaded.q s))) then
        BitVec.ofNat 64 (0x1000+4*3035)
      else BitVec.ofNat 64 (0x1000+4*2953) := by
  rw [Radix12SignBranchTry.first_pc, first_x14 s h6,
    highSumWord_nat]

#print axioms first_pc_q

#print axioms first_x14
end Radix12HighSumTry
end
-- END Radix12HighSumTry

-- BEGIN Radix12RankRegsTry from /tmp/sig-radix12-sign/Radix12RankRegsTry.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12RankRegsTry
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym

def bar1word (s : MachineState) : Word :=
  s.getReg .x20 + (s.getReg .x10 >>> 12) + 1#64

theorem term0_x19 (s : MachineState) :
    (term0.res.toState s).getReg .x19 = (s.getReg .x9 >>> 12) := by
  simp only [Result.toState_getReg, term0.res, rv_simp]
  norm_num

theorem term1_x20 (s : MachineState) :
    (term1.res.toState s).getReg .x20 =
      s.getReg .x20 + (s.getReg .x10 >>> 12) := by
  simp only [Result.toState_getReg, term1.res, rv_simp]
  norm_num

theorem term1_x19 (s : MachineState) :
    (term1.res.toState s).getReg .x19 =
      s.getReg .x19 + rv64_divu (bar1word s * (bar1word s - 1#64)) (2#64) := by
  simp only [Result.toState_getReg, term1.res, rv_simp, bar1word]
  norm_num
  all_goals simp only [BitVec.add_sub_cancel]


def bar2word (s : MachineState) : Word :=
  s.getReg .x20 + (s.getReg .x11 >>> 12) + 2#64

theorem term2_x20 (s : MachineState) :
    (term2.res.toState s).getReg .x20 =
      s.getReg .x20 + (s.getReg .x11 >>> 12) := by
  simp only [Result.toState_getReg, term2.res, rv_simp]
  norm_num

theorem term2_x19 (s : MachineState) :
    (term2.res.toState s).getReg .x19 =
      s.getReg .x19 + rv64_divu
        ((bar2word s * (bar2word s - 1#64)) * (bar2word s - 2#64)) (6#64) := by
  simp only [Result.toState_getReg, term2.res, rv_simp, bar2word]
  norm_num
  have hsub1 : ∀ a : Word, a + 2#64 - 1#64 = a + 1#64 := by
    intro a
    bv_normalize
  have hsub2 : ∀ a : Word, a + 2#64 - 2#64 = a := by
    intro a
    exact BitVec.add_sub_cancel a 2#64
  all_goals simp only [hsub1, hsub2]


def bar3word (s : MachineState) : Word :=
  s.getReg .x20 + (s.getReg .x12 >>> 12) + 3#64

theorem term3_x20 (s : MachineState) :
    (term3.res.toState s).getReg .x20 =
      s.getReg .x20 + (s.getReg .x12 >>> 12) := by
  simp only [Result.toState_getReg, term3.res, rv_simp]
  norm_num

theorem term3_x19 (s : MachineState) :
    (term3.res.toState s).getReg .x19 =
      s.getReg .x19 + rv64_divu
        (((bar3word s * (bar3word s - 1#64)) *
          (bar3word s - 2#64)) * (bar3word s - 3#64)) (24#64) := by
  simp only [Result.toState_getReg, term3.res, rv_simp, bar3word]
  norm_num
  have hsub1 : ∀ a : Word, a + 3#64 - 1#64 = a + 2#64 := by
    intro a
    bv_normalize
  have hsub2 : ∀ a : Word, a + 3#64 - 2#64 = a + 1#64 := by
    intro a
    bv_normalize
  have hsub3 : ∀ a : Word, a + 3#64 - 3#64 = a := by
    intro a
    exact BitVec.add_sub_cancel a 3#64
  all_goals simp only [hsub1, hsub2, hsub3]

def bar4word (s : MachineState) : Word :=
  s.getReg .x20 + (s.getReg .x13 >>> 12) + 4#64

theorem term4_x20 (s : MachineState) :
    (term4.res.toState s).getReg .x20 =
      s.getReg .x20 + (s.getReg .x13 >>> 12) := by
  simp only [Result.toState_getReg, term4.res, rv_simp]
  norm_num

theorem term4_x19 (s : MachineState) :
    (term4.res.toState s).getReg .x19 =
      s.getReg .x19 + rv64_divu
        ((((bar4word s * (bar4word s - 1#64)) *
          (bar4word s - 2#64)) * (bar4word s - 3#64)) *
          (bar4word s - 4#64)) (120#64) := by
  simp only [Result.toState_getReg, term4.res, rv_simp, bar4word]
  norm_num
  have hsub1 : ∀ a : Word, a + 4#64 - 1#64 = a + 3#64 := by
    intro a
    bv_normalize
  have hsub2 : ∀ a : Word, a + 4#64 - 2#64 = a + 2#64 := by
    intro a
    bv_normalize
  have hsub3 : ∀ a : Word, a + 4#64 - 3#64 = a + 1#64 := by
    intro a
    bv_normalize
  have hsub4 : ∀ a : Word, a + 4#64 - 4#64 = a := by
    intro a
    exact BitVec.add_sub_cancel a 4#64
  all_goals simp only [hsub1, hsub2, hsub3, hsub4]

#print axioms term3_x19
#print axioms term4_x19

#print axioms term2_x19

#print axioms term1_x19
end Radix12RankRegsTry
end
-- END Radix12RankRegsTry

-- BEGIN Radix12Rank0 from /tmp/sig-radix12-sign/Radix12Rank0.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12Rank0
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym

def v0 (s : MachineState) : MachineState := first.res.toState s
def v1 (s : MachineState) : MachineState := term0.res.toState (v0 s)

theorem term0_x20 (s : MachineState) :
    (term0.res.toState s).getReg .x20 = s.getReg .x9 >>> 12 := by
  simp only [Result.toState_getReg, term0.res, rv_simp]
  norm_num

theorem v1_x19 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v1 s).getReg .x19 =
      Radix12HighSumTry.highWord (Radix12SignLoaded.q s) 0 := by
  rw [v1, Radix12RankRegsTry.term0_x19]
  unfold v0
  rw [Radix12SignLoaded.first_x9 s h6]
  rfl

theorem v1_x20 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v1 s).getReg .x20 =
      Radix12HighSumTry.highWord (Radix12SignLoaded.q s) 0 := by
  rw [v1, term0_x20]
  unfold v0
  rw [Radix12SignLoaded.first_x9 s h6]
  rfl

#print axioms v1_x19
#print axioms v1_x20
end Radix12Rank0
end
-- END Radix12Rank0

-- BEGIN Radix12Rank1 from /tmp/sig-radix12-sign/Radix12Rank1.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12Rank1
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym
  Radix12HighSumTry

abbrev q (s : MachineState) := Radix12SignLoaded.q s

def v2 (s : MachineState) : MachineState := term1.res.toState (Radix12Rank0.v1 s)

def bar1Word (q : BitVec 160) : Word := highWord q 0 + highWord q 1 + 1#64

def rank2Word (q : BitVec 160) : Word :=
  highWord q 0 + rv64_divu (bar1Word q * (bar1Word q - 1#64)) (2#64)

theorem v1_x10 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (Radix12Rank0.v1 s).getReg .x10 =
      ((Radix27.word (q s) 1).zeroExtend 64) := by
  have h : (Radix12Rank0.v1 s).getReg .x10 =
      (Radix12Rank0.v0 s).getReg .x10 := by
    simp only [Radix12Rank0.v1, Result.toState_getReg, term0.res, rv_simp]
  rw [h]
  exact Radix12SignLoaded.first_x10 s h6

theorem v2_x20 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v2 s).getReg .x20 = highWord (q s) 0 + highWord (q s) 1 := by
  change (term1.res.toState (Radix12Rank0.v1 s)).getReg .x20 = _
  rw [Radix12RankRegsTry.term1_x20, Radix12Rank0.v1_x20 s h6,
    v1_x10 s h6]
  rfl

theorem v2_x19 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v2 s).getReg .x19 = rank2Word (q s) := by
  change (term1.res.toState (Radix12Rank0.v1 s)).getReg .x19 = _
  rw [Radix12RankRegsTry.term1_x19]
  simp only [Radix12RankRegsTry.bar1word]
  rw [Radix12Rank0.v1_x19 s h6, Radix12Rank0.v1_x20 s h6,
    v1_x10 s h6]
  rfl

#print axioms v2_x20
#print axioms v2_x19
end Radix12Rank1
end
-- END Radix12Rank1

-- BEGIN Radix12Rank2 from /tmp/sig-radix12-sign/Radix12Rank2.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12Rank2
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym
  Radix12HighSumTry Radix12Rank1

abbrev q (s : MachineState) := Radix12SignLoaded.q s

def v3 (s : MachineState) : MachineState := term2.res.toState (v2 s)

def bar2Word (q : BitVec 160) : Word :=
  highWord q 0 + highWord q 1 + highWord q 2 + 2#64

def rank3Word (q : BitVec 160) : Word :=
  rank2Word q + rv64_divu
    ((bar2Word q * (bar2Word q - 1#64)) * (bar2Word q - 2#64)) (6#64)

theorem v2_x11 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v2 s).getReg .x11 = ((Radix27.word (q s) 2).zeroExtend 64) := by
  have h1 : (v2 s).getReg .x11 =
      (Radix12Rank0.v1 s).getReg .x11 := by
    simp only [v2, Result.toState_getReg, term1.res, rv_simp]
  have h0 : (Radix12Rank0.v1 s).getReg .x11 =
      (Radix12Rank0.v0 s).getReg .x11 := by
    simp only [Radix12Rank0.v1, Result.toState_getReg, term0.res, rv_simp]
  rw [h1, h0]
  exact Radix12SignLoaded.first_x11 s h6

theorem v3_x20 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v3 s).getReg .x20 =
      highWord (q s) 0 + highWord (q s) 1 + highWord (q s) 2 := by
  change (term2.res.toState (v2 s)).getReg .x20 = _
  rw [Radix12RankRegsTry.term2_x20, v2_x20 s h6, v2_x11 s h6]
  rfl

theorem v3_x19 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v3 s).getReg .x19 = rank3Word (q s) := by
  change (term2.res.toState (v2 s)).getReg .x19 = _
  rw [Radix12RankRegsTry.term2_x19]
  simp only [Radix12RankRegsTry.bar2word]
  rw [v2_x19 s h6, v2_x20 s h6, v2_x11 s h6]
  rfl

#print axioms v3_x20
#print axioms v3_x19
end Radix12Rank2
end
-- END Radix12Rank2

-- BEGIN Radix12Rank3 from /tmp/sig-radix12-sign/Radix12Rank3.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12Rank3
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym
  Radix12HighSumTry Radix12Rank1 Radix12Rank2

abbrev q (s : MachineState) := Radix12SignLoaded.q s

def v4 (s : MachineState) : MachineState := term3.res.toState (v3 s)

def bar3Word (q : BitVec 160) : Word :=
  highWord q 0 + highWord q 1 + highWord q 2 + highWord q 3 + 3#64

def rank4Word (q : BitVec 160) : Word :=
  rank3Word q + rv64_divu
    (((bar3Word q * (bar3Word q - 1#64)) *
      (bar3Word q - 2#64)) * (bar3Word q - 3#64)) (24#64)

theorem v3_x12 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v3 s).getReg .x12 = ((Radix27.word (q s) 3).zeroExtend 64) := by
  have h : (v3 s).getReg .x12 =
      (Radix12Rank0.v0 s).getReg .x12 := by
    simp only [v3, v2, Radix12Rank0.v1, Result.toState_getReg,
      term2.res, term1.res, term0.res, rv_simp]
  rw [h]
  exact Radix12SignLoaded.first_x12 s h6

theorem v4_x20 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v4 s).getReg .x20 =
      highWord (q s) 0 + highWord (q s) 1 +
      highWord (q s) 2 + highWord (q s) 3 := by
  change (term3.res.toState (v3 s)).getReg .x20 = _
  rw [Radix12RankRegsTry.term3_x20, v3_x20 s h6, v3_x12 s h6]
  rfl

theorem v4_x19 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v4 s).getReg .x19 = rank4Word (q s) := by
  change (term3.res.toState (v3 s)).getReg .x19 = _
  rw [Radix12RankRegsTry.term3_x19]
  simp only [Radix12RankRegsTry.bar3word]
  rw [v3_x19 s h6, v3_x20 s h6, v3_x12 s h6]
  rfl

#print axioms v4_x20
#print axioms v4_x19
end Radix12Rank3
end
-- END Radix12Rank3

-- BEGIN Radix12Rank4 from /tmp/sig-radix12-sign/Radix12Rank4.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12Rank4
open RiscvZkvm.Rv64 SigGolfCandidate.Rv Radix12SignSym
  Radix12HighSumTry Radix12Rank1 Radix12Rank2 Radix12Rank3

abbrev q (s : MachineState) := Radix12SignLoaded.q s

def v5 (s : MachineState) : MachineState := term4.res.toState (v4 s)

def bar4Word (q : BitVec 160) : Word :=
  highWord q 0 + highWord q 1 + highWord q 2 +
  highWord q 3 + highWord q 4 + 4#64

def rank5Word (q : BitVec 160) : Word :=
  rank4Word q + rv64_divu
    ((((bar4Word q * (bar4Word q - 1#64)) *
      (bar4Word q - 2#64)) * (bar4Word q - 3#64)) *
      (bar4Word q - 4#64)) (120#64)

theorem v4_x13 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v4 s).getReg .x13 = ((Radix27.word (q s) 4).zeroExtend 64) := by
  have h : (v4 s).getReg .x13 =
      (Radix12Rank0.v0 s).getReg .x13 := by
    simp only [v4, v3, v2, Radix12Rank0.v1, Result.toState_getReg,
      term3.res, term2.res, term1.res, term0.res, rv_simp]
  rw [h]
  exact Radix12SignLoaded.first_x13 s h6

theorem v5_x20 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v5 s).getReg .x20 =
      highWord (q s) 0 + highWord (q s) 1 +
      highWord (q s) 2 + highWord (q s) 3 + highWord (q s) 4 := by
  change (term4.res.toState (v4 s)).getReg .x20 = _
  rw [Radix12RankRegsTry.term4_x20, v4_x20 s h6, v4_x13 s h6]
  rfl

theorem v5_x19 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v5 s).getReg .x19 = rank5Word (q s) := by
  change (term4.res.toState (v4 s)).getReg .x19 = _
  rw [Radix12RankRegsTry.term4_x19]
  simp only [Radix12RankRegsTry.bar4word]
  rw [v4_x19 s h6, v4_x20 s h6, v4_x13 s h6]
  rfl

#print axioms v5_x20
#print axioms v5_x19
end Radix12Rank4
end
-- END Radix12Rank4

-- BEGIN Radix12RankNat from /tmp/sig-radix12-sign/Radix12RankNat.lean
section
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000
namespace Radix12RankNat
open RiscvZkvm.Rv64 Radix12HighSumTry
  Radix12Rank1 Radix12Rank2 Radix12Rank3 Radix12Rank4

abbrev H (q : BitVec 160) (i : Nat) : Nat := (highWord q i).toNat

theorem highSum_eq_H (q : BitVec 160) :
    Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) =
      H q 0 + H q 1 + H q 2 + H q 3 + H q 4 := by
  simp only [H, Radix12.counterSum, Radix12Split.highWords,
    Radix12Split.hi, Radix12Split.B, Radix12.countersQ,
    highWord_nat]

theorem bar1Word_nat (q : BitVec 160)
    (hv : Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) < 381) :
    (bar1Word q).toNat = H q 0 + H q 1 + 1 := by
  rw [highSum_eq_H] at hv
  simp only [H] at hv ⊢
  simp only [bar1Word, BitVec.toNat_add, BitVec.toNat_ofNat]
  norm_num at *
  omega

theorem bar2Word_nat (q : BitVec 160)
    (hv : Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) < 381) :
    (bar2Word q).toNat = H q 0 + H q 1 + H q 2 + 2 := by
  rw [highSum_eq_H] at hv
  simp only [H] at hv ⊢
  simp only [bar2Word, BitVec.toNat_add, BitVec.toNat_ofNat]
  norm_num at *
  omega

theorem bar3Word_nat (q : BitVec 160)
    (hv : Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) < 381) :
    (bar3Word q).toNat = H q 0 + H q 1 + H q 2 + H q 3 + 3 := by
  rw [highSum_eq_H] at hv
  simp only [H] at hv ⊢
  simp only [bar3Word, BitVec.toNat_add, BitVec.toNat_ofNat]
  norm_num at *
  omega

theorem bar4Word_nat (q : BitVec 160)
    (hv : Radix12.counterSum (Radix12Split.highWords (Radix12.countersQ q)) < 381) :
    (bar4Word q).toNat = H q 0 + H q 1 + H q 2 + H q 3 + H q 4 + 4 := by
  rw [highSum_eq_H] at hv
  simp only [H] at hv ⊢
  simp only [bar4Word, BitVec.toNat_add, BitVec.toNat_ofNat]
  norm_num at *
  omega

#print axioms bar1Word_nat
#print axioms bar4Word_nat
end Radix12RankNat
end
-- END Radix12RankNat
