-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import SigGolfCandidate.Packed.Radix12Bundle15

-- BEGIN SignClone12.TreeChain from /tmp/sig-radix12-sign/SignClone12/TreeChain.lean
section

/-! ### cloned TreeChain -/

/-!
# `sign`, tree_build: the chains of one leaf (`tb_chain_loop`, instructions 517 .. 556)

`chains_sim` : from `tb_chain_loop` with `I = 0`, the machine refines the 42 chains of
`buildLeaf` (ends at `LB + 32 + 16 i`, captured values at `SIGL + 8 + 16 i` in leaf `e`).
-/

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

/-- Parameters of the chains of leaf `ep` of tree `(lay, tau)` with capture leaf `e`. -/
structure LeafPar where
  lay : Nat
  tau : Nat
  e : Nat
  ep : Nat
  sigl : Nat

/-- Facts at the start of the chain loop of leaf `ep`. -/
structure ChainCtx (S : List Byte) (x : List Nat) (p : LeafPar) (tl : MachineState) : Prop where
  hlay : p.lay < 7
  htau : p.tau < 2 ^ 30
  he : p.e < 64
  hep : p.ep < 64
  hsigl : p.sigl = 0x900 + 856 * p.lay
  hx : ∀ i, x.getD i 0 < 8
  x5 : tl.getReg .x5 = 0
  x13 : tl.getReg .x13 = BitVec.ofNat 64 p.e
  x18 : tl.getReg .x18 = BitVec.ofNat 64 p.sigl
  x20 : tl.getReg .x20 = BitVec.ofNat 64 p.ep
  dig : ∀ i < 42, tl.getMem (BitVec.ofNat 64 (0x780 + 8 * i)) = BitVec.ofNat 64 (x.getD i 0)
  pb0 : lo32 (tl.getMem (BitVec.ofNat 64 0x6A0)) = BitVec.ofNat 32 (1 + 65536 * p.lay)
  pb8 : tl.getMem (BitVec.ofNat 64 0x6A8) = BitVec.ofNat 64 (p.tau + 2 ^ 32 * p.ep)
  pbP : tl.readWords (BitVec.ofNat 64 0x6B0) 2 = [0, 0]
  pbS : tl.readWords (BitVec.ofNat 64 0x6C0) 4 = wordsOf S
  cb0 : lo32 (tl.getMem (BitVec.ofNat 64 0xC0)) = BitVec.ofNat 32 (0x101 + 65536 * p.lay)
  cb8 : tl.getMem (BitVec.ofNat 64 0xC8) = BitVec.ofNat 64 (p.tau + 2 ^ 32 * p.ep)
  cbP : tl.readWords (BitVec.ofNat 64 0xD0) 4 = [0, 0, 0, 0]

/-- Addresses written by the chain loop. -/
def chainW (p : LeafPar) (a : Nat) : Prop :=
  a = 0x6A0 ∨ a = 0xC0 ∨ (0xF0 ≤ a ∧ a < 0x110) ∨ (0x140 ≤ a ∧ a < 0x160) ∨ (0x360 ≤ a ∧ a < 0x360 + 672) ∨
    (p.ep = p.e ∧ p.sigl + 8 ≤ a ∧ a < p.sigl + 8 + 672)

def chainRegs : List Reg := [.x1, .x2, .x3, .x10, .x11, .x12, .x21, .x23, .x24, .x25, .x29]

/-- Invariant after `i` chains. -/
def ChainInv (p : LeafPar) (tl : MachineState) (i : Nat) (st : List Val × List Val) (t : MachineState) :
    Prop :=
  i ≤ 42 ∧ st.1.length = i ∧ st.2.length = i ∧ (∀ v ∈ st.1, v.length = 16) ∧
  (∀ v ∈ st.2, v.length = 16) ∧ Slots t 0x360 st.1 ∧ (p.ep = p.e → Slots t (p.sigl + 8) st.2) ∧
  t.pc = (if i < 42 then pcOf 486 else pcOf 541) ∧ t.getReg .x21 = BitVec.ofNat 64 i ∧
  t.getReg .x24 = BitVec.ofNat 64 (8 * i) ∧
  RegsEq tl t chainRegs ∧ Frame tl t (chainW p) ∧
  lo32 (t.getMem (BitVec.ofNat 64 0x6A0)) = lo32 (tl.getMem (BitVec.ofNat 64 0x6A0)) ∧
  lo32 (t.getMem (BitVec.ofNat 64 0xC0)) = lo32 (tl.getMem (BitVec.ofNat 64 0xC0))

/-- The paired-secret leaf body as a bind chain. -/
theorem chain_pair_spec (S : List Byte) (lay tau ep k : Nat) (x : List Nat) (st : List Val × List Val) :
    (do
      let (s0, s1) ← prf2 (prfInput S lay tau ep k)
      let (v0, c0) ← chainSteps lay tau ep (2 * k) (x.getD (2 * k) 0) s0
      let (v1, c1) ← chainSteps lay tau ep (2 * k + 1) (x.getD (2 * k + 1) 0) s1
      pure (st.1 ++ [v0, v1], st.2 ++ [c0, c1]) : OracleComp HashSpec (List Val × List Val)) =
    H (prfInput S lay tau ep k) >>= fun a =>
      (chainSteps lay tau ep (2 * k) (x.getD (2 * k) 0) (answerBytes 16 a) >>= fun q =>
        pure (st.1 ++ [q.1], st.2 ++ [q.2])) >>= fun r =>
      chainSteps lay tau ep (2 * k + 1) (x.getD (2 * k + 1) 0) (hiVal a) >>= fun q =>
        pure (r.1 ++ [q.1], r.2 ++ [q.2]) := by
  simp only [prf2_eq, bind_assoc, pure_bind, List.append_assoc, List.cons_append, List.nil_append]

/-- The secret region `SEC` is untouched. -/
def SecPres (s t : MachineState) : Prop :=
  ∀ x, x < 2 ^ 64 → 0x140 ≤ x → x < 0x160 → t.getMem (BitVec.ofNat 64 x) = s.getMem (BitVec.ofNat 64 x)

/-- From the step loop to the end of chain `i` (steps, then instructions 548 .. 556). -/
theorem chain_rest (p : LeafPar) (tl : MachineState) (i xi : Nat) (hi : i < 42) (hxi : xi < 8)
    (st : List Val × List Val) (hl1 : st.1.length = i) (hl2 : st.2.length = i)
    (hv1 : ∀ v ∈ st.1, v.length = 16) (hv2 : ∀ v ∈ st.2, v.length = 16)
    (ts : MachineState) (sctx : StepCtx ⟨p.lay, p.tau, p.e, p.ep, i, xi, p.sigl⟩ ts) (v0 : Val)
    (h0 : StepInv ⟨p.lay, p.tau, p.e, p.ep, i, xi, p.sigl⟩ ts 0 (v0, v0) ts)
    (hends : Slots ts 0x360 st.1) (hcaps : p.ep = p.e → Slots ts (p.sigl + 8) st.2)
    (tregs : RegsEq tl ts chainRegs) (tframe : Frame tl ts (chainW p))
    (tlo1 : lo32 (ts.getMem (BitVec.ofNat 64 0x6A0)) = lo32 (tl.getMem (BitVec.ofNat 64 0x6A0)))
    (tlo2 : lo32 (ts.getMem (BitVec.ofNat 64 0xC0)) = lo32 (tl.getMem (BitVec.ofNat 64 0xC0))) :
    Sim image ts (7 * 29 + 9) ((List.range' 1 7).foldlM (fun (st : Val × Val) mu => do
        let v ← hash16 (chainInput p.lay p.tau p.ep i mu st.1)
        pure (v, if mu = xi then v else st.2)) (v0, v0) >>= fun q =>
          pure (st.1 ++ [q.1], st.2 ++ [q.2]))
      (fun r t' => ChainInv p tl (i + 1) r t' ∧ t'.getReg .x11 = BitVec.ofNat 64 64 ∧ SecPres ts t') := by
  have hsig : p.sigl = 0x900 + 856 * p.lay := sctx.hsigl
  have hl : p.lay < 7 := sctx.hlay
  refine Sim.bind (steps_sim ⟨p.lay, p.tau, p.e, p.ep, i, xi, p.sigl⟩ ts sctx v0 h0)
    (fun q t5 h5 => ?_)
  obtain ⟨-, hq1, hq2, tv5, -, pc5, -, x524, cap5, sregs, sframe, slo⟩ := h5
  have pc5' : t5.pc = pcOf 532 := by rw [pc5]; rfl
  have x521 : t5.getReg .x21 = BitVec.ofNat 64 i := by rw [sregs.get .x21, sctx.x21]
  have hs6 := symRun_sound blk532 codeAt_532 t5 pc5' (by
    simp only [blk532.res, rv_simp]; bvsimp [x521, accessValid_ofNat]; omega)
  have hc6 : blk532.res.cycles = 9 := rfl
  rw [hc6] at hs6
  set t6 := blk532.res.toState t5 with ht6
  have f6 : Frame t5 t6 (fun x => x = 0x360 + 16 * i ∨ x = 0x360 + 16 * i + 8) := by
    apply frame_toState; intro x hx hW
    simp only [blk532.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq]
    bvsimp [x521, ofNat_eq_iff]
    omega
  have r6 : RegsEq t5 t6 [.x1, .x2, .x3, .x21, .x24] := by
    intro r hr; rw [ht6, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have fs6 : Frame ts t6 (fun x => stepW ⟨p.lay, p.tau, p.e, p.ep, i, xi, p.sigl⟩ x ∨
      (x = 0x360 + 16 * i ∨ x = 0x360 + 16 * i + 8)) := sframe.trans f6
  refine Sim.pure_steps hs6 ⟨⟨by omega, by simp [hl1], by simp [hl2], ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_,
    ?_, ?_, ?_⟩, by rw [r6.get .x11, sregs.get .x11, sctx.x11],
    fun x hx h1 h2 => fs6.getMem hx (by dsimp only [stepW]; omega)⟩
  · intro v hv; rcases List.mem_append.mp hv with hv | hv
    · exact hv1 v hv
    · simp at hv; subst hv; exact hq1
  · intro v hv; rcases List.mem_append.mp hv with hv | hv
    · exact hv2 v hv
    · simp at hv; subst hv; exact hq2
  · apply Slots.snoc
    · exact hends.frame fs6 (by omega) (by
        intro j hj; dsimp only [stepW]; constructor <;> omega)
    · rw [hl1, readWords_ofNat_two, ← tv5, readWords_ofNat_two]
      simp only [ht6, blk532.res, rv_simp]
      bvsimp [x521, ofNat_eq_iff]
      simp (disch := bvomega) only [if_pos, if_neg]
  · intro hee
    apply Slots.snoc
    · exact (hcaps hee).frame fs6 (by omega) (by
        intro j hj; dsimp only [stepW]; constructor <;> omega)
    · rw [hl2, f6.readWords _ _ (by omega) (by intro j hj; omega)]
      exact cap5 hee (show xi ≤ 7 by omega)
  · simp only [ht6, blk532.res, rv_simp]
    bvsimp [x521, ofNat_bne_ofNat]
    by_cases h : i + 1 < 42
    · rw [if_pos h, if_pos (by simp; omega)]
    · rw [if_neg h, if_neg (by simp; omega)]
  · simp only [ht6, blk532.res, rv_simp]; bvsimp [x521]
  · simp only [ht6, blk532.res, rv_simp]; bvsimp [x524]
    rw [show 8 * i + 7 + 1 = 8 * (i + 1) by ring]
  · exact ((tregs.trans sregs).trans r6).mono (by decide)
  · exact (tframe.trans fs6).mono (by
      intro x hx; dsimp only [chainW, stepW] at hx ⊢; omega)
  · rw [f6.getMem (by norm_num) (by omega), sframe.getMem (by norm_num) (by dsimp only [stepW]; omega),
      tlo1]
  · rw [f6.getMem (by norm_num) (by omega), slo, tlo2]

/-- The capture at `MU = 0` (instructions 527 .. 532, same code as 540 .. 545). -/
theorem chain_capture (sigl i : Nat) (hsig : sigl < 0x900 + 856 * 7) (hsig8 : sigl % 8 = 0) (hi : i < 42) (t : MachineState)
    (tpc : t.pc = pcOf 507) (t21 : t.getReg .x21 = BitVec.ofNat 64 i)
    (t18 : t.getReg .x18 = BitVec.ofNat 64 sigl) :
    ∃ t', Steps image t 6 6 t' ∧ t'.pc = pcOf 513 ∧ RegsEq t t' [.x1, .x2, .x3] ∧
      Frame t t' (fun x => x = sigl + 8 + 16 * i ∨ x = sigl + 16 + 16 * i) ∧
      t'.readWords (BitVec.ofNat 64 (sigl + 8 + 16 * i)) 2 = t.readWords (BitVec.ofNat 64 0xF0) 2 := by
  have hs := symRun_sound blk507 codeAt_507 t tpc (by
    simp only [blk507.res, rv_simp]; bvsimp [t21, t18, accessValid_ofNat]; omega)
  refine ⟨_, hs, by simp only [blk507.res, rv_simp], ?_, ?_, ?_⟩
  · intro r hr; rw [Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  · apply frame_toState; intro x hx hW
    simp only [blk507.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq]
    bvsimp [t21, t18, ofNat_eq_iff]
    omega
  · rw [readWords_ofNat_two, readWords_ofNat_two]
    simp only [blk507.res, rv_simp]
    bvsimp [t21, t18, ofNat_eq_iff]
    simp (disch := bvomega) only [if_pos, if_neg]

/-- Chain `i` of leaf `ep` from `prf_have` (instruction 492): its secret `s` at `SEC + 16 (i & 1)`. -/
theorem chain_B (x : List Nat) (p : LeafPar) (S : List Byte)
    (tl : MachineState) (ctx : ChainCtx S x p tl) (i : Nat) (hi : i < 42) (s : Val) (hs : s.length = 16)
    (st : List Val × List Val) (hl1 : st.1.length = i) (hl2 : st.2.length = i)
    (hv1 : ∀ v ∈ st.1, v.length = 16) (hv2 : ∀ v ∈ st.2, v.length = 16)
    (t : MachineState) (hends : Slots t 0x360 st.1) (hcaps : p.ep = p.e → Slots t (p.sigl + 8) st.2)
    (tpc : t.pc = pcOf 494) (t21 : t.getReg .x21 = BitVec.ofNat 64 i)
    (t24 : t.getReg .x24 = BitVec.ofNat 64 (8 * i)) (t11 : t.getReg .x11 = BitVec.ofNat 64 64)
    (tsec : t.readWords (BitVec.ofNat 64 (0x140 + 16 * (i % 2))) 2 = wordsOf s)
    (tregs : RegsEq tl t chainRegs) (tframe : Frame tl t (chainW p))
    (tlo1 : lo32 (t.getMem (BitVec.ofNat 64 0x6A0)) = lo32 (tl.getMem (BitVec.ofNat 64 0x6A0)))
    (tlo2 : lo32 (t.getMem (BitVec.ofNat 64 0xC0)) = lo32 (tl.getMem (BitVec.ofNat 64 0xC0))) :
    Sim image t (12 + (1 + (6 + (7 * 29 + 9))))
      (chainSteps p.lay p.tau p.ep i (x.getD i 0) s >>= fun q => pure (st.1 ++ [q.1], st.2 ++ [q.2]))
      (fun r t' => ChainInv p tl (i + 1) r t' ∧ t'.getReg .x11 = BitVec.ofNat 64 64 ∧ SecPres t t') := by
  have hsig := ctx.hsigl
  have hl := ctx.hlay
  have htau := ctx.htau
  have hep := ctx.hep
  have he := ctx.he
  have hxi := ctx.hx i
  have tx5 : t.getReg .x5 = 0 := by rw [tregs.get .x5, ctx.x5]
  have tx13 : t.getReg .x13 = BitVec.ofNat 64 p.e := by rw [tregs.get .x13, ctx.x13]
  have tx18 : t.getReg .x18 = BitVec.ofNat 64 p.sigl := by rw [tregs.get .x18, ctx.x18]
  have tx20 : t.getReg .x20 = BitVec.ofNat 64 p.ep := by rw [tregs.get .x20, ctx.x20]
  have hi2 : i % 2 < 2 := Nat.mod_lt _ (by norm_num)
  -- block 492: secret → CB+48, step setup, digit, test EP = e
  have hs3 := symRun_sound blk494 codeAt_494 t tpc (by
    simp only [blk494.res, rv_simp]
    rw [t21, secAddr i (by omega) 328 (by norm_num), secAddr i (by omega) 320 (by norm_num)]
    bvsimp [accessValid_ofNat, ne_eq, ofNat_eq_iff]; omega)
  have hc3 : blk494.res.cycles = 12 := rfl
  rw [hc3] at hs3
  set t3 := blk494.res.toState t with ht3
  have f3 : Frame t t3 (fun x => x = 0xF0 ∨ x = 0xF8) := by
    apply frame_toState; intro x hx hW
    simp only [blk494.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq, ofNat_eq_iff]
    omega
  have r3 : RegsEq t t3 [.x1, .x2, .x3, .x10, .x12, .x23, .x25] := by
    intro r hr; rw [ht3, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have ft3 : Frame t t3 (fun x => 0xF0 ≤ x ∧ x < 0x110) :=
    f3.mono (by intro x hx; omega)
  have x325 : t3.getReg .x25 = BitVec.ofNat 64 (x.getD i 0) := by
    simp only [ht3, blk494.res, rv_simp]; bvsimp [t21]
    rw [show i * 8 + 1920 = 0x780 + 8 * i by ring, tframe.getMem (by omega) (by simp only [chainW]; omega),
      ctx.dig i hi]
  have x323 : t3.getReg .x23 = BitVec.ofNat 64 0 := by simp only [ht3, blk494.res, rv_simp]
  have x312 : t3.getReg .x12 = BitVec.ofNat 64 0xF0 := by simp only [ht3, blk494.res, rv_simp]
  have v3 : t3.readWords (BitVec.ofNat 64 0xF0) 2 = wordsOf s := by
    rw [← tsec, readWords_ofNat_two, readWords_ofNat_two]
    simp only [ht3, blk494.res, rv_simp, t21]
    rw [secAddr i (by omega) 328 (by norm_num), secAddr i (by omega) 320 (by norm_num)]
    simp (config := { decide := true }) only [↓reduceIte]
    rw [show 328 + 16 * (i % 2) = 0x140 + 16 * (i % 2) + 8 by omega]
  have z3 : t3.readWords (BitVec.ofNat 64 0xD0) 4 = [0, 0, 0, 0] := by
    rw [ft3.readWords _ _ (by norm_num) (by intro i hi; omega),
      tframe.readWords _ _ (by norm_num) (by intro i hi; simp only [chainW]; omega), ctx.cbP]
  have pc3 : t3.pc = if p.ep = p.e then pcOf 506 else pcOf 513 := by
    simp only [ht3, blk494.res, rv_simp, tx20, tx13, ofNat_bne_ofNat]
    by_cases h : p.ep = p.e
    · rw [if_pos h, if_neg (by simp; omega)]
    · rw [if_neg h, if_pos (by simp; omega)]
  -- common continuation from `tb_step_loop`
  have hrest : ∀ ts : MachineState, ts.pc = pcOf 513 → RegsEq t3 ts [.x1, .x2, .x3] →
      Frame t3 ts (fun x => p.ep = p.e ∧ (x = p.sigl + 8 + 16 * i ∨ x = p.sigl + 16 + 16 * i)) →
      (p.ep = p.e → x.getD i 0 ≤ 0 →
        ts.readWords (BitVec.ofNat 64 (p.sigl + 8 + 16 * i)) 2 = wordsOf s) →
      Sim image ts (7 * 29 + 9)
        (chainSteps p.lay p.tau p.ep i (x.getD i 0) s >>= fun q => pure (st.1 ++ [q.1], st.2 ++ [q.2]))
        (fun r t' => ChainInv p tl (i + 1) r t' ∧ t'.getReg .x11 = BitVec.ofNat 64 64 ∧ SecPres t t') := by
    intro ts tspc tsr tsf tscap
    have fts : Frame t ts (fun x => (0xF0 ≤ x ∧ x < 0x110) ∨
        (p.ep = p.e ∧ (x = p.sigl + 8 + 16 * i ∨ x = p.sigl + 16 + 16 * i))) := ft3.trans tsf
    have rts : RegsEq t ts ([.x1, .x2, .x3, .x10, .x12, .x23, .x25] ++ [.x1, .x2, .x3]) :=
      r3.trans tsr
    have sctx : StepCtx ⟨p.lay, p.tau, p.e, p.ep, i, x.getD i 0, p.sigl⟩ ts := by
      refine ⟨hl, htau, he, hep, hi, hxi, hsig, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · rw [rts.get .x5, tx5]
      · rw [rts.get .x11, t11]
      · rw [tsr.get .x12, x312]
      · rw [rts.get .x13, tx13]
      · rw [rts.get .x18, tx18]
      · rw [rts.get .x20, tx20]
      · rw [rts.get .x21, t21]
      · rw [tsr.get .x25, x325]
      · rw [fts.getMem (by norm_num) (by omega), tlo2, ctx.cb0]
      · rw [fts.getMem (by norm_num) (by omega), tframe.getMem (by norm_num) (by simp only [chainW]; omega),
          ctx.cb8]
      · rw [fts.readWords _ _ (by norm_num) (by intro j hj; omega),
          tframe.readWords _ _ (by norm_num) (by intro j hj; simp only [chainW]; omega), ctx.cbP]
    have h0 : StepInv ⟨p.lay, p.tau, p.e, p.ep, i, x.getD i 0, p.sigl⟩ ts 0 (s, s) ts := by
      refine ⟨by norm_num, hs, hs, ?_, ?_, by rw [tspc]; rfl, ?_, ?_, tscap,
        RegsEq.refl _ _, Frame.refl _ _, rfl⟩
      · rw [tsf.readWords _ _ (by norm_num) (by intro j hj; omega), v3]
      · rw [tsf.readWords _ _ (by norm_num) (by intro j hj; omega), z3]
      · rw [tsr.get .x23, x323]
      · show ts.getReg .x24 = BitVec.ofNat 64 (8 * i + 0)
        rw [rts.get .x24, t24, Nat.add_zero]
    have := chain_rest p tl i (x.getD i 0) hi hxi st hl1 hl2 hv1 hv2 ts sctx s h0
      (hends.frame fts (by omega) (by intro j hj; constructor <;> omega))
      (fun hee => (hcaps hee).frame fts (by omega) (by intro j hj; constructor <;> omega))
      ((tregs.trans rts).mono (by decide))
      ((tframe.trans fts).mono (by intro x hx; simp only [chainW] at hx ⊢; omega))
      (by rw [fts.getMem (by norm_num) (by omega), tlo1])
      (by rw [fts.getMem (by norm_num) (by omega), tlo2])
    unfold chainSteps
    exact this.mono (le_refl _) (fun r t' h => ⟨h.1, h.2.1, fun y hy h1 h2 => by
      rw [h.2.2 y hy h1 h2, fts.getMem hy (by omega)]⟩)
  by_cases hee : p.ep = p.e
  · have hs4 := symRun_sound blk506 codeAt_506 t3 (by rw [pc3, if_pos hee])
      (by simp only [blk506.res, rv_simp])
    have hc4 : blk506.res.cycles = 1 := rfl
    rw [hc4] at hs4
    set t4 := blk506.res.toState t3 with ht4
    have f4 : Frame t3 t4 (fun _ => False) := by
      apply frame_toState; intro x hx hW; simp [blk506.res]
    have r4 : RegsEq t3 t4 [] := by
      intro r hr; rw [ht4, Result.toState_getReg]
      cases r <;> first | exact absurd (by decide) hr | rfl
    have pc4 : t4.pc = if x.getD i 0 = 0 then pcOf 507 else pcOf 513 := by
      simp only [ht4, blk506.res, rv_simp, x323, x325, ofNat_bne_ofNat]
      by_cases h : x.getD i 0 = 0
      · rw [if_pos h, if_neg (by rw [bne_cond _ _ (by norm_num) (by omega)]; omega)]
      · rw [if_neg h, if_pos (by rw [bne_cond _ _ (by norm_num) (by omega)]; omega)]
    by_cases hx0 : x.getD i 0 = 0
    · obtain ⟨t5, hs5, pc5, r5, f5, cap5⟩ := chain_capture p.sigl i (by omega) (by omega) hi t4
        (by rw [pc4, if_pos hx0]) (by rw [r4.get .x21, r3.get .x21, t21])
        (by rw [r4.get .x18, r3.get .x18, tx18])
      have := hrest t5 pc5 ((r4.trans r5).mono (by decide))
        ((f4.trans f5).mono (by intro x hx; rcases hx with h | h; exact h.elim; exact ⟨hee, h⟩))
        (fun _ _ => by rw [cap5, f4.readWords _ _ (by norm_num) (by simp), v3])
      exact (Sim.steps hs3 (Sim.steps hs4 (Sim.steps hs5 this))).mono (by norm_num) (fun _ _ h => h)
    · have := hrest t4 (by rw [pc4, if_neg hx0]) (r4.mono (by decide))
        (f4.mono (by intro x hx; exact hx.elim)) (fun _ h => absurd (Nat.le_zero.mp h) hx0)
      exact (Sim.steps hs3 (Sim.steps hs4 this)).mono (by norm_num) (fun _ _ h => h)
  · have := hrest t3 (by rw [pc3, if_neg hee]) (RegsEq.refl _ _) (Frame.refl _ _)
      (fun h => absurd h hee)
    exact (Sim.steps hs3 this).mono (by norm_num) (fun _ _ h => h)

theorem chain_pair (S : List Byte) (hS : S.length = 32) (x : List Nat) (p : LeafPar)
    (tl : MachineState) (ctx : ChainCtx S x p tl) (k : Nat) (hk : k < 21)
    (st : List Val × List Val) (t : MachineState) (hinv : ChainInv p tl (2 * k) st t) :
    Sim image t 480
      (do
        let (s0, s1) ← prf2 (prfInput S p.lay p.tau p.ep k)
        let (v0, c0) ← chainSteps p.lay p.tau p.ep (2 * k) (x.getD (2 * k) 0) s0
        let (v1, c1) ← chainSteps p.lay p.tau p.ep (2 * k + 1) (x.getD (2 * k + 1) 0) s1
        pure (st.1 ++ [v0, v1], st.2 ++ [c0, c1]))
      (ChainInv p tl (2 * k + 2)) := by
  rw [chain_pair_spec]
  obtain ⟨-, hl1, hl2, hv1, hv2, hends, hcaps, tpc, t21, t24, tregs, tframe, tlo1, tlo2⟩ := hinv
  have hsig := ctx.hsigl
  have hl := ctx.hlay
  have htau := ctx.htau
  have hep := ctx.hep
  have tpc' : t.pc = pcOf 486 := by rw [tpc, if_pos (by omega)]
  have tx5 : t.getReg .x5 = 0 := by rw [tregs.get .x5, ctx.x5]
  -- block 484: even
  have hs0 := symRun_sound blk486 codeAt_486 t tpc' (by simp only [blk486.res, rv_simp])
  have hc0 : blk486.res.cycles = 2 := rfl
  rw [hc0] at hs0
  set t1 := blk486.res.toState t with ht1
  have m1 : ∀ z, t1.getMem z = t.getMem z := fun z => by
    rw [ht1, Result.toState_getMem, show blk486.res.st.mem = [] from rfl, memEval_nil]
  have r1 : RegsEq t t1 [.x3] := by
    intro r hr; rw [ht1, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have pc1 : t1.pc = pcOf 488 := by
    simp only [ht1, blk486.res, rv_simp, t21]
    rw [and_one_ofNat _ (by omega), if_neg (by rw [ofNat_bne_ofNat]; simp)]
  -- block 486: the paired prf query
  have hs2 := symRun_sound blk488 codeAt_488 t1 pc1 (by simp only [blk488.res, rv_simp])
  have hc2 : blk488.res.cycles = 5 := rfl
  rw [hc2] at hs2
  set t2 := blk488.res.toState t1 with ht2
  have f2 : Frame t1 t2 (fun x => x = 0x6A0) := by
    apply frame_toState; intro x hx hW
    simp only [blk488.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq, ofNat_eq_iff]
    omega
  have r2 : RegsEq t1 t2 [.x3, .x10, .x11, .x12] := by
    intro r hr; rw [ht2, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have e2 := symRun_ecall blk488 codeAt_488 t1 (by simp only [blk488.res, rv_simp]) rfl
  have x10 : t2.getReg .x10 = BitVec.ofNat 64 0x6A0 := by simp only [ht2, blk488.res, rv_simp]
  have x11 : t2.getReg .x11 = BitVec.ofNat 64 64 := by simp only [ht2, blk488.res, rv_simp]
  have x12 : t2.getReg .x12 = BitVec.ofNat 64 0x140 := by simp only [ht2, blk488.res, rv_simp]
  have x5 : t2.getReg .x5 = 0 := by rw [r2.get .x5, r1.get .x5, tx5]
  have pc2 : t2.pc = pcOf 493 := by simp only [ht2, blk488.res, rv_simp]
  have t121 : t1.getReg .x21 = BitVec.ofNat 64 (2 * k) := by rw [r1.get .x21, t21]
  have m6A0 : t2.getMem (BitVec.ofNat 64 0x6A0) = twWord0 0 p.lay p.tau k := by
    simp only [ht2, blk488.res, rv_simp, t121]
    bvsimp []
    rw [show 2 * k / 2 = k by omega]
    refine (word_of_halves _ (1 + 65536 * p.lay) k (by rw [lo32_replace1, m1, tlo1, ctx.pb0])
      (by rw [hi32_replace1])).trans ?_
    unfold twWord0; congr 1
    rw [Nat.div_eq_of_lt (by omega : p.tau < 2 ^ 32)]; omega
  have ft2 : Frame t t2 (fun x => x = 0x6A0) := fun z hz hW => by rw [f2.getMem hz hW, m1]
  have hq : hashInput t2 = pad64 (prfInput S p.lay p.tau p.ep k) := by
    obtain ⟨hn, hw⟩ := words_prfInput S hS p.lay p.tau p.ep k
    refine hashInput_eq_pad64 t2 _ 0 hn (by rw [x11]) (by norm_num) (by rw [x10]; decide) ?_
    rw [hw, x10, show 8 * (0 + 1) = 1 + 1 + 2 + 4 from rfl]
    rw [readWords_ofNat_add, readWords_ofNat_add, readWords_ofNat_add]
    simp only [Nat.reduceMul, Nat.reduceAdd]
    rw [readWords_ofNat_one, readWords_ofNat_one, m6A0, ft2.getMem (by norm_num) (by norm_num),
      tframe.getMem (by norm_num) (by simp only [chainW]; omega), ctx.pb8,
      ft2.readWords _ _ (by norm_num) (by intro i hi; omega),
      ft2.readWords _ _ (by norm_num) (by intro i hi; omega),
      tframe.readWords _ _ (by norm_num) (by intro i hi; simp only [chainW]; omega),
      tframe.readWords _ _ (by norm_num) (by intro i hi; simp only [chainW]; omega), ctx.pbP, ctx.pbS]
    simp only [twWords_eq, List.cons_append, List.nil_append, List.cons.injEq, and_true, true_and]
    congr 1; omega
  have hb : (pad64 (prfInput S p.lay p.tau p.ep k)).blocks = 1 := by
    simp [pad64, Query.blocks, (words_prfInput S hS p.lay p.tau p.ep k).1]
  refine (Sim.steps hs0 (Sim.steps hs2 (Sim.query_bind (W := 231 + (2 + 231)) e2 x5
    (hashArgs_of x10 x11 x12 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num)
      (by norm_num)) (hq.trans (fmt_thInput _ _ _ _ _ _ (by decide)).symm) (fun a => ?_)))).mono
    (by rw [show prfInput S p.lay p.tau p.ep k = thInput (tweak 0 p.lay p.tau k p.ep) S from rfl] at *; rw [blocks_fmt_th _ _ _ _ _ _ (by decide)]
        rw [hb]; norm_num)
    (fun _ _ h => h)
  set t3 := writeHash t2 a with ht3
  have f3 : Frame t2 t3 (fun x => 0x140 ≤ x ∧ x < 0x140 + 32) := frame_writeHash t2 a _ x12 (by norm_num)
  have pc3 : t3.pc = pcOf 494 := by rw [ht3, writeHash_pc, pc2]; apply BitVec.eq_of_toNat_eq; simp
  have g3 : ∀ q, t3.getReg q = t2.getReg q := fun q => by rw [ht3, writeHash_getReg]
  have ft3 : Frame t t3 (fun x => x = 0x6A0 ∨ (0x140 ≤ x ∧ x < 0x140 + 32)) := ft2.trans f3
  have rt3 : RegsEq tl t3 chainRegs := ((tregs.trans r1).trans r2 |>.trans
    (show RegsEq t2 t3 [] from fun q _ => g3 q)).mono (by decide)
  have hA := chain_B x p S tl ctx (2 * k) (by omega) (answerBytes 16 a) (by simp) st hl1 hl2 hv1 hv2 t3
    (hends.frame ft3 (by omega) (by intro i hi; constructor <;> omega))
    (fun hee => (hcaps hee).frame ft3 (by rw [ctx.hsigl]; omega) (by
      intro i hi; rw [ctx.hsigl]; constructor <;> omega))
    pc3 (by rw [g3, r2.get .x21, t121]) (by rw [g3, r2.get .x24, r1.get .x24, t24])
    (by rw [g3, x11])
    (by rw [show 0x140 + 16 * (2 * k % 2) = 0x140 by omega]; exact sec_lo t2 a x12)
    rt3 ((tframe.trans ft3).mono (by intro x hx; simp only [chainW] at hx ⊢; omega))
    (by rw [f3.getMem (by norm_num) (by omega), m6A0, ctx.pb0]; simp only [twWord0, lo32_ofNat]
        apply BitVec.eq_of_toNat_eq; simp; omega)
    (by rw [ft3.getMem (by norm_num) (by omega), tlo2])
  refine Sim.bind hA (fun r t4 h4 => ?_)
  obtain ⟨⟨-, hl14, hl24, hv14, hv24, hends4, hcaps4, tpc4, t421, t424, tregs4, tframe4, tlo14, tlo24⟩,
    x411, sec4⟩ := h4
  -- block 484: odd
  have hs5 := symRun_sound blk486 codeAt_486 t4 (by rw [tpc4, if_pos (by omega)])
    (by simp only [blk486.res, rv_simp])
  have hc5 : blk486.res.cycles = 2 := rfl
  rw [hc5] at hs5
  set t5 := blk486.res.toState t4 with ht5
  have m5 : ∀ z, t5.getMem z = t4.getMem z := fun z => by
    rw [ht5, Result.toState_getMem, show blk486.res.st.mem = [] from rfl, memEval_nil]
  have r5 : RegsEq t4 t5 [.x3] := by
    intro r hr; rw [ht5, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have pc5 : t5.pc = pcOf 494 := by
    simp only [ht5, blk486.res, rv_simp, t421]
    rw [and_one_ofNat _ (by omega), if_pos (by rw [ofNat_bne_ofNat]; simp)]
  have fr5 : Frame t4 t5 (fun _ => False) := fun z _ _ => m5 _
  have hB := chain_B x p S tl ctx (2 * k + 1) (by omega) (hiVal a) (by simp) r hl14 hl24 hv14 hv24 t5
    (hends4.frame fr5 (by omega) (by simp)) (fun hee => (hcaps4 hee).frame fr5 (by rw [ctx.hsigl]; omega)
      (by simp)) pc5 (by rw [r5.get .x21, t421]) (by rw [r5.get .x24, t424]) (by rw [r5.get .x11, x411])
    (by
      rw [show 0x140 + 16 * ((2 * k + 1) % 2) = 0x150 by omega, readWords_ofNat_two, m5, m5,
        sec4 _ (by norm_num) (by norm_num) (by norm_num), sec4 _ (by norm_num) (by norm_num) (by norm_num),
        ← readWords_ofNat_two]
      exact sec_hi t2 a x12)
    ((tregs4.trans r5).mono (by decide))
    ((tframe4.trans fr5).mono (by intro x hx; rcases hx with h | h; exact h; exact h.elim))
    (by rw [m5, tlo14]) (by rw [m5, tlo24])
  exact (Sim.steps hs5 hB).mono (by norm_num) (fun _ _ h => h.1)

/-- **Chains** `i = 0 .. 41` of leaf `ep` (pairs `k = 0 .. 20`). -/
theorem chains_sim (S : List Byte) (hS : S.length = 32) (x : List Nat) (p : LeafPar)
    (tl : MachineState) (ctx : ChainCtx S x p tl) (hpc : tl.pc = pcOf 486)
    (h21 : tl.getReg .x21 = BitVec.ofNat 64 0) (h24 : tl.getReg .x24 = BitVec.ofNat 64 0) :
    Sim image tl (21 * 480) ((List.range (nChains / 2)).foldlM (fun (st : List Val × List Val) k => do
        let (s0, s1) ← prf2 (prfInput S p.lay p.tau p.ep k)
        let (v0, c0) ← chainSteps p.lay p.tau p.ep (2 * k) (x.getD (2 * k) 0) s0
        let (v1, c1) ← chainSteps p.lay p.tau p.ep (2 * k + 1) (x.getD (2 * k + 1) 0) s1
        pure (st.1 ++ [v0, v1], st.2 ++ [c0, c1])) ([], [])) (ChainInv p tl 42) := by
  unfold nChains
  exact Sim.foldlM_range 21 _ ([], []) (fun k => ChainInv p tl (2 * k)) 480
    (fun k hk st t h => by rw [show 2 * (k + 1) = 2 * k + 2 by ring]; exact chain_pair S hS x p tl ctx k hk st t h)
    ⟨by norm_num, rfl, rfl, by simp, by simp, Slots.nil _ _, fun _ => Slots.nil _ _,
      by simpa using hpc, h21, by simpa using h24, RegsEq.refl _ _, Frame.refl _ _, rfl, rfl⟩

end SigGolfCandidate.Radix12Sign

end
-- END SignClone12.TreeChain

-- BEGIN SignClone12.TreeLeaf from /tmp/sig-radix12-sign/SignClone12/TreeLeaf.lean
section

/-! ### cloned TreeLeaf -/

/-!
# `sign`, tree_build: the leaves (`tb_leaf_loop`, instructions 510 .. 563)

`leaves_sim` : from `tb_leaf_loop` with `EP = 0`, the machine refines `buildLeaves S lay tau h e x`:
leaf `j` in `TA + 16 j`, the captured chain values of leaf `e` at `SIGL + 8 + 16 i`.
-/

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

/-- Parameters of a tree: layer, tree index, height, capture leaf, stage base. -/
structure TreePar where
  lay : Nat
  tau : Nat
  h : Nat
  e : Nat
  sigl : Nat

/-- Facts at the start of tree_build's leaf loop. -/
structure TreeCtx (S : List Byte) (x : List Nat) (p : TreePar) (tt : MachineState) : Prop where
  hlay : p.lay < 7
  htau : p.tau < 2 ^ 30
  hh : p.h ≤ 6
  he : p.e < 2 ^ p.h
  hsigl : p.sigl = 0x900 + 856 * p.lay
  hheight : p.h = height p.lay
  hx : ∀ i, x.getD i 0 < 8
  x5 : tt.getReg .x5 = 0
  x8 : tt.getReg .x8 = BitVec.ofNat 64 p.lay
  x9 : tt.getReg .x9 = BitVec.ofNat 64 p.h
  x13 : tt.getReg .x13 = BitVec.ofNat 64 p.e
  x17 : tt.getReg .x17 = BitVec.ofNat 64 (2 ^ p.h)
  x18 : tt.getReg .x18 = BitVec.ofNat 64 p.sigl
  x19 : tt.getReg .x19 = BitVec.ofNat 64 0x34100
  x30 : tt.getReg .x30 = BitVec.ofNat 64 p.tau
  dig : ∀ i < 42, tt.getMem (BitVec.ofNat 64 (0x780 + 8 * i)) = BitVec.ofNat 64 (x.getD i 0)
  pb0 : lo32 (tt.getMem (BitVec.ofNat 64 0x6A0)) = BitVec.ofNat 32 (1 + 65536 * p.lay)
  pbP : tt.readWords (BitVec.ofNat 64 0x6B0) 2 = [0, 0]
  pbS : tt.readWords (BitVec.ofNat 64 0x6C0) 4 = wordsOf S
  cb0 : lo32 (tt.getMem (BitVec.ofNat 64 0xC0)) = BitVec.ofNat 32 (0x101 + 65536 * p.lay)
  cbP : tt.readWords (BitVec.ofNat 64 0xD0) 4 = [0, 0, 0, 0]
  lb0 : tt.getMem (BitVec.ofNat 64 0x340) = twWord0 2 p.lay p.tau 0
  lbP : tt.readWords (BitVec.ofNat 64 0x350) 2 = [0, 0]
  nbP : tt.readWords (BitVec.ofNat 64 0x1D0) 2 = [0, 0]

/-- Addresses written by the leaf loop. -/
def leavesW (p : TreePar) (a : Nat) : Prop :=
  a = 0x6A0 ∨ a = 0x6A8 ∨ a = 0xC0 ∨ a = 0xC8 ∨ (0xF0 ≤ a ∧ a < 0x110) ∨ (0x140 ≤ a ∧ a < 0x160) ∨ a = 0x348 ∨
    (0x360 ≤ a ∧ a < 0x360 + 672) ∨ (p.sigl + 8 ≤ a ∧ a < p.sigl + 8 + 672) ∨
    (0x34100 ≤ a ∧ a < 0x34100 + 16 * 65)

def leavesRegs : List Reg := [.x1, .x2, .x3, .x10, .x11, .x12, .x20, .x21, .x23, .x24, .x25, .x29]

/-- Invariant after `j` leaves. -/
def TLeafInv (p : TreePar) (tt : MachineState) (j : Nat) (st : List Val × List Val) (t : MachineState) :
    Prop :=
  j ≤ 2 ^ p.h ∧ st.1.length = j ∧ (∀ v ∈ st.1, v.length = 16) ∧ Slots t 0x34100 st.1 ∧
  (p.e < j → st.2.length = 42 ∧ (∀ v ∈ st.2, v.length = 16) ∧ Slots t (p.sigl + 8) st.2) ∧
  t.pc = (if j < 2 ^ p.h then pcOf 479 else pcOf 548) ∧ t.getReg .x20 = BitVec.ofNat 64 j ∧
  RegsEq tt t leavesRegs ∧ Frame tt t (leavesW p) ∧
  lo32 (t.getMem (BitVec.ofNat 64 0x6A0)) = lo32 (tt.getMem (BitVec.ofNat 64 0x6A0)) ∧
  lo32 (t.getMem (BitVec.ofNat 64 0xC0)) = lo32 (tt.getMem (BitVec.ofNat 64 0xC0))

theorem buildLeaf_bind {β : Type} (S : List Byte) (lay tau e : Nat) (x : List Nat)
    (g : Val × List Val → OracleComp HashSpec β) :
    buildLeaf S lay tau e x >>= g =
      (List.range (nChains / 2)).foldlM (fun (st : List Val × List Val) k => do
        let (s0, s1) ← prf2 (prfInput S lay tau e k)
        let (v0, c0) ← chainSteps lay tau e (2 * k) (x.getD (2 * k) 0) s0
        let (v1, c1) ← chainSteps lay tau e (2 * k + 1) (x.getD (2 * k + 1) 0) s1
        pure (st.1 ++ [v0, v1], st.2 ++ [c0, c1])) ([], []) >>= fun st =>
          hash16 (leafInput lay tau e st.1) >>= fun leaf => g (leaf, st.2) := by
  simp only [buildLeaf, bind_assoc, pure_bind]

theorem pow_le32 (h : Nat) (hh : h ≤ 6) : 2 ^ h ≤ 64 :=
  calc 2 ^ h ≤ 2 ^ 6 := Nat.pow_le_pow_right (by norm_num) hh
    _ = 64 := by norm_num

theorem tleaf_body (S : List Byte) (hS : S.length = 32) (x : List Nat) (p : TreePar)
    (tt : MachineState) (ctx : TreeCtx S x p tt) (j : Nat) (hj : j < 2 ^ p.h)
    (st : List Val × List Val) (t : MachineState) (hinv : TLeafInv p tt j st t) :
    Sim image t (7 + (21 * 480 + (4 + (88 + 2))))
      (do
        let (leaf, c) ← buildLeaf S p.lay p.tau j x
        pure (st.1 ++ [leaf], if j = p.e then c else st.2))
      (TLeafInv p tt (j + 1)) := by
  obtain ⟨-, hl1, hv1, hsl, hcap, tpc, t20, tregs, tframe, tlo1, tlo2⟩ := hinv
  have hsig := ctx.hsigl
  have hl := ctx.hlay
  have htau := ctx.htau
  have h32 := pow_le32 p.h ctx.hh
  have he := ctx.he
  have tpc' : t.pc = pcOf 479 := by rw [tpc, if_pos hj]
  have tx30 : t.getReg .x30 = BitVec.ofNat 64 p.tau := by rw [tregs.get .x30, ctx.x30]
  -- block 510: leaf tweak words
  have hs1 := symRun_sound blk479 codeAt_479 t tpc' (by simp only [blk479.res, rv_simp])
  have hc1 : blk479.res.cycles = 7 := rfl
  rw [hc1] at hs1
  set tl := blk479.res.toState t with htl
  have f1 : Frame t tl (fun x => x = 0x6A8 ∨ x = 0xC8 ∨ x = 0x348) := by
    apply frame_toState; intro x hx hW
    simp only [blk479.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq, ofNat_eq_iff]
    omega
  have r1 : RegsEq t tl [.x3, .x21, .x24] := by
    intro r hr; rw [htl, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have hw : ∀ a, a = 0x6A8 ∨ a = 0xC8 ∨ a = 0x348 →
      tl.getMem (BitVec.ofNat 64 a) = BitVec.ofNat 64 (p.tau + 2 ^ 32 * j) := by
    intro a ha
    simp only [htl, blk479.res, rv_simp]
    bvsimp [t20, tx30, ofNat_eq_iff]
    rw [ofNat_or_disjoint (j * 4294967296) p.tau 32 (by omega) (by omega) (by omega)]
    rcases ha with rfl | rfl | rfl <;> simp (disch := bvomega) only [if_pos, if_neg, if_true] <;>
      (congr 1; ring)
  have ft1 : Frame tt tl (leavesW p) := (tframe.trans f1).mono (by
    intro x hx; simp only [leavesW] at hx ⊢; omega)
  have rt1 : RegsEq tt tl leavesRegs := (tregs.trans r1).mono (by decide)
  have cctx : ChainCtx S x ⟨p.lay, p.tau, p.e, j, p.sigl⟩ tl := by
    refine ⟨hl, htau, show p.e < 64 by omega, show j < 64 by omega, hsig, ctx.hx, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · rw [rt1.get .x5, ctx.x5]
    · rw [rt1.get .x13, ctx.x13]
    · rw [rt1.get .x18, ctx.x18]
    · simp only [htl, blk479.res, rv_simp, t20]
    · intro i hi
      rw [ft1.getMem (by omega) (by simp only [leavesW]; omega), ctx.dig i hi]
    · rw [f1.getMem (by norm_num) (by omega), tlo1, ctx.pb0]
    · exact hw _ (Or.inl rfl)
    · rw [ft1.readWords _ _ (by norm_num) (by intro i hi; simp only [leavesW]; omega), ctx.pbP]
    · rw [ft1.readWords _ _ (by norm_num) (by intro i hi; simp only [leavesW]; omega), ctx.pbS]
    · rw [f1.getMem (by norm_num) (by omega), tlo2, ctx.cb0]
    · exact hw _ (Or.inr (Or.inl rfl))
    · rw [ft1.readWords _ _ (by norm_num) (by intro i hi; simp only [leavesW]; omega), ctx.cbP]
  rw [buildLeaf_bind]
  refine Sim.steps hs1 (Sim.bind (chains_sim S hS x ⟨p.lay, p.tau, p.e, j, p.sigl⟩ tl cctx
    (by simp only [htl, blk479.res, rv_simp]) (by simp only [htl, blk479.res, rv_simp])
    (by simp only [htl, blk479.res, rv_simp])) (fun cs t2 h2 => ?_))
  obtain ⟨-, hc1', hc2', hcv1, hcv2, hends, hcaps, pc2, -, -, cregs, cframe, clo1, clo2⟩ := h2
  have pc2' : t2.pc = pcOf 541 := by rw [pc2]; rfl
  have hcaps' : j = p.e → Slots t2 (p.sigl + 8) cs.2 := hcaps
  have rt2 : RegsEq tt t2 (leavesRegs ++ chainRegs) := rt1.trans cregs
  have x220 : t2.getReg .x20 = BitVec.ofNat 64 j := by
    rw [cregs.get .x20]; simp only [htl, blk479.res, rv_simp, t20]
  have x219 : t2.getReg .x19 = BitVec.ofNat 64 0x34100 := by rw [rt2.get .x19, ctx.x19]
  -- block 557: leaf hash
  have hs3 := symRun_sound blk541 codeAt_541 t2 pc2' (by simp only [blk541.res, rv_simp])
  have hc3 : blk541.res.cycles = 4 := rfl
  rw [hc3] at hs3
  set t3 := blk541.res.toState t2 with ht3
  have f3 : Frame t2 t3 (fun _ => False) := by
    apply frame_toState; intro x hx hW; simp [blk541.res]
  have r3 : RegsEq t2 t3 [.x3, .x10, .x11, .x12] := by
    intro r hr; rw [ht3, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have e3 := symRun_ecall blk541 codeAt_541 t2 (by simp only [blk541.res, rv_simp]) rfl
  have x10 : t3.getReg .x10 = BitVec.ofNat 64 0x340 := by simp only [ht3, blk541.res, rv_simp]
  have x11 : t3.getReg .x11 = BitVec.ofNat 64 704 := by simp only [ht3, blk541.res, rv_simp]
  have x12 : t3.getReg .x12 = BitVec.ofNat 64 (0x34100 + 16 * j) := by
    simp only [ht3, blk541.res, rv_simp]; bvsimp [x220, x219]; congr 1; ring
  have x5 : t3.getReg .x5 = 0 := by rw [r3.get .x5, rt2.get .x5, ctx.x5]
  have pc3 : t3.pc = pcOf 545 := by simp only [ht3, blk541.res, rv_simp]
  have fl3 : Frame tl t3 (chainW ⟨p.lay, p.tau, p.e, j, p.sigl⟩) := (cframe.trans f3).mono (by
    intro x hx; rcases hx with h | h; exact h; exact h.elim)
  have hq : hashInput t3 = pad64 (leafInput p.lay p.tau j cs.1) := by
    obtain ⟨hn, hw'⟩ := words_thVals 2 p.lay p.tau 0 j cs.1 hcv1 10 (by rw [hc1'])
    refine hashInput_eq_pad64 t3 _ 10 hn (by rw [x11]) (by norm_num) (by rw [x10]; decide) ?_
    rw [leafInput, hw', x10, show 8 * (10 + 1) = 1 + 1 + 2 + 2 * 42 from rfl]
    rw [readWords_ofNat_add, readWords_ofNat_add, readWords_ofNat_add]
    simp only [Nat.reduceMul, Nat.reduceAdd]
    rw [readWords_ofNat_one, readWords_ofNat_one,
      fl3.getMem (by norm_num) (by dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl]; omega),
      f1.getMem (by norm_num) (by omega), tframe.getMem (by norm_num) (by simp only [leavesW]; omega),
      ctx.lb0, fl3.getMem (by norm_num) (by dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl]; omega), hw _ (Or.inr (Or.inr rfl)),
      fl3.readWords _ _ (by norm_num) (by intro i hi; dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl]; omega),
      ft1.readWords _ _ (by norm_num) (by intro i hi; simp only [leavesW]; omega), ctx.lbP,
      show (84 : Nat) = 2 * cs.1.length by rw [hc1'], f3.readWords _ _ (by rw [hc1']; norm_num) (by simp),
      readWords_slots t2 0x360 cs.1 hends]
    simp only [twWords_eq, twWord0, List.cons_append, List.nil_append, List.cons.injEq, true_and]
    refine ⟨?_, trivial⟩
    congr 1
    rw [Nat.mod_eq_of_lt (by omega : p.tau < 2 ^ 32), Nat.mod_eq_of_lt (by omega : j < 2 ^ 32)]
  have hb : (pad64 (leafInput p.lay p.tau j cs.1)).blocks = 11 :=
    congrArg (· + 1) (words_thVals 2 p.lay p.tau 0 j cs.1 hcv1 10 (by rw [hc1'])).1
  refine (Sim.steps hs3 (Sim.hash16_bind (W := 2) e3 x5
    (hashArgs_of x10 x11 x12 (by norm_num) (by norm_num) (by norm_num) (by omega) (by omega)
      (by norm_num)) hq (fmt_thInput _ _ _ _ _ _ (by decide)) (fun a => ?_))).mono (by rw [hb]) (fun _ _ h => h)
  set t4 := writeHash t3 a with ht4
  have f4 : Frame t3 t4 (fun x => 0x34100 + 16 * j ≤ x ∧ x < 0x34100 + 16 * j + 32) :=
    frame_writeHash t3 a _ x12 (by omega)
  have v4 : t4.readWords (BitVec.ofNat 64 (0x34100 + 16 * j)) 2 = wordsOf (answerBytes 16 a) :=
    writeHash_readWords_val t3 a _ x12 (by omega)
  have pc4 : t4.pc = pcOf 546 := by rw [ht4, writeHash_pc, pc3]; apply BitVec.eq_of_toNat_eq; simp
  have hs5 := symRun_sound blk546 codeAt_546 t4 pc4 (by simp only [blk546.res, rv_simp])
  have hc5 : blk546.res.cycles = 2 := rfl
  rw [hc5] at hs5
  set t5 := blk546.res.toState t4 with ht5
  have f5 : Frame t4 t5 (fun _ => False) := by
    apply frame_toState; intro x hx hW; simp [blk546.res]
  have r5 : RegsEq t4 t5 [.x20] := by
    intro r hr; rw [ht5, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have x420 : t4.getReg .x20 = BitVec.ofNat 64 j := by rw [ht4, writeHash_getReg, r3.get .x20, x220]
  have x417 : t4.getReg .x17 = BitVec.ofNat 64 (2 ^ p.h) := by
    rw [ht4, writeHash_getReg, r3.get .x17, rt2.get .x17, ctx.x17]
  have ftot : Frame t t5 (fun x => (x = 0x6A8 ∨ x = 0xC8 ∨ x = 0x348) ∨
      chainW ⟨p.lay, p.tau, p.e, j, p.sigl⟩ x ∨ (0x34100 + 16 * j ≤ x ∧ x < 0x34100 + 16 * j + 32)) :=
    (f1.trans (fl3.trans f4)).trans f5 |>.mono (by
      intro x hx; rcases hx with (h | h | h) | h
      · exact Or.inl h
      · exact Or.inr (Or.inl h)
      · exact Or.inr (Or.inr h)
      · exact h.elim)
  refine Sim.pure_steps hs5 ⟨by omega, by simp [hl1], ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro v hv; rcases List.mem_append.mp hv with hv | hv
    · exact hv1 v hv
    · simp at hv; subst hv; simp
  · apply Slots.snoc
    · exact hsl.frame ftot (by omega) (by
        intro i hi; dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl]; constructor <;> omega)
    · rw [hl1, f5.readWords _ _ (by omega) (by simp), v4]
  · intro hej
    by_cases hje : j = p.e
    · rw [if_pos hje]
      refine ⟨hc2', hcv2, ?_⟩
      exact (hcaps' hje).frame ((f4.trans f5).mono (fun x hx => hx)) (by omega) (by
        intro i hi; rw [hc2'] at hi; constructor <;> (try simp only [or_false]) <;> omega)
    · rw [if_neg hje]
      obtain ⟨c1, c2, c3⟩ := hcap (by omega)
      refine ⟨c1, c2, c3.frame ftot (by omega) ?_⟩
      intro i hi; rw [c1] at hi; dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl]; constructor <;> omega
  · simp only [ht5, blk546.res, rv_simp, x420, x417, ofNat_add_ofNat, ofNat_bne_ofNat]
    by_cases h : j + 1 < 2 ^ p.h
    · rw [if_pos h, if_pos (by rw [bne_cond _ _ (by omega) (by omega)]; omega)]
    · rw [if_neg h, if_neg (by rw [bne_cond _ _ (by omega) (by omega)]; omega)]
  · simp only [ht5, blk546.res, rv_simp, x420, ofNat_add_ofNat]
  · exact ((((rt2.trans r3).trans (regsEq_writeHash _ _ [])).trans r5)).mono (by decide)
  · exact (tframe.trans ftot).mono (by intro x hx; simp only [leavesW] at hx ⊢; dsimp only [chainW, LeafPar.e, LeafPar.ep, LeafPar.sigl] at hx; omega)
  · rw [f5.getMem (by norm_num) (by simp), f4.getMem (by norm_num) (by omega),
      f3.getMem (by norm_num) (by simp), clo1, f1.getMem (by norm_num) (by omega), tlo1]
  · rw [f5.getMem (by norm_num) (by simp), f4.getMem (by norm_num) (by omega),
      f3.getMem (by norm_num) (by simp), clo2, f1.getMem (by norm_num) (by omega), tlo2]

end SigGolfCandidate.Radix12Sign

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

/-- Cycle bound of one leaf. -/
def tleafCyc : Nat := 7 + (21 * 480 + (4 + (88 + 2)))

/-- **Leaves** `0 .. 2^h - 1` of a tree (with capture of leaf `e`). -/
theorem leaves_sim (S : List Byte) (hS : S.length = 32) (x : List Nat) (p : TreePar)
    (tt : MachineState) (ctx : TreeCtx S x p tt) (hpc : tt.pc = pcOf 479)
    (h20 : tt.getReg .x20 = BitVec.ofNat 64 0) :
    Sim image tt (2 ^ p.h * tleafCyc) (buildLeaves S p.lay p.tau p.h p.e x) (TLeafInv p tt (2 ^ p.h)) := by
  unfold buildLeaves
  exact Sim.foldlM_range (2 ^ p.h) _ ([], []) (TLeafInv p tt) tleafCyc
    (fun j hj st t h => by unfold tleafCyc; exact tleaf_body S hS x p tt ctx j hj st t h)
    ⟨Nat.zero_le _, rfl, by simp, Slots.nil _ _, fun h => absurd h (by omega),
      by rw [hpc, if_pos (Nat.two_pow_pos _)], h20, RegsEq.refl _ _,
      Frame.refl _ _, rfl, rfl⟩

end SigGolfCandidate.Radix12Sign

end
-- END SignClone12.TreeLeaf

-- BEGIN SignClone12.TreeLevel from /tmp/sig-radix12-sign/SignClone12/TreeLevel.lean
section

/-! ### cloned TreeLevel -/

/-!
# `sign`, tree_build: the levels (`tb_level_loop`, instructions 565 .. 603)

`tlevels_sim` : from `tb_level_loop` with `LAM = 1`, `NCNT = 2^h` and the leaves in `TA`, the
machine refines the level fold of `buildLevels (nodeInput lay tau) e h leaves`; the path node of
level `l` is staged at `SIGL + 680 + 16 l`.
-/

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

theorem seg566_eq : seg566 = nodeSegA := rfl
theorem seg583_eq : seg583 = nodeSegB := rfl

theorem codeAt_node566 : CodeAt image (pcOf 566) nodeSegA := seg566_eq ▸ codeAt_566
theorem codeAt_node583 : CodeAt image (pcOf (566 + 17)) nodeSegB := seg583_eq ▸ codeAt_583

/-- Facts at the start of the tree level loop. -/
structure TLevCtx (p : TreePar) (t0 : MachineState) : Prop where
  hlay : p.lay < 7
  htau : p.tau < 2 ^ 30
  hh : 1 ≤ p.h ∧ p.h ≤ 6
  he : p.e < 2 ^ p.h
  hsigl : p.sigl = 0x900 + 856 * p.lay
  hheight : p.h = height p.lay
  x5 : t0.getReg .x5 = 0
  x8 : t0.getReg .x8 = BitVec.ofNat 64 p.lay
  x9 : t0.getReg .x9 = BitVec.ofNat 64 p.h
  x13 : t0.getReg .x13 = BitVec.ofNat 64 p.e
  x18 : t0.getReg .x18 = BitVec.ofNat 64 p.sigl
  x19 : t0.getReg .x19 = BitVec.ofNat 64 0x34100
  x30 : t0.getReg .x30 = BitVec.ofNat 64 p.tau
  nbP : t0.readWords (BitVec.ofNat 64 0x1D0) 2 = [0, 0]

def tlevW (p : TreePar) (a : Nat) : Prop :=
  a = 0x1C0 ∨ a = 0x1C8 ∨ (0x1E0 ≤ a ∧ a < 0x200) ∨ (0x34100 ≤ a ∧ a < 0x34100 + 16 * 65) ∨
    (p.sigl + 680 ≤ a ∧ a < p.sigl + 856)

def tlevRegs : List Reg := [.x1, .x2, .x3, .x10, .x11, .x12, .x15, .x16, .x17, .x29]

/-- Invariant after `j` levels. -/
def TLevInv (p : TreePar) (t0 : MachineState) (j : Nat) (st : List Val × List Val) (t : MachineState) :
    Prop :=
  j ≤ p.h ∧ st.1.length = 2 ^ (p.h - j) ∧ (∀ v ∈ st.1, v.length = 16) ∧ Slots t 0x34100 st.1 ∧
  st.2.length = j ∧ (∀ v ∈ st.2, v.length = 16) ∧ Slots t (p.sigl + 680) st.2 ∧
  t.pc = (if j < p.h then pcOf 549 else pcOf 587) ∧ t.getReg .x15 = BitVec.ofNat 64 (j + 1) ∧
  t.getReg .x17 = BitVec.ofNat 64 (2 ^ (p.h - j)) ∧
  RegsEq t0 t tlevRegs ∧ Frame t0 t (tlevW p)

theorem tlev_path_ne (sigl lay i j m : Nat) (hsig : sigl = 0x900 + 856 * lay) (hl : lay < 7)
    (hij : i < j) (hj : j < 6) (hm : m ≤ 32) :
    ((¬sigl + 680 + 16 * i = 448 ∧ ¬sigl + 680 + 16 * i = 456 ∧
        ¬sigl + 680 + 16 * i = sigl + 680 + 16 * j ∧ ¬sigl + 680 + 16 * i = sigl + 680 + 16 * j + 8) ∧
      ¬(213248 ≤ sigl + 680 + 16 * i ∧ sigl + 680 + 16 * i < 213248 + 32 * m) ∧
        ¬sigl + 680 + 16 * i = 456 ∧ ¬sigl + 680 + 16 * i = 480 ∧
          ¬sigl + 680 + 16 * i = 488 ∧ ¬sigl + 680 + 16 * i = 496 ∧ ¬sigl + 680 + 16 * i = 504) ∧
    ((¬sigl + 680 + 16 * i + 8 = 448 ∧ ¬sigl + 680 + 16 * i + 8 = 456 ∧
        ¬sigl + 680 + 16 * i + 8 = sigl + 680 + 16 * j ∧
          ¬sigl + 680 + 16 * i + 8 = sigl + 680 + 16 * j + 8) ∧
      ¬(213248 ≤ sigl + 680 + 16 * i + 8 ∧ sigl + 680 + 16 * i + 8 < 213248 + 32 * m) ∧
        ¬sigl + 680 + 16 * i + 8 = 456 ∧ ¬sigl + 680 + 16 * i + 8 = 480 ∧
          ¬sigl + 680 + 16 * i + 8 = 488 ∧ ¬sigl + 680 + 16 * i + 8 = 496 ∧
            ¬sigl + 680 + 16 * i + 8 = 504) := by
  subst hsig; omega

theorem tlevel_body (p : TreePar) (t0 : MachineState) (ctx : TLevCtx p t0) (j : Nat) (hj : j < p.h)
    (st : List Val × List Val) (t : MachineState) (hinv : TLevInv p t0 j st t) :
    Sim image t (17 + (2 ^ (p.h - 1 - j) * 26 + 2))
      (levelStep (nodeInput p.lay p.tau) p.e st (1 + j)) (TLevInv p t0 (j + 1)) := by
  obtain ⟨-, hlen, hvals, hslots, hplen, hpvals, hpath, tpc, t15, t17, tregs, tframe⟩ := hinv
  have hsig := ctx.hsigl
  have hl := ctx.hlay
  have htau := ctx.htau
  have hh := ctx.hh
  have he := ctx.he
  have tpc' : t.pc = pcOf 549 := by rw [tpc, if_pos hj]
  have tx5 : t.getReg .x5 = 0 := by rw [tregs.get .x5, ctx.x5]
  have tx8 : t.getReg .x8 = BitVec.ofNat 64 p.lay := by rw [tregs.get .x8, ctx.x8]
  have tx9 : t.getReg .x9 = BitVec.ofNat 64 p.h := by rw [tregs.get .x9, ctx.x9]
  have tx13 : t.getReg .x13 = BitVec.ofNat 64 p.e := by rw [tregs.get .x13, ctx.x13]
  have tx18 : t.getReg .x18 = BitVec.ofNat 64 p.sigl := by rw [tregs.get .x18, ctx.x18]
  have tx19 : t.getReg .x19 = BitVec.ofNat 64 0x34100 := by rw [tregs.get .x19, ctx.x19]
  have tx30 : t.getReg .x30 = BitVec.ofNat 64 p.tau := by rw [tregs.get .x30, ctx.x30]
  have hpow : 2 ^ (p.h - j) = 2 * 2 ^ (p.h - 1 - j) := by
    rw [show p.h - j = p.h - 1 - j + 1 by omega, Nat.pow_succ]; ring
  have hp32 : 2 ^ (p.h - j) ≤ 64 := pow_le32 _ (by omega)
  set sib := (p.e / 2 ^ j) ^^^ 1 with hsib
  have hsib_lt : sib < 2 ^ (p.h - j) := by
    apply xor1_lt _ _ _ (by omega)
    rw [Nat.div_lt_iff_lt_mul (by positivity), ← Nat.pow_add, show p.h - j + j = p.h by omega]
    exact he
  have hudiv : p.e / 2 ^ j ≤ p.e := Nat.div_le_self _ _
  have he32 : p.e < 64 := lt_of_lt_of_le he (pow_le32 _ hh.2)
  -- block 565: capture sibling, node tweak
  have hs1 := symRun_sound blk549 codeAt_549 t tpc' (by
    simp only [blk549.res, rv_simp]
    bvsimp [t15, tx13, tx18, tx19, accessValid_ofNat, ne_eq, ofNat_eq_iff]
    rw [← hsib]; omega)
  have hc1 : blk549.res.cycles = 17 := rfl
  rw [hc1] at hs1
  set t1 := blk549.res.toState t with ht1
  have f1 : Frame t t1 (fun x => x = 0x1C0 ∨ x = 0x1C8 ∨ x = p.sigl + 680 + 16 * j ∨
      x = p.sigl + 680 + 16 * j + 8) := by
    apply frame_toState; intro x hx hW
    simp only [blk549.res, rv_simp, List.forall_mem_cons, List.not_mem_nil, IsEmpty.forall_iff,
      implies_true, and_true, ne_eq]
    bvsimp [t15, tx18, ofNat_eq_iff]
    omega
  have r1 : RegsEq t t1 [.x1, .x2, .x3, .x16, .x17, .x29] := by
    intro r hr; rw [ht1, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have pc1 : t1.pc = pcOf 566 := by simp only [ht1, blk549.res, rv_simp]
  have y16 : t1.getReg .x16 = 0 := by simp only [ht1, blk549.res, rv_simp]
  have y17 : t1.getReg .x17 = BitVec.ofNat 64 (2 ^ (p.h - 1 - j)) := by
    simp only [ht1, blk549.res, rv_simp]
    bvsimp [t17]
    congr 1; rw [hpow]; omega
  have y19 : t1.getReg .x19 = BitVec.ofNat 64 0x34100 := by rw [r1.get .x19, tx19]
  have y5 : t1.getReg .x5 = 0 := by rw [r1.get .x5, tx5]
  have w448 : t1.getMem (BitVec.ofNat 64 448) = twWord0 3 p.lay p.tau 0 := by
    simp only [ht1, blk549.res, rv_simp]
    bvsimp [t15, tx8, tx18, ofNat_eq_iff]
    rw [ofNat_or_disjoint (p.lay * 65536) 769 16 (by omega) (by omega) (by omega)]
    unfold twWord0; congr 1
    rw [Nat.div_eq_of_lt (by omega : p.tau < 2 ^ 32), Nat.mod_eq_of_lt (a := p.lay) (by omega)]
    omega
  have w456 : lo32 (t1.getMem (BitVec.ofNat 64 456)) = BitVec.ofNat 32 p.tau := by
    simp only [ht1, blk549.res, rv_simp]
    bvsimp [t15, tx18, tx30, ofNat_eq_iff]
    rw [lo32_replace0]
  have hcap1 : t1.readWords (BitVec.ofNat 64 (p.sigl + 680 + 16 * j)) 2 =
      wordsOf (st.1.getD sib []) := by
    rw [← hslots.getD sib (by omega), readWords_ofNat_two, readWords_ofNat_two]
    simp only [ht1, blk549.res, rv_simp]
    bvsimp [t15, tx13, tx18, tx19, ofNat_eq_iff]
    simp (disch := bvomega) only [if_pos, if_neg]
    have e : (p.e / 2 ^ j ^^^ 1) * 16 = 16 * sib := by rw [hsib, Nat.mul_comm]
    rw [e, Nat.add_comm (16 * sib) 213248]
  -- node loop
  let c : NodeCtx := ⟨3, p.lay, p.tau, 1 + j, 0x34100, 2 ^ (p.h - 1 - j)⟩
  have hnode := nodeLoop_sim codeAt_node566 codeAt_node583 c st.1 (by simp only [c]; rw [hlen, hpow])
    hvals (by simp only [c]; positivity) (by simp only [c]; norm_num) (by simp only [c])
    (by simp only [c]; omega) t1 pc1 y16 y17 y19 y5 (by simp only [c]; omega)
    (fun j' l r hj' hl hr => by
      simp only [c] at hj' ⊢
      show fmt (nodeInput p.lay p.tau (1 + j) j' l r) =
        pad64 (nodeFmt 3 p.lay p.tau 0 (2 ^ (p.h - 1 - j) + j') l r)
      rw [fmt_nodeInput _ _ _ _ _ _ hl hr (by omega) (by omega) (by omega),
        pad64_len64 _ (length_nodeFmt _ _ _ _ _ _ _ hl hr)]
      unfold heapIndex nodeFmt
      rw [← ctx.hheight, show p.h - (1 + j) = p.h - 1 - j by omega])
    w448 w456
    (by rw [f1.getMem (by norm_num) (by omega), tframe.getMem (by norm_num) (by simp only [tlevW]; omega)]
        have := ctx.nbP; rw [readWords_ofNat_two] at this; simp only [List.cons.injEq] at this
        exact this.1)
    (by rw [f1.getMem (by norm_num) (by omega), tframe.getMem (by norm_num) (by simp only [tlevW]; omega)]
        have := ctx.nbP; rw [readWords_ofNat_two] at this; simp only [List.cons.injEq] at this
        exact this.2.1)
    (hslots.frame f1 (by omega) (by intro i hi; constructor <;> ((try simp only); omega)))
  have hstep : levelStep (nodeInput p.lay p.tau) p.e st (1 + j) =
      buildLevel (nodeFmt 3 p.lay p.tau) (1 + j) st.1 >>= fun level =>
        pure (level, st.2 ++ [st.1.getD sib []]) := by
    simp only [levelStep, hsib, show 1 + j - 1 = j by omega]; rfl
  rw [hstep]
  refine Sim.steps hs1 (Sim.bind hnode (fun acc t2 hn => ?_))
  obtain ⟨-, hacc, haccv, haccs, -, pc2, x216, nregs, nframe⟩ := hn
  have pc2' : t2.pc = pcOf 585 := by rw [pc2, if_neg (lt_irrefl _)]
  have hs3 := symRun_sound blk585 codeAt_585 t2 pc2' (by simp only [blk585.res, rv_simp])
  have hc3 : blk585.res.cycles = 2 := rfl
  rw [hc3] at hs3
  set t3 := blk585.res.toState t2 with ht3
  have r3 : RegsEq t2 t3 [.x15] := by
    intro r hr; rw [ht3, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have f3 : Frame t2 t3 (fun _ => False) := by
    apply frame_toState; intro x hx hW; simp [blk585.res]
  have x215 : t2.getReg .x15 = BitVec.ofNat 64 (j + 1) := by
    rw [nregs.toRegsEq.get .x15, r1.get .x15, t15]
  have x29 : t2.getReg .x9 = BitVec.ofNat 64 p.h := by
    rw [nregs.toRegsEq.get .x9, r1.get .x9, tx9]
  have ft13 : Frame t t3 (fun x => (x = 0x1C0 ∨ x = 0x1C8 ∨ x = p.sigl + 680 + 16 * j ∨
      x = p.sigl + 680 + 16 * j + 8) ∨ ((c.B ≤ x ∧ x < c.B + 32 * c.m) ∨ x = 456 ∨ x = 480 ∨
        x = 488 ∨ x = 496 ∨ x = 504)) := (f1.trans (nframe.toFrame.trans f3)).mono (by
      intro x hx; rcases hx with h | h | h; exact Or.inl h; exact Or.inr h; exact h.elim)
  refine Sim.pure_steps hs3 ⟨by omega, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · rw [hacc, show p.h - (j + 1) = p.h - 1 - j by omega]
  · exact haccv
  · show Slots t3 0x34100 acc
    have hm32 : acc.length ≤ 64 := by
      rw [hacc]; have := pow_le32 (p.h - 1 - j) (by omega); simp only [c]; omega
    exact (show Slots t2 0x34100 acc from haccs).frame f3 (by omega) (by simp)
  · simp [hplen]
  · intro v hv; rcases List.mem_append.mp hv with hv | hv
    · exact hpvals v hv
    · simp at hv; subst hv
      simp only [List.getElem?_eq_getElem (show sib < st.1.length by omega), Option.getD_some]
      exact hvals _ (List.getElem_mem _)
  · apply Slots.snoc
    · have hb : p.sigl + 680 + 16 * st.2.length + 16 < 2 ^ 64 := by rw [hplen]; omega
      refine hpath.frame ft13 hb ?_
      intro i hi
      have hij : i < j := by rw [hplen] at hi; exact hi
      have hm16 : 2 ^ (p.h - 1 - j) ≤ 32 := by
        have := pow_le32 (p.h - j) (by omega)
        have hp : 2 ^ (p.h - j) = 2 * 2 ^ (p.h - 1 - j) := by
          rw [show p.h - j = p.h - 1 - j + 1 by omega, Nat.pow_succ]; ring
        omega
      simp only [c, not_or]
      generalize 2 ^ (p.h - 1 - j) = m at hm16 ⊢
      exact tlev_path_ne p.sigl p.lay i j m hsig hl hij (by omega) hm16
    · rw [hplen, f3.readWords _ _ (by omega) (by simp),
        nframe.toFrame.readWords _ _ (by omega) (by intro i hi; simp only [c]; omega), hcap1]
  · simp only [ht3, blk585.res, rv_simp, x215, x29, ofNat_add_ofNat]
    rw [ofNat_slt_ofNat _ _ (by omega) (by omega)]
    by_cases h : j + 1 < p.h
    · rw [if_pos h]; simp; omega
    · rw [if_neg h]; simp; omega
  · simp only [ht3, blk585.res, rv_simp, x215, ofNat_add_ofNat]
  · rw [r3.get .x17, nregs.toRegsEq.get .x17, y17, show p.h - (j + 1) = p.h - 1 - j by omega]
  · exact (((tregs.trans r1).trans nregs.toRegsEq).trans r3).mono (by decide)
  · exact (tframe.trans ft13).mono (by
      intro x hx; simp only [tlevW, c] at hx ⊢; omega)

end SigGolfCandidate.Radix12Sign

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

/-- **Tree levels** `1 .. h` (with capture of the path of leaf `e`). -/
theorem tlevels_sim (p : TreePar) (t0 : MachineState) (ctx : TLevCtx p t0) (leaves : List Val)
    (hlen : leaves.length = 2 ^ p.h) (hvals : ∀ v ∈ leaves, v.length = 16)
    (hslots : Slots t0 0x34100 leaves) (hpc : t0.pc = pcOf 549) (h15 : t0.getReg .x15 = BitVec.ofNat 64 1)
    (h17 : t0.getReg .x17 = BitVec.ofNat 64 (2 ^ p.h)) :
    Sim image t0 (p.h * 853) ((List.range' 1 p.h).foldlM (levelStep (nodeInput p.lay p.tau) p.e)
      (leaves, [])) (TLevInv p t0 p.h) := by
  have hh := ctx.hh
  apply Sim.foldlM_range' 1 p.h _ _ (TLevInv p t0) 853
  · intro j hj st t h
    refine (tlevel_body p t0 ctx j hj st t h).mono ?_ (fun _ _ h => h)
    have : 2 ^ (p.h - 1 - j) ≤ 32 := by
      have := pow_le32 (p.h - j) (by omega)
      have hp : 2 ^ (p.h - j) = 2 * 2 ^ (p.h - 1 - j) := by
        rw [show p.h - j = p.h - 1 - j + 1 by omega, Nat.pow_succ]; ring
      omega
    omega
  · exact ⟨Nat.zero_le _, by simpa using hlen, hvals, hslots, rfl, by simp, Slots.nil _ _,
      by rw [hpc, if_pos (by omega)], h15, by simpa using h17, RegsEq.refl _ _, Frame.refl _ _⟩

end SigGolfCandidate.Radix12Sign

end
-- END SignClone12.TreeLevel

-- BEGIN SignClone12.Tree from /tmp/sig-radix12-sign/SignClone12/Tree.lean
section

/-! ### cloned Tree -/

/-!
# `sign`, tree_build as a whole (instructions 510 .. 603)

`tree_sim` : from `tb_leaf_loop` (`EP = 0`) the machine refines `buildTree S lay tau h e x`: the
root in `TA[0]`, the captured chain values at `SIGL + 8`, the path at `SIGL + 680`.
-/

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false
set_option linter.unnecessarySeqFocus false

namespace SigGolfCandidate.Radix12Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv SigGolfCandidate.Ref

def treeW (p : TreePar) (a : Nat) : Prop := leavesW p a ∨ tlevW p a

def treeRegs : List Reg := leavesRegs ++ [.x15] ++ tlevRegs

/-- Result of tree_build. -/
def TreePost (p : TreePar) (tt : MachineState) (r : Val × List Val × List Val) (t : MachineState) :
    Prop :=
  t.pc = pcOf 587 ∧ r.1.length = 16 ∧ Slots t 0x34100 [r.1] ∧
  r.2.1.length = 42 ∧ (∀ v ∈ r.2.1, v.length = 16) ∧ Slots t (p.sigl + 8) r.2.1 ∧
  r.2.2.length = p.h ∧ (∀ v ∈ r.2.2, v.length = 16) ∧ Slots t (p.sigl + 680) r.2.2 ∧
  RegsEq tt t treeRegs ∧ Frame tt t (treeW p)

theorem buildTree_eq (S : List Byte) (lay tau h e : Nat) (x : List Nat) :
    buildTree S lay tau h e x =
      buildLeaves S lay tau h e x >>= fun q =>
        (List.range' 1 h).foldlM (levelStep (nodeInput lay tau) e) (q.1, []) >>= fun st =>
          pure (st.1.getD 0 [], q.2, st.2) := by
  simp only [buildTree, buildLevels, bind_assoc, pure_bind]

/-- Cycle bound of tree_build. -/
def treeCyc : Nat := 64 * tleafCyc + (1 + 6 * 853)

theorem tree_sim (S : List Byte) (hS : S.length = 32) (x : List Nat) (p : TreePar)
    (tt : MachineState) (ctx : TreeCtx S x p tt) (h1 : 1 ≤ p.h) (hpc : tt.pc = pcOf 479)
    (h20 : tt.getReg .x20 = BitVec.ofNat 64 0) :
    Sim image tt treeCyc (buildTree S p.lay p.tau p.h p.e x) (TreePost p tt) := by
  have hh := ctx.hh
  have h32 := pow_le32 p.h hh
  have hsig := ctx.hsigl
  have hlay := ctx.hlay
  rw [buildTree_eq]
  have hW : 2 ^ p.h * tleafCyc + (1 + p.h * 853) ≤ treeCyc := by
    unfold treeCyc
    have := Nat.mul_le_mul_right tleafCyc h32
    have := Nat.mul_le_mul_right 853 hh
    omega
  refine (Sim.bind (leaves_sim S hS x p tt ctx hpc h20) (fun q t2 h2 => ?_)).mono hW
    (fun _ _ h => h)
  obtain ⟨-, hlv, hlvv, hlvs, hcap, pc2, -, lregs, lframe, -, -⟩ := h2
  obtain ⟨hc1, hc2, hc3⟩ := hcap ctx.he
  have pc2' : t2.pc = pcOf 548 := by rw [pc2, if_neg (lt_irrefl _)]
  have hs3 := symRun_sound blk548 codeAt_548 t2 pc2' (by simp only [blk548.res, rv_simp])
  have hc67 : blk548.res.cycles = 1 := rfl
  rw [hc67] at hs3
  set t3 := blk548.res.toState t2 with ht3
  have f3 : Frame t2 t3 (fun _ => False) := by
    apply frame_toState; intro x hx hW; simp [blk548.res]
  have r3 : RegsEq t2 t3 [.x15] := by
    intro r hr; rw [ht3, Result.toState_getReg]
    cases r <;> first | exact absurd (by decide) hr | rfl
  have rt3 : RegsEq tt t3 (leavesRegs ++ [.x15]) := lregs.trans r3
  have ft3 : Frame tt t3 (leavesW p) := (lframe.trans f3).mono (by
    intro x hx; rcases hx with h | h; exact h; exact h.elim)
  have vctx : TLevCtx p t3 := by
    refine ⟨ctx.hlay, ctx.htau, ⟨h1, hh⟩, ctx.he, ctx.hsigl, ctx.hheight, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · rw [rt3.get .x5, ctx.x5]
    · rw [rt3.get .x8, ctx.x8]
    · rw [rt3.get .x9, ctx.x9]
    · rw [rt3.get .x13, ctx.x13]
    · rw [rt3.get .x18, ctx.x18]
    · rw [rt3.get .x19, ctx.x19]
    · rw [rt3.get .x30, ctx.x30]
    · have := ctx.hsigl
      rw [ft3.readWords _ _ (by norm_num) (by intro i hi; simp only [leavesW]; omega), ctx.nbP]
  refine (Sim.steps hs3 (Sim.bind (W₂ := 0) (tlevels_sim p t3 vctx q.1 hlv hlvv
    (hlvs.frame f3 (by omega) (by simp)) (by simp only [ht3, blk548.res, rv_simp])
    (by simp only [ht3, blk548.res, rv_simp]) (by rw [rt3.get .x17, ctx.x17]))
    (fun st t4 h4 => ?_))).mono (by omega) (fun _ _ h => h)
  obtain ⟨-, hl4, hv4, hs4, hp4, hpv4, hps4, pc4, -, -, vregs, vframe⟩ := h4
  refine Sim.pure ⟨by rw [pc4, if_neg (lt_irrefl _)], ?_, ?_, hc1, hc2, ?_, hp4, hpv4, hps4, ?_, ?_⟩
  · rw [getD_of_lt (by rw [hl4]; simp)]; exact hv4 _ (List.getElem_mem _)
  · intro i hi
    simp at hi; subst hi
    have := hs4.getD 0 (by rw [hl4]; simp)
    simpa using this
  · refine hc3.frame (f3.trans vframe) (by rw [hc1]; omega) ?_
    intro i hi; rw [hc1] at hi
    have := ctx.hsigl; have := ctx.hlay
    constructor <;> (simp only [tlevW, or_false, false_or]; omega)
  · exact (rt3.trans vregs).mono (by decide)
  · exact (ft3.trans (f3.trans vframe)).mono (by
      intro x hx; simp only [treeW]; rcases hx with h | h | h
      · exact Or.inl h
      · exact h.elim
      · exact Or.inr h)

end SigGolfCandidate.Radix12Sign

end
-- END SignClone12.Tree
