-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import Mathlib
import RiscvZkvm.Rv64.Word
import SigGolfCandidate.Packed.ByteCodec
import SigGolfCandidate.Packed.Radix12Bundle01
import SigGolfCandidate.Packed.Radix12Bundle04
import SigGolfCandidate.Packed.Radix12Bundle07
import SigGolfCandidate.Packed.Radix12Bundle08

-- BEGIN Radix27SignRank from /tmp/sig-radix27-codec/Radix27SignRank.lean
section

namespace Radix27SignRank
open RiscvZkvm.Rv64 Radix27
open SigGolfCandidate.Radix27Images SigGolfCandidate.Rv

def high64 (w : BitVec 32) : Word := w.zeroExtend 64 >>> 16

theorem high64_nat (w : BitVec 32) :
    (high64 w).toNat = (w.extractLsb' 16 16).toNat := by
  simp [high64, BitVec.toNat_ushiftRight, BitVec.extractLsb'_toNat,
    Nat.shiftRight_eq_div_pow]
  have hw := BitVec.isLt w
  omega

theorem horner_nat (a b : Word) (ha : a.toNat < 14348907)
    (hb : b.toNat < 27) :
    (a * 27#64 + b).toNat = a.toNat * 27 + b.toNat := by
  rw [BitVec.toNat_add, BitVec.toNat_mul]
  simp only [BitVec.toNat_ofNat]
  have hm : a.toNat * 27 < 2 ^ 64 := by omega
  rw [Nat.mod_eq_of_lt hm]
  have hs : a.toNat * 27 + b.toNat < 2 ^ 64 := by omega
  exact Nat.mod_eq_of_lt hs

def rankWord (q : BitVec 160) : Word :=
  (((high64 (word q 4) * 27#64 + high64 (word q 3)) * 27#64 +
    high64 (word q 2)) * 27#64 + high64 (word q 1)) * 27#64 +
    high64 (word q 0)

theorem rankWord_nat (q : BitVec 160) (h : validQ q) :
    (rankWord q).toNat = rankQ q := by
  rcases h with ⟨h0, h1, h2, h3, h4⟩
  let a0 := high64 (word q 0)
  let a1 := high64 (word q 1)
  let a2 := high64 (word q 2)
  let a3 := high64 (word q 3)
  let a4 := high64 (word q 4)
  have n0 : a0.toNat = (highQ q 0).toNat := high64_nat _
  have n1 : a1.toNat = (highQ q 1).toNat := high64_nat _
  have n2 : a2.toNat = (highQ q 2).toNat := high64_nat _
  have n3 : a3.toNat = (highQ q 3).toNat := high64_nat _
  have n4 : a4.toNat = (highQ q 4).toNat := high64_nat _
  have b43 : (a4 * 27#64 + a3).toNat = a4.toNat * 27 + a3.toNat :=
    horner_nat a4 a3 (by omega) (by omega)
  have b432 : ((a4 * 27#64 + a3) * 27#64 + a2).toNat =
      (a4.toNat * 27 + a3.toNat) * 27 + a2.toNat := by
    rw [horner_nat _ _ (by rw [b43]; omega) (by omega), b43]
  have b4321 : (((a4 * 27#64 + a3) * 27#64 + a2) * 27#64 + a1).toNat =
      ((a4.toNat * 27 + a3.toNat) * 27 + a2.toNat) * 27 + a1.toNat := by
    rw [horner_nat _ _ (by rw [b432]; omega) (by omega), b432]
  have b43210 : ((((a4 * 27#64 + a3) * 27#64 + a2) * 27#64 + a1) * 27#64 + a0).toNat =
      (((a4.toNat * 27 + a3.toNat) * 27 + a2.toNat) * 27 + a1.toNat) * 27 + a0.toNat := by
    rw [horner_nat _ _ (by rw [b4321]; omega) (by omega), b4321]
  change ((((a4 * 27#64 + a3) * 27#64 + a2) * 27#64 + a1) * 27#64 + a0).toNat = _
  rw [b43210, n0, n1, n2, n3, n4]
  unfold rankQ rank5
  omega

def v0 (s : MachineState) := signFirst.res.toState s
def v1 (s : MachineState) := signValid0.res.toState (v0 s)
def v2 (s : MachineState) := signValid1.res.toState (v1 s)
def v3 (s : MachineState) := signValid2.res.toState (v2 s)
def v4 (s : MachineState) := signValid3.res.toState (v3 s)
def v5 (s : MachineState) := signValid4.res.toState (v4 s)
def v6 (s : MachineState) := signValidEnd.res.toState (v5 s)

theorem valid_rank (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (v6 s).getReg .x14 = rankWord (Radix27SignLoaded.q s) := by
  simp only [v6, v5, v4, v3, v2, v1, v0, Result.toState_getReg,
    signValidEnd.res, signValid4.res, signValid3.res, signValid2.res, signValid1.res,
    signValid0.res, signFirst.res, rv_simp, h6, rankWord,
    Radix27SignLoaded.qword0, Radix27SignLoaded.qword1,
    Radix27SignLoaded.qword2, Radix27SignLoaded.qword3,
    Radix27SignLoaded.qword4]
  simp only [high64, BitVec.toNat_ofNat, Nat.reduceDiv,
    show 8432#64 + 16#64 = 8448#64 by decide,
    show 8432#64 + 8#64 = 8440#64 by decide]

#print axioms high64_nat
#print axioms rankWord_nat
#print axioms valid_rank
end Radix27SignRank
end
-- END Radix27SignRank

-- BEGIN Radix27SignValidSteps from /tmp/sig-radix27-codec/Radix27SignValidSteps.lean
section

namespace Radix27SignValidSteps
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Radix27Images SigGolfCandidate.Rv Radix27

theorem valid_word0_lt (q : BitVec 160) (h : validQ q) :
    (word q 0).toNat < 4194304 := by
  have h0 := h.1
  have hlo := BitVec.isLt (lowQ q 0)
  have hw := word_high_low q 0
  have hn : (word q 0).toNat =
      (highQ q 0).toNat * 65536 + (lowQ q 0).toNat := by
    rw [← hw, toNat_join16]
  norm_num at hlo
  omega

theorem first_pc_valid (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (Radix27SignRank.v0 s).pc = BitVec.ofNat 64 (0x1000 + 4 * 2948) := by
  rw [Radix27SignRank.v0, signFirst_pc s h6]
  have hq : s.getWord32 (BitVec.ofNat 64 0x20F0) =
      word (Radix27SignLoaded.q s) 0 := by
    rw [Radix27SignLoaded.qword0]
    rfl
  rw [hq, if_pos (valid_word0_lt _ hv)]

theorem valid_h13 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (((Radix27SignRank.v0 s).getReg .x13) >>> 16).toNat < 27 := by
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x13 s h6]
  change (Radix27SignRank.high64 (word (Radix27SignLoaded.q s) 4)).toNat < 27
  rw [Radix27SignRank.high64_nat]
  exact hv.2.2.2.2

theorem valid_h12 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (((Radix27SignRank.v1 s).getReg .x12) >>> 16).toNat < 27 := by
  have heq : (Radix27SignRank.v1 s).getReg .x12 =
      (Radix27SignRank.v0 s).getReg .x12 := by
    simp only [Radix27SignRank.v1, Result.toState_getReg,
      signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x12 s h6]
  change (Radix27SignRank.high64 (word (Radix27SignLoaded.q s) 3)).toNat < 27
  rw [Radix27SignRank.high64_nat]
  exact hv.2.2.2.1

theorem valid_h11 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (((Radix27SignRank.v2 s).getReg .x11) >>> 16).toNat < 27 := by
  have heq : (Radix27SignRank.v2 s).getReg .x11 =
      (Radix27SignRank.v0 s).getReg .x11 := by
    simp only [Radix27SignRank.v2, Radix27SignRank.v1,
      Result.toState_getReg, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x11 s h6]
  change (Radix27SignRank.high64 (word (Radix27SignLoaded.q s) 2)).toNat < 27
  rw [Radix27SignRank.high64_nat]
  exact hv.2.2.1

theorem valid_h10 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (((Radix27SignRank.v3 s).getReg .x10) >>> 16).toNat < 27 := by
  have heq : (Radix27SignRank.v3 s).getReg .x10 =
      (Radix27SignRank.v0 s).getReg .x10 := by
    simp only [Radix27SignRank.v3, Radix27SignRank.v2,
      Radix27SignRank.v1, Result.toState_getReg,
      signValid2.res, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x10 s h6]
  change (Radix27SignRank.high64 (word (Radix27SignLoaded.q s) 1)).toNat < 27
  rw [Radix27SignRank.high64_nat]
  exact hv.2.1

theorem valid_h9 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hv : validQ (Radix27SignLoaded.q s)) :
    (((Radix27SignRank.v4 s).getReg .x9) >>> 16).toNat < 27 := by
  have heq : (Radix27SignRank.v4 s).getReg .x9 =
      (Radix27SignRank.v0 s).getReg .x9 := by
    simp only [Radix27SignRank.v4, Radix27SignRank.v3,
      Radix27SignRank.v2, Radix27SignRank.v1,
      Result.toState_getReg, signValid3.res,
      signValid2.res, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x9 s h6]
  change (Radix27SignRank.high64 (word (Radix27SignLoaded.q s) 0)).toNat < 27
  rw [Radix27SignRank.high64_nat]
  exact hv.1

theorem valid_path (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * 2935))
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x3F40)
    (hv : validQ (Radix27SignLoaded.q s)) :
    ∃ k c, Steps signImage s k c (Radix27SignRank.v6 s) ∧
      k < 100 ∧ c < 100 ∧
      (Radix27SignRank.v6 s).pc = BitVec.ofNat 64 (0x1000 + 4 * 2983) := by
  let u0 := Radix27SignRank.v0 s
  let u1 := Radix27SignRank.v1 s
  let u2 := Radix27SignRank.v2 s
  let u3 := Radix27SignRank.v3 s
  let u4 := Radix27SignRank.v4 s
  let u5 := Radix27SignRank.v5 s
  let u6 := Radix27SignRank.v6 s
  have st0 : Steps signImage s 12 12 u0 := signFirst_steps s hpc h6
  have hp0 : u0.pc = BitVec.ofNat 64 (0x1000 + 4 * 2948) := first_pc_valid s h6 hv
  have h16 (u : MachineState) (hu : u = u0 ∨ u = u1 ∨ u = u2 ∨ u = u3 ∨ u = u4) :
      u.getReg .x16 = 27#64 := by
    rcases hu with rfl | rfl | rfl | rfl | rfl <;>
      simp only [u0, u1, u2, u3, u4,
        Radix27SignRank.v4, Radix27SignRank.v3, Radix27SignRank.v2,
        Radix27SignRank.v1, Radix27SignRank.v0,
        Result.toState_getReg, signValid3.res, signValid2.res,
        signValid1.res, signValid0.res, signFirst.res, rv_simp]
  have ho1 : signValid0.res.obligs u0 := by simp only [signValid0.res, rv_simp]
  have st1 : Steps signImage u0 signValid0.res.steps signValid0.res.cycles u1 :=
    symRun_sound signValid0 codeAt_signValid0 u0 hp0 ho1
  have hp1 : u1.pc = BitVec.ofNat 64 (0x1000 + 4 * 2950) :=
    Radix27SignTailProbe.valid0_pc u0 (valid_h13 s h6 hv) (h16 u0 (Or.inl rfl))
  have ho2 : signValid1.res.obligs u1 := by simp only [signValid1.res, rv_simp]
  have st2 : Steps signImage u1 signValid1.res.steps signValid1.res.cycles u2 :=
    symRun_sound signValid1 codeAt_signValid1 u1 hp1 ho2
  have hp2 : u2.pc = BitVec.ofNat 64 (0x1000 + 4 * 2953) :=
    Radix27SignTailProbe.valid1_pc u1 (valid_h12 s h6 hv) (h16 u1 (Or.inr (Or.inl rfl)))
  have ho3 : signValid2.res.obligs u2 := by simp only [signValid2.res, rv_simp]
  have st3 : Steps signImage u2 signValid2.res.steps signValid2.res.cycles u3 :=
    symRun_sound signValid2 codeAt_signValid2 u2 hp2 ho3
  have hp3 : u3.pc = BitVec.ofNat 64 (0x1000 + 4 * 2957) :=
    Radix27SignTailProbe.valid2_pc u2 (valid_h11 s h6 hv)
      (h16 u2 (Or.inr (Or.inr (Or.inl rfl))))
  have ho4 : signValid3.res.obligs u3 := by simp only [signValid3.res, rv_simp]
  have st4 : Steps signImage u3 signValid3.res.steps signValid3.res.cycles u4 :=
    symRun_sound signValid3 codeAt_signValid3 u3 hp3 ho4
  have hp4 : u4.pc = BitVec.ofNat 64 (0x1000 + 4 * 2961) :=
    Radix27SignTailProbe.valid3_pc u3 (valid_h10 s h6 hv)
      (h16 u3 (Or.inr (Or.inr (Or.inr (Or.inl rfl)))))
  have ho5 : signValid4.res.obligs u4 := by simp only [signValid4.res, rv_simp]
  have st5 : Steps signImage u4 signValid4.res.steps signValid4.res.cycles u5 :=
    symRun_sound signValid4 codeAt_signValid4 u4 hp4 ho5
  have hp5 : u5.pc = BitVec.ofNat 64 (0x1000 + 4 * 2965) :=
    Radix27SignTailProbe.valid4_pc u4 (valid_h9 s h6 hv)
      (h16 u4 (Or.inr (Or.inr (Or.inr (Or.inr rfl)))))
  have h7u5 : u5.getReg .x7 = BitVec.ofNat 64 0x3F40 := by
    simpa only [u5, u4, u3, u2, u1, u0,
      Radix27SignRank.v5, Radix27SignRank.v4, Radix27SignRank.v3,
      Radix27SignRank.v2, Radix27SignRank.v1, Radix27SignRank.v0,
      Result.toState_getReg, signValid4.res, signValid3.res,
      signValid2.res, signValid1.res, signValid0.res, signFirst.res,
      rv_simp] using h7
  have ho6 : signValidEnd.res.obligs u5 := signValidEnd_obligs u5 h7u5
  have st6 : Steps signImage u5 signValidEnd.res.steps signValidEnd.res.cycles u6 :=
    symRun_sound signValidEnd codeAt_signValidEnd u5 hp5 ho6
  have hp6 : u6.pc = BitVec.ofNat 64 (0x1000 + 4 * 2983) := by
    simp only [u6, Radix27SignRank.v6, Result.toState_pc, signValidEnd.res, rv_simp]
  have ht := (((((st0.trans st1).trans st2).trans st3).trans st4).trans st5).trans st6
  exact ⟨_, _, ht, by decide, by decide, hp6⟩

end Radix27SignValidSteps
end
-- END Radix27SignValidSteps

-- BEGIN Radix27SignHighs from /tmp/sig-radix27-codec/Radix27SignHighs.lean
section

namespace Radix27SignHighs
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Radix27Images SigGolfCandidate.Rv Radix27

theorem high13_nat (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (((Radix27SignRank.v0 s).getReg .x13) >>> 16).toNat =
      (highQ (Radix27SignLoaded.q s) 4).toNat := by
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x13 s h6]
  exact Radix27SignRank.high64_nat _

theorem high12_nat (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (((Radix27SignRank.v1 s).getReg .x12) >>> 16).toNat =
      (highQ (Radix27SignLoaded.q s) 3).toNat := by
  have heq : (Radix27SignRank.v1 s).getReg .x12 =
      (Radix27SignRank.v0 s).getReg .x12 := by
    simp only [Radix27SignRank.v1, Result.toState_getReg,
      signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x12 s h6]
  exact Radix27SignRank.high64_nat _

theorem high11_nat (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (((Radix27SignRank.v2 s).getReg .x11) >>> 16).toNat =
      (highQ (Radix27SignLoaded.q s) 2).toNat := by
  have heq : (Radix27SignRank.v2 s).getReg .x11 =
      (Radix27SignRank.v0 s).getReg .x11 := by
    simp only [Radix27SignRank.v2, Radix27SignRank.v1,
      Result.toState_getReg, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x11 s h6]
  exact Radix27SignRank.high64_nat _

theorem high10_nat (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (((Radix27SignRank.v3 s).getReg .x10) >>> 16).toNat =
      (highQ (Radix27SignLoaded.q s) 1).toNat := by
  have heq : (Radix27SignRank.v3 s).getReg .x10 =
      (Radix27SignRank.v0 s).getReg .x10 := by
    simp only [Radix27SignRank.v3, Radix27SignRank.v2,
      Radix27SignRank.v1, Result.toState_getReg,
      signValid2.res, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x10 s h6]
  exact Radix27SignRank.high64_nat _

theorem high9_nat (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0) :
    (((Radix27SignRank.v4 s).getReg .x9) >>> 16).toNat =
      (highQ (Radix27SignLoaded.q s) 0).toNat := by
  have heq : (Radix27SignRank.v4 s).getReg .x9 =
      (Radix27SignRank.v0 s).getReg .x9 := by
    simp only [Radix27SignRank.v4, Radix27SignRank.v3,
      Radix27SignRank.v2, Radix27SignRank.v1,
      Result.toState_getReg, signValid3.res,
      signValid2.res, signValid1.res, signValid0.res, rv_simp]
  rw [heq]
  unfold Radix27SignRank.v0
  rw [Radix27SignLoaded.first_x9 s h6]
  exact Radix27SignRank.high64_nat _

#print axioms high13_nat
#print axioms high9_nat
end Radix27SignHighs
end
-- END Radix27SignHighs

-- BEGIN Radix27ByteCodec from /tmp/sig-radix27-codec/Radix27ByteCodec.lean
section

namespace Radix27ByteCodec
open Radix27 SigGolfCandidate.Legacy SigGolfCandidate.Packed SigGolfCandidate.Ref
set_option maxRecDepth 100000

theorem toList_split13 (b : Bytes 6397) :
    toList b = toList (body13 b) ++ toList (n := 13) (trailer13 b) := by
  have h := toList_concat (n := 6384) (m := 13) (body13 b) (trailer13 b)
  have hs : trailer13 b ++ body13 b = b := join13_parts b
  simpa only [hs, BitVec.cast_eq] using h

theorem toList_body13 (b : Bytes 6397) :
    toList (body13 b) = (toList b).take 6384 := by
  rw [toList_split13]
  simp [length_toList]

theorem toList_trailer13 (b : Bytes 6397) :
    toList (n := 13) (trailer13 b) = (toList b).drop 6384 := by
  rw [toList_split13]
  simp [length_toList]

theorem body13_byte (b : Bytes 6397) (i : Nat) (hi : i < 6384) :
    (toList (body13 b)).getD i 0 = (toList b).getD i 0 := by
  rw [toList_body13]
  simp only [List.getD_eq_getElem?_getD, List.getElem?_take, if_pos hi]

theorem trailer13_byte (b : Bytes 6397) (i : Nat) (_hi : i < 13) :
    (toList (n := 13) (trailer13 b)).getD i 0 =
      (toList b).getD (6384 + i) 0 := by
  rw [toList_trailer13]
  simp only [List.getD_eq_getElem?_getD, List.getElem?_drop]

theorem readBuffer_trailer13 (s : RiscvZkvm.Rv64.MachineState) :
    readBuffer s 0x3F40 13 = trailer13 (readBuffer s 0x2650 6397) := by
  apply readBuffer_eq_of_bytes
  intro i hi
  rw [trailer13_byte _ i hi,
    readBuffer_byte s 0x2650 6397 (6384 + i) (by omega)]
  have heq : 0x3F40 + i = 0x2650 + (6384 + i) := by omega
  rw [heq]

theorem toList_expandWitness13 (b : Bytes 6397) :
    toList (expandWitness13 b) =
      toList (body13 b) ++ toList (n := 20) (expand13 (trailer13 b)) := by
  have h := toList_concat (n := 6384) (m := 20)
    (body13 b) (expand13 (trailer13 b))
  change toList (expandWitness13 b) = _
  exact h

theorem expandWitness13_body_byte (b : Bytes 6397) (i : Nat)
    (hi : i < 6384) :
    (toList (expandWitness13 b)).getD i 0 =
      (toList (body13 b)).getD i 0 := by
  rw [toList_expandWitness13]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_left (by rw [length_toList]; exact hi)]

theorem expandWitness13_counter_byte (b : Bytes 6397) (i : Nat)
    (_hi : i < 20) :
    (toList (expandWitness13 b)).getD (6384 + i) 0 =
      (toList (n := 20) (expand13 (trailer13 b))).getD i 0 := by
  rw [toList_expandWitness13]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_right (by rw [length_toList]; omega)]
  simp only [length_toList, Nat.add_sub_cancel_left]

#print axioms readBuffer_trailer13
end Radix27ByteCodec
end
-- END Radix27ByteCodec

-- BEGIN Radix27SignTrailer from /tmp/sig-radix27-codec/Radix27SignTrailer.lean
section

namespace Radix27SignTrailer
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Radix27Images SigGolfCandidate.Rv
  SigGolfCandidate.Packed SigGolfCandidate.Ref SigGolfCandidate.Mem

def tailData (u : MachineState) : BitVec 104 :=
  (u.getReg .x14).truncate 24 ++ (u.getReg .x17).truncate 16 ++
    u.getMem (BitVec.ofNat 64 0x3F40)

theorem tailData_split (u : MachineState) :
    toList (n := 13) (tailData u) =
      toList (n := 8) (u.getMem (BitVec.ofNat 64 0x3F40)) ++
      toList (n := 2) ((u.getReg .x17).truncate 16) ++
      toList (n := 3) ((u.getReg .x14).truncate 24) := by
  unfold tailData
  have h1 := toList_concat (n := 8) (m := 5)
    (u.getMem (BitVec.ofNat 64 0x3F40))
    ((u.getReg .x14).truncate 24 ++ (u.getReg .x17).truncate 16)
  have h2 := toList_concat (n := 2) (m := 3)
    ((u.getReg .x17).truncate 16) ((u.getReg .x14).truncate 24)
  simp only [BitVec.cast_eq] at h1 h2
  rw [h2] at h1
  simpa only [List.append_assoc] using h1

theorem trailer_low_mem (u : MachineState)
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40) :
    (signTrailer.res.toState u).getMem (BitVec.ofNat 64 0x3F40) =
      u.getMem (BitVec.ofNat 64 0x3F40) := by
  simp only [Result.toState_getMem, signTrailer.res, rv_simp, h7]
  simp only [show 16192#64 ≠ 16192#64 + 8#64 by decide, if_false]

theorem tailData_low_byte (u : MachineState) (j : Nat) (hj : j < 8) :
    (toList (n := 13) (tailData u)).getD j 0 =
      (toList (n := 8) (u.getMem (BitVec.ofNat 64 0x3F40))).getD j 0 := by
  rw [tailData_split]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_left (by simp [length_toList]; omega)]
  rw [List.getElem?_append_left (by rw [length_toList]; exact hj)]

theorem tailData_mid_byte (u : MachineState) (j : Nat) (hj : j < 2) :
    (toList (n := 13) (tailData u)).getD (8 + j) 0 =
      (toList (n := 2) ((u.getReg .x17).truncate 16)).getD j 0 := by
  rw [tailData_split]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_left (by simp [length_toList]; omega)]
  rw [List.getElem?_append_right (by rw [length_toList]; omega)]
  simp only [length_toList, Nat.add_sub_cancel_left]

theorem tailData_rank_byte (u : MachineState) (j : Nat) (hj : j < 3) :
    (toList (n := 13) (tailData u)).getD (10 + j) 0 =
      (toList (n := 3) ((u.getReg .x14).truncate 24)).getD j 0 := by
  rw [tailData_split]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_right (by simp [length_toList])]
  simp only [List.length_append, length_toList]
  have heq : 10 + j - (8 + 2) = j := by omega
  rw [heq]

theorem tailData_high_byte (u : MachineState) (j : Nat) (hj : j < 5) :
    (toList (n := 13) (tailData u)).getD (8 + j) 0 =
      (toList (n := 5)
        ((u.getReg .x14).truncate 24 ++ (u.getReg .x17).truncate 16)).getD j 0 := by
  rw [tailData_split]
  have hp := toList_concat (n := 2) (m := 3)
    ((u.getReg .x17).truncate 16) ((u.getReg .x14).truncate 24)
  simp only [BitVec.cast_eq] at hp
  simp only [List.append_assoc]
  rw [← hp]
  simp only [List.getD_eq_getElem?_getD]
  rw [List.getElem?_append_right (by rw [length_toList]; omega)]
  simp only [length_toList, Nat.add_sub_cancel_left]

def trailerHighWord (u : MachineState) : Word :=
  replaceByte
    (replaceWord32 (u.getMem (BitVec.ofNat 64 0x3F48)) 0
      ((u.getReg .x14 <<< 16 ||| u.getReg .x17).truncate 32))
    4 ((u.getReg .x14 >>> 16).truncate 8)

theorem trailer_high_mem (u : MachineState)
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40) :
    (signTrailer.res.toState u).getMem (BitVec.ofNat 64 0x3F48) =
      trailerHighWord u := by
  simp only [Result.toState_getMem, signTrailer.res, rv_simp, h7,
    trailerHighWord]
  simp only [show 16192#64 + 8#64 = 16200#64 by decide, if_true]
  norm_num

theorem trailer_steps (u : MachineState)
    (hpc : u.pc = BitVec.ofNat 64 (0x1000 + 4 * 2983))
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40) :
    Steps signImage u signTrailer.res.steps signTrailer.res.cycles
      (signTrailer.res.toState u) ∧
    fetch signImage (signTrailer.res.toState u) = some (.base .ECALL) ∧
    (signTrailer.res.toState u).getReg .x5 = 1 ∧
    (signTrailer.res.toState u).getReg .x10 = 0 := by
  have ho : signTrailer.res.obligs u := by
    simp only [signTrailer.res, rv_simp, h7]
    decide
  exact ⟨symRun_sound signTrailer codeAt_signTrailer u hpc ho,
    symRun_ecall signTrailer codeAt_signTrailer u ho rfl,
    by simp only [Result.toState_getReg, signTrailer.res, rv_simp],
    by simp only [Result.toState_getReg, signTrailer.res, rv_simp]⟩

theorem rankLow16Word (r : Word) (l : BitVec 16) :
    ((r <<< 16 ||| l.zeroExtend 64).truncate 32) =
      r.truncate 16 ++ l := by
  apply BitVec.eq_of_getLsbD_eq
  intro i hi
  simp only [BitVec.getLsbD_or, BitVec.getLsbD_shiftLeft,
    BitVec.getLsbD_setWidth, BitVec.getLsbD_append]
  interval_cases i <;> simp [BitVec.getLsbD_ofNat, Nat.testBit]

theorem high40_byte (m r : Word) (l : BitVec 16) (j : Nat)
    (hj : j < 5) :
    extractByte
      (replaceByte (replaceWord32 m 0 (r.truncate 16 ++ l)) 4
        ((r >>> 16).truncate 8)) j =
      (toList (n := 5) (r.truncate 24 ++ l)).getD j 0 := by
  interval_cases j <;>
    simp [toList, SigGolfCandidate.Legacy.bytes,
      replaceByte, extractByte,
      replaceWord32, BitVec.truncate_eq_setWidth,
      BitVec.setWidth_ushiftRight_eq_extractLsb] <;>
    bv_normalize <;>
    simp_all [BitVec.extractLsb'_extractLsb'_of_le,
      BitVec.extractLsb'_append_eq_right,
      BitVec.extractLsb'_append_eq_of_add_le,
      BitVec.extractLsb'_append_eq_of_le] <;>
    (have hlast : BitVec.extractLsb' 0 8
        (0#56 ++ BitVec.extractLsb' 16 8 r) = BitVec.extractLsb' 16 8 r :=
          BitVec.extractLsb'_append_eq_right
     simp_all [hlast])

theorem lowReg_eq (x : Word) (hx : x.toNat < 65536) :
    x = (x.truncate 16).zeroExtend 64 := by
  apply BitVec.eq_of_toNat_eq
  simp only [BitVec.zeroExtend, BitVec.truncate,
    BitVec.toNat_setWidth]
  omega

theorem trailer_high_byte (u : MachineState)
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40)
    (hx : (u.getReg .x17).toNat < 65536)
    (j : Nat) (hj : j < 5) :
    (signTrailer.res.toState u).getByte (BitVec.ofNat 64 (0x3F48 + j)) =
      (toList (n := 5)
        ((u.getReg .x14).truncate 24 ++ (u.getReg .x17).truncate 16)).getD j 0 := by
  have ha : alignToDword (BitVec.ofNat 64 (0x3F48 + j)) =
      BitVec.ofNat 64 0x3F48 := by
    apply BitVec.eq_of_toNat_eq
    rw [alignToDword_toNat]
    simp only [BitVec.toNat_ofNat]
    omega
  have hb : byteOffset (BitVec.ofNat 64 (0x3F48 + j)) = j := by
    rw [byteOffset_ofNat (by omega)]
    omega
  simp only [MachineState.getByte]
  rw [ha, hb, trailer_high_mem u h7]
  unfold trailerHighWord
  have htrunc : (((u.getReg .x17).truncate 16).zeroExtend 64).truncate 16 =
      (u.getReg .x17).truncate 16 := by
    simpa only [BitVec.truncate_eq_setWidth, BitVec.zeroExtend_eq_setWidth,
      BitVec.setWidth_eq] using
      (BitVec.setWidth_setWidth_of_le
        ((u.getReg .x17).truncate 16) (by decide : 16 ≤ 64))
  rw [lowReg_eq _ hx, rankLow16Word, htrunc]
  exact high40_byte _ _ _ j hj

theorem trailer_low_byte (u : MachineState)
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40)
    (j : Nat) (hj : j < 8) :
    (signTrailer.res.toState u).getByte (BitVec.ofNat 64 (0x3F40 + j)) =
      u.getByte (BitVec.ofNat 64 (0x3F40 + j)) := by
  have ha : alignToDword (BitVec.ofNat 64 (0x3F40 + j)) =
      BitVec.ofNat 64 0x3F40 := by
    apply BitVec.eq_of_toNat_eq
    rw [alignToDword_toNat]
    simp only [BitVec.toNat_ofNat]
    omega
  simp only [MachineState.getByte]
  rw [ha, trailer_low_mem u h7]

theorem trailer_output (u : MachineState)
    (h7 : u.getReg .x7 = BitVec.ofNat 64 0x3F40)
    (hx : (u.getReg .x17).toNat < 65536) :
    readBuffer (signTrailer.res.toState u) 0x3F40 13 = tailData u := by
  apply readBuffer_eq_of_bytes
  intro i hi
  by_cases hlo : i < 8
  · rw [trailer_low_byte u h7 i hlo, tailData_low_byte u i hlo]
    have ha : alignToDword (BitVec.ofNat 64 (0x3F40 + i)) =
        BitVec.ofNat 64 0x3F40 := by
      apply BitVec.eq_of_toNat_eq
      rw [alignToDword_toNat]
      simp only [BitVec.toNat_ofNat]
      omega
    have hb : byteOffset (BitVec.ofNat 64 (0x3F40 + i)) = i := by
      rw [byteOffset_ofNat (by omega)]
      omega
    simp only [MachineState.getByte]
    rw [ha, hb]
    simp [toList, SigGolfCandidate.Legacy.bytes, hlo, extractByte,
      BitVec.truncate_eq_setWidth,
      BitVec.setWidth_ushiftRight_eq_extractLsb, Nat.mul_comm]
  · have hj : i - 8 < 5 := by omega
    have heq : 0x3F40 + i = 0x3F48 + (i - 8) := by omega
    rw [heq, trailer_high_byte u h7 hx (i - 8) hj]
    have hi' : 8 + (i - 8) = i := by omega
    rw [← hi', tailData_high_byte u (i - 8) hj]
    simp only [Nat.add_sub_cancel_left]

#print axioms rankLow16Word
#print axioms high40_byte

end Radix27SignTrailer
end
-- END Radix27SignTrailer

-- BEGIN Radix27SignReservedPath from /tmp/sig-radix27-codec/Radix27SignReservedPath.lean
section

namespace Radix27SignReservedPath
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Radix27Images SigGolfCandidate.Rv Radix27

def first (s : MachineState) := signFirst.res.toState s
def second (s : MachineState) := signSecond.res.toState (first s)
def reserved (s : MachineState) := signReserved.res.toState (second s)

theorem first_pc_reserved (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hr : reservedMarker (Radix27SignLoaded.q s)) :
    (first s).pc = BitVec.ofNat 64 (0x1000 + 4*2947) := by
  rw [first, signFirst_pc s h6]
  have hf : ¬ (s.getWord32 (BitVec.ofNat 64 0x20F0)).toNat < 4194304 := by
    have h0 := hr.1
    rw [Radix27SignLoaded.qword0] at h0
    simpa only [MachineState.getWord32,
      show alignToDword (8432#64) = 8432#64 by decide,
      show byteOffset (8432#64) / 4 = 0 by decide] using (Nat.not_lt.mpr h0)
  rw [if_neg hf]

theorem first_x19 (s : MachineState) :
    (first s).getReg .x19 = BitVec.ofNat 64 6622613 := by
  simp only [first, Result.toState_getReg, signFirst.res, rv_simp]

theorem second_pc_reserved (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (hr : reservedMarker (Radix27SignLoaded.q s)) :
    (second s).pc = BitVec.ofNat 64 (0x1000 + 4*2973) := by
  have h9 : ((first s).getReg .x9).toNat < 6622613 := by
    rw [first, Radix27SignLoaded.first_x9 s h6]
    have hn := BitVec.isLt (word (Radix27SignLoaded.q s) 0)
    simp only [BitVec.zeroExtend_eq_setWidth, BitVec.toNat_setWidth]
    rw [Nat.mod_eq_of_lt (by omega : (word (Radix27SignLoaded.q s) 0).toNat < 2^64)]
    exact hr.2
  simp only [second, Result.toState_pc, signSecond.res, rv_simp, first_x19]
  simpa [BitVec.ult_eq_decide] using h9

theorem reserved_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4*2935))
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x20F0)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x3F40)
    (hr : reservedMarker (Radix27SignLoaded.q s)) :
    Steps signImage s
      (signFirst.res.steps+signSecond.res.steps+signReserved.res.steps)
      (signFirst.res.cycles+signSecond.res.cycles+signReserved.res.cycles)
      (reserved s) ∧
    (reserved s).pc = BitVec.ofNat 64 (0x1000 + 4*2983) := by
  have st0 := signFirst_steps s hpc h6
  have ho1 : signSecond.res.obligs (first s) := by
    simp only [signSecond.res, rv_simp]
  have st1 := symRun_sound signSecond codeAt_signSecond (first s)
    (first_pc_reserved s h6 hr) ho1
  have h7s : (second s).getReg .x7 = BitVec.ofNat 64 0x3F40 := by
    simpa only [second, first, Result.toState_getReg,
      signSecond.res, signFirst.res, rv_simp] using h7
  have ho2 : signReserved.res.obligs (second s) := by
    simp only [signReserved.res, rv_simp, h7s]
    decide
  have st2 := symRun_sound signReserved codeAt_signReserved (second s)
    (second_pc_reserved s h6 hr) ho2
  constructor
  · exact (st0.trans st1).trans st2
  · simp only [reserved, Result.toState_pc, signReserved.res, rv_simp]

#print axioms reserved_steps
end Radix27SignReservedPath
end
-- END Radix27SignReservedPath

-- BEGIN Radix27ByteLemmas from /tmp/Radix27ByteLemmas.lean
section

namespace Radix27StoreByteTry
open RiscvZkvm.Rv64

theorem byte_ext {w1 w2 : Word}
    (h : ∀ j, j < 8 → extractByte w1 j = extractByte w2 j) : w1 = w2 := by
  apply BitVec.eq_of_getLsbD_eq
  intro p hp
  have hmod : p % 8 < 8 := Nat.mod_lt _ (by decide)
  have h2 : p / 8 * 8 + p % 8 = p := by omega
  have hbit := congrArg (fun bb => bb.getLsbD (p % 8)) (h (p / 8) (by omega))
  simp only [extractByte, BitVec.getLsbD_setWidth, BitVec.getLsbD_ushiftRight, h2, hmod,
    decide_true, Bool.true_and] at hbit
  exact hbit

local macro "byte_algebra" : tactic =>
  `(tactic| (ext i (hi : i < 8); simp [BitVec.truncate, BitVec.zeroExtend];
             try { interval_cases i <;> simp_all }))

theorem byte_replaceHalfword (w : Word) (h : BitVec 16) {pos j : Nat}
    (hpos : pos < 4) (hj : j < 8) :
    extractByte (replaceHalfword w pos h) j
      = if j = 2 * pos then h.truncate 8
        else if j = 2 * pos + 1 then (h >>> 8).truncate 8
        else extractByte w j := by
  interval_cases pos <;> interval_cases j <;>
    simp only [replaceHalfword, extractByte, Nat.reduceMul, Nat.reduceAdd,
      reduceIte, Nat.zero_ne_add_one, Nat.add_one_ne_zero] <;>
    byte_algebra

#print axioms byte_replaceHalfword
end Radix27StoreByteTry
end
-- END Radix27ByteLemmas

-- BEGIN Radix27StoreWords from /tmp/sig-radix27-codec/Radix27StoreWords.lean
section

namespace Radix27StoreWords
open RiscvZkvm.Rv64
open Radix27StoreByteTry

local macro "byte_algebra" : tactic =>
  `(tactic| (ext i (hi : i < 8); simp [BitVec.truncate, BitVec.zeroExtend];
             try { interval_cases i <;> simp_all }))

theorem byte_replaceWord32 (w : Word) (v : BitVec 32) {pos j : Nat}
    (hpos : pos < 2) (hj : j < 8) :
    extractByte (replaceWord32 w pos v) j
      = if j = 4 * pos then v.truncate 8
        else if j = 4 * pos + 1 then (v >>> 8).truncate 8
        else if j = 4 * pos + 2 then (v >>> 16).truncate 8
        else if j = 4 * pos + 3 then (v >>> 24).truncate 8
        else extractByte w j := by
  interval_cases pos <;> interval_cases j <;>
    simp only [replaceWord32, extractByte, Nat.reduceMul, Nat.reduceAdd,
      reduceIte, Nat.zero_ne_add_one, Nat.add_one_ne_zero] <;>
    byte_algebra

theorem two_words (m : Word) (a b : BitVec 32) :
    replaceWord32 (replaceWord32 m 0 a) 1 b = b ++ a := by
  apply byte_ext
  intro j hj
  interval_cases j <;>
    (repeat rw [byte_replaceWord32 _ _ (by decide) (by decide)]) <;>
    simp [extractByte, BitVec.truncate, BitVec.setWidth_ushiftRight_eq_extractLsb]
  case «0» =>
    rw [BitVec.setWidth_eq_extractLsb' (by decide)]
    rw [BitVec.setWidth_eq_extractLsb' (by decide)]
    rw [BitVec.extractLsb'_append_eq_of_add_le (by decide)]
  case «1» => rw [BitVec.extractLsb'_append_eq_of_add_le (by decide)]
  case «2» => rw [BitVec.extractLsb'_append_eq_of_add_le (by decide)]
  case «3» => rw [BitVec.extractLsb'_append_eq_of_add_le (by decide)]
  case «4» =>
    rw [BitVec.extractLsb'_append_eq_of_le (by decide)]
    rw [BitVec.setWidth_eq_extractLsb' (by decide)]
  case «5» => rw [BitVec.extractLsb'_append_eq_of_le (by decide)]
  case «6» => rw [BitVec.extractLsb'_append_eq_of_le (by decide)]
  case «7» => rw [BitVec.extractLsb'_append_eq_of_le (by decide)]

#print axioms two_words
end Radix27StoreWords
end
-- END Radix27StoreWords

-- BEGIN Radix12SplitFallbackBytesSD from /tmp/Radix12SplitFallbackBytesSD.lean
section

namespace Radix12SplitFallbackBytesSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv SigGolfCandidate.Mem
  Radix12SplitExpandImageSD Radix12SplitFinalSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem fallback_word0 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x3F40)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0) :
    (fallback.res.toState s).getMem (BitVec.ofNat 64 0x20F0) =
      extractWord32 (s.getMem 0x3F40) 0 ++ (4194304#32) := by
  simp only [Result.toState_getMem, fallback.res, memEval, Addr.eval,
    E.eval, BinOp.eval, StoreKind.merge, h6, h7]
  simp [UnOp.eval, LoadKind.fromWord, Radix27StoreWords.two_words]

theorem fallback_word1 (s : MachineState)
    (h6 : s.getReg .x6 = BitVec.ofNat 64 0x3F40)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0) :
    (fallback.res.toState s).getMem (BitVec.ofNat 64 0x20F8) =
      extractWord32 (s.getMem 0x3F48) 0 ++
        extractWord32 (s.getMem 0x3F40) 1 := by
  simp only [Result.toState_getMem, fallback.res, memEval, Addr.eval,
    E.eval, BinOp.eval, StoreKind.merge, h6, h7]
  simp [UnOp.eval, LoadKind.fromWord, Radix27StoreWords.two_words]

theorem fallback_word2 (s : MachineState)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0) :
    ((fallback.res.toState s).getMem (BitVec.ofNat 64 0x2100)).extractLsb' 0 32 = 0 := by
  simp only [Result.toState_getMem, fallback.res, memEval, Addr.eval,
    E.eval, BinOp.eval, StoreKind.merge, h7]
  apply BitVec.eq_of_getLsbD_eq
  intro i hi
  interval_cases i <;>
    simp [replaceWord32, BitVec.getLsbD_or, BitVec.getLsbD_and,
      BitVec.getLsbD_not, BitVec.getLsbD_extractLsb',
      BitVec.getLsbD_ofNat, Nat.testBit]

theorem fallback_pc (s : MachineState) :
    (fallback.res.toState s).pc = BitVec.ofNat 64 4580 := by
  simp only [Result.toState_pc, fallback.res, rv_simp]

theorem fallback_mem_frame (s : MachineState) (a : Word)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0)
    (h0 : a ≠ BitVec.ofNat 64 0x20F0)
    (h1 : a ≠ BitVec.ofNat 64 0x20F8)
    (h2 : a ≠ BitVec.ofNat 64 0x2100) :
    (fallback.res.toState s).getMem a = s.getMem a := by
  simp only [Result.toState_getMem, fallback.res, memEval, Addr.eval,
    E.eval, h7]
  simp [h0, h1, h2]

#print axioms fallback_word0
#print axioms fallback_word1
#print axioms fallback_word2
#print axioms fallback_mem_frame

def fallbackCounters (s : MachineState) : BitVec 160 :=
  (0#32) ++
    ((extractWord32 (s.getMem 0x3F48) 0 ++
        extractWord32 (s.getMem 0x3F40) 1) ++
      (extractWord32 (s.getMem 0x3F40) 0 ++ (4194304#32)))

theorem fallback_out_word0 (s : MachineState) :
    (fallbackCounters s).extractLsb' 0 64 =
      extractWord32 (s.getMem 0x3F40) 0 ++ (4194304#32) := by
  unfold fallbackCounters
  rw [BitVec.extractLsb'_append_eq_of_add_le (by decide : 0 + 64 ≤ 128),
    BitVec.extractLsb'_append_eq_right]

theorem fallback_out_word1 (s : MachineState) :
    (fallbackCounters s).extractLsb' 64 64 =
      extractWord32 (s.getMem 0x3F48) 0 ++
        extractWord32 (s.getMem 0x3F40) 1 := by
  simp only [fallbackCounters,
    BitVec.extractLsb'_append_eq_of_add_le (by decide : 64 + 64 ≤ 128),
    BitVec.extractLsb'_append_eq_left]

theorem fallback_out_word2 (s : MachineState) :
    (fallbackCounters s).extractLsb' 128 32 = 0 := by
  unfold fallbackCounters
  simp only [BitVec.extractLsb'_append_eq_left]
  rfl

private theorem nestedExtract {w : Nat} (x : BitVec w) (a l b n : Nat)
    (h : b + n ≤ l) :
    (x.extractLsb' a l).extractLsb' b n = x.extractLsb' (a + b) n := by
  apply BitVec.eq_of_getLsbD_eq
  intro i hi
  simp only [BitVec.getLsbD_extractLsb']
  have hib : b + i < l := by omega
  simp [hi, hib, Nat.add_assoc]

private theorem byteExtract (x : BitVec 64) (i : Nat) :
    extractByte x i = x.extractLsb' (8 * i) 8 := by
  simp only [extractByte, BitVec.truncate_eq_setWidth,
    BitVec.setWidth_ushiftRight_eq_extractLsb, Nat.mul_comm]

theorem fallback_body_byte (s : MachineState)
    (h7 : s.getReg .x7 = 0x20F0) (j : Nat) (hj : j < 6384) :
    (fallback.res.toState s).getByte (BitVec.ofNat 64 (0x800 + j)) =
      s.getByte (BitVec.ofNat 64 (0x800 + j)) := by
  have ha : (alignToDword (BitVec.ofNat 64 (0x800 + j))).toNat < 0x20F0 := by
    rw [alignToDword_toNat, BitVec.toNat_ofNat]
    omega
  have hne (x : Nat) (hx : 0x20F0 ≤ x) (hxb : x < 2 ^ 64) :
      alignToDword (BitVec.ofNat 64 (0x800 + j)) ≠ BitVec.ofNat 64 x := by
    intro h
    rw [h] at ha
    rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt hxb] at ha
    omega
  simp only [MachineState.getByte]
  rw [fallback_mem_frame s _ h7 (hne _ (by omega) (by decide))
    (hne _ (by omega) (by decide)) (hne _ (by omega) (by decide))]

#print axioms fallback_body_byte

theorem fallback_counter_byte (s : MachineState)
    (h6 : s.getReg .x6 = 0x3F40)
    (h7 : s.getReg .x7 = 0x20F0)
    (j : Nat) (hj : j < 20) :
    (fallback.res.toState s).getByte (BitVec.ofNat 64 (0x20F0 + j)) =
      (fallbackCounters s).extractLsb' (8 * j) 8 := by
  have ha : alignToDword (BitVec.ofNat 64 (0x20F0 + j)) =
      BitVec.ofNat 64 (0x20F0 + 8 * (j / 8)) := by
    apply BitVec.eq_of_toNat_eq
    rw [alignToDword_toNat]
    simp only [BitVec.toNat_ofNat]
    omega
  have hb : byteOffset (BitVec.ofNat 64 (0x20F0 + j)) = j % 8 := by
    rw [byteOffset_ofNat (by omega)]
    omega
  simp only [MachineState.getByte]
  rw [ha, hb]
  by_cases hj0 : j < 8
  · have hd : j / 8 = 0 := by omega
    have hm : j % 8 = j := by omega
    simp only [hd, hm, Nat.mul_zero, Nat.add_zero]
    rw [fallback_word0 s h6 h7, byteExtract, ← fallback_out_word0]
    simpa only [Nat.zero_add] using
      nestedExtract (fallbackCounters s) 0 64 (8 * j) 8 (by omega)
  · by_cases hj1 : j < 16
    · have hd : j / 8 = 1 := by omega
      have hm : j % 8 = j - 8 := by omega
      simp only [hd, hm, Nat.mul_one, Nat.reduceAdd]
      rw [fallback_word1 s h6 h7, byteExtract, ← fallback_out_word1]
      rw [nestedExtract (fallbackCounters s) 64 64 (8 * (j - 8)) 8 (by omega)]
      congr 1
      omega
    · have hd : j / 8 = 2 := by omega
      have hm : j % 8 = j - 16 := by omega
      simp only [hd, hm, Nat.reduceMul, Nat.reduceAdd]
      let x := (fallback.res.toState s).getMem (BitVec.ofNat 64 0x2100)
      calc
        extractByte x (j - 16) =
            (x.extractLsb' 0 32).extractLsb' (8 * (j - 16)) 8 := by
          rw [byteExtract]
          simpa only [Nat.zero_add] using
            (nestedExtract x 0 32 (8 * (j - 16)) 8 (by omega)).symm
        _ = ((fallbackCounters s).extractLsb' 128 32).extractLsb'
            (8 * (j - 16)) 8 := by
          exact congrArg (fun v : BitVec 32 => v.extractLsb' (8 * (j - 16)) 8)
            ((fallback_word2 s h7).trans (fallback_out_word2 s).symm)
        _ = (fallbackCounters s).extractLsb' (8 * j) 8 := by
          rw [nestedExtract (fallbackCounters s) 128 32 (8 * (j - 16)) 8 (by omega)]
          congr 1
          omega

#print axioms fallback_counter_byte

end Radix12SplitFallbackBytesSD
end
-- END Radix12SplitFallbackBytesSD

-- BEGIN Radix12SplitFallbackCodecSD from /tmp/Radix12SplitFallbackCodecSD.lean
section

namespace Radix12SplitFallbackCodecSD
open RiscvZkvm.Rv64 Radix12 Radix12Split
  Radix12SplitExpandLoadedSD Radix12SplitFallbackBytesSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem highRank_lt_cap (w : Counter5)
    (h : counterSum (highWords w) < 381) :
    highRank w < Nat.choose 385 5 := by
  have h01 : bar0 (highWords w).c0 <
      bar1 (highWords w).c0 (highWords w).c1 := by simp [bar0, bar1]
  have h12 : bar1 (highWords w).c0 (highWords w).c1 <
      bar2 (highWords w).c0 (highWords w).c1 (highWords w).c2 := by
    simp [bar1, bar2]
  have h23 : bar2 (highWords w).c0 (highWords w).c1 (highWords w).c2 <
      bar3 (highWords w).c0 (highWords w).c1 (highWords w).c2
        (highWords w).c3 := by simp [bar2, bar3]
  have h34 : bar3 (highWords w).c0 (highWords w).c1 (highWords w).c2
      (highWords w).c3 <
      bar4 (highWords w).c0 (highWords w).c1 (highWords w).c2
        (highWords w).c3 (highWords w).c4 := by simp [bar3, bar4]
  have hrank := (rank5_interval h01 h12 h23 h34).2
  have hb : bar4 (highWords w).c0 (highWords w).c1 (highWords w).c2
      (highWords w).c3 (highWords w).c4 + 1 ≤ 385 := by
    simp only [bar4, counterSum] at h ⊢
    omega
  exact lt_of_lt_of_le hrank (Nat.choose_le_choose 5 hb)

theorem decode_bad (p : Fin (2 ^ 96))
    (hcap : Nat.choose 385 5 ≤ highCode p.val) :
    Radix12Split.decode p = badWords p.val := by
  have hneg : ¬(counterSum (highWords (decodedValue p.val)) < 381 ∧
      rankValue (decodedValue p.val) = p.val) := by
    intro h
    have hlt := highRank_lt_cap (decodedValue p.val) h.1
    have hc := highCode_rankValue (decodedValue p.val)
    rw [h.2] at hc
    omega
  change (if counterSum (highWords (decodedValue p.val)) < 381 ∧
      rankValue (decodedValue p.val) = p.val then
        decodedValue p.val else badWords p.val) = badWords p.val
  exact if_neg hneg

theorem chunk (p : BitVec 96) (k : Nat) :
    BitVec.ofNat 32 ((p.toNat / 2 ^ k) % 2 ^ 32) =
      p.extractLsb' k 32 := by
  apply BitVec.eq_of_toNat_eq
  simp only [BitVec.toNat_ofNat, BitVec.extractLsb'_toNat,
    Nat.shiftRight_eq_div_pow]
  exact Nat.mod_mod _ _

theorem trailer_chunk0 (s : RiscvZkvm.Rv64.MachineState) :
    (trailer96 s).extractLsb' 0 32 =
      extractWord32 (s.getMem 0x3F40) 0 := by
  unfold trailer96 trailerHi trailerLo extractWord32
  bv_normalize

theorem trailer_chunk1 (s : RiscvZkvm.Rv64.MachineState) :
    (trailer96 s).extractLsb' 32 32 =
      extractWord32 (s.getMem 0x3F40) 1 := by
  unfold trailer96 trailerHi trailerLo extractWord32
  bv_normalize

theorem trailer_chunk2 (s : RiscvZkvm.Rv64.MachineState) :
    (trailer96 s).extractLsb' 64 32 =
      extractWord32 (s.getMem 0x3F48) 0 := by
  unfold trailer96 trailerHi trailerLo extractWord32
  bv_normalize

theorem fallbackCounters_eq (s : RiscvZkvm.Rv64.MachineState) :
    fallbackCounters s =
      encodeWords (badWords (trailer96 s).toNat) := by
  simp only [fallbackCounters, encodeWords, badWords]
  have h0 := chunk (trailer96 s) 0
  simp only [Nat.pow_zero, Nat.div_one] at h0
  rw [h0, chunk (trailer96 s) 32, chunk (trailer96 s) 64]
  rw [trailer_chunk0, trailer_chunk1, trailer_chunk2]
  have hc : (4194304#32) = BitVec.ofNat 32 (2 ^ 22) := by decide
  simp only [BitVec.append_assoc, BitVec.cast_eq, hc]

#print axioms decode_bad
#print axioms chunk
#print axioms fallbackCounters_eq
end Radix12SplitFallbackCodecSD
end
-- END Radix12SplitFallbackCodecSD

-- BEGIN Radix12SplitFallbackBufferSD from /tmp/Radix12SplitFallbackBufferSD.lean
section

namespace Radix12SplitFallbackBufferSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Ref SigGolfCandidate.Mem SigGolfCandidate.Packed
  Radix12SplitExpandImageSD Radix12SplitFinalSD Radix12SplitFallbackBytesSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem toList_join (s : MachineState) :
    toList (n := 6404) ((fallbackCounters s) ++ readBuffer s 0x800 6384) =
      toList (readBuffer s 0x800 6384) ++
        toList (n := 20) (fallbackCounters s) := by
  exact toList_concat (n := 6384) (m := 20)
    (readBuffer s 0x800 6384) (fallbackCounters s)

theorem fallback_readBuffer (s : MachineState)
    (h6 : s.getReg .x6 = 0x3F40)
    (h7 : s.getReg .x7 = 0x20F0) :
    readBuffer (fallback.res.toState s) 0x800 6404 =
      (fallbackCounters s) ++ readBuffer s 0x800 6384 := by
  apply readBuffer_eq_of_bytes
  intro i hi
  rw [toList_join]
  by_cases hb : i < 6384
  · rw [fallback_body_byte s h7 i hb]
    rw [List.getD_eq_getElem?_getD,
      List.getElem?_append_left (by rw [length_toList]; exact hb)]
    exact (readBuffer_byte s 0x800 6384 i hb).symm
  · have hj : i - 6384 < 20 := by omega
    have heq : 0x800 + i = 0x20F0 + (i - 6384) := by omega
    rw [heq, fallback_counter_byte s h6 h7 (i - 6384) hj]
    rw [List.getD_eq_getElem?_getD,
      List.getElem?_append_right (by rw [length_toList]; omega),
      length_toList]
    simpa only [List.getD_eq_getElem?_getD, SigGolfCandidate.Ref.toList] using
      (getD_bytes (fallbackCounters s) (i - 6384) hj).symm

#print axioms fallback_readBuffer
end Radix12SplitFallbackBufferSD
end
-- END Radix12SplitFallbackBufferSD

-- BEGIN Radix12SplitFallbackStartSD from /tmp/Radix12SplitFallbackStartSD.lean
section

namespace Radix12SplitFallbackStartSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv SigGolfCandidate.Expand Radix12SplitExpandImageSD
  Radix12SplitExpandPreludeSD Radix12SplitExpandFirstSD
  Radix12SplitTrailerBridgeSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem start_invalid_refined (m : Message) (pk : PublicKey)
    (σ : Bytes 6396) :
    let p := Radix12Split.trailer σ
    let code := (p.extractLsb' 60 36).toNat
    ∃ v, Steps expandImage (Radix12SplitInitTable.initState m pk σ)
        (runPre.res.steps + 1596 * 6 + runCtr.res.steps + first7.res.steps)
        (runPre.res.cycles + 1596 * 6 + runCtr.res.cycles + first7.res.cycles) v ∧
      v.pc = BitVec.ofNat 64 4184 ∧
      v.getReg .x10 = BitVec.ofNat 64 code ∧
      v.getReg .x6 = BitVec.ofNat 64 0x3F40 ∧
      v.getReg .x7 = BitVec.ofNat 64 0x20F0 ∧
      Radix12SplitExpandLoadedSD.trailer96 v = p ∧
      readBuffer v 0x800 6384 = Radix12Split.body σ := by
  let t := Radix12SplitInitTable.initState m pk σ
  obtain ⟨v,hstep,hpc,h10,_h8,_h2,h7,_htable,hbody⟩ :=
    Radix12SplitStartRefinedSD.start_refined m pk σ
  have htpc : t.pc = 0x1000 := by
    simp only [t, Radix12SplitInitTable.initState, MachineState.pc_setReg,
      MachineState.pc_writeBytesAsWords]
  obtain ⟨u,hstage,hupc,hcopy⟩ :=
    body_stage t htpc (fun a => t.getByte (BitVec.ofNat 64 a))
      (by intro a ha; rfl)
  obtain ⟨hctr,h6c,hcpc⟩ := ctr_steps u hupc
  let c := runCtr.res.toState u
  let v' := first7.res.toState c
  have hfirst : Steps expandImage c first7.res.steps first7.res.cycles v' :=
    first7_steps c hcpc h6c
  have hstep' : Steps expandImage t
      (runPre.res.steps + 1596 * 6 + runCtr.res.steps + first7.res.steps)
      (runPre.res.cycles + 1596 * 6 + runCtr.res.cycles + first7.res.cycles) v' :=
    Steps.of_eq (hstage.trans (hctr.trans hfirst)) (by omega) (by omega)
  have heq : v = v' := Radix12SplitStepsDet.steps_det hstep hstep'
  subst v
  have h6 : v'.getReg .x6 = 0x3F40 := by
    simp only [v', Result.toState_getReg, first7.res, rv_simp]
    exact h6c
  have hvtr : Radix12SplitExpandLoadedSD.trailer96 v' =
      Radix12SplitExpandLoadedSD.trailer96 c := by
    simp only [Radix12SplitExpandLoadedSD.trailer96,
      Radix12SplitExpandLoadedSD.trailerHi,
      Radix12SplitExpandLoadedSD.trailerLo, v', first7_mem]
  have hcutr : Radix12SplitExpandLoadedSD.trailer96 c =
      Radix12SplitExpandLoadedSD.trailer96 u := by
    simp only [Radix12SplitExpandLoadedSD.trailer96,
      Radix12SplitExpandLoadedSD.trailerHi,
      Radix12SplitExpandLoadedSD.trailerLo, c, ctr_mem]
  have hut : Radix12SplitExpandLoadedSD.trailer96 u =
      Radix12Split.trailer σ :=
    (trailer_preserved_copy t u hcopy).trans (initState_trailer m pk σ)
  exact ⟨v',hstep,hpc,h10,h6,h7,hvtr.trans (hcutr.trans hut),hbody⟩

#print axioms start_invalid_refined
end Radix12SplitFallbackStartSD
end
-- END Radix12SplitFallbackStartSD

-- BEGIN Radix12SplitFallbackPhaseSD from /tmp/Radix12SplitFallbackPhaseSD.lean
section

namespace Radix12SplitFallbackPhaseSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv SigGolfCandidate.Mem
  Radix12SplitExpandImageSD Radix12SplitFinalSD Radix12SplitFinalFlowSD
  Radix12SplitSetupSD Radix12SplitFallbackSD
  Radix12SplitFallbackBytesSD Radix12SplitFallbackBufferSD
  Radix12SplitFallbackCodecSD Radix12SplitExpandLoadedSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem highCode_trailer (p : BitVec 96) :
    Radix12Split.highCode p.toNat = (p.extractLsb' 60 36).toNat := by
  unfold Radix12Split.highCode
  rw [BitVec.extractLsb'_toNat, Nat.shiftRight_eq_div_pow]
  have hp : p.toNat / 2 ^ 60 < 2 ^ 36 := by
    have h := p.isLt
    omega
  exact (Nat.mod_eq_of_lt hp).symm

theorem fallback_phase (v : MachineState) (p : BitVec 96)
    (hpc : v.pc = BitVec.ofNat 64 4184)
    (h10 : v.getReg .x10 = BitVec.ofNat 64
      (p.extractLsb' 60 36).toNat)
    (h6 : v.getReg .x6 = BitVec.ofNat 64 0x3F40)
    (h7 : v.getReg .x7 = BitVec.ofNat 64 0x20F0)
    (htr : trailer96 v = p)
    (hcap : Nat.choose 385 5 ≤ (p.extractLsb' 60 36).toNat) :
    ∃ u, Steps expandImage v
        (setup.res.steps + fallback.res.steps + done.res.steps)
        (setup.res.cycles + fallback.res.cycles + done.res.cycles) u ∧
      fetch expandImage u = some (.base .ECALL) ∧
      u.getReg .x5 = 1 ∧ u.getReg .x10 = 0 ∧
      readBuffer u 0x800 6404 =
        Radix12Split.expandSplit p ++ readBuffer v 0x800 6384 := by
  let a := setup.res.toState v
  let b := fallback.res.toState a
  let u := done.res.toState b
  have hs : Steps expandImage v setup.res.steps setup.res.cycles a :=
    setup_steps v hpc
  have hpc_a : a.pc = BitVec.ofNat 64 4544 :=
    setup_pc_invalid v _ h10 hcap (p.extractLsb' 60 36).isLt
  have h6a : a.getReg .x6 = 0x3F40 := by
    simp only [a, Result.toState_getReg, setup.res, rv_simp]
    exact h6
  have h7a : a.getReg .x7 = 0x20F0 := by
    have hh := setup_regs v
    exact hh.2.2.2.2.2.1.trans h7
  have htr_a : trailer96 a = p := by
    have he : trailer96 a = trailer96 v := by
      simp only [trailer96, trailerHi, trailerLo, a, setup_mem]
    exact he.trans htr
  have hbody_a : readBuffer a 0x800 6384 = readBuffer v 0x800 6384 :=
    Radix12SplitBodyBridgeSD.mem_eq_readBuffer (s := v) (t := a)
      (setup_mem v) 0x800 6384
  have hf : Steps expandImage a fallback.res.steps fallback.res.cycles b :=
    fallback_steps a hpc_a h6a h7a
  obtain ⟨hd,hfetch,h5,h10u⟩ := done_steps b (fallback_pc a)
  have hbuf : readBuffer b 0x800 6404 =
      fallbackCounters a ++ readBuffer a 0x800 6384 :=
    fallback_readBuffer a h6a h7a
  have hdmem : readBuffer u 0x800 6404 = readBuffer b 0x800 6404 :=
    Radix12SplitBodyBridgeSD.mem_eq_readBuffer (s := b) (t := u)
      (done_mem b) 0x800 6404
  have hdecode : Radix12Split.expandSplit p =
      Radix12.encodeWords (Radix12.badWords p.toNat) := by
    unfold Radix12Split.expandSplit
    rw [decode_bad ⟨p.toNat, p.isLt⟩ (by rw [highCode_trailer]; exact hcap)]
  refine ⟨u, Steps.of_eq ((hs.trans hf).trans hd) (by omega) (by omega),
    hfetch, h5, h10u, ?_⟩
  rw [hdmem, hbuf, fallbackCounters_eq, htr_a, ← hdecode, hbody_a]

#print axioms highCode_trailer
#print axioms fallback_phase
end Radix12SplitFallbackPhaseSD
end
-- END Radix12SplitFallbackPhaseSD

-- BEGIN Radix12SplitFallbackInitialSD from /tmp/Radix12SplitFallbackInitialSD.lean
section

namespace Radix12SplitFallbackInitialSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
  Radix12SplitExpandPreludeSD Radix12SplitExpandFirstSD
  Radix12SplitFallbackSD Radix12SplitFinalSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem fallback_initial (m : Message) (pk : PublicKey) (σ : Bytes 6396)
    (hcap : Nat.choose 385 5 ≤
      ((Radix12Split.trailer σ).extractLsb' 60 36).toNat) :
    ∃ u n c, Steps expandImage (Radix12SplitInitTable.initState m pk σ) n c u ∧
      fetch expandImage u = some (.base .ECALL) ∧
      u.getReg .x5 = 1 ∧ u.getReg .x10 = 0 ∧
      readBuffer u 0x800 6404 = Radix12Split.expandWitness σ ∧
      n = runPre.res.steps + 1596 * 6 + runCtr.res.steps + first7.res.steps +
        Radix12SplitSetupSD.setup.res.steps +
        fallback.res.steps + done.res.steps ∧
      c = runPre.res.cycles + 1596 * 6 + runCtr.res.cycles + first7.res.cycles +
        Radix12SplitSetupSD.setup.res.cycles +
        fallback.res.cycles + done.res.cycles := by
  let p := Radix12Split.trailer σ
  obtain ⟨v,hstart,hpc,h10,h6,h7,htr,hbody⟩ :=
    Radix12SplitFallbackStartSD.start_invalid_refined m pk σ
  obtain ⟨u,hphase,hfetch,h5,h10u,hout⟩ :=
    Radix12SplitFallbackPhaseSD.fallback_phase v p
      hpc h10 h6 h7 htr hcap
  have hresult : readBuffer u 0x800 6404 = Radix12Split.expandWitness σ := by
    rw [hout, hbody]
    rfl
  exact ⟨u,_,_,Steps.of_eq (hstart.trans hphase) (by omega) (by omega),
    hfetch,h5,h10u,hresult,rfl,rfl⟩

#print axioms fallback_initial
end Radix12SplitFallbackInitialSD
end
-- END Radix12SplitFallbackInitialSD
