-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import SigGolfCandidate.Budget.Bridge
import SigGolfCandidate.Final.Discharge
import SigGolfCandidate.Final.Main
import SigGolfCandidate.Keygen.Main
import SigGolfCandidate.Packed.Radix12Bundle20
import SigGolfCandidate.Verify.Main

-- BEGIN Radix12FinalSecurity from /tmp/Radix12FinalSecurity.lean
section

namespace Radix12FinalSecurity
open SigGolfCandidate SigGolfCandidate.Legacy OracleComp
open SigGolfCandidate.Packed (oldSubmission observed)
open SigGolfCandidate.Packed.Sign
set_option maxRecDepth 200000
set_option maxHeartbeats 3000000
set_option allowUnsafeReducibility true in
attribute [local reducible] SigGolfCandidate.Legacy.Input SigGolfCandidate.Legacy.Output
  SigGolfCandidate.Packed.oldSubmission
  SigGolfCandidate.Radix12Split.shortSubmission
  SigGolfCandidate.submission Radix12Submission.concrete

private abbrev baseLayout : Layout := SigGolfCandidate.submission.layout
private abbrev oldImages : Phase → Riscv.Image := SigGolfCandidate.submission.image
private abbrev newImages : Phase → Riscv.Image := Radix12Submission.concrete.image
private abbrev concrete := Radix12Submission.concrete

theorem assumptions_of_phases
    (hK : ∀ sk : SecretKey,
      (observed <$> concrete.run .keygen sk) =
        (observed <$> SigGolfCandidate.submission.run .keygen sk))
    (hS : ∀ (sk : SecretKey) (cache : Bytes CACHE_BYTES) (message : Message),
      (observed <$> concrete.run .sign (sk, cache, message)) =
        ((fun r => (r.value.map Radix12Split.packOldAny, r.hashCalls)) <$>
          SigGolfCandidate.submission.run .sign (sk, cache, message)))
    (hV : ∀ (m : Message) (pk : PublicKey) (w : Bytes 6404),
      (observed <$> concrete.run .verify (m, pk, w)) =
        (observed <$> SigGolfCandidate.submission.run .verify (m, pk, w))) :
    SigGolfCandidate.Radix12Split.AssumptionsAny baseLayout oldImages newImages where
  keygen sk := by
    exact hK sk
  sign sk cache message := by
    exact hS sk cache message
  expand message pk signature := by
    change (observed <$> concrete.run .expand (message, pk, signature)) =
      (observed <$> SigGolfCandidate.submission.run .expand
        (message, pk, Radix12Split.unpackOld signature))
    rw [SigGolfCandidate.Expand.expand_run]
    obtain ⟨_, _, he⟩ := Radix12SplitExpandActualSD.expand_run message pk signature
    rw [he, Radix12Split.expand_unpackOld]
    rfl
  verify message pk witness := by
    exact hV message pk witness

theorem secure_of_phases
    (hK : ∀ sk : SecretKey,
      (observed <$> concrete.run .keygen sk) =
        (observed <$> SigGolfCandidate.submission.run .keygen sk))
    (hS : ∀ (sk : SecretKey) (cache : Bytes CACHE_BYTES) (message : Message),
      (observed <$> concrete.run .sign (sk, cache, message)) =
        ((fun r => (r.value.map Radix12Split.packOldAny, r.hashCalls)) <$>
          SigGolfCandidate.submission.run .sign (sk, cache, message)))
    (hV : ∀ (m : Message) (pk : PublicKey) (w : Bytes 6404),
      (observed <$> concrete.run .verify (m, pk, w)) =
        (observed <$> SigGolfCandidate.submission.run .verify (m, pk, w))) :
    concrete.Secure := by
  have hOld : (oldSubmission baseLayout oldImages).Secure := by
    change SigGolfCandidate.submission.Secure
    exact SigGolfCandidate.Final.certificate.security
  exact SigGolfCandidate.Radix12Split.secureAny
    (assumptions_of_phases hK hS hV) hOld

theorem sign_observed (hS : Radix12FinalCore.SignRefinement12)
    (sk : SecretKey) (cache : Cache) (message : Message) :
    (observed <$> concrete.run .sign (sk, cache, message)) =
      ((fun r => (r.value.map Radix12Split.packOldAny, r.hashCalls)) <$>
        SigGolfCandidate.submission.run .sign (sk, cache, message)) := by
  have hs := congrArg (fun X =>
    (fun p : Option (Bytes 6396) × Nat × Nat => (p.1, p.2.1)) <$> X)
      (hS sk cache message)
  have ho := congrArg (fun X =>
    (fun p : Option (Bytes 6404) × Nat × Nat =>
      (p.1.map Radix12Split.packOldAny, p.2.1)) <$> X)
      (SigGolfCandidate.Final.signRefinement sk cache message)
  simp only [Functor.map_map] at hs
  change (observed <$> concrete.run .sign (sk, cache, message)) =
    ((fun r => (r.value.map Radix12Split.packOldAny, r.hashCalls)) <$>
      SigGolfCandidate.submission.run .sign (sk, cache, message))
  calc
    observed <$> concrete.run .sign (sk, cache, message) =
      (fun p => (p.1.map Radix12Split.packOldAny, p.2.1)) <$>
        countBoth (Ref.signRef sk cache message) := by
      change (fun r => (r.value, r.hashCalls)) <$>
        concrete.run .sign (sk, cache, message) = _
      simpa only using hs
    _ = (fun r => (r.value.map Radix12Split.packOldAny, r.hashCalls)) <$>
        SigGolfCandidate.submission.run .sign (sk, cache, message) := by
      calc
        (fun p => (p.1.map Radix12Split.packOldAny, p.2.1)) <$>
            countBoth (Ref.signRef sk cache message) =
          (fun p : Option (Bytes 6404) × Nat × Nat =>
            (p.1.map Radix12Split.packOldAny, p.2.1)) <$>
            ((fun r => (r.value, r.hashCalls, r.hashCompressions)) <$>
              SigGolfCandidate.submission.run .sign (sk, cache, message)) := ho.symm
        _ = _ := by rw [Functor.map_map]

#print axioms assumptions_of_phases
#print axioms secure_of_phases
#print axioms sign_observed
end Radix12FinalSecurity
end
-- END Radix12FinalSecurity

-- BEGIN Radix12FinalBudget from /tmp/Radix12FinalBudget.lean
section

namespace Radix12FinalBudget
open SigGolfCandidate SigGolfCandidate.Legacy OracleComp
set_option maxRecDepth 200000
set_option maxHeartbeats 3000000
set_option allowUnsafeReducibility true in
attribute [local reducible] SigGolfCandidate.Legacy.Input SigGolfCandidate.Legacy.Output
  Radix12Submission.concrete

private abbrev concrete := Radix12Submission.concrete

structure BaselineProps : Prop where
  keygen_valid : (concrete.image .keygen).Valid concrete.sizes concrete.layout
  verify_valid : (concrete.image .verify).Valid concrete.sizes concrete.layout
  keygen_run_eq : ∀ sk : SecretKey,
    concrete.run .keygen sk = SigGolfCandidate.submission.run .keygen sk
  verify_run_eq : ∀ (m : Message) (pk : PublicKey) (w : Bytes 6404),
    concrete.run .verify (m, pk, w) =
      SigGolfCandidate.submission.run .verify (m, pk, w)
  keygen_runWith_eq : ∀ (hash : Hash) (sk : SecretKey),
    concrete.runWith hash .keygen sk =
      SigGolfCandidate.submission.runWith hash .keygen sk
  verify_runWith_eq : ∀ (hash : Hash) (m : Message) (pk : PublicKey)
      (w : Bytes 6404),
    concrete.runWith hash .verify (m, pk, w) =
      SigGolfCandidate.submission.runWith hash .verify (m, pk, w)

theorem budget_of_sign (hB : BaselineProps)
    (hS : Radix12FinalCore.SignRefinement12) :
    concrete.CompressionBounds := by
  apply SigGolfCandidate.Budget.compressionBounds_of_refinement concrete
  · apply SigGolfCandidate.Budget.keygenRefines_of_counts concrete
    intro sk
    refine ⟨some, ?_⟩
    rw [hB.keygen_run_eq]
    exact SigGolfCandidate.Keygen.keygen_run_counts sk
  · apply SigGolfCandidate.Budget.signRefines_of_counts concrete rfl
    intro sk cache m
    refine ⟨Option.map Radix12Split.packOldAny, ?_⟩
    exact hS sk cache m
  · apply SigGolfCandidate.Budget.expandNoHash_of_counts concrete
    rintro ⟨m, pk, σ⟩
    refine ⟨Unit, (), fun _ => some (Radix12Split.expandWitness σ), ?_⟩
    obtain ⟨cyc, _, he⟩ := Radix12SplitExpandActualSD.expand_run m pk σ
    rw [he]
    rfl

theorem terminates_of_sign
    (hB : BaselineProps)
    (hS : ∀ (hash : Hash) (sk : SecretKey) (cache : Cache) (m : Message),
      (concrete.runWith hash .sign (sk, cache, m)).finished = true ∧
        (concrete.runWith hash .sign (sk, cache, m)).cycles < CYCLE_LIMIT) :
    concrete.Terminates := by
  intro hash phase input
  cases phase with
  | keygen =>
      dsimp only
      change (concrete.runWith hash .keygen input).finished = true ∧
        (concrete.runWith hash .keygen input).cycles < CYCLE_LIMIT
      rw [hB.keygen_runWith_eq]
      rw [SigGolfCandidate.Keygen.keygen_runWith]
      exact ⟨rfl, by change 13500615 < CYCLE_LIMIT; decide⟩
  | sign =>
      obtain ⟨sk, cache, m⟩ := input
      exact hS hash sk cache m
  | expand =>
      obtain ⟨m, pk, σ⟩ := input
      dsimp only
      obtain ⟨cyc, hcyc, he⟩ :=
        Radix12SplitExpandActualSD.expand_runWith hash m pk σ
      rw [he]
      exact ⟨rfl, hcyc⟩
  | verify =>
      obtain ⟨m, pk, w⟩ := input
      dsimp only
      change (concrete.runWith hash .verify (m, pk, w)).finished = true ∧
        (concrete.runWith hash .verify (m, pk, w)).cycles < CYCLE_LIMIT
      rw [hB.verify_runWith_eq]
      exact ⟨(SigGolfCandidate.Verify.verify_terminates hash (m, pk, w)).1,
        (SigGolfCandidate.Verify.verify_terminates hash (m, pk, w)).2.2⟩

theorem verificationBound (hB : BaselineProps) :
    concrete.VerificationBound 11523 := by
  intro hash sk m
  dsimp only
  intro h
  obtain ⟨⟨m', pk, w⟩, hacc, hcyc⟩ :=
    SigGolfCandidate.Final.honest_success_verify concrete hash sk m h
  rw [hcyc]
  have hb := (SigGolfCandidate.Verify.verify_terminates hash (m', pk, w)).2.1
  rw [hB.verify_runWith_eq]
  change (SigGolfCandidate.submission.runWith hash .verify (m', pk, w)).cycles + 26 ≤ 11523
  have hb' :
      (SigGolfCandidate.submission.runWith hash .verify (m', pk, w)).cycles ≤
        11497 := by
    simpa only [SigGolfCandidate.Verify.cycleBound] using hb
  omega

theorem admissible (hB : BaselineProps) : concrete.Admissible := by
  refine ⟨?_, ?_⟩
  · change Radix12SignImage.sizes12.Valid
    unfold Sizes.Valid
    decide
  · intro phase
    cases phase with
    | keygen => exact hB.keygen_valid
    | sign => exact Radix12SignImage.sign_valid
    | expand => exact Radix12SplitExpandImageSD.expand_valid
    | verify => exact hB.verify_valid

#print axioms budget_of_sign
#print axioms terminates_of_sign
#print axioms verificationBound
#print axioms admissible
end Radix12FinalBudget
end
-- END Radix12FinalBudget

-- BEGIN Radix12BaselineBridge from /tmp/sig-radix12-sign/Radix12BaselineBridge.lean
section

namespace Radix12BaselineBridge
open SigGolfCandidate SigGolfCandidate.Legacy SigGolfCandidate.Ref OracleComp

set_option maxRecDepth 100000
set_option maxHeartbeats 3000000
set_option allowUnsafeReducibility true in
attribute [local reducible] SigGolfCandidate.Legacy.Input SigGolfCandidate.Legacy.Output
  Radix12Submission.concrete SigGolfCandidate.submission

private abbrev concrete := Radix12Submission.concrete

theorem keygen_valid :
    (concrete.image .keygen).Valid concrete.sizes concrete.layout := by
  constructor
  · exact SigGolfCandidate.submission_keygen_valid.1
  · decide +kernel

theorem verify_valid :
    (concrete.image .verify).Valid concrete.sizes concrete.layout := by
  constructor
  · exact SigGolfCandidate.submission_verify_valid.1
  · decide +kernel

theorem keygen_initial_eq (sk : SecretKey) :
    initialState concrete .keygen sk =
      initialState SigGolfCandidate.submission .keygen sk := by
  unfold initialState
  rw [if_pos keygen_valid, if_pos SigGolfCandidate.submission_keygen_valid]
  rfl

theorem verify_initial_eq (m : Message) (pk : PublicKey) (w : Bytes 6404) :
    initialState concrete .verify (m, pk, w) =
      initialState SigGolfCandidate.submission .verify (m, pk, w) := by
  unfold initialState
  rw [if_pos verify_valid, if_pos SigGolfCandidate.submission_verify_valid]
  rfl

theorem keygen_run_eq (sk : SecretKey) :
    concrete.run .keygen sk = SigGolfCandidate.submission.run .keygen sk := by
  unfold Submission.run
  rw [keygen_initial_eq]
  rfl

private theorem runVerifyEq (a b : Submission)
    (x : Input a.sizes .verify) (y : Input b.sizes .verify)
    (hi : initialState a .verify x = initialState b .verify y)
    (hc : a.image .verify = b.image .verify) :
    a.run .verify x = b.run .verify y := by
  unfold Submission.run
  rw [hi, hc]

theorem verify_run_eq (m : Message) (pk : PublicKey) (w : Bytes 6404) :
    concrete.run .verify (m, pk, w) =
      SigGolfCandidate.submission.run .verify (m, pk, w) := by
  apply runVerifyEq
  · exact verify_initial_eq m pk w
  · rfl

theorem keygen_runWith_eq (hash : Hash) (sk : SecretKey) :
    concrete.runWith hash .keygen sk =
      SigGolfCandidate.submission.runWith hash .keygen sk := by
  unfold Submission.runWith
  rw [keygen_run_eq]
  rfl

theorem verify_runWith_eq (hash : Hash) (m : Message) (pk : PublicKey)
    (w : Bytes 6404) :
    concrete.runWith hash .verify (m, pk, w) =
      SigGolfCandidate.submission.runWith hash .verify (m, pk, w) := by
  unfold Submission.runWith
  rw [verify_run_eq]

theorem keygen_value (sk : SecretKey) :
    (fun r => r.value) <$> concrete.run .keygen sk =
      some <$> Ref.keygenRef sk := by
  rw [keygen_run_eq]
  exact SigGolfCandidate.Final.keygen_value
    (fun sk => SigGolfCandidate.Keygen.keygen_run_counts sk) sk

theorem verify_value (m : Message) (pk : PublicKey) (w : Bytes 6404) :
    (fun r => r.value.isSome) <$> concrete.run .verify (m, pk, w) =
      Ref.verifyRef m pk w := by
  rw [verify_run_eq]
  exact SigGolfCandidate.Final.verify_value
    (fun m pk w => SigGolfCandidate.Verify.verify_refines m pk w) m pk w

#print axioms keygen_run_eq
#print axioms verify_run_eq
#print axioms keygen_runWith_eq
#print axioms verify_runWith_eq
#print axioms keygen_value
#print axioms verify_value
end Radix12BaselineBridge
end
-- END Radix12BaselineBridge

-- BEGIN Radix12FinalCert from /tmp/Radix12FinalCert.lean
section

namespace Radix12FinalCert
open SigGolfCandidate SigGolfCandidate.Legacy OracleComp OracleSpec
open SigGolfCandidate.Packed (observed)
set_option maxRecDepth 200000
set_option maxHeartbeats 3000000
set_option allowUnsafeReducibility true in
attribute [local reducible] SigGolfCandidate.Legacy.Input SigGolfCandidate.Legacy.Output
  Radix12Submission.concrete

private abbrev concrete := Radix12Submission.concrete

theorem baselineProps : Radix12FinalBudget.BaselineProps where
  keygen_valid := Radix12BaselineBridge.keygen_valid
  verify_valid := Radix12BaselineBridge.verify_valid
  keygen_run_eq := Radix12BaselineBridge.keygen_run_eq
  verify_run_eq := Radix12BaselineBridge.verify_run_eq
  keygen_runWith_eq := Radix12BaselineBridge.keygen_runWith_eq
  verify_runWith_eq := Radix12BaselineBridge.verify_runWith_eq

theorem signRefinement12 : Radix12FinalCore.SignRefinement12 := by
  intro sk cache m
  exact SigGolfCandidate.Radix12Sign.sign_refines12_concrete sk cache m

theorem signTermination12 :
    ∀ (hash : Hash) (sk : SecretKey) (cache : Cache) (m : Message),
      (concrete.runWith hash .sign (sk, cache, m)).finished = true ∧
        (concrete.runWith hash .sign (sk, cache, m)).cycles < CYCLE_LIMIT := by
  intro hash sk cache m
  have hs := SigGolfCandidate.Radix12Sign.sign_terminates12_concrete
    hash sk cache m
  exact ⟨hs.1, lt_of_le_of_lt hs.2
    SigGolfCandidate.Radix12Sign.signW_post_lt⟩

theorem certificate12 : Certificate concrete 11523 where
  admissible := Radix12FinalBudget.admissible baselineProps
  termination := Radix12FinalBudget.terminates_of_sign baselineProps signTermination12
  completeness := Radix12FinalCore.complete_of_phase_refinements
    Radix12BaselineBridge.keygen_value signRefinement12
    Radix12BaselineBridge.verify_value
  compressionBounds := Radix12FinalBudget.budget_of_sign baselineProps signRefinement12
  security := Radix12FinalSecurity.secure_of_phases
    (fun sk => congrArg (fun X => observed <$> X)
      (Radix12BaselineBridge.keygen_run_eq sk))
    (Radix12FinalSecurity.sign_observed signRefinement12)
    (fun m pk w => congrArg (fun X => observed <$> X)
      (Radix12BaselineBridge.verify_run_eq m pk w))
  verificationBound := Radix12FinalBudget.verificationBound baselineProps

#print axioms signRefinement12
#print axioms signTermination12
#print axioms certificate12
end Radix12FinalCert
end
-- END Radix12FinalCert
