-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import SigGolfCandidate.Final.Abstract
import SigGolfCandidate.Final.Completeness
import SigGolfCandidate.SphincsSecurity.Completeness.Assembly
import SigGolfCandidate.SphincsSecurity.Completeness.Counter
import SigGolfCandidate.SphincsSecurity.Completeness.Decay
import SigGolfCandidate.SphincsSecurity.Completeness.Encoding
import SigGolfCandidate.SphincsSecurity.Completeness.Search
import SigGolfCandidate.SphincsSecurity.Completeness.Signing

-- BEGIN CounterPrefixTail from /tmp/CounterPrefixTail.lean
section

open OracleComp OracleSpec
namespace SphincsSecurity.Completeness

/-! A generic first-success search decomposes into a prefix and continuation.
    This is scratch for a 13-byte counter trailer; it is not a submitted proof. -/

theorem searchLoop_split {β γ : Type}
    (inputs : Nat → HashInput) (decode : HashOutput → Option β)
    (success : Nat → β → OracleComp HashSpec γ)
    (head rest start : Nat) :
    searchLoop inputs decode success (head + rest) start =
      (searchLoop inputs decode success head start >>= fun r =>
        match r with
        | none => searchLoop inputs decode success rest (start + head)
        | some v => pure (some v)) := by
  induction head generalizing start with
  | zero => simp [searchLoop]
  | succ head ih =>
      simp only [Nat.succ_add, searchLoop]
      rw [ih]
      simp only [bind_assoc]
      refine bind_congr fun answer => ?_
      cases decode answer with
      | none =>
          simp [Nat.add_comm, Nat.add_left_comm]
      | some v => simp

theorem searchLoop_tagged_range {β : Type}
    (inputs : Nat → HashInput) (decode : HashOutput → Option β) :
    ∀ (n start : Nat) (out : Option (Nat × β)),
      out ∈ support (searchLoop inputs decode
        (fun c v => pure (c, v)) n start) →
      ∀ c v, out = some (c, v) → start ≤ c ∧ c < start + n := by
  intro n
  induction n with
  | zero =>
      intro start out h c v heq
      simp only [searchLoop, support_pure, Set.mem_singleton_iff] at h
      rw [heq] at h
      cases h
  | succ n ih =>
      intro start out h c v heq
      rw [searchLoop] at h
      obtain ⟨answer, _, hrest⟩ := (mem_support_bind_iff _ _ _).mp h
      cases hdecode : decode answer with
      | none =>
          simp only [hdecode] at hrest
          obtain ⟨hlo, hhi⟩ := ih (start + 1) out hrest c v heq
          omega
      | some value =>
          simp only [hdecode, support_map, support_pure,
            Set.mem_singleton_iff, Set.mem_image] at hrest
          obtain ⟨word, hword, hpair⟩ := hrest
          subst word
          rw [heq] at hpair
          simp only [Option.some.injEq] at hpair
          have hfst := congrArg Prod.fst hpair
          omega

/-- The real encoding search returns a 32-bit counter rather than a `Nat`.
    Mapping the tagged abstract result commutes with the whole search. -/
theorem searchLoop_map_tagged {β γ : Type}
    (inputs : Nat → HashInput) (decode : HashOutput → Option β)
    (make : Nat → β → γ) :
    ∀ n start,
      searchLoop inputs decode (fun c v => pure (make c v)) n start =
        (Option.map (fun p : Nat × β => make p.1 p.2)) <$>
          searchLoop inputs decode (fun c v => pure (c, v)) n start := by
  intro n
  induction n with
  | zero => intro start; simp [searchLoop]
  | succ n ih =>
      intro start
      rw [searchLoop, searchLoop]
      rw [map_bind]
      refine bind_congr fun answer => ?_
      cases hdecode : decode answer with
      | none => simpa only [hdecode] using ih (start + 1)
      | some value => simp

/-- A tagged search either exhausted every trial or succeeded after the short cutoff. -/
def searchLoopTailEvent {β : Type} (start head : Nat)
    (r : Option (Nat × β) × QueryCache HashSpec) : Prop :=
  match r.1 with
  | none => True
  | some (c, _) => start + head ≤ c


/-- Exhausting the search or reaching a counter outside a short trailer's
    range requires every trial in the initial range to fail. This generic
    lemma is independent of the particular 13-byte codec. -/
theorem searchLoop_tagged_tail_le {β : Type}
    (inputs : Nat → HashInput) (decode : HashOutput → Option β)
    (bound head rest start : Nat) (cache : QueryCache HashSpec)
    (hinj : ∀ s s', s < bound → s' < bound → inputs s = inputs s' → s = s')
    (hbound : start + head + rest ≤ bound)
    (hfresh : ∀ s, start ≤ s → s < bound → cache (inputs s) = none) :
    Pr[searchLoopTailEvent start head |
      (simulateQ randomOracle (searchLoop inputs decode
        (fun c v => pure (c, v)) (head + rest) start)).run cache]
      ≤ failMass decode ^ head := by
  let part : OracleComp HashSpec (Option (Nat × β)) :=
    searchLoop inputs decode (fun c v => pure (c, v)) head start
  let tail : Option (Nat × β) → OracleComp HashSpec (Option (Nat × β)) :=
    fun r => match r with
      | none => searchLoop inputs decode (fun c v => pure (c, v)) rest (start + head)
      | some v => pure (some v)
  have hsplit : searchLoop inputs decode (fun c v => pure (c, v)) (head + rest) start =
      part >>= tail := by
    refine (searchLoop_split inputs decode (fun c v => pure (c, v))
      head rest start).trans ?_
    unfold part tail
    congr 1
    funext r
    cases r <;> rfl
  rw [hsplit]
  have hprefix :
      Pr[fun r => r.1 = none | (simulateQ randomOracle part).run cache] ≤
        failMass decode ^ head := by
    exact probEvent_searchLoop inputs decode (fun c v => pure (c, v)) bound
      hinj head start (by omega) cache hfresh
  have hbind :
      Pr[searchLoopTailEvent start head |
        (simulateQ randomOracle (part >>= tail)).run cache] ≤
        Pr[fun r => r.1 = none | (simulateQ randomOracle part).run cache] + 0 := by
    apply probEvent_bind_le_add part tail (fun r => r.1 = none)
      (searchLoopTailEvent start head) cache 0
    intro r hr hnot
    cases hres : r.1 with
    | none => exact (hnot hres).elim
    | some cv =>
        rcases cv with ⟨c, v⟩
        have hmem : some (c, v) ∈ support part := by
          apply support_simulateQ_run'_subset randomOracle part cache
          rw [StateT.run'_eq, support_map]
          exact ⟨r, hr, by simp [hres]⟩
        have hrange := searchLoop_tagged_range inputs decode head start
          (some (c, v)) hmem c v rfl
        simp only [tail, simulateQ_pure, StateT.run_pure]
        simp [searchLoopTailEvent, show ¬ start + head ≤ c by omega]
  exact hbind.trans (by simpa using hprefix)

#print axioms searchLoop_split
#print axioms searchLoop_tagged_range
#print axioms searchLoop_map_tagged
#print axioms searchLoop_tagged_tail_le

open ENNReal
open SphincsSecurity.Concrete
open SphincsSecurity.TargetSum

theorem encodingSearch_map_tagged (parameter : PublicParameter)
    (lay : Layer) (tree : TreeIndex) (leaf : LeafIndex)
    (message : Digest) (n start : Nat) :
    (encodingSearch parameter lay tree leaf message n start :
      OracleComp HashSpec (Option (Counter × Encoding))) =
      (Option.map (fun p : Nat × Encoding =>
        (BitVec.ofNat counterBits p.1, p.2))) <$>
        searchLoop (encodeInput parameter lay tree leaf message)
          (fun out => decodeDigest (truncateHash out))
          (fun c v => pure (c, v)) n start := by
  rw [encodingSearch_eq_searchLoop]
  exact searchLoop_map_tagged
    (encodeInput parameter lay tree leaf message)
    (fun out => decodeDigest (truncateHash out))
    (fun c v => (BitVec.ofNat counterBits c, v)) n start

#print axioms encodingSearch_map_tagged

def radix27CounterLimit : Nat := 27 * 2 ^ 16

theorem radix27CounterLimit_large : codeShare * 530 ≤ radix27CounterLimit := by
  norm_num [codeShare, radix27CounterLimit]

theorem radix27CounterTail_le :
    failMass (fun out => decodeDigest (truncateHash out)) ^
      radix27CounterLimit ≤ (2⁻¹ : ℝ≥0∞) ^ 530 := by
  have hroom := failMass_encoding_add_le
  have hhalf := pow_le_half_ennreal codeShare (by decide)
    (failMass (fun out => decodeDigest (truncateHash out))) hroom
  have hone : failMass (fun out => decodeDigest (truncateHash out)) ≤ 1 :=
    le_trans le_self_add hroom
  calc
    failMass (fun out => decodeDigest (truncateHash out)) ^ radix27CounterLimit
        ≤ failMass (fun out => decodeDigest (truncateHash out)) ^ (codeShare * 530) :=
          pow_le_pow_right_of_le_one' hone radix27CounterLimit_large
    _ = (failMass (fun out => decodeDigest (truncateHash out)) ^ codeShare) ^ 530 :=
          pow_mul _ _ _
    _ ≤ (2⁻¹ : ℝ≥0∞) ^ 530 := pow_le_pow_left₀ (by positivity) hhalf _

theorem radix27_allMessages_extra_le :
    (2 : ℝ≥0∞) ^ 256 * (5 * (2⁻¹ : ℝ≥0∞) ^ 530) ≤
      (2⁻¹ : ℝ≥0∞) ^ 271 := by
  have hfive : (5 : ℝ≥0∞) ≤ 8 := by norm_num
  have hterm : 5 * (2⁻¹ : ℝ≥0∞) ^ 530 ≤
      (2⁻¹ : ℝ≥0∞) ^ 527 := by
    calc
      5 * (2⁻¹ : ℝ≥0∞) ^ 530 ≤ 8 * (2⁻¹ : ℝ≥0∞) ^ 530 :=
        mul_le_mul' hfive le_rfl
      _ = (2⁻¹ : ℝ≥0∞) ^ 527 := by
        rw [show (8 : ℝ≥0∞) = 2 ^ 3 by norm_num, ← ENNReal.inv_pow,
          mul_comm, ← ENNReal.div_eq_inv_mul,
          show (530 : Nat) = 3 + 527 by norm_num,
          two_pow_div_two_pow]
  calc
    (2 : ℝ≥0∞) ^ 256 * (5 * (2⁻¹ : ℝ≥0∞) ^ 530) ≤
        (2 : ℝ≥0∞) ^ 256 * (2⁻¹ : ℝ≥0∞) ^ 527 :=
      mul_le_mul' le_rfl hterm
    _ = (2⁻¹ : ℝ≥0∞) ^ 271 := by
      rw [← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
        show (527 : Nat) = 256 + 271 by norm_num,
        two_pow_div_two_pow]

theorem radix27_complete_numeric :
    (2 : ℝ≥0∞) ^ 256 *
      ((2⁻¹ : ℝ≥0∞) ^ 1023 +
        5 * (2⁻¹ : ℝ≥0∞) ^ 1256 +
        5 * (2⁻¹ : ℝ≥0∞) ^ 530) ≤
      ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := by
  let x : ℝ≥0∞ := 2⁻¹
  have holdA : x ^ 1023 ≤ x ^ 529 := inv_two_pow_anti (by norm_num)
  have holdB : 5 * x ^ 1256 ≤ x ^ 529 := by
    have hpow : x ^ 1256 ≤ x ^ 532 := inv_two_pow_anti (by norm_num)
    calc
      5 * x ^ 1256 ≤ 8 * x ^ 532 := mul_le_mul' (by norm_num) hpow
      _ = x ^ 529 := by
        dsimp [x]
        rw [show (8 : ℝ≥0∞) = 2 ^ 3 by norm_num,
          ← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
          show (532 : Nat) = 3 + 529 by norm_num,
          two_pow_div_two_pow]
  have hold : x ^ 1023 + 5 * x ^ 1256 ≤ x ^ 528 :=
    (add_le_add holdA holdB).trans_eq (inv_two_pow_succ_add 528)
  have hnew : 5 * x ^ 530 ≤ x ^ 527 := by
    calc
      5 * x ^ 530 ≤ 8 * x ^ 530 := mul_le_mul' (by norm_num) le_rfl
      _ = x ^ 527 := by
        dsimp [x]
        rw [show (8 : ℝ≥0∞) = 2 ^ 3 by norm_num,
          ← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
          show (530 : Nat) = 3 + 527 by norm_num,
          two_pow_div_two_pow]
  have hsum : x ^ 1023 + 5 * x ^ 1256 + 5 * x ^ 530 ≤ x ^ 526 := by
    calc
      _ ≤ x ^ 528 + x ^ 527 := add_le_add hold hnew
      _ ≤ x ^ 527 + x ^ 527 :=
        add_le_add (inv_two_pow_anti (by norm_num)) le_rfl
      _ = x ^ 526 := inv_two_pow_succ_add 526
  have hcast : ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ = x ^ 256 := by
    simp only [x, Nat.cast_pow, Nat.cast_ofNat, ENNReal.inv_pow]
  rw [hcast]
  calc
    (2 : ℝ≥0∞) ^ 256 *
        (x ^ 1023 + 5 * x ^ 1256 + 5 * x ^ 530) ≤
        (2 : ℝ≥0∞) ^ 256 * x ^ 526 := mul_le_mul' le_rfl hsum
    _ = x ^ 270 := by
      dsimp [x]
      rw [← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
        show (526 : Nat) = 256 + 270 by norm_num,
        two_pow_div_two_pow]
    _ ≤ x ^ 256 := inv_two_pow_anti (by norm_num)

def radix27EncodingBad
    (r : Option (Counter × Encoding) × QueryCache HashSpec) : Prop :=
  match r.1 with
  | none => True
  | some (counter, _) => radix27CounterLimit ≤ counter.toNat

/-- The concrete 32-bit encoding search's combined exhaustion/overflow event
    has the same prefix bound as the tagged `Nat` search. -/
theorem radix27EncodingBad_le (parameter : PublicParameter)
    (lay : Layer) (tree : TreeIndex) (leaf : LeafIndex)
    (message : Digest) (cache : QueryCache HashSpec)
    (hfresh : ∀ c, c < encodingAttemptLimit →
      cache (encodeInput parameter lay tree leaf message c) = none) :
    Pr[radix27EncodingBad |
      (simulateQ randomOracle (encodingSearch parameter lay tree leaf message
        encodingAttemptLimit 0 :
          OracleComp HashSpec (Option (Counter × Encoding)))).run cache] ≤
      (2⁻¹ : ℝ≥0∞) ^ 530 := by
  let inp := encodeInput parameter lay tree leaf message
  let dec : HashOutput → Option Encoding :=
    fun out => decodeDigest (truncateHash out)
  let tagged : OracleComp HashSpec (Option (Nat × Encoding)) :=
    searchLoop inp dec (fun c v => pure (c, v)) encodingAttemptLimit 0
  have hmap :
      (encodingSearch parameter lay tree leaf message encodingAttemptLimit 0 :
        OracleComp HashSpec (Option (Counter × Encoding))) =
      (Option.map (fun p : Nat × Encoding =>
        (BitVec.ofNat counterBits p.1, p.2))) <$> tagged :=
    encodingSearch_map_tagged parameter lay tree leaf message _ _
  rw [hmap, simulateQ_map, StateT.run_map, probEvent_map]
  have hmono :
      Pr[radix27EncodingBad ∘
        (fun r : Option (Nat × Encoding) × QueryCache HashSpec =>
          (Option.map (fun p : Nat × Encoding =>
            (BitVec.ofNat counterBits p.1, p.2)) r.1, r.2)) |
        (simulateQ randomOracle tagged).run cache] ≤
      Pr[searchLoopTailEvent 0 radix27CounterLimit |
        (simulateQ randomOracle tagged).run cache] := by
    apply probEvent_mono
    intro r hr hbad
    cases hres : r.1 with
    | none => simp [searchLoopTailEvent, hres]
    | some pair =>
        rcases pair with ⟨c, v⟩
        have hmem : some (c, v) ∈ support tagged := by
          apply support_simulateQ_run'_subset randomOracle tagged cache
          rw [StateT.run'_eq, support_map]
          exact ⟨r, hr, by simp [hres]⟩
        have hrange := searchLoop_tagged_range inp dec encodingAttemptLimit 0
          (some (c, v)) hmem c v rfl
        have hc32 : c < 2 ^ 32 := by
          have := hrange.2
          norm_num [encodingAttemptLimit] at this ⊢
          omega
        simp only [Function.comp_apply, radix27EncodingBad,
          searchLoopTailEvent, hres, Option.map_some,
          BitVec.toNat_ofNat, counterBits] at hbad ⊢
        have hcmod : c % 4294967296 = c := Nat.mod_eq_of_lt (by omega)
        simpa [hcmod] using hbad
  have hprefix :
      Pr[searchLoopTailEvent 0 radix27CounterLimit |
        (simulateQ randomOracle tagged).run cache] ≤
      failMass dec ^ radix27CounterLimit := by
    apply searchLoop_tagged_tail_le inp dec encodingAttemptLimit
      radix27CounterLimit (encodingAttemptLimit - radix27CounterLimit) 0 cache
    · intro s s' hs hs' heq
      exact encodeInput_inj parameter lay tree leaf message
        (by have := hs; norm_num [encodingAttemptLimit] at this ⊢; omega)
        (by have := hs'; norm_num [encodingAttemptLimit] at this ⊢; omega) heq
    · norm_num [encodingAttemptLimit, radix27CounterLimit]
    · intro s _ hs
      exact hfresh s hs
  exact (hmono.trans hprefix).trans radix27CounterTail_le

#print axioms radix27CounterTail_le
#print axioms radix27_allMessages_extra_le
#print axioms radix27_complete_numeric
#print axioms radix27EncodingBad_le

end SphincsSecurity.Completeness
end
-- END CounterPrefixTail

-- BEGIN CounterLayerPure from /tmp/CounterLayerPure.lean
section

namespace SphincsSecurity.Completeness

open Concrete

def LayerCountersSmall (remaining : Nat)
    (out : Option (Layer → LayerOutput)) : Prop :=
  ∃ parts, out = some parts ∧
    ∀ lay : Layer, lay.val < remaining →
      (parts lay).1.toNat < radix27CounterLimit

theorem layerCountersSmall_zero :
    LayerCountersSmall 0 (some fun _ => (0, fun _ => 0, fun _ => 0)) := by
  refine ⟨_, rfl, ?_⟩
  intro lay h
  omega

theorem layerCountersSmall_top (counter : Counter)
    (values : ChainIndex → Digest) (path : Nat → Digest)
    (hcounter : counter.toNat < radix27CounterLimit) :
    LayerCountersSmall 1 (some fun other =>
      if other = topLayer then (counter, values, path)
      else (0, fun _ => 0, fun _ => 0)) := by
  refine ⟨_, rfl, ?_⟩
  intro lay h
  have htop : lay = topLayer := Fin.ext (by simp [topLayer]; omega)
  simp [htop, hcounter]

theorem layerCountersSmall_extend (r : Nat) (hr : r < numLayers)
    (counter : Counter) (values : ChainIndex → Digest)
    (path : Nat → Digest) (rest : Layer → LayerOutput)
    (hcounter : counter.toNat < radix27CounterLimit)
    (hrest : LayerCountersSmall r (some rest)) :
    LayerCountersSmall (r + 1)
      (some fun other =>
        if other = (⟨r, hr⟩ : Layer) then (counter, values, path)
        else rest other) := by
  refine ⟨_, rfl, ?_⟩
  intro lay hlt
  by_cases heq : lay = (⟨r, hr⟩ : Layer)
  · simp [heq, hcounter]
  · have hval : lay.val < r := by
      have hne : lay.val ≠ r := by
        intro h
        apply heq
        exact Fin.ext h
      omega
    obtain ⟨parts, hparts, hsmall⟩ := hrest
    have hrest_eq_parts : rest = parts := Option.some.inj hparts
    simpa [heq, hrest_eq_parts] using hsmall lay hval

#print axioms layerCountersSmall_zero
#print axioms layerCountersSmall_top
#print axioms layerCountersSmall_extend

end SphincsSecurity.Completeness
end
-- END CounterLayerPure

-- BEGIN CounterLayerStep from /tmp/CounterLayerStep.lean
section

namespace SphincsSecurity.Completeness

open Concrete

def radix27LayerContinuation (parameter : PublicParameter) (index : Index)
    (secret : Layer → TreeIndex → LeafIndex → ChainPair → OracleComp HashSpec (Digest × Digest))
    (topNode : Nat → Nat → OracleComp HashSpec Digest)
    (r : Nat) (hlayer : r < numLayers)
    (out : Option (Counter × Encoding)) :
    OracleComp HashSpec (Option (Layer → LayerOutput)) :=
  let lay : Layer := ⟨r, hlayer⟩
  let tree := treeIndexAt index lay
  let leaf := leafIndexAt index lay
  match out with
  | none => pure none
  | some (counter, encoding) => do
      let (values, path, root) ←
        buildLayerTreePaired parameter lay tree (secret lay tree) leaf encoding
      let some rest ← signLayersPaired parameter index secret topNode r root
        | return none
      return some fun other =>
        if other = lay then (counter, values, path) else rest other

theorem signLayersPaired_succ_bind (parameter : PublicParameter) (index : Index)
    (secret : Layer → TreeIndex → LeafIndex → ChainPair → OracleComp HashSpec (Digest × Digest))
    (topNode : Nat → Nat → OracleComp HashSpec Digest)
    (r : Nat) (hlayer : r < numLayers) (hnzero : r ≠ 0) (message : Digest) :
    signLayersPaired parameter index secret topNode (r + 1) message =
      encodingSearch parameter ⟨r, hlayer⟩ (treeIndexAt index ⟨r, hlayer⟩)
        (leafIndexAt index ⟨r, hlayer⟩) message encodingAttemptLimit 0 >>=
          radix27LayerContinuation parameter index secret topNode r hlayer := by
  rw [signLayersPaired]
  simp only [dif_pos hlayer, if_neg hnzero]
  unfold radix27LayerContinuation
  refine bind_congr fun out => ?_
  cases out with
  | none => rfl
  | some pair =>
      rcases pair with ⟨counter, encoding⟩
      rfl

#print axioms signLayersPaired_succ_bind

end SphincsSecurity.Completeness
end
-- END CounterLayerStep

-- BEGIN CounterFiveLayer from /tmp/CounterFiveLayer.lean
section

open OracleComp OracleSpec ENNReal

namespace SphincsSecurity.Completeness

open Concrete
set_option maxRecDepth 10000
set_option maxHeartbeats 200000
attribute [local irreducible] Seeded.signDigestLoop Concrete.buildLayerTreePaired Concrete.buildForestPaired
  Concrete.encodingSearch digestAttemptLimit encodingAttemptLimit SphincsSecurity.deriveKey
  Seeded.signChecked

def TopCounterSmall (out : Option LayerOutput) : Prop :=
  ∃ value, out = some value ∧ value.1.toNat < radix27CounterLimit

theorem probEvent_signTopLayerPaired_notSmall
    (parameter : PublicParameter) (index : Index)
    (secret : LeafIndex → ChainPair → OracleComp HashSpec (Digest × Digest))
    (topNode : Nat → Nat → OracleComp HashSpec Digest)
    (message : Digest) (cache : QueryCache HashSpec)
    (hfresh : EncodingFresh parameter (fun l => l.val < 1) cache) :
    Pr[fun r => ¬ TopCounterSmall r.1 |
      (simulateQ randomOracle
        (signTopLayerPaired parameter index secret topNode message)).run cache] ≤
      (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [signTopLayerPaired]
  refine le_trans (probEvent_bind_le_add _ _
    (fun r => radix27EncodingBad r)
    (fun r => ¬ TopCounterSmall r.1) cache 0 ?_) ?_
  · rintro ⟨result, c1⟩ _ hgood
    cases result with
    | none =>
        exact (hgood (by simp [radix27EncodingBad])).elim
    | some pair =>
        obtain ⟨counter, encoding⟩ := pair
        have hcounter : counter.toNat < radix27CounterLimit := by
          have hnot : ¬ radix27CounterLimit ≤ counter.toNat := by
            simpa [radix27EncodingBad] using hgood
          omega
        dsimp only
        refine probEvent_bind_le _ _ _ c1 0 (fun r1 _ => ?_)
        refine probEvent_bind_le _ _ _ r1.2 0 (fun r2 _ => ?_)
        simp [TopCounterSmall, hcounter]
  · rw [add_zero]
    exact radix27EncodingBad_le parameter _ _ _ message cache
      (fun c _ => hfresh topLayer (by decide) _ _ _)

#print axioms probEvent_signTopLayerPaired_notSmall

theorem probEvent_signLayersPaired_notSmall (sk : Seeded.SecretKey) (index : Index)
    (topNode : Nat → Nat → OracleComp HashSpec Digest) :
    ∀ (remaining : Nat), remaining ≤ numLayers → ∀ (message : Digest) (cache : QueryCache HashSpec),
      EncodingFresh sk.parameter (fun l => l.val < remaining) cache →
      Pr[fun r => ¬ LayerCountersSmall remaining r.1 |
        (simulateQ (randomOracle : QueryImpl HashSpec _)
          (signLayersPaired sk.parameter index (Seeded.otsSecret sk.parameter sk.seed)
            topNode remaining message : OracleComp HashSpec (Option (Layer → LayerOutput)))).run cache]
        ≤ (remaining : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  intro remaining
  induction remaining with
  | zero =>
      intro _ message cache _
      simp [signLayersPaired, LayerCountersSmall]
  | succ r ih =>
      intro hrem message cache hfresh
      by_cases hzero : r = 0
      · subst hzero
        rw [signLayersPaired]
        split
        next hlayer =>
          rw [if_pos rfl]
          refine le_trans (probEvent_bind_le_add _ _
            (fun out => ¬ TopCounterSmall out.1)
            (fun out => ¬ LayerCountersSmall 1 out.1) cache 0 ?_) ?_
          · rintro ⟨result, c1⟩ _ hgood
            obtain ⟨⟨counter, values, path⟩, hresult, hcounter⟩ :=
              (not_not.mp hgood : TopCounterSmall result)
            subst result
            have hsmall := layerCountersSmall_top counter values path hcounter
            simp [LayerCountersSmall]
            intro x hx
            have htop : x = topLayer := Fin.ext (by simp [topLayer]; omega)
            simpa [htop] using hcounter
          · rw [add_zero, Nat.zero_add, Nat.cast_one, one_mul]
            exact probEvent_signTopLayerPaired_notSmall sk.parameter index _ topNode message cache hfresh
        next hlayer => exact absurd (show 0 < numLayers by decide) hlayer
      · have hlayer : r < numLayers := Nat.lt_of_succ_le hrem
        rw [signLayersPaired_succ_bind sk.parameter index
          (Seeded.otsSecret sk.parameter sk.seed) topNode r hlayer hzero message]
        refine le_trans (probEvent_bind_le_add
          (encodingSearch sk.parameter ⟨r, hlayer⟩
            (treeIndexAt index ⟨r, hlayer⟩) (leafIndexAt index ⟨r, hlayer⟩)
            message encodingAttemptLimit 0)
          (radix27LayerContinuation sk.parameter index
            (Seeded.otsSecret sk.parameter sk.seed) topNode r hlayer)
          radix27EncodingBad
          (fun out => ¬ LayerCountersSmall (r + 1) out.1) cache
          ((r : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530) ?_) ?_
        · rintro ⟨result, c1⟩ hr hgood
          cases result with
          | none => exact (hgood (by simp [radix27EncodingBad])).elim
          | some pair =>
              obtain ⟨counter, encoding⟩ := pair
              have hcounter : counter.toNat < radix27CounterLimit := by
                have hnot : ¬ radix27CounterLimit ≤ counter.toNat := by
                  simpa [radix27EncodingBad] using hgood
                omega
              dsimp only
              have h1 : EncodingFresh sk.parameter (fun l => l.val < r) c1 :=
                (hfresh.mono fun l hl => Nat.lt_succ_of_lt hl).step _ ⟨_, c1⟩ hr
                  (fun f l hl tree leaf payload => Avoids.encodingSearch f _ _ _ _ _ _
                    (fun _ => encodingInput_ne_of_layer_ne _
                      (fun h => by rw [← h] at hl; exact absurd hl (Nat.lt_irrefl _)) _ _ _ _ _ _) _ _)
              refine probEvent_bind_le _ _ _ c1 _ (fun built hbuilt => ?_)
              have h2 := h1.step _ built hbuilt (fun f l _ tree leaf payload =>
                Avoids.buildLayerTreePaired_of_structural f _ _ _ _ _ _ _
                  (structural_encoding sk.parameter sk.seed l tree leaf payload))
              obtain ⟨⟨values, path, root⟩, c2⟩ := built
              dsimp only
              refine le_trans (probEvent_bind_le_add _ _
                (fun out => ¬ LayerCountersSmall r out.1)
                (fun out => ¬ LayerCountersSmall (r + 1) out.1) c2 0 ?_) ?_
              · rintro ⟨result3, c3⟩ _ hsmall
                obtain ⟨rest, hresult, hrest⟩ :=
                  (not_not.mp hsmall : LayerCountersSmall r result3)
                subst result3
                simp [LayerCountersSmall]
                intro x hx
                by_cases heq : x = (⟨r, hlayer⟩ : Layer)
                · simpa [heq] using hcounter
                · have hval : x.val < r := by
                    have hne : x.val ≠ r := by
                      intro h
                      exact heq (Fin.ext h)
                    omega
                  simpa [heq] using hrest x hval
              · rw [add_zero]
                exact ih (Nat.le_of_succ_le hrem) root c2 h2
        · calc
            _ ≤ (2⁻¹ : ℝ≥0∞) ^ 530 +
                  (r : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
                  refine add_le_add ?_ le_rfl
                  exact radix27EncodingBad_le sk.parameter _ _ _ message cache
                    (fun c _ => hfresh ⟨r, hlayer⟩ (by simp) _ _ _)
            _ = ((r + 1 : Nat) : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
                  push_cast
                  ring

#print axioms probEvent_signLayersPaired_notSmall

end SphincsSecurity.Completeness
end
-- END CounterFiveLayer

-- BEGIN CounterSignFrom from /tmp/CounterSignFrom.lean
section

open OracleComp OracleSpec ENNReal

namespace SphincsSecurity.Completeness

open Concrete
set_option maxRecDepth 10000
set_option maxHeartbeats 300000
attribute [local irreducible] Concrete.buildForestPaired

def SignatureCountersSmall (out : Option Signature) : Prop :=
  ∃ σ, out = some σ ∧
    ∀ lay : Layer, (σ.layers lay).counter.toNat < radix27CounterLimit

theorem layerCountersSmall_signature (randomness : Randomness)
    (secrets : FtsTree → Digest) (ftsPath : FtsTree → Fin ftsTreeHeight → Digest)
    (out : Option (Layer → LayerOutput))
    (h : LayerCountersSmall numLayers out) :
    SignatureCountersSmall (do
      let parts ← out
      some ⟨randomness, secrets, ftsPath,
        fun lay => LayerOutput.toSignature lay (parts lay)⟩) := by
  obtain ⟨parts, hout, hsmall⟩ := h
  subst out
  refine ⟨_, rfl, ?_⟩
  intro lay
  exact hsmall lay lay.isLt

theorem probEvent_signFrom_notSmall (sk : Seeded.SecretKey) (index : Index)
    (topNode : Nat → Nat → OracleComp HashSpec Digest) (randomness : Randomness)
    (leaves : IndexGroup → FtsLeaf) (cache : QueryCache HashSpec)
    (hfresh : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureCountersSmall r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (signFromPaired sk.parameter index (Seeded.ftsSecret sk.parameter sk.seed index)
          (Seeded.otsSecret sk.parameter sk.seed) topNode randomness leaves
          : OracleComp HashSpec (Option Signature))).run cache]
      ≤ (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [signFromPaired]
  refine probEvent_bind_le _ _ _ cache _ (fun forest hforest => ?_)
  have h1 := hfresh.step _ forest hforest (fun f l _ tree leaf payload =>
    Avoids.buildForestPaired_of_structural f _ _ _ _ _
      (structural_encoding sk.parameter sk.seed l tree leaf payload))
  obtain ⟨⟨secrets, ftsPath, ftsPublicKey⟩, c1⟩ := forest
  dsimp only
  refine le_trans (probEvent_bind_le_add _ _
    (fun out => ¬ LayerCountersSmall numLayers out.1)
    (fun out => ¬ SignatureCountersSmall out.1) c1 0 ?_) ?_
  · rintro ⟨result, c2⟩ _ hsmall
    obtain ⟨parts, hresult, hparts⟩ := (not_not.mp hsmall : LayerCountersSmall numLayers result)
    subst result
    simp [SignatureCountersSmall, LayerOutput.toSignature, hparts]
  · rw [add_zero]
    exact probEvent_signLayersPaired_notSmall sk index topNode numLayers le_rfl
      ftsPublicKey c1 (h1.mono fun _ _ => trivial)

#print axioms layerCountersSmall_signature
#print axioms probEvent_signFrom_notSmall

end SphincsSecurity.Completeness
end
-- END CounterSignFrom

-- BEGIN CounterSignChecked from /tmp/CounterSignChecked.lean
section

open OracleComp OracleSpec ENNReal

namespace SphincsSecurity.Completeness

open Concrete
set_option maxRecDepth 10000
set_option maxHeartbeats 300000
attribute [local irreducible] Seeded.signDigestLoop

theorem probEvent_signChecked_notSmall (sk : Seeded.SecretKey)
    (topCache : TopCache) (message : Message) (cache : QueryCache HashSpec)
    (hrand : ∀ s, cache (randInput sk message s) = none)
    (hmsg : ∀ ρ, cache (msgInput sk message ρ) = none)
    (henc : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureCountersSmall r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (Seeded.signChecked sk topCache message : OracleComp HashSpec (Option Signature))).run cache]
      ≤ digestFactor ^ digestAttemptLimit +
        (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [Seeded.signChecked]
  refine le_trans (probEvent_bind_le_add _ _ (fun r => r.1 = none) _ cache
    ((numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530) ?_) ?_
  · rintro ⟨result, c1⟩ hr hsome
    obtain ⟨⟨randomness, index, leaves⟩, rfl⟩ := Option.ne_none_iff_exists'.mp hsome
    dsimp only
    have h1 : EncodingFresh sk.parameter (fun _ => True) c1 :=
      henc.step _ ⟨_, c1⟩ hr (fun f l _ tree leaf payload =>
        Avoids.signDigestLoop_of_structural f _ sk message
          (structural_encoding sk.parameter sk.seed l tree leaf payload) _ _)
    exact probEvent_signFrom_notSmall sk index _ randomness leaves c1 h1
  · exact add_le_add (probEvent_signDigestLoop sk message digestAttemptLimit 0 cache ∅
      (by rw [digestAttemptLimit]; omega) (by simp) (fun s _ _ => hrand s) (fun ρ _ => hmsg ρ)) le_rfl

theorem probEvent_sign_notSmall (sk : Seeded.SecretKey)
    (topCache : TopCache) (message : Message) (cache : QueryCache HashSpec)
    (hmac : cache (macHashInput sk.parameter sk.seed topCache.region) = some topCache.tag)
    (hrand : ∀ s, cache (randInput sk message s) = none)
    (hmsg : ∀ ρ, cache (msgInput sk message ρ) = none)
    (henc : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureCountersSmall r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (Seeded.sign sk topCache message : OracleComp HashSpec (Option Signature))).run cache]
      ≤ digestFactor ^ digestAttemptLimit +
        (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [Seeded.sign]
  simp only [oracleHash, HasQuery.query, simulateQ_bind, simulateQ_spec_query, StateT.run_bind]
  rw [cached_run _ _ _ hmac, pure_bind, if_pos rfl]
  exact probEvent_signChecked_notSmall sk topCache message cache hrand hmsg henc

#print axioms probEvent_signChecked_notSmall
#print axioms probEvent_sign_notSmall

end SphincsSecurity.Completeness
end
-- END CounterSignChecked

-- BEGIN CounterKeygen from /tmp/CounterKeygen.lean
section

open OracleComp OracleSpec ENNReal

namespace SphincsSecurity.Completeness

open Concrete
set_option maxRecDepth 10000
set_option maxHeartbeats 300000

theorem probEvent_signedWithKeys_notSmall (seed : MasterSeed) (message : Message) :
    Pr[fun r => ¬ SignatureCountersSmall r.1.2 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (signedWithKeys seed message)).run ∅]
      ≤ digestFactor ^ digestAttemptLimit +
        (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [signedWithKeys]
  refine probEvent_bind_le _ _ _ ∅ _ (fun r hr => ?_)
  obtain ⟨hrand, hmsg, henc⟩ := keygen_fresh seed r hr message
  have hmac := keygen_mac_cached seed r hr
  refine le_trans (probEvent_bind_le_add _ _
    (fun out => ¬ SignatureCountersSmall out.1)
    (fun (out : ((PublicKey × TopCache × Seeded.SecretKey) × Option Signature) × QueryCache HashSpec) =>
      ¬ SignatureCountersSmall out.1.2) r.2 0 ?_) ?_
  · rintro ⟨result, c⟩ _ hsmall
    obtain ⟨signature, hresult, hcnt⟩ := (not_not.mp hsmall : SignatureCountersSmall result)
    subst result
    simp [SignatureCountersSmall, hcnt]
  · rw [add_zero]
    exact probEvent_sign_notSmall r.1.2.2 r.1.2.1 message r.2 hmac hrand hmsg henc

#print axioms probEvent_signedWithKeys_notSmall

end SphincsSecurity.Completeness
end
-- END CounterKeygen

-- BEGIN CounterSmallHQ from /tmp/CounterSmallHQ.lean
section

open OracleComp OracleSpec
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

noncomputable def smallSuccess (result : Option Signature) : Bool := by
  classical
  exact decide (SignatureCountersSmall result)

noncomputable def smallGame (seed : MasterSeed) (message : Message) :
    OracleComp SphincsSecurity.HashSpec Bool := by
  classical
  exact do
    let (_, cache, sk) ← Seeded.keygenFromSeed seed
    let result ← (Seeded.sign sk cache message : OracleComp SphincsSecurity.HashSpec (Option Signature))
    pure (smallSuccess result)

theorem hq_smallGame (seed : MasterSeed) (message : Message) :
    Equiv.HQ (smallGame seed message) := by
  classical
  unfold smallGame Seeded.keygenFromSeed Seeded.maskRegion
  simp only [bind_assoc, pure_bind]
  refine Equiv.hq_bind (Equiv.hq_buildLayerTablePaired _ rfl _ _ _
    (fun _ _ => Equiv.hq_otsSecret _ _ _ _ _ _) _ _) fun t => ?_
  refine Equiv.hq_bind (Equiv.hq_sequenceFin _ fun _ =>
    Equiv.hq_bind (Equiv.hq_sequenceFin _ fun _ =>
      Equiv.hq_bind (Equiv.hq_maskSecret _ _ _ _) fun _ => Equiv.hq_pure _)
      fun _ => Equiv.hq_pure _) fun _ => ?_
  refine Equiv.hq_bind (Equiv.hq_mac _ _ _) fun _ => ?_
  refine Equiv.hq_bind (Equiv.hq_sign _ rfl _ _) fun _ => Equiv.hq_pure _

#print axioms hq_smallGame
end SigGolfCandidate.Final
end
-- END CounterSmallHQ

-- BEGIN CounterSmallEq from /tmp/CounterSmallEq.lean
section

open OracleComp OracleSpec
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

theorem smallGame_eq (seed : MasterSeed) (message : Message) :
    smallGame seed message =
      (fun kr => smallSuccess kr.2) <$>
        signedWithKeys seed message := by
  classical
  unfold smallGame signedWithKeys
  rw [map_bind]
  refine bind_congr fun keys => ?_
  rcases keys with ⟨pk, cache, sk⟩
  rw [map_bind]
  refine bind_congr fun result => ?_
  simp only [map_pure, pure_bind]

#print axioms smallGame_eq
end SigGolfCandidate.Final
end
-- END CounterSmallEq

-- BEGIN CounterSmallSim from /tmp/CounterSmallSim.lean
section

open OracleComp OracleSpec
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

set_option maxHeartbeats 30000

theorem smallGame_simulated_eq (seed : MasterSeed) (message : Message) :
    (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
      (smallGame seed message)).run' ∅ =
    (fun kr => smallSuccess kr.2) <$>
      (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
        (signedWithKeys seed message)).run' ∅ := by
  rw [smallGame_eq, simulateQ_map]
  rw [StateT.run'_eq, StateT.run_map]
  simp only [Functor.map_map, Function.comp_def, StateT.run'_eq]

#print axioms smallGame_simulated_eq
end SigGolfCandidate.Final
end
-- END CounterSmallSim

-- BEGIN CounterSmallEvent from /tmp/CounterSmallEvent.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

theorem smallSuccess_false_iff (result : Option Signature) :
    smallSuccess result = false ↔ ¬ SignatureCountersSmall result := by
  classical
  simp [smallSuccess]

set_option maxHeartbeats 40000
theorem probOutput_smallGame_false_eq (seed : MasterSeed) (message : Message) :
    Pr[= false | (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
      (smallGame seed message)).run' ∅] =
    Pr[fun r => ¬ SignatureCountersSmall r.1.2 |
      (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
        (signedWithKeys seed message)).run ∅] := by
  rw [smallGame_simulated_eq, StateT.run'_eq, probOutput_map, probEvent_map]
  simp only [Function.comp_def, smallSuccess_false_iff]

#print axioms probOutput_smallGame_false_eq
end SigGolfCandidate.Final
end
-- END CounterSmallEvent

-- BEGIN CounterSmallBound from /tmp/CounterSmallBound.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

theorem probOutput_smallGame_false_le (seed : MasterSeed) (message : Message) :
    Pr[= false | (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
      (smallGame seed message)).run' ∅] ≤
      digestFactor ^ digestAttemptLimit +
        (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [probOutput_smallGame_false_eq]
  exact probEvent_signedWithKeys_notSmall seed message

#print axioms probOutput_smallGame_false_le
end SigGolfCandidate.Final
end
-- END CounterSmallBound

-- BEGIN CounterSmallHD from /tmp/CounterSmallHD.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness
open SigGolfCandidate.Bridge (relabel relabel_relabel)

noncomputable def smallGameHD (seed : MasterSeed) (message : Message) :
    OracleComp (HD →ₒ SphincsSecurity.HashOutput) Bool :=
  relabel toHD (smallGame seed message)

theorem relabel_val_smallGameHD (seed : MasterSeed) (message : Message) :
    relabel Subtype.val (smallGameHD seed message) = smallGame seed message := by
  unfold smallGameHD
  rw [relabel_relabel]
  exact Bridge.relabel_eq_self_of_allQ Equiv.Honest _ (fun x hx => val_toHD x hx)
    (hq_smallGame seed message)

theorem probOutput_smallGameHD_false_le (seed : MasterSeed) (message : Message) :
    Pr[= false | (simulateQ randomOracle (smallGameHD seed message)).run' ∅] ≤
      digestFactor ^ digestAttemptLimit +
        (numLayers : ℝ≥0∞) * (2⁻¹ : ℝ≥0∞) ^ 530 := by
  rw [run'_relabel Subtype.val Subtype.val_injective (smallGameHD seed message) ∅ ∅
    (fun _ => rfl), relabel_val_smallGameHD]
  exact probOutput_smallGame_false_le seed message

#print axioms probOutput_smallGameHD_false_le
end SigGolfCandidate.Final
end
-- END CounterSmallHD

-- BEGIN CounterSmallAll from /tmp/CounterSmallAll.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity
open SphincsSecurity.Completeness

private noncomputable abbrev x : ℝ≥0∞ := 2⁻¹

theorem smallGame_failure_seeded (seed : MasterSeed) :
    ∑' message : Message,
      Pr[= false | (simulateQ randomOracle (smallGameHD seed message)).run' ∅] ≤
      ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := by
  calc
    ∑' message : Message,
        Pr[= false | (simulateQ randomOracle (smallGameHD seed message)).run' ∅]
        ≤ ∑' _message : Message,
          (x ^ 1023 + 5 * x ^ 530) := by
            apply ENNReal.tsum_le_tsum
            intro message
            refine (probOutput_smallGameHD_false_le seed message).trans ?_
            rw [show ((numLayers : Nat) : ℝ≥0∞) = 5 by norm_num [numLayers]]
            exact add_le_add digestFactor_pow_le le_rfl
    _ = (2 : ℝ≥0∞) ^ 256 * (x ^ 1023 + 5 * x ^ 530) := by
          rw [tsum_fintype, Finset.sum_const, nsmul_eq_mul, Finset.card_univ,
            show Fintype.card Message = 2 ^ 256 by simp [messageBits], Nat.cast_pow, Nat.cast_ofNat]
    _ ≤ ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := by
      refine le_trans ?_ radix27_complete_numeric
      apply mul_le_mul' le_rfl
      have h : x ^ 1023 ≤ x ^ 1023 + 5 * x ^ 1256 :=
        le_add_of_nonneg_right (show (0 : ℝ≥0∞) ≤ 5 * x ^ 1256 from bot_le)
      exact add_le_add_left h _

#print axioms smallGame_failure_seeded
end SigGolfCandidate.Final
end
-- END CounterSmallAll
