-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import Mathlib
import SigGolfCandidate.Packed.Radix12Bundle01
import SigGolfCandidate.SphincsSecurity.Completeness.Decay

-- BEGIN Radix12FiveLayer from /tmp/Radix12FiveLayer.lean
section

open OracleComp OracleSpec ENNReal
namespace SphincsSecurity.Completeness
open Concrete TargetSum

set_option maxRecDepth 10000
set_option maxHeartbeats 700000
attribute [local irreducible] Seeded.signDigestLoop Concrete.buildLayerTreePaired
  Concrete.buildForestPaired Concrete.encodingSearch digestAttemptLimit
  encodingAttemptLimit SphincsSecurity.deriveKey Seeded.signChecked

theorem probEvent_signLayersPaired_sumBad (sk : Seeded.SecretKey) (index : Index)
    (topNode : Nat → Nat → OracleComp HashSpec Digest) :
    ∀ (remaining : Nat), remaining ≤ numLayers → 0 < remaining →
      ∀ (message : Digest) (cache : QueryCache HashSpec) (cut : Nat),
      0 < cut → cut ≤ encodingAttemptLimit →
      EncodingFresh sk.parameter (fun l => l.val < remaining) cache →
      Pr[fun r => ¬ LayerSumSmall remaining cut r.1 |
        (simulateQ (randomOracle : QueryImpl HashSpec _)
          (signLayersPaired sk.parameter index (Seeded.otsSecret sk.parameter sk.seed)
            topNode remaining message : OracleComp HashSpec (Option (Layer → LayerOutput)))).run cache]
        ≤ layerTailBound (failMass (fun out => decodeDigest (truncateHash out))) remaining cut := by
  intro remaining
  induction remaining with
  | zero => intro _ hpos; omega
  | succ r ih =>
      intro hrem hpos message cache cut hcutpos hcut hfresh
      by_cases hzero : r = 0
      · subst hzero
        rw [signLayersPaired]
        split
        next hlayer =>
          rw [if_pos rfl]
          refine le_trans (probEvent_bind_le_add _ _
            (fun out => ¬ TopSumSmall cut out.1)
            (fun out => ¬ LayerSumSmall 1 cut out.1) cache 0 ?_) ?_
          · rintro ⟨result, c1⟩ _ hgood
            obtain ⟨⟨counter, values, path⟩, hresult, hcounter⟩ :=
              (not_not.mp hgood : TopSumSmall cut result)
            subst result
            have hsmall := topSumSmall_layer counter values path cut hcounter
            obtain ⟨parts, hparts, hbound⟩ := hsmall
            have heq := Option.some.inj hparts
            subst parts
            simpa [LayerSumSmall] using hbound
          · rw [add_zero]
            have htop := probEvent_signTopLayerPaired_notSumSmall sk.parameter index
              (Seeded.otsSecret sk.parameter sk.seed topLayer (treeIndexAt index topLayer))
              topNode message cache cut hcut hfresh
            simpa [layerTailBound] using htop
        next hlayer => exact absurd (show 0 < numLayers by decide) hlayer
      · have hlayer : r < numLayers := Nat.lt_of_succ_le hrem
        rw [signLayersPaired_succ_bind sk.parameter index
          (Seeded.otsSecret sk.parameter sk.seed) topNode r hlayer hzero message]
        let q : ℝ≥0∞ := failMass (fun out => decodeDigest (truncateHash out))
        let f : Nat → ℝ≥0∞ := fun j => layerTailBound q r (cut - j)
        have hmain := encodingSearch_bind_class_le sk.parameter ⟨r, hlayer⟩
          (treeIndexAt index ⟨r, hlayer⟩) (leafIndexAt index ⟨r, hlayer⟩)
          message cache cut hcut
          (radix27LayerContinuation sk.parameter index
            (Seeded.otsSecret sk.parameter sk.seed) topNode r hlayer)
          (fun out => ¬ LayerSumSmall (r + 1) cut out.1) f
          (fun c _ => hfresh ⟨r, hlayer⟩ (by simp) _ _ _)
          (by
            intro res hres hclass
            cases henc : res.1 with
            | none =>
                simp only [encodingClass, henc] at hclass
                omega
            | some pair =>
                obtain ⟨counter, encoding⟩ := pair
                have hcounter : counter.toNat < cut := by
                  simpa only [encodingClass, henc] using hclass
                have hc : encodingClass cut res = counter.toNat := by
                  simp only [encodingClass, henc]
                rw [hc]
                change Pr[fun out => ¬ LayerSumSmall (r + 1) cut out.1 |
                  (simulateQ randomOracle
                    (radix27LayerContinuation sk.parameter index
                      (Seeded.otsSecret sk.parameter sk.seed) topNode r hlayer
                      (some (counter, encoding)))).run res.2] ≤
                  layerTailBound q r (cut - counter.toNat)
                have h1 : EncodingFresh sk.parameter (fun l => l.val < r) res.2 :=
                  (hfresh.mono fun l hl => Nat.lt_succ_of_lt hl).step _ res hres
                    (fun f l hl tree leaf payload => Avoids.encodingSearch f _ _ _ _ _ _
                      (fun _ => encodingInput_ne_of_layer_ne _
                        (fun h => by rw [← h] at hl; exact absurd hl (Nat.lt_irrefl _))
                        _ _ _ _ _ _) _ _)
                unfold radix27LayerContinuation
                dsimp only
                refine probEvent_bind_le _ _ _ res.2 _ (fun built hbuilt => ?_)
                have h2 := h1.step _ built hbuilt (fun f l _ tree leaf payload =>
                  Avoids.buildLayerTreePaired_of_structural f _ _ _ _ _ _ _
                    (structural_encoding sk.parameter sk.seed l tree leaf payload))
                obtain ⟨⟨values, path, root⟩, c2⟩ := built
                dsimp only
                refine le_trans (probEvent_bind_le_add _ _
                  (fun out => ¬ LayerSumSmall r (cut - counter.toNat) out.1)
                  (fun out => ¬ LayerSumSmall (r + 1) cut out.1) c2 0 ?_) ?_
                · rintro ⟨result3, c3⟩ _ hsmall
                  obtain ⟨rest, hresult, hrest⟩ :=
                    (not_not.mp hsmall : LayerSumSmall r (cut - counter.toNat) result3)
                  subst result3
                  have hfull : LayerSumSmall (r + 1) cut
                      (some fun other => if other = (⟨r, hlayer⟩ : Layer)
                        then (counter, values, path) else rest other) :=
                    (layerSumSmall_wrapped_iff r hlayer counter values path rest cut hcounter).2
                      ⟨rest, rfl, hrest⟩
                  obtain ⟨parts, hparts, hbound⟩ := hfull
                  have heq := Option.some.inj hparts
                  subst parts
                  simpa [LayerSumSmall] using hbound
                · rw [add_zero]
                  have hpos : 0 < cut - counter.toNat := by omega
                  exact ih (Nat.le_of_succ_le hrem) (by omega) root c2
                    (cut - counter.toNat) hpos (by omega) h2)
        refine hmain.trans ?_
        exact layerTailBound_recurrence q r cut (by omega) hcutpos

#print axioms probEvent_signLayersPaired_sumBad
end SphincsSecurity.Completeness
end
-- END Radix12FiveLayer

-- BEGIN Radix12SignFrom from /tmp/Radix12SignFrom.lean
section

open OracleComp OracleSpec ENNReal
namespace SphincsSecurity.Completeness
open Concrete

def sigCounterParts (σ : Signature) : Layer → LayerOutput :=
  fun lay => ((σ.layers lay).counter, fun _ => 0, fun _ => 0)

def SignatureSumSmall (cut : Nat) (out : Option Signature) : Prop :=
  ∃ σ, out = some σ ∧ layerCounterSum numLayers (sigCounterParts σ) < cut

theorem layerCounterSum_counter_congr (n : Nat) (f g : Layer → LayerOutput)
    (h : ∀ lay : Layer, lay.val < n → (f lay).1 = (g lay).1) :
    layerCounterSum n f = layerCounterSum n g := by
  induction n with
  | zero => rfl
  | succ r ih =>
      unfold layerCounterSum
      split
      next hr =>
        rw [h ⟨r, hr⟩ (by simp), ih (fun lay hl => h lay (by omega))]
      next _ => rfl

theorem layerSumSmall_signature (cut : Nat) (randomness : Randomness)
    (secrets : FtsTree → Digest) (ftsPath : FtsTree → Fin ftsTreeHeight → Digest)
    (out : Option (Layer → LayerOutput))
    (h : LayerSumSmall numLayers cut out) :
    SignatureSumSmall cut (do
      let parts ← out
      some ⟨randomness, secrets, ftsPath,
        fun lay => LayerOutput.toSignature lay (parts lay)⟩) := by
  obtain ⟨parts, hout, hsum⟩ := h
  subst out
  refine ⟨_, rfl, ?_⟩
  exact (layerCounterSum_counter_congr numLayers _ _
    (fun lay _ => rfl)).symm ▸ hsum

set_option maxRecDepth 10000
set_option maxHeartbeats 300000
attribute [local irreducible] Concrete.buildForestPaired

theorem probEvent_signFrom_sumBad (sk : Seeded.SecretKey) (index : Index)
    (topNode : Nat → Nat → OracleComp HashSpec Digest) (randomness : Randomness)
    (leaves : IndexGroup → FtsLeaf) (cache : QueryCache HashSpec)
    (cut : Nat) (hpos : 0 < cut) (hcut : cut ≤ encodingAttemptLimit)
    (hfresh : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureSumSmall cut r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (signFromPaired sk.parameter index (Seeded.ftsSecret sk.parameter sk.seed index)
          (Seeded.otsSecret sk.parameter sk.seed) topNode randomness leaves
          : OracleComp HashSpec (Option Signature))).run cache]
      ≤ layerTailBound (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
        numLayers cut := by
  rw [signFromPaired]
  refine probEvent_bind_le _ _ _ cache _ (fun forest hforest => ?_)
  have h1 := hfresh.step _ forest hforest (fun f l _ tree leaf payload =>
    Avoids.buildForestPaired_of_structural f _ _ _ _ _
      (structural_encoding sk.parameter sk.seed l tree leaf payload))
  obtain ⟨⟨secrets, ftsPath, ftsPublicKey⟩, c1⟩ := forest
  dsimp only
  refine le_trans (probEvent_bind_le_add _ _
    (fun out => ¬ LayerSumSmall numLayers cut out.1)
    (fun out => ¬ SignatureSumSmall cut out.1) c1 0 ?_) ?_
  · rintro ⟨result, c2⟩ _ hsmall
    obtain ⟨parts, hresult, hsum⟩ :=
      (not_not.mp hsmall : LayerSumSmall numLayers cut result)
    subst result
    have hsig := layerSumSmall_signature cut randomness secrets ftsPath
      (some parts) ⟨parts, rfl, hsum⟩
    simpa [SignatureSumSmall] using hsig
  · rw [add_zero]
    exact probEvent_signLayersPaired_sumBad sk index topNode numLayers le_rfl
      (by decide) ftsPublicKey c1 cut hpos hcut (h1.mono fun _ _ => trivial)

#print axioms layerSumSmall_signature
#print axioms probEvent_signFrom_sumBad
end SphincsSecurity.Completeness
end
-- END Radix12SignFrom

-- BEGIN Radix12SignChecked from /tmp/Radix12SignChecked.lean
section

open OracleComp OracleSpec ENNReal
namespace SphincsSecurity.Completeness
open Concrete

set_option maxRecDepth 10000
set_option maxHeartbeats 300000
attribute [local irreducible] Seeded.signDigestLoop

theorem probEvent_signChecked_sumBad (sk : Seeded.SecretKey)
    (topCache : TopCache) (message : Message) (cache : QueryCache HashSpec)
    (cut : Nat) (hpos : 0 < cut) (hcut : cut ≤ encodingAttemptLimit)
    (hrand : ∀ s, cache (randInput sk message s) = none)
    (hmsg : ∀ ρ, cache (msgInput sk message ρ) = none)
    (henc : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureSumSmall cut r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (Seeded.signChecked sk topCache message : OracleComp HashSpec (Option Signature))).run cache]
      ≤ digestFactor ^ digestAttemptLimit +
        layerTailBound (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
          numLayers cut := by
  rw [Seeded.signChecked]
  refine le_trans (probEvent_bind_le_add _ _ (fun r => r.1 = none) _ cache
    (layerTailBound (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
      numLayers cut) ?_) ?_
  · rintro ⟨result, c1⟩ hr hsome
    obtain ⟨⟨randomness, index, leaves⟩, rfl⟩ := Option.ne_none_iff_exists'.mp hsome
    dsimp only
    have h1 : EncodingFresh sk.parameter (fun _ => True) c1 :=
      henc.step _ ⟨_, c1⟩ hr (fun f l _ tree leaf payload =>
        Avoids.signDigestLoop_of_structural f _ sk message
          (structural_encoding sk.parameter sk.seed l tree leaf payload) _ _)
    exact probEvent_signFrom_sumBad sk index _ randomness leaves c1 cut hpos hcut h1
  · exact add_le_add (probEvent_signDigestLoop sk message digestAttemptLimit 0 cache ∅
      (by rw [digestAttemptLimit]; omega) (by simp) (fun s _ _ => hrand s)
      (fun ρ _ => hmsg ρ)) le_rfl

theorem probEvent_sign_sumBad (sk : Seeded.SecretKey)
    (topCache : TopCache) (message : Message) (cache : QueryCache HashSpec)
    (cut : Nat) (hpos : 0 < cut) (hcut : cut ≤ encodingAttemptLimit)
    (hmac : cache (macHashInput sk.parameter sk.seed topCache.region) = some topCache.tag)
    (hrand : ∀ s, cache (randInput sk message s) = none)
    (hmsg : ∀ ρ, cache (msgInput sk message ρ) = none)
    (henc : EncodingFresh sk.parameter (fun _ => True) cache) :
    Pr[fun r => ¬ SignatureSumSmall cut r.1 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (Seeded.sign sk topCache message : OracleComp HashSpec (Option Signature))).run cache]
      ≤ digestFactor ^ digestAttemptLimit +
        layerTailBound (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
          numLayers cut := by
  rw [Seeded.sign]
  simp only [oracleHash, HasQuery.query, simulateQ_bind, simulateQ_spec_query, StateT.run_bind]
  rw [cached_run _ _ _ hmac, pure_bind, if_pos rfl]
  exact probEvent_signChecked_sumBad sk topCache message cache cut hpos hcut hrand hmsg henc

#print axioms probEvent_signChecked_sumBad
#print axioms probEvent_sign_sumBad
end SphincsSecurity.Completeness
end
-- END Radix12SignChecked

-- BEGIN Radix12Keygen from /tmp/Radix12Keygen.lean
section

open OracleComp OracleSpec ENNReal
namespace SphincsSecurity.Completeness
open Concrete

set_option maxRecDepth 10000
set_option maxHeartbeats 300000

theorem probEvent_signedWithKeys_sumBad (seed : MasterSeed) (message : Message)
    (cut : Nat) (hpos : 0 < cut) (hcut : cut ≤ encodingAttemptLimit) :
    Pr[fun r => ¬ SignatureSumSmall cut r.1.2 |
      (simulateQ (randomOracle : QueryImpl HashSpec _)
        (signedWithKeys seed message)).run ∅]
      ≤ digestFactor ^ digestAttemptLimit +
        layerTailBound (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
          numLayers cut := by
  rw [signedWithKeys]
  refine probEvent_bind_le _ _ _ ∅ _ (fun r hr => ?_)
  obtain ⟨hrand, hmsg, henc⟩ := keygen_fresh seed r hr message
  have hmac := keygen_mac_cached seed r hr
  refine le_trans (probEvent_bind_le_add _ _
    (fun out => ¬ SignatureSumSmall cut out.1)
    (fun (out : ((PublicKey × TopCache × Seeded.SecretKey) × Option Signature) ×
      QueryCache HashSpec) => ¬ SignatureSumSmall cut out.1.2) r.2 0 ?_) ?_
  · rintro ⟨result, c⟩ _ hsmall
    obtain ⟨signature, hresult, hcnt⟩ :=
      (not_not.mp hsmall : SignatureSumSmall cut result)
    subst result
    simp [SignatureSumSmall, hcnt]
  · rw [add_zero]
    exact probEvent_sign_sumBad r.1.2.2 r.1.2.1 message r.2 cut hpos hcut
      hmac hrand hmsg henc

#print axioms probEvent_signedWithKeys_sumBad
end SphincsSecurity.Completeness
end
-- END Radix12Keygen

-- BEGIN Radix12Numeric from /tmp/Radix12Numeric.lean
section

set_option maxRecDepth 10000
set_option maxHeartbeats 600000

theorem radix12_96bit_capacity : Nat.choose (1565526 + 4) 5 < 2 ^ 96 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  norm_num [Nat.descFactorial]

theorem radix12_geom_block : (3337 : ℚ) ^ 3338 * 5 ≤ 2 * (3338 : ℚ) ^ 3338 := by
  have h : 3337 ^ 3338 * 5 ≤ 2 * 3338 ^ 3338 := by decide
  exact_mod_cast h

#print axioms radix12_96bit_capacity
#print axioms radix12_geom_block
end
-- END Radix12Numeric

-- BEGIN Radix12TailNumeric from /tmp/Radix12TailNumeric.lean
section

open ENNReal
open SphincsSecurity.Completeness
set_option maxRecDepth 10000
set_option maxHeartbeats 300000

theorem radix12_geom_block_enn :
    ((3337 : ℝ≥0∞) / 3338) ^ 3338 ≤ (2 : ℝ≥0∞) / 5 := by
  have hnat : 3337 ^ 3338 * 5 ≤ 2 * 3338 ^ 3338 := by decide
  have hnn : ((3337 : NNReal) / 3338) ^ 3338 ≤ (2 : NNReal) / 5 := by
    rw [div_pow]
    apply (div_le_div_iff₀ (by positivity) (by positivity)).2
    exact_mod_cast hnat
  have hcast : ((↑((3337 : NNReal) / 3338) : ℝ≥0∞) ^ 3338) ≤
      (↑((2 : NNReal) / 5) : ℝ≥0∞) := by exact_mod_cast hnn
  rw [ENNReal.coe_div (by norm_num : (3338 : NNReal) ≠ 0),
      ENNReal.coe_div (by norm_num : (5 : NNReal) ≠ 0)] at hcast
  simpa using hcast

theorem radix12_seven_block :
    ((2 : ℝ≥0∞) / 5) ^ 7 ≤ (2⁻¹ : ℝ≥0∞) ^ 9 := by
  have hnn : ((2 : NNReal) / 5) ^ 7 ≤ ((1 : NNReal) / 2) ^ 9 := by
    rw [div_pow, div_pow]
    apply (div_le_div_iff₀ (by positivity) (by positivity)).2
    norm_num
  have hcast : ((↑((2 : NNReal) / 5) : ℝ≥0∞) ^ 7) ≤
      ((↑((1 : NNReal) / 2) : ℝ≥0∞) ^ 9) := by exact_mod_cast hnn
  rw [ENNReal.coe_div (by norm_num : (5 : NNReal) ≠ 0),
      ENNReal.coe_div (by norm_num : (2 : NNReal) ≠ 0)] at hcast
  simpa [one_div] using hcast

theorem radix12_geom_tail :
    ((3337 : ℝ≥0∞) / 3338) ^ (1565526 - 4) ≤
      (2⁻¹ : ℝ≥0∞) ^ 603 := by
  have hexp : 1565526 - 4 = 3338 * (7 * 67) := by norm_num
  rw [hexp, pow_mul, pow_mul]
  calc
    ((((3337 : ℝ≥0∞) / 3338) ^ 3338) ^ 7) ^ 67 ≤
        (((2 : ℝ≥0∞) / 5) ^ 7) ^ 67 := by
      gcongr
      exact radix12_geom_block_enn
    _ ≤ ((2⁻¹ : ℝ≥0∞) ^ 9) ^ 67 := by
      exact pow_le_pow_left₀ (by positivity) radix12_seven_block 67
    _ = (2⁻¹ : ℝ≥0∞) ^ 603 := by rw [← pow_mul]

theorem radix12_failure_extra_le :
    (5 : ℝ≥0∞) * (1565526 : ℝ≥0∞) ^ 4 *
      (((3337 : ℝ≥0∞) / 3338) ^ (1565526 - 4)) ≤
      (2⁻¹ : ℝ≥0∞) ^ 516 := by
  have hN : (1565526 : ℝ≥0∞) ≤ (2 : ℝ≥0∞) ^ 21 := by norm_num
  have hfive : (5 : ℝ≥0∞) ≤ (2 : ℝ≥0∞) ^ 3 := by norm_num
  calc
    (5 : ℝ≥0∞) * (1565526 : ℝ≥0∞) ^ 4 *
        (((3337 : ℝ≥0∞) / 3338) ^ (1565526 - 4)) ≤
      5 * (1565526 : ℝ≥0∞) ^ 4 * (2⁻¹ : ℝ≥0∞) ^ 603 := by
        exact mul_le_mul_right radix12_geom_tail _
    _ ≤ (2 : ℝ≥0∞) ^ 3 * ((2 : ℝ≥0∞) ^ 21) ^ 4 *
        (2⁻¹ : ℝ≥0∞) ^ 603 := by gcongr
    _ = (2 : ℝ≥0∞) ^ 87 * (2⁻¹ : ℝ≥0∞) ^ 603 := by norm_num [pow_mul]
    _ = (2⁻¹ : ℝ≥0∞) ^ 516 := by
      rw [← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
        show (603 : Nat) = 87 + 516 by norm_num, two_pow_div_two_pow]

#print axioms radix12_geom_block_enn
#print axioms radix12_geom_tail
#print axioms radix12_failure_extra_le
end
-- END Radix12TailNumeric

-- BEGIN Radix12QBound from /tmp/Radix12QBound.lean
section

open ENNReal SphincsSecurity SphincsSecurity.Completeness SphincsSecurity.TargetSum

theorem radix12_q_le :
    failMass (fun out => decodeDigest (truncateHash out)) ≤
      (3337 : ℝ≥0∞) / 3338 := by
  have hroom := failMass_encoding_add_le
  have hsum : (3337 : ℝ≥0∞) / 3338 + (3338 : ℝ≥0∞)⁻¹ = 1 := by
    have hnn : (3337 : NNReal) / 3338 + (1 : NNReal) / 3338 = 1 := by
      norm_num
    have hcast := congrArg (fun x : NNReal => (x : ℝ≥0∞)) hnn
    simp only [ENNReal.coe_add, ENNReal.coe_div (by norm_num : (3338 : NNReal) ≠ 0),
      ENNReal.coe_natCast, ENNReal.coe_one, one_div] at hcast
    simpa using hcast
  have hroom' : failMass (fun out => decodeDigest (truncateHash out)) +
      (3338 : ℝ≥0∞)⁻¹ ≤ 1 := by simpa [codeShare] using hroom
  have hsum' : failMass (fun out => decodeDigest (truncateHash out)) +
      (3338 : ℝ≥0∞)⁻¹ ≤
      (3337 : ℝ≥0∞) / 3338 + (3338 : ℝ≥0∞)⁻¹ := by
    simpa only [hsum] using hroom'
  exact (ENNReal.add_le_add_iff_right (by norm_num : (3338 : ℝ≥0∞)⁻¹ ≠ ⊤)).mp hsum'

#print axioms radix12_q_le
end
-- END Radix12QBound

-- BEGIN Radix12NumericClose from /tmp/Radix12NumericClose.lean
section

open ENNReal SphincsSecurity SphincsSecurity.Completeness SphincsSecurity.TargetSum
set_option maxRecDepth 10000
set_option maxHeartbeats 300000

theorem radix12_layer_tail_le :
    layerTailBound
      (failMass (fun out => decodeDigest (truncateHash out)))
      numLayers 1565526 ≤ (2⁻¹ : ℝ≥0∞) ^ 516 := by
  let q : ℝ≥0∞ := failMass (fun out => decodeDigest (truncateHash out))
  let q₀ : ℝ≥0∞ := (3337 : ℝ≥0∞) / 3338
  have hq : q ≤ q₀ := radix12_q_le
  have hq₀ : q₀ ≤ 1 := by
    dsimp [q₀]
    have hnn : (3337 : NNReal) / 3338 ≤ 1 := by
      apply (div_le_iff₀ (by positivity)).2
      norm_num
    have hcast : (↑((3337 : NNReal) / 3338) : ℝ≥0∞) ≤ 1 := by
      exact_mod_cast hnn
    rw [ENNReal.coe_div (by norm_num : (3338 : NNReal) ≠ 0)] at hcast
    simpa using hcast
  have hpow : q ^ 1565526 ≤ q₀ ^ (1565526 - 4) :=
    (pow_le_pow_left₀ bot_le hq _).trans
      (pow_le_pow_right_of_le_one' hq₀ (by omega))
  calc
    layerTailBound q numLayers 1565526 =
        5 * (1565526 : ℝ≥0∞) ^ 4 * q ^ 1565526 := by
          simp [layerTailBound, numLayers]
    _ ≤ 5 * (1565526 : ℝ≥0∞) ^ 4 * q₀ ^ (1565526 - 4) := by
          exact mul_le_mul' le_rfl hpow
    _ ≤ (2⁻¹ : ℝ≥0∞) ^ 516 := radix12_failure_extra_le

#print axioms radix12_layer_tail_le
end
-- END Radix12NumericClose

-- BEGIN Radix12AllNumeric from /tmp/Radix12AllNumeric.lean
section

open ENNReal SphincsSecurity.Completeness

theorem radix12_complete_numeric :
    (2 : ℝ≥0∞) ^ 256 *
      ((2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516) ≤
      ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := by
  let x : ℝ≥0∞ := 2⁻¹
  have hsum : x ^ 1023 + x ^ 516 ≤ x ^ 515 := by
    calc
      x ^ 1023 + x ^ 516 ≤ x ^ 516 + x ^ 516 :=
        add_le_add (inv_two_pow_anti (by norm_num)) le_rfl
      _ = x ^ 515 := inv_two_pow_succ_add 515
  have hcast : ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ = x ^ 256 := by
    simp only [x, Nat.cast_pow, Nat.cast_ofNat, ENNReal.inv_pow]
  rw [hcast]
  calc
    (2 : ℝ≥0∞) ^ 256 * (x ^ 1023 + x ^ 516) ≤
        (2 : ℝ≥0∞) ^ 256 * x ^ 515 := mul_le_mul' le_rfl hsum
    _ = x ^ 259 := by
      dsimp [x]
      rw [← ENNReal.inv_pow, mul_comm, ← ENNReal.div_eq_inv_mul,
        show (515 : Nat) = 256 + 259 by norm_num,
        two_pow_div_two_pow]
    _ ≤ x ^ 256 := inv_two_pow_anti (by norm_num)

#print axioms radix12_complete_numeric
end
-- END Radix12AllNumeric

-- BEGIN Radix12GameShape from /tmp/Radix12GameShape.lean
section

open OracleComp OracleSpec
namespace SigGolfCandidate.Final
open SphincsSecurity SphincsSecurity.Completeness

noncomputable def smallSuccess12 (out : Option Signature) : Bool :=
  by classical exact decide (SignatureSumSmall 1565526 out)

theorem smallSuccess12_true_iff (out : Option Signature) :
    smallSuccess12 out = true ↔ SignatureSumSmall 1565526 out := by
  classical
  simp [smallSuccess12]

noncomputable def game12 (seed : MasterSeed) (message : SphincsSecurity.Message) :
    OracleComp SphincsSecurity.HashSpec Bool := do
  let (pk, cache, sk) ← Seeded.keygenFromSeed seed
  let result ← (Seeded.sign sk cache message : OracleComp SphincsSecurity.HashSpec (Option Signature))
  match result with
  | none => pure false
  | some σ =>
      if smallSuccess12 (some σ) then
        (Concrete.verify pk message σ : OracleComp SphincsSecurity.HashSpec Bool)
      else pure false

theorem game12_eq_signedWithKeys (seed : MasterSeed)
    (message : SphincsSecurity.Message) :
    game12 seed message = signedWithKeys seed message >>= fun kr =>
      match kr.2 with
      | none => pure false
      | some σ =>
          if smallSuccess12 (some σ) then
            (Concrete.verify kr.1.1 message σ : OracleComp SphincsSecurity.HashSpec Bool)
          else pure false := by
  unfold game12 signedWithKeys
  simp only [bind_assoc, pure_bind]

theorem hq_game12 (seed : MasterSeed) (message : SphincsSecurity.Message) :
    Equiv.HQ (game12 seed message) := by
  unfold game12 Seeded.keygenFromSeed Seeded.maskRegion
  simp only [bind_assoc, pure_bind]
  refine Equiv.hq_bind (Equiv.hq_buildLayerTablePaired _ rfl _ _ _
    (fun _ _ => Equiv.hq_otsSecret _ _ _ _ _ _) _ _) fun t => ?_
  refine Equiv.hq_bind (Equiv.hq_sequenceFin _ fun _ =>
    Equiv.hq_bind (Equiv.hq_sequenceFin _ fun _ =>
      Equiv.hq_bind (Equiv.hq_maskSecret _ _ _ _) fun _ => Equiv.hq_pure _)
      fun _ => Equiv.hq_pure _) fun _ => ?_
  refine Equiv.hq_bind (Equiv.hq_mac _ _ _) fun _ => ?_
  refine Equiv.hq_bind (Equiv.hq_sign _ rfl _ _) fun s => ?_
  rcases s with _ | σ
  · exact Equiv.hq_pure _
  · by_cases h : smallSuccess12 (some σ) = true
    · simp only [h, if_true]
      exact Equiv.hq_verify _ rfl _ _
    · simp only [h, if_false]
      exact Equiv.hq_pure _

#print axioms game12_eq_signedWithKeys
#print axioms hq_game12
end SigGolfCandidate.Final
end
-- END Radix12GameShape

-- BEGIN Radix12GameBound from /tmp/Radix12GameBound.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity SphincsSecurity.Completeness

set_option maxHeartbeats 1000000
set_option maxRecDepth 100000
attribute [local irreducible] Seeded.signDigestLoop Concrete.signFrom Concrete.buildLayerTree
  Concrete.sequenceFin digestAttemptLimit encodingAttemptLimit

theorem probEvent_game12_false_le (seed : MasterSeed)
    (message : SphincsSecurity.Message) :
    Pr[fun r => r.1 = false |
      (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
        (game12 seed message)).run ∅] ≤
    Pr[fun r => ¬ SignatureSumSmall 1565526 r.1.2 |
      (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
        (signedWithKeys seed message)).run ∅] := by
  rw [game12_eq_signedWithKeys]
  refine le_trans (probEvent_bind_le_add _ _
    (fun r => ¬ SignatureSumSmall 1565526 r.1.2) _ ∅ 0 ?_) (by rw [add_zero])
  rintro ⟨⟨⟨pk, topCache, sk⟩, result⟩, cache⟩ hr hgood
  obtain ⟨signature, hresult, hsum⟩ :=
    (not_not.mp hgood : SignatureSumSmall 1565526 result)
  subst result
  have hv : smallSuccess12 (some signature) = true :=
    (smallSuccess12_true_iff _).2 ⟨signature, rfl, hsum⟩
  dsimp only
  rw [hv]
  rw [nonpos_iff_eq_zero, probEvent_eq_zero_iff]
  rintro ⟨b, cache'⟩ hr'
  obtain ⟨f, hf⟩ := QueryCache.exists_agreesWithFn (spec := SphincsSecurity.HashSpec) cache'
  obtain ⟨hle, hverify, _⟩ := replay_of_mem_support _ cache b cache' hr' f hf
  obtain ⟨hsigned, _⟩ := replay_of_mem_support_of_le _ ∅ _ cache cache' hr hle f hf
  simp only [signedWithKeys, evalWithAnswerFn_bind, evalWithAnswerFn_pure] at hsigned
  have hkeys : evalWithAnswerFn f (Seeded.keygenFromSeed seed) = (pk, topCache, sk) :=
    congrArg Prod.fst hsigned
  have hsign := congrArg Prod.snd hsigned
  rw [hkeys] at hsign
  have htrue := verify_of_keygen_sign f seed message hkeys hsign
  simp only [if_true] at hverify
  rw [htrue] at hverify
  try dsimp only
  rw [← hverify]
  decide

theorem probOutput_game12_false_le (seed : MasterSeed)
    (message : SphincsSecurity.Message) :
    Pr[= false | (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
      (game12 seed message)).run' ∅] ≤
      (2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516 := by
  rw [StateT.run'_eq, probOutput_map]
  calc
    _ ≤ Pr[fun r => ¬ SignatureSumSmall 1565526 r.1.2 |
      (simulateQ (randomOracle : QueryImpl SphincsSecurity.HashSpec _)
        (signedWithKeys seed message)).run ∅] :=
          probEvent_game12_false_le seed message
    _ ≤ digestFactor ^ digestAttemptLimit +
        layerTailBound
          (failMass (fun out => TargetSum.decodeDigest (truncateHash out)))
          numLayers 1565526 := by
            exact probEvent_signedWithKeys_sumBad seed message 1565526
              (by decide) (by norm_num [encodingAttemptLimit])
    _ ≤ (2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516 :=
          add_le_add digestFactor_pow_le radix12_layer_tail_le

#print axioms probEvent_game12_false_le
#print axioms probOutput_game12_false_le
end SigGolfCandidate.Final
end
-- END Radix12GameBound

-- BEGIN Radix12GameAll from /tmp/Radix12GameAll.lean
section

open OracleComp OracleSpec ENNReal
namespace SigGolfCandidate.Final
open SphincsSecurity SphincsSecurity.Completeness
open SigGolfCandidate.Bridge (relabel relabel_relabel)

noncomputable def game12HD (seed : MasterSeed) (message : SphincsSecurity.Message) :
    OracleComp (HD →ₒ SphincsSecurity.HashOutput) Bool :=
  relabel toHD (game12 seed message)

theorem relabel_val_game12HD (seed : MasterSeed)
    (message : SphincsSecurity.Message) :
    relabel Subtype.val (game12HD seed message) = game12 seed message := by
  unfold game12HD
  rw [relabel_relabel]
  exact Bridge.relabel_eq_self_of_allQ Equiv.Honest _ (fun x hx => val_toHD x hx)
    (hq_game12 seed message)

theorem probOutput_game12HD_false_le (seed : MasterSeed)
    (message : SphincsSecurity.Message) :
    Pr[= false | (simulateQ randomOracle (game12HD seed message)).run' ∅] ≤
      (2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516 := by
  rw [run'_relabel Subtype.val Subtype.val_injective (game12HD seed message) ∅ ∅
    (fun _ => rfl), relabel_val_game12HD]
  exact probOutput_game12_false_le seed message

theorem game12_failure_seeded (seed : MasterSeed) :
    ∑' message : SphincsSecurity.Message,
      Pr[= false | (simulateQ randomOracle (game12HD seed message)).run' ∅] ≤
      ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := by
  calc
    ∑' message : SphincsSecurity.Message,
        Pr[= false | (simulateQ randomOracle (game12HD seed message)).run' ∅]
        ≤ ∑' _message : SphincsSecurity.Message,
          ((2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516) := by
            apply ENNReal.tsum_le_tsum
            intro message
            exact probOutput_game12HD_false_le seed message
    _ = (2 : ℝ≥0∞) ^ 256 *
      ((2⁻¹ : ℝ≥0∞) ^ 1023 + (2⁻¹ : ℝ≥0∞) ^ 516) := by
        rw [tsum_fintype, Finset.sum_const, nsmul_eq_mul, Finset.card_univ,
          show Fintype.card SphincsSecurity.Message = 2 ^ 256 by simp [messageBits],
          Nat.cast_pow, Nat.cast_ofNat]
    _ ≤ ((2 ^ 256 : Nat) : ℝ≥0∞)⁻¹ := radix12_complete_numeric

#print axioms game12_failure_seeded
end SigGolfCandidate.Final
end
-- END Radix12GameAll

-- BEGIN Radix12Combinadic from /tmp/Radix12Combinadic.lean
section

set_option maxRecDepth 10000
set_option maxHeartbeats 300000

namespace Radix12

def bar0 (c0 : Nat) : Nat := c0
def bar1 (c0 c1 : Nat) : Nat := c0 + c1 + 1
def bar2 (c0 c1 c2 : Nat) : Nat := c0 + c1 + c2 + 2
def bar3 (c0 c1 c2 c3 : Nat) : Nat := c0 + c1 + c2 + c3 + 3
def bar4 (c0 c1 c2 c3 c4 : Nat) : Nat := c0 + c1 + c2 + c3 + c4 + 4

def rank1 (b0 : Nat) : Nat := b0.choose 1
def rank2 (b0 b1 : Nat) : Nat := rank1 b0 + b1.choose 2
def rank3 (b0 b1 b2 : Nat) : Nat := rank2 b0 b1 + b2.choose 3
def rank4 (b0 b1 b2 b3 : Nat) : Nat := rank3 b0 b1 b2 + b3.choose 4
def rank5 (b0 b1 b2 b3 b4 : Nat) : Nat := rank4 b0 b1 b2 b3 + b4.choose 5

theorem rank1_interval {b0 b1 : Nat} (h01 : b0 < b1) :
    b0.choose 1 ≤ rank1 b0 ∧ rank1 b0 < b1.choose 1 := by
  simp [rank1, Nat.choose_one_right, h01]

theorem rank2_interval {b0 b1 b2 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) :
    b1.choose 2 ≤ rank2 b0 b1 ∧ rank2 b0 b1 < b2.choose 2 := by
  have h1 := (rank1_interval h01).2
  have hpas : (b1 + 1).choose 2 = b1.choose 1 + b1.choose 2 := by
    simpa using Nat.choose_succ_succ' b1 1
  have hmono := Nat.choose_le_choose 2 (show b1 + 1 ≤ b2 by omega)
  constructor
  · simp [rank2]
  · dsimp [rank2]
    omega

theorem rank3_interval {b0 b1 b2 b3 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) (h23 : b2 < b3) :
    b2.choose 3 ≤ rank3 b0 b1 b2 ∧ rank3 b0 b1 b2 < b3.choose 3 := by
  have h2 := (rank2_interval h01 h12).2
  have hpas : (b2 + 1).choose 3 = b2.choose 2 + b2.choose 3 := by
    simpa using Nat.choose_succ_succ' b2 2
  have hmono := Nat.choose_le_choose 3 (show b2 + 1 ≤ b3 by omega)
  constructor
  · simp [rank3]
  · dsimp [rank3]
    omega

theorem rank4_interval {b0 b1 b2 b3 b4 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) (h23 : b2 < b3) (h34 : b3 < b4) :
    b3.choose 4 ≤ rank4 b0 b1 b2 b3 ∧ rank4 b0 b1 b2 b3 < b4.choose 4 := by
  have h3 := (rank3_interval h01 h12 h23).2
  have hpas : (b3 + 1).choose 4 = b3.choose 3 + b3.choose 4 := by
    simpa using Nat.choose_succ_succ' b3 3
  have hmono := Nat.choose_le_choose 4 (show b3 + 1 ≤ b4 by omega)
  constructor
  · simp [rank4]
  · dsimp [rank4]
    omega

theorem rank5_interval {b0 b1 b2 b3 b4 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) (h23 : b2 < b3) (h34 : b3 < b4) :
    b4.choose 5 ≤ rank5 b0 b1 b2 b3 b4 ∧
      rank5 b0 b1 b2 b3 b4 < (b4 + 1).choose 5 := by
  have h4 := (rank4_interval h01 h12 h23 h34).2
  have hpas : (b4 + 1).choose 5 = b4.choose 4 + b4.choose 5 := by
    simpa using Nat.choose_succ_succ' b4 4
  constructor
  · simp [rank5]
  · dsimp [rank5]
    omega

theorem rank2_self_interval {b0 b1 : Nat} (h01 : b0 < b1) :
    b1.choose 2 ≤ rank2 b0 b1 ∧ rank2 b0 b1 < (b1 + 1).choose 2 :=
  rank2_interval h01 (Nat.lt_succ_self b1)

theorem rank3_self_interval {b0 b1 b2 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) :
    b2.choose 3 ≤ rank3 b0 b1 b2 ∧ rank3 b0 b1 b2 < (b2 + 1).choose 3 :=
  rank3_interval h01 h12 (Nat.lt_succ_self b2)

theorem rank4_self_interval {b0 b1 b2 b3 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) (h23 : b2 < b3) :
    b3.choose 4 ≤ rank4 b0 b1 b2 b3 ∧
      rank4 b0 b1 b2 b3 < (b3 + 1).choose 4 :=
  rank4_interval h01 h12 h23 (Nat.lt_succ_self b3)

theorem choose_interval_index_eq (k n m x y : Nat)
    (hnlo : n.choose k ≤ x) (hnhi : x < (n + 1).choose k)
    (hmlo : m.choose k ≤ y) (hmhi : y < (m + 1).choose k)
    (hxy : x = y) : n = m := by
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hgt
  · have hmono := Nat.choose_le_choose k (show n + 1 ≤ m by omega)
    omega
  · have hmono := Nat.choose_le_choose k (show m + 1 ≤ n by omega)
    omega

theorem rank5_injective_onIncreasing
    {a0 a1 a2 a3 a4 b0 b1 b2 b3 b4 : Nat}
    (ha01 : a0 < a1) (ha12 : a1 < a2) (ha23 : a2 < a3) (ha34 : a3 < a4)
    (hb01 : b0 < b1) (hb12 : b1 < b2) (hb23 : b2 < b3) (hb34 : b3 < b4)
    (heq : rank5 a0 a1 a2 a3 a4 = rank5 b0 b1 b2 b3 b4) :
    a0 = b0 ∧ a1 = b1 ∧ a2 = b2 ∧ a3 = b3 ∧ a4 = b4 := by
  have hia := rank5_interval ha01 ha12 ha23 ha34
  have hib := rank5_interval hb01 hb12 hb23 hb34
  have h4 : a4 = b4 :=
    choose_interval_index_eq 5 a4 b4 _ _ hia.1 hia.2 hib.1 hib.2 heq
  have heq4 : rank4 a0 a1 a2 a3 = rank4 b0 b1 b2 b3 := by
    rw [h4] at heq
    dsimp [rank5] at heq
    omega
  have hia3 := rank4_self_interval ha01 ha12 ha23
  have hib3 := rank4_self_interval hb01 hb12 hb23
  have h3 : a3 = b3 :=
    choose_interval_index_eq 4 a3 b3 _ _ hia3.1 hia3.2 hib3.1 hib3.2 heq4
  have heq3 : rank3 a0 a1 a2 = rank3 b0 b1 b2 := by
    rw [h3] at heq4
    dsimp [rank4] at heq4
    omega
  have hia2 := rank3_self_interval ha01 ha12
  have hib2 := rank3_self_interval hb01 hb12
  have h2 : a2 = b2 :=
    choose_interval_index_eq 3 a2 b2 _ _ hia2.1 hia2.2 hib2.1 hib2.2 heq3
  have heq2 : rank2 a0 a1 = rank2 b0 b1 := by
    rw [h2] at heq3
    dsimp [rank3] at heq3
    omega
  have hia1 := rank2_self_interval ha01
  have hib1 := rank2_self_interval hb01
  have h1 : a1 = b1 :=
    choose_interval_index_eq 2 a1 b1 _ _ hia1.1 hia1.2 hib1.1 hib1.2 heq2
  have heq1 : rank1 a0 = rank1 b0 := by
    rw [h1] at heq2
    dsimp [rank2] at heq2
    omega
  have h0 : a0 = b0 := by simpa [rank1, Nat.choose_one_right] using heq1
  exact ⟨h0, h1, h2, h3, h4⟩

def packRank (c0 c1 c2 c3 c4 : Nat) : Nat :=
  rank5 (bar0 c0) (bar1 c0 c1) (bar2 c0 c1 c2)
    (bar3 c0 c1 c2 c3) (bar4 c0 c1 c2 c3 c4)

theorem packRank_lt_96bits {c0 c1 c2 c3 c4 : Nat}
    (hsum : c0 + c1 + c2 + c3 + c4 < 1565526) :
    packRank c0 c1 c2 c3 c4 < 2 ^ 96 := by
  have h01 : bar0 c0 < bar1 c0 c1 := by simp [bar0, bar1]
  have h12 : bar1 c0 c1 < bar2 c0 c1 c2 := by simp [bar1, bar2]
  have h23 : bar2 c0 c1 c2 < bar3 c0 c1 c2 c3 := by simp [bar2, bar3]
  have h34 : bar3 c0 c1 c2 c3 < bar4 c0 c1 c2 c3 c4 := by simp [bar3, bar4]
  have hrank := (rank5_interval h01 h12 h23 h34).2
  have hb : bar4 c0 c1 c2 c3 c4 + 1 ≤ 1565526 + 4 := by
    simp only [bar4]
    omega
  exact lt_trans hrank ((Nat.choose_le_choose 5 hb).trans_lt radix12_96bit_capacity)

theorem packRank_injective
    {c0 c1 c2 c3 c4 d0 d1 d2 d3 d4 : Nat}
    (h : packRank c0 c1 c2 c3 c4 = packRank d0 d1 d2 d3 d4) :
    c0 = d0 ∧ c1 = d1 ∧ c2 = d2 ∧ c3 = d3 ∧ c4 = d4 := by
  have hc01 : bar0 c0 < bar1 c0 c1 := by simp [bar0, bar1]
  have hc12 : bar1 c0 c1 < bar2 c0 c1 c2 := by simp [bar1, bar2]
  have hc23 : bar2 c0 c1 c2 < bar3 c0 c1 c2 c3 := by simp [bar2, bar3]
  have hc34 : bar3 c0 c1 c2 c3 < bar4 c0 c1 c2 c3 c4 := by simp [bar3, bar4]
  have hd01 : bar0 d0 < bar1 d0 d1 := by simp [bar0, bar1]
  have hd12 : bar1 d0 d1 < bar2 d0 d1 d2 := by simp [bar1, bar2]
  have hd23 : bar2 d0 d1 d2 < bar3 d0 d1 d2 d3 := by simp [bar2, bar3]
  have hd34 : bar3 d0 d1 d2 d3 < bar4 d0 d1 d2 d3 d4 := by simp [bar3, bar4]
  have hbars := rank5_injective_onIncreasing hc01 hc12 hc23 hc34
    hd01 hd12 hd23 hd34 h
  dsimp [bar0, bar1, bar2, bar3, bar4] at hbars
  omega

#print axioms rank5_interval
#print axioms rank5_injective_onIncreasing
#print axioms packRank_lt_96bits
#print axioms packRank_injective

end Radix12
end
-- END Radix12Combinadic

-- BEGIN Radix12AbstractCodec from /tmp/Radix12AbstractCodec.lean
section

set_option maxRecDepth 10000
set_option maxHeartbeats 400000

namespace Radix12

structure Counter5 where
  c0 : Nat
  c1 : Nat
  c2 : Nat
  c3 : Nat
  c4 : Nat
deriving Repr

theorem Counter5.ext {a b : Counter5}
    (h0 : a.c0 = b.c0) (h1 : a.c1 = b.c1) (h2 : a.c2 = b.c2)
    (h3 : a.c3 = b.c3) (h4 : a.c4 = b.c4) : a = b := by
  cases a
  cases b
  simp_all

def counterSum (w : Counter5) : Nat := w.c0 + w.c1 + w.c2 + w.c3 + w.c4
def counterRank (w : Counter5) : Nat := packRank w.c0 w.c1 w.c2 w.c3 w.c4

def badWords (code : Nat) : Counter5 :=
  ⟨2 ^ 22, code % 2 ^ 32, (code / 2 ^ 32) % 2 ^ 32,
    (code / 2 ^ 64) % 2 ^ 32, 0⟩

def badPayload (w : Counter5) : Nat :=
  (w.c1 + 2 ^ 32 * w.c2 + 2 ^ 64 * w.c3) % 2 ^ 96

def encode (w : Counter5) : Nat :=
  if w.c0 < 2 ^ 22 ∧ counterSum w < 1565526 then counterRank w
  else badPayload w

theorem encode_lt (w : Counter5) : encode w < 2 ^ 96 := by
  unfold encode
  split_ifs with h
  · exact packRank_lt_96bits h.2
  · exact Nat.mod_lt _ (by decide)

noncomputable def decode (code : Fin (2 ^ 96)) : Counter5 :=
  by
    classical
    exact if h : ∃ w : Counter5, counterSum w < 1565526 ∧ counterRank w = code.val then
      Classical.choose h
    else badWords code.val

theorem decode_encode (code : Fin (2 ^ 96)) : encode (decode code) = code.val := by
  unfold decode
  split_ifs with h
  · obtain ⟨hsum, hrank⟩ := Classical.choose_spec h
    have hc0 : (Classical.choose h).c0 < 2 ^ 22 := by
      have hle : (Classical.choose h).c0 ≤ counterSum (Classical.choose h) := by
        simp only [counterSum]
        omega
      exact lt_trans (lt_of_le_of_lt hle hsum) (by decide)
    exact (if_pos ⟨hc0, hsum⟩).trans hrank
  · have hb : encode (badWords code.val) = badPayload (badWords code.val) := by
      simp [encode, badWords]
    rw [hb]
    simp only [badPayload, badWords]
    have hcode := code.isLt
    norm_num at hcode ⊢
    omega

theorem badWords_invalid (code : Nat) : ¬ (badWords code).c0 < 2 ^ 22 := by
  simp [badWords]

theorem decode_encode_small (w : Counter5)
    (hsum : counterSum w < 1565526) :
    decode ⟨encode w, encode_lt w⟩ = w := by
  have hc0 : w.c0 < 2 ^ 22 := by
    have hle : w.c0 ≤ counterSum w := by
      simp only [counterSum]
      omega
    exact lt_trans (lt_of_le_of_lt hle hsum) (by decide)
  have henc : encode w = counterRank w := if_pos ⟨hc0, hsum⟩
  unfold decode
  split_ifs with h
  · have hspec := Classical.choose_spec h
    have heq : counterRank (Classical.choose h) = counterRank w := by
      rw [hspec.2, ← henc]
    apply Counter5.ext
    · exact (packRank_injective heq).1
    · exact (packRank_injective heq).2.1
    · exact (packRank_injective heq).2.2.1
    · exact (packRank_injective heq).2.2.2.1
    · exact (packRank_injective heq).2.2.2.2
  · exfalso
    apply h
    exact ⟨w, hsum, henc.symm⟩

#print axioms encode_lt
#print axioms decode_encode
#print axioms decode_encode_small

end Radix12
end
-- END Radix12AbstractCodec

-- BEGIN Radix12Greedy from /tmp/Radix12Greedy.lean
section

set_option maxRecDepth 10000
set_option maxHeartbeats 300000

namespace Radix12

def chooseMax (k bound code : Nat) : Nat :=
  Nat.findGreatest (fun n => n.choose k ≤ code) bound

theorem chooseMax_eq_of_interval (k bound n code : Nat)
    (hbound : n ≤ bound)
    (hlo : n.choose k ≤ code)
    (hhi : code < (n + 1).choose k) :
    chooseMax k bound code = n := by
  unfold chooseMax
  apply Nat.findGreatest_eq_iff.mpr
  refine ⟨hbound, ?_, ?_⟩
  · intro _
    exact hlo
  · intro m hnm _ hm
    have hmono := Nat.choose_le_choose k (show n + 1 ≤ m by omega)
    omega

def greedyBars (code : Nat) : Nat × Nat × Nat × Nat × Nat := Id.run do
  let b4 := chooseMax 5 (1565526 + 3) code
  let r4 := code - b4.choose 5
  let b3 := chooseMax 4 b4 r4
  let r3 := r4 - b3.choose 4
  let b2 := chooseMax 3 b3 r3
  let r2 := r3 - b2.choose 3
  let b1 := chooseMax 2 b2 r2
  let r1 := r2 - b1.choose 2
  let b0 := chooseMax 1 b1 r1
  return (b0,b1,b2,b3,b4)

theorem greedyBars_rank5
    {b0 b1 b2 b3 b4 : Nat}
    (h01 : b0 < b1) (h12 : b1 < b2) (h23 : b2 < b3) (h34 : b3 < b4)
    (hbound : b4 ≤ 1565526 + 3) :
    greedyBars (rank5 b0 b1 b2 b3 b4) = (b0,b1,b2,b3,b4) := by
  have h4i := rank5_interval h01 h12 h23 h34
  have hb4 : chooseMax 5 (1565526 + 3) (rank5 b0 b1 b2 b3 b4) = b4 :=
    chooseMax_eq_of_interval 5 _ b4 _ hbound h4i.1 h4i.2
  have hr4 : rank5 b0 b1 b2 b3 b4 - b4.choose 5 = rank4 b0 b1 b2 b3 := by
    simp [rank5]
  have h3i := rank4_self_interval h01 h12 h23
  have hb3 : chooseMax 4 b4 (rank4 b0 b1 b2 b3) = b3 :=
    chooseMax_eq_of_interval 4 _ b3 _ (by omega) h3i.1 h3i.2
  have hr3 : rank4 b0 b1 b2 b3 - b3.choose 4 = rank3 b0 b1 b2 := by
    simp [rank4]
  have h2i := rank3_self_interval h01 h12
  have hb2 : chooseMax 3 b3 (rank3 b0 b1 b2) = b2 :=
    chooseMax_eq_of_interval 3 _ b2 _ (by omega) h2i.1 h2i.2
  have hr2 : rank3 b0 b1 b2 - b2.choose 3 = rank2 b0 b1 := by
    simp [rank3]
  have h1i := rank2_self_interval h01
  have hb1 : chooseMax 2 b2 (rank2 b0 b1) = b1 :=
    chooseMax_eq_of_interval 2 _ b1 _ (by omega) h1i.1 h1i.2
  have hr1 : rank2 b0 b1 - b1.choose 2 = rank1 b0 := by
    simp [rank2]
  have h0i : b0.choose 1 ≤ rank1 b0 ∧ rank1 b0 < (b0 + 1).choose 1 := by
    simp [rank1, Nat.choose_one_right]
  have hb0 : chooseMax 1 b1 (rank1 b0) = b0 :=
    chooseMax_eq_of_interval 1 _ b0 _ (by omega) h0i.1 h0i.2
  simp only [greedyBars, hb4, hr4, hb3, hr3, hb2, hr2, hb1, hr1, hb0]
  rfl

def counterBars (w : Counter5) : Nat × Nat × Nat × Nat × Nat :=
  (bar0 w.c0, bar1 w.c0 w.c1, bar2 w.c0 w.c1 w.c2,
    bar3 w.c0 w.c1 w.c2 w.c3, bar4 w.c0 w.c1 w.c2 w.c3 w.c4)

def fromBars : Nat × Nat × Nat × Nat × Nat → Counter5
  | (b0,b1,b2,b3,b4) =>
      ⟨b0, b1 - b0 - 1, b2 - b1 - 1, b3 - b2 - 1, b4 - b3 - 1⟩

theorem fromBars_counterBars (w : Counter5) : fromBars (counterBars w) = w := by
  cases w with
  | mk c0 c1 c2 c3 c4 =>
    apply Counter5.ext <;>
      simp only [fromBars, counterBars, bar0, bar1, bar2, bar3, bar4] <;>
      omega

def greedyDecoded (code : Nat) : Counter5 := fromBars (greedyBars code)

theorem greedyDecoded_rank (w : Counter5)
    (hsum : counterSum w < 1565526) :
    greedyDecoded (counterRank w) = w := by
  have h01 : bar0 w.c0 < bar1 w.c0 w.c1 := by simp [bar0, bar1]
  have h12 : bar1 w.c0 w.c1 < bar2 w.c0 w.c1 w.c2 := by simp [bar1, bar2]
  have h23 : bar2 w.c0 w.c1 w.c2 < bar3 w.c0 w.c1 w.c2 w.c3 := by simp [bar2, bar3]
  have h34 : bar3 w.c0 w.c1 w.c2 w.c3 < bar4 w.c0 w.c1 w.c2 w.c3 w.c4 :=
    by simp [bar3, bar4]
  have hb : bar4 w.c0 w.c1 w.c2 w.c3 w.c4 ≤ 1565526 + 3 := by
    simp only [counterSum, bar4] at hsum ⊢
    omega
  change fromBars (greedyBars (packRank w.c0 w.c1 w.c2 w.c3 w.c4)) = w
  rw [show packRank w.c0 w.c1 w.c2 w.c3 w.c4 =
      rank5 (bar0 w.c0) (bar1 w.c0 w.c1) (bar2 w.c0 w.c1 w.c2)
        (bar3 w.c0 w.c1 w.c2 w.c3) (bar4 w.c0 w.c1 w.c2 w.c3 w.c4) from rfl]
  rw [greedyBars_rank5 h01 h12 h23 h34 hb]
  exact fromBars_counterBars w

def decodeGreedy (code : Fin (2 ^ 96)) : Counter5 :=
  let w := greedyDecoded code.val
  if counterSum w < 1565526 ∧ counterRank w = code.val then w
  else badWords code.val

theorem decodeGreedy_encode_small (w : Counter5)
    (hsum : counterSum w < 1565526) :
    decodeGreedy ⟨encode w, encode_lt w⟩ = w := by
  have hc0 : w.c0 < 2 ^ 22 := by
    have hle : w.c0 ≤ counterSum w := by
      simp only [counterSum]
      omega
    exact lt_trans (lt_of_le_of_lt hle hsum) (by decide)
  have henc : encode w = counterRank w := if_pos ⟨hc0, hsum⟩
  unfold decodeGreedy
  have hdec : greedyDecoded (encode w) = w := by rw [henc]; exact greedyDecoded_rank w hsum
  rw [hdec]
  simp [hsum, henc]

theorem encode_badWords (code : Fin (2 ^ 96)) :
    encode (badWords code.val) = code.val := by
  have hbranch : ¬ ((badWords code.val).c0 < 2 ^ 22 ∧
      counterSum (badWords code.val) < 1565526) := by
    simp [badWords]
  simp only [encode, if_neg hbranch, badPayload, badWords]
  have hcode := code.isLt
  norm_num at hcode ⊢
  omega

theorem decodeGreedy_encode (code : Fin (2 ^ 96)) :
    encode (decodeGreedy code) = code.val := by
  change encode (if counterSum (greedyDecoded code.val) < 1565526 ∧
      counterRank (greedyDecoded code.val) = code.val then
        greedyDecoded code.val else badWords code.val) = code.val
  split_ifs with h
  · obtain ⟨hsum, hrank⟩ := h
    have hc0 : (greedyDecoded code.val).c0 < 2 ^ 22 := by
      have hle : (greedyDecoded code.val).c0 ≤
          counterSum (greedyDecoded code.val) := by
        simp only [counterSum]
        omega
      exact lt_trans (lt_of_le_of_lt hle hsum) (by decide)
    exact (if_pos ⟨hc0, hsum⟩).trans hrank
  · exact encode_badWords code

#print axioms chooseMax_eq_of_interval
#print axioms greedyBars_rank5
#print axioms decodeGreedy_encode_small
#print axioms decodeGreedy_encode

end Radix12
end
-- END Radix12Greedy
