-- Generated by /tmp/radix12_bundle.py; source order is the import graph.
import SigGolfCandidate.Packed.Radix12Bundle04
import SigGolfCandidate.Packed.Radix12Bundle05

-- BEGIN Radix12SplitSearchFirstSD from /tmp/Radix12SplitSearchFirstSD.lean
section

namespace Radix12SplitSearchFirstSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 28)),
   (15 + 28, (expandTail.drop 28).take 9),
   (15 + 37, expandTail.drop 37)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel

theorem codeAt_search9 :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
      ((expandTail.drop 28).take 9) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)

sym_block search9 := symRun {} ((expandTail.drop 28).take 9)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 28))) 15

theorem search9_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
    (ho : search9.res.obligs s) :
    Steps expandImage s search9.res.steps search9.res.cycles
      (search9.res.toState s) :=
  symRun_sound search9 codeAt_search9 s hpc ho

#print axioms search9_steps
end Radix12SplitSearchFirstSD
end
-- END Radix12SplitSearchFirstSD

-- BEGIN Radix12SplitSearchMidSD from /tmp/Radix12SplitSearchMidSD.lean
section

namespace Radix12SplitSearchMidSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchFirstSD

theorem search9_midpoint (s : MachineState) (lo hi : Nat)
    (hlo : s.getReg .x14 = BitVec.ofNat 64 lo)
    (hhi : s.getReg .x13 = BitVec.ofNat 64 hi)
    (hbound : lo + hi < 2 ^ 64) :
    (search9.res.toState s).getReg .x15 =
      BitVec.ofNat 64 ((lo + hi) / 2) := by
  simp only [Result.toState_getReg, search9.res, rv_simp]
  rw [hlo, hhi]
  apply BitVec.eq_of_toNat_eq
  simp only [BitVec.toNat_ushiftRight, Nat.shiftRight_eq_div_pow,
    BitVec.toNat_add, BitVec.toNat_ofNat]
  have hlo64 : lo < 2 ^ 64 := by omega
  have hhi64 : hi < 2 ^ 64 := by omega
  simp only [Nat.mod_eq_of_lt hlo64, Nat.mod_eq_of_lt hhi64,
    Nat.mod_eq_of_lt hbound]
  norm_num
  omega

#print axioms search9_midpoint
end Radix12SplitSearchMidSD
end
-- END Radix12SplitSearchMidSD

-- BEGIN Radix12SplitSearchAddrSD from /tmp/Radix12SplitSearchAddrSD.lean
section

namespace Radix12SplitSearchAddrSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchFirstSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem search9_addr (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    (search9.res.toState s).getReg .x25 =
      BitVec.ofNat 64 (0xffc3d0 + 8 * ((k - 1) * 385 + (lo + hi) / 2)) := by
  have hbound : lo + hi < 2 ^ 64 := by omega
  have hmid := Radix12SplitSearchMidSD.search9_midpoint s lo hi h14 h13 hbound
  simp only [Result.toState_getReg, search9.res, rv_simp] at hmid ⊢
  rw [h11, h27, h13, h14, h2]
  rw [h13, h14] at hmid
  rw [hmid]
  simpa only [show ((3#64).toNat % 64) = 3 by decide] using
    (Radix12SplitTableAddr.table_addr_arith k ((lo + hi) / 2)
      hk hk5 (by omega))

theorem search9_x20_mem (s : MachineState) :
    (search9.res.toState s).getReg .x20 =
      s.getMem ((search9.res.toState s).getReg .x25) := by
  simp only [Result.toState_getReg, search9.res, rv_simp]

theorem search9_choose (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hmem : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    (search9.res.toState s).getReg .x20 =
      BitVec.ofNat 64 (Nat.choose ((lo + hi) / 2) k) := by
  let mid := (lo + hi) / 2
  let i := (k - 1) * 385 + mid
  have hmid : mid < 385 := by dsimp [mid]; omega
  have hi' : i < 5 * 385 := by dsimp [i]; omega
  have himod : i % 385 = mid := by dsimp [i]; omega
  have hidiv : i / 385 + 1 = k := by dsimp [i]; omega
  rw [search9_x20_mem,
    search9_addr s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi]
  change s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) = _
  rw [hmem i hi', himod, hidiv]

theorem search9_pc (s : MachineState) :
    (search9.res.toState s).pc =
      if BitVec.ult (s.getReg .x10) ((search9.res.toState s).getReg .x20) then
        BitVec.ofNat 64 4312 else BitVec.ofNat 64 4304 := by
  simp only [Result.toState_pc, Result.toState_getReg, search9.res, rv_simp]

theorem search9_pc_nat (s : MachineState) (k lo hi rank : Nat)
    (h10 : s.getReg .x10 = BitVec.ofNat 64 rank)
    (hrank : rank < 2 ^ 64)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hmem : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    (search9.res.toState s).pc =
      if rank < Nat.choose ((lo + hi) / 2) k then
        BitVec.ofNat 64 4312 else BitVec.ofNat 64 4304 := by
  have hmid : (lo + hi) / 2 < 385 := by omega
  have hchoose : Nat.choose ((lo + hi) / 2) k < 2 ^ 64 :=
    Radix12ChooseBound64.choose_lt64 _ _ hmid hk5
  rw [search9_pc, h10,
    search9_choose s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi hmem]
  simp only [BitVec.ult_eq_decide_lt]
  have hiff : (BitVec.ofNat 64 rank <
      BitVec.ofNat 64 (Nat.choose ((lo + hi) / 2) k)) ↔
      rank < Nat.choose ((lo + hi) / 2) k := by
    simp only [BitVec.lt_def, BitVec.toNat_ofNat,
      Nat.mod_eq_of_lt hrank, Nat.mod_eq_of_lt hchoose]
  simp only [hiff, decide_eq_true_eq]

theorem search9_obligs (s : MachineState) (k lo hi : Nat)
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    search9.res.obligs s := by
  simp only [Result.obligs, search9.res, rv_simp]
  have hadd := search9_addr s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi
  simp only [Result.toState_getReg, search9.res, rv_simp] at hadd
  rw [hadd]
  apply (accessValid_iff _ _).2
  have hmid : (lo + hi) / 2 < 385 := by omega
  have hi' : (k - 1) * 385 + (lo + hi) / 2 < 5 * 385 := by omega
  have haddr : 0xffc3d0 + 8 * ((k - 1) * 385 + (lo + hi) / 2) < 2 ^ 64 := by omega
  rw [BitVec.toNat_ofNat, Nat.mod_eq_of_lt haddr]
  simp only [MEMORY_BYTES]
  constructor <;> omega

theorem search9_steps_bounded (s : MachineState) (k lo hi : Nat)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 28)))
    (h11 : s.getReg .x11 = BitVec.ofNat 64 k)
    (h27 : s.getReg .x27 = BitVec.ofNat 64 385)
    (h13 : s.getReg .x13 = BitVec.ofNat 64 hi)
    (h14 : s.getReg .x14 = BitVec.ofNat 64 lo)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hlohi : lo < hi) (hhi : hi ≤ 385) :
    Steps Radix12SplitExpandImageSD.expandImage s search9.res.steps search9.res.cycles
      (search9.res.toState s) :=
  search9_steps s hpc
    (search9_obligs s k lo hi h11 h27 h13 h14 h2 hk hk5 hlohi hhi)

theorem search9_frame (s : MachineState) :
    (search9.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (search9.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (search9.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (search9.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (search9.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (search9.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (search9.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (search9.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (search9.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (search9.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_getReg, Result.toState_getMem,
    search9.res, rv_simp, memEval]
  simp

#print axioms search9_addr
#print axioms search9_choose
#print axioms search9_pc
#print axioms search9_pc_nat
#print axioms search9_obligs
#print axioms search9_steps_bounded
#print axioms search9_frame
end Radix12SplitSearchAddrSD
end
-- END Radix12SplitSearchAddrSD

-- BEGIN Radix12SplitSearchBranchSD from /tmp/Radix12SplitSearchBranchSD.lean
section

namespace Radix12SplitSearchBranchSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 37)),
   (15 + 37, (expandTail.drop 37).take 2),
   (15 + 39, (expandTail.drop 39).take 1),
   (15 + 40, (expandTail.drop 40).take 2),
   (15 + 42, expandTail.drop 42)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel

theorem codeAt_false : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 37)))
    ((expandTail.drop 37).take 2) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_true : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 39)))
    ((expandTail.drop 39).take 1) :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_bottom : CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 40)))
    ((expandTail.drop 40).take 2) :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)

sym_block falseBlock := symRun {} ((expandTail.drop 37).take 2)
  (BitVec.ofNat 64 4304) 5
sym_block trueBlock := symRun {} ((expandTail.drop 39).take 1)
  (BitVec.ofNat 64 4312) 3
sym_block bottomBlock := symRun {} ((expandTail.drop 40).take 2)
  (BitVec.ofNat 64 4316) 4

theorem false_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4304) :
    Steps expandImage s falseBlock.res.steps falseBlock.res.cycles
      (falseBlock.res.toState s) := by
  have ho : falseBlock.res.obligs s := by simp only [falseBlock.res, rv_simp]
  exact symRun_sound falseBlock codeAt_false s hpc ho

theorem true_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4312) :
    Steps expandImage s trueBlock.res.steps trueBlock.res.cycles
      (trueBlock.res.toState s) := by
  have ho : trueBlock.res.obligs s := by simp only [trueBlock.res, rv_simp]
  exact symRun_sound trueBlock codeAt_true s hpc ho

theorem bottom_steps (s : MachineState) (hpc : s.pc = BitVec.ofNat 64 4316) :
    Steps expandImage s bottomBlock.res.steps bottomBlock.res.cycles
      (bottomBlock.res.toState s) := by
  have ho : bottomBlock.res.obligs s := by simp only [bottomBlock.res, rv_simp]
  exact symRun_sound bottomBlock codeAt_bottom s hpc ho

#print axioms false_steps
#print axioms true_steps
#print axioms bottom_steps
end Radix12SplitSearchBranchSD
end
-- END Radix12SplitSearchBranchSD

-- BEGIN Radix12SplitSearchBranchPropsSD from /tmp/Radix12SplitSearchBranchPropsSD.lean
section

namespace Radix12SplitSearchBranchPropsSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitSearchBranchSD

theorem false_sem (s : MachineState) :
    (falseBlock.res.toState s).pc = BitVec.ofNat 64 4316 ∧
    (falseBlock.res.toState s).getReg .x14 = s.getReg .x15 ∧
    (falseBlock.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (falseBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (falseBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (falseBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (falseBlock.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (falseBlock.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (falseBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (falseBlock.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (falseBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_pc, Result.toState_getReg,
    Result.toState_getMem, falseBlock.res, rv_simp, memEval]
  simp

theorem true_sem (s : MachineState) :
    (trueBlock.res.toState s).pc = BitVec.ofNat 64 4316 ∧
    (trueBlock.res.toState s).getReg .x13 = s.getReg .x15 ∧
    (trueBlock.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (trueBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (trueBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (trueBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (trueBlock.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (trueBlock.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (trueBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (trueBlock.res.toState s).getReg .x30 = s.getReg .x30 ∧
    (∀ a, (trueBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_pc, Result.toState_getReg,
    Result.toState_getMem, trueBlock.res, rv_simp, memEval]
  simp

theorem bottom_sem (s : MachineState) :
    (bottomBlock.res.toState s).getReg .x30 = s.getReg .x30 - 1#64 ∧
    (bottomBlock.res.toState s).getReg .x13 = s.getReg .x13 ∧
    (bottomBlock.res.toState s).getReg .x14 = s.getReg .x14 ∧
    (bottomBlock.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (bottomBlock.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (bottomBlock.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (bottomBlock.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (bottomBlock.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (bottomBlock.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (∀ a, (bottomBlock.res.toState s).getMem a = s.getMem a) := by
  simp only [Result.toState_getReg, Result.toState_getMem,
    bottomBlock.res, rv_simp, memEval]
  simp

theorem bottom_pc (s : MachineState) (fuel : Nat)
    (h30 : s.getReg .x30 = BitVec.ofNat 64 fuel)
    (hfuel : 1 ≤ fuel) (hfuel9 : fuel ≤ 9) :
    (bottomBlock.res.toState s).pc =
      if 1 < fuel then BitVec.ofNat 64 4268 else BitVec.ofNat 64 4324 := by
  simp only [Result.toState_pc, bottomBlock.res, rv_simp]
  rw [h30]
  rw [BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel]
  by_cases h : fuel = 1
  · subst fuel
    decide
  · have hp : 0 < fuel - 1 := by omega
    have hp64 : fuel - 1 < 2 ^ 64 := by omega
    have hne : BitVec.ofNat 64 (fuel - 1) ≠ (0#64) := by
      intro hz
      have hzN := congrArg BitVec.toNat hz
      simp only [BitVec.toNat_ofNat, Nat.mod_eq_of_lt hp64] at hzN
      norm_num at hzN
      omega
    have hb : (BitVec.ofNat 64 (fuel - 1) != 0#64) = true := by
      simpa using hne
    simp [hb, show 1 < fuel by omega]

#print axioms false_sem
#print axioms true_sem
#print axioms bottom_sem
#print axioms bottom_pc
end Radix12SplitSearchBranchPropsSD
end
-- END Radix12SplitSearchBranchPropsSD

-- BEGIN Radix12SplitSearchRoundSD from /tmp/Radix12SplitSearchRoundSD.lean
section

namespace Radix12SplitSearchRoundSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
  Radix12SplitSearchFirstSD Radix12SplitSearchAddrSD
  Radix12SplitSearchBranchSD Radix12SplitSearchBranchPropsSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

structure Core (s : MachineState) (k rank lo hi fuel : Nat) : Prop where
  x10 : s.getReg .x10 = BitVec.ofNat 64 rank
  x11 : s.getReg .x11 = BitVec.ofNat 64 k
  x13 : s.getReg .x13 = BitVec.ofNat 64 hi
  x14 : s.getReg .x14 = BitVec.ofNat 64 lo
  x27 : s.getReg .x27 = BitVec.ofNat 64 385
  x28 : s.getReg .x28 = BitVec.ofNat 64 0x4000
  x7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0
  x2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0
  x30 : s.getReg .x30 = BitVec.ofNat 64 fuel
  table : ∀ i < 5 * 385,
    s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
      BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))

theorem search_round (s : MachineState) (k rank lo hi fuel : Nat)
    (hpc : s.pc = BitVec.ofNat 64 4268)
    (hs : Core s k rank lo hi fuel)
    (hk : 1 ≤ k) (hk5 : k ≤ 5)
    (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hfuel : 1 ≤ fuel) (hfuel9 : fuel ≤ 9)
    (hrank : rank < 2 ^ 64) :
    let mid := (lo + hi) / 2
    let test := rank < Nat.choose mid k
    ∃ t n c, Steps expandImage s n c t ∧ n ≤ 13 ∧ c ≤ 16 ∧
      Core t k rank (if test then lo else mid) (if test then mid else hi) (fuel - 1) ∧
      t.pc = (if 1 < fuel then BitVec.ofNat 64 4268 else BitVec.ofNat 64 4324) ∧
      (∀ a, t.getMem a = s.getMem a) := by
  let mid := (lo + hi) / 2
  have hqsteps := search9_steps_bounded s k lo hi hpc hs.x11 hs.x27 hs.x13
    hs.x14 hs.x2 hk hk5 hlohi hhi
  let q := search9.res.toState s
  have hqmid : q.getReg .x15 = BitVec.ofNat 64 mid :=
    Radix12SplitSearchMidSD.search9_midpoint s lo hi hs.x14 hs.x13 (by omega)
  have hqpc := search9_pc_nat s k lo hi rank hs.x10 hrank hs.x11 hs.x27
    hs.x13 hs.x14 hs.x2 hk hk5 hlohi hhi hs.table
  obtain ⟨hq13, hq14, hq10, hq11, hq27, hq28, hq7, hq2, hq30, hqmem⟩ := search9_frame s
  by_cases htest : rank < Nat.choose mid k
  · let r := trueBlock.res.toState q
    have hrpc : q.pc = BitVec.ofNat 64 4312 := by
      change (search9.res.toState s).pc = _
      simpa [mid, htest] using hqpc
    have hrsteps := true_steps q hrpc
    obtain ⟨hrpc', hr13, hr14, hr10, hr11, hr27, hr28, hr7, hr2, hr30, hrmem⟩ := true_sem q
    have hr30' : r.getReg .x30 = BitVec.ofNat 64 fuel := by
      rw [hr30, hq30, hs.x30]
    let t := bottomBlock.res.toState r
    have htsteps := bottom_steps r hrpc'
    obtain ⟨ht30, ht13, ht14, ht10, ht11, ht27, ht28, ht7, ht2, htmem⟩ := bottom_sem r
    have htpc := bottom_pc r fuel hr30' hfuel hfuel9
    refine ⟨t, 12, 15, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · exact Steps.of_eq (hqsteps.trans (hrsteps.trans htsteps))
        (by decide) (by decide)
    · decide
    · decide
    · have htest' : rank < Nat.choose ((lo + hi) / 2) k := by
        simpa only [mid] using htest
      simp only [htest', ↓reduceIte]
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · exact ht10.trans (hr10.trans (hq10.trans hs.x10))
      · exact ht11.trans (hr11.trans (hq11.trans hs.x11))
      · exact ht13.trans (hr13.trans hqmid)
      · exact ht14.trans (hr14.trans (hq14.trans hs.x14))
      · exact ht27.trans (hr27.trans (hq27.trans hs.x27))
      · exact ht28.trans (hr28.trans (hq28.trans hs.x28))
      · exact ht7.trans (hr7.trans (hq7.trans hs.x7))
      · exact ht2.trans (hr2.trans (hq2.trans hs.x2))
      · calc
          t.getReg .x30 = r.getReg .x30 - 1#64 := ht30
          _ = BitVec.ofNat 64 fuel - 1#64 := by rw [hr30']
          _ = BitVec.ofNat 64 (fuel - 1) :=
            BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel
      · intro i hi'
        rw [htmem, hrmem, hqmem]
        exact hs.table i hi'
    · exact htpc
    · intro a
      rw [htmem, hrmem, hqmem]
  · let r := falseBlock.res.toState q
    have hrpc : q.pc = BitVec.ofNat 64 4304 := by
      change (search9.res.toState s).pc = _
      simpa [mid, htest] using hqpc
    have hrsteps := false_steps q hrpc
    obtain ⟨hrpc', hr14, hr13, hr10, hr11, hr27, hr28, hr7, hr2, hr30, hrmem⟩ := false_sem q
    have hr30' : r.getReg .x30 = BitVec.ofNat 64 fuel := by
      rw [hr30, hq30, hs.x30]
    let t := bottomBlock.res.toState r
    have htsteps := bottom_steps r hrpc'
    obtain ⟨ht30, ht13, ht14, ht10, ht11, ht27, ht28, ht7, ht2, htmem⟩ := bottom_sem r
    have htpc := bottom_pc r fuel hr30' hfuel hfuel9
    refine ⟨t, 13, 16, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · exact Steps.of_eq (hqsteps.trans (hrsteps.trans htsteps))
        (by decide) (by decide)
    · decide
    · decide
    · have htest' : ¬rank < Nat.choose ((lo + hi) / 2) k := by
        simpa only [mid] using htest
      simp only [htest', ↓reduceIte]
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · exact ht10.trans (hr10.trans (hq10.trans hs.x10))
      · exact ht11.trans (hr11.trans (hq11.trans hs.x11))
      · exact ht13.trans (hr13.trans (hq13.trans hs.x13))
      · exact ht14.trans (hr14.trans hqmid)
      · exact ht27.trans (hr27.trans (hq27.trans hs.x27))
      · exact ht28.trans (hr28.trans (hq28.trans hs.x28))
      · exact ht7.trans (hr7.trans (hq7.trans hs.x7))
      · exact ht2.trans (hr2.trans (hq2.trans hs.x2))
      · calc
          t.getReg .x30 = r.getReg .x30 - 1#64 := ht30
          _ = BitVec.ofNat 64 fuel - 1#64 := by rw [hr30']
          _ = BitVec.ofNat 64 (fuel - 1) :=
            BitVec.ofNat_sub_ofNat_of_le fuel 1 (by decide) hfuel
      · intro i hi'
        rw [htmem, hrmem, hqmem]
        exact hs.table i hi'
    · exact htpc
    · intro a
      rw [htmem, hrmem, hqmem]

#print axioms search_round
end Radix12SplitSearchRoundSD
end
-- END Radix12SplitSearchRoundSD

-- BEGIN Radix12SplitSearchLoopSD from /tmp/Radix12SplitSearchLoopSD.lean
section

namespace Radix12SplitSearchLoopSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
  Radix12SplitSearchRoundSD Radix12FixedPair Radix12MachineBisect
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem search_loop : ∀ fuel : Nat, ∀ (s : MachineState) (k rank lo hi : Nat),
    s.pc = BitVec.ofNat 64 4268 →
    Core s k rank lo hi fuel →
    1 ≤ k → k ≤ 5 → lo < hi → hi ≤ 385 →
    lo.choose k ≤ rank → rank < hi.choose k →
    1 ≤ fuel → fuel ≤ 9 → rank < 2 ^ 64 →
    ∃ t n c, Steps expandImage s n c t ∧
      n ≤ 13 * fuel ∧ c ≤ 16 * fuel ∧
      Core t k rank (fixedPair k rank lo hi fuel).1
        (fixedPair k rank lo hi fuel).2 0 ∧
      t.pc = BitVec.ofNat 64 4324 ∧
      (∀ a, t.getMem a = s.getMem a) := by
  intro fuel
  induction fuel with
  | zero =>
      intro s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi hfuel hfuel9 hrank
      omega
  | succ f ih =>
      intro s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi hfuel hfuel9 hrank
      let mid := (lo + hi) / 2
      let test := rank < Nat.choose mid k
      let lo' := if test then lo else mid
      let hi' := if test then mid else hi
      obtain ⟨t, n, c, hsteps, hn, hc, htcore, htpc, htmem⟩ :=
        search_round s k rank lo hi (f + 1) hpc hs hk hk5 hlohi hhi
          hfuel hfuel9 hrank
      have hb := Radix12FixedPair.round_bracket k rank lo hi hlohi hlo hrhi
      have hnew : lo' < hi' ∧ lo'.choose k ≤ rank ∧
          rank < hi'.choose k ∧ hi' ≤ hi := by
        simpa only [lo', hi', test, mid] using hb
      have hpair : fixedPair k rank lo hi (f + 1) =
          fixedPair k rank lo' hi' f := by
        simpa only [lo', hi', test, mid] using
          (Radix12FixedPair.fixedPair_step k rank lo hi f)
      have htcore' : Core t k rank lo' hi' f := by
        simpa only [lo', hi', test, mid, Nat.add_sub_cancel] using htcore
      by_cases hf0 : f = 0
      · subst f
        have hpc' : t.pc = BitVec.ofNat 64 4324 := by simpa using htpc
        have hp0 : fixedPair k rank lo hi 1 = (lo', hi') := by
          simpa only [fixedPair] using hpair
        refine ⟨t, n, c, hsteps, ?_, ?_, ?_, hpc', htmem⟩
        · simpa using hn
        · simpa using hc
        · simpa only [hp0, Prod.fst, Prod.snd] using htcore'
      · have hfpos : 1 ≤ f := by omega
        have hpc' : t.pc = BitVec.ofNat 64 4268 := by
          simpa [show 1 < f + 1 by omega] using htpc
        obtain ⟨u, n', c', htail, hn', hc', hucore, hupc, humem⟩ :=
          ih t k rank lo' hi' hpc' htcore' hk hk5 hnew.1
            (le_trans hnew.2.2.2 hhi) hnew.2.1 hnew.2.2.1
            hfpos (by omega) hrank
        refine ⟨u, n + n', c + c', hsteps.trans htail, ?_, ?_, ?_, hupc, ?_⟩
        · omega
        · omega
        · simpa only [hpair] using hucore
        · intro a
          rw [humem, htmem]

theorem search9_bar (s : MachineState) (k rank lo hi : Nat)
    (hpc : s.pc = BitVec.ofNat 64 4268)
    (hs : Core s k rank lo hi 9)
    (hk : 1 ≤ k) (hk5 : k ≤ 5)
    (hlohi : lo < hi) (hhi : hi ≤ 385)
    (hlo : lo.choose k ≤ rank) (hrhi : rank < hi.choose k)
    (hrank : rank < 2 ^ 64) :
    ∃ t n c, Steps expandImage s n c t ∧ n ≤ 117 ∧ c ≤ 144 ∧
      Core t k rank (fixedPair k rank lo hi 9).1
        (fixedPair k rank lo hi 9).2 0 ∧
      t.pc = BitVec.ofNat 64 4324 ∧
      t.getReg .x14 = BitVec.ofNat 64 (Radix12.bisectChoose k rank lo hi 9) ∧
      (∀ a, t.getMem a = s.getMem a) := by
  obtain ⟨t, n, c, hsteps, hn, hc, hcore, hpc', hmem⟩ :=
    search_loop 9 s k rank lo hi hpc hs hk hk5 hlohi hhi hlo hrhi
      (by decide) (by decide) hrank
  refine ⟨t, n, c, hsteps, ?_, ?_, hcore, hpc', ?_, hmem⟩
  · simpa using hn
  · simpa using hc
  · calc
      t.getReg .x14 = BitVec.ofNat 64 (fixedPair k rank lo hi 9).1 := hcore.x14
      _ = BitVec.ofNat 64 (fixedBisect k rank lo hi 9) := by
        rw [fixedPair_fst]
      _ = BitVec.ofNat 64 (Radix12.bisectChoose k rank lo hi 9) := by
        rw [fixedBisect_eq k rank 9 lo hi hlo hlohi]

#print axioms search_loop
#print axioms search9_bar
end Radix12SplitSearchLoopSD
end
-- END Radix12SplitSearchLoopSD

-- BEGIN Radix12SplitOneStageSD from /tmp/Radix12SplitOneStageSD.lean
section

namespace Radix12SplitOneStageSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
  Radix12SplitStageStartSD Radix12SplitSearchRoundSD
  Radix12SplitSearchLoopSD Radix12SplitStagePostSDOblig
  Radix12SplitStagePostSDProps Radix12SplitStagePostSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

structure Input (s : MachineState) (k rank bound : Nat) : Prop where
  pc : s.pc = BitVec.ofNat 64 4252
  x10 : s.getReg .x10 = BitVec.ofNat 64 rank
  x11 : s.getReg .x11 = BitVec.ofNat 64 k
  x12 : s.getReg .x12 = BitVec.ofNat 64 bound
  x27 : s.getReg .x27 = BitVec.ofNat 64 385
  x28 : s.getReg .x28 = BitVec.ofNat 64 0x4000
  x7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0
  x2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0
  table : ∀ i < 5 * 385,
    s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
      BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))

theorem stage_core (s : MachineState) (k rank bound : Nat)
    (hs : Input s k rank bound)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hbound : bound ≤ 384) :
    Core (stage.res.toState s) k rank (k - 1) (bound + 1) 9 := by
  obtain ⟨h13,h14,h30,h10,h11,h12,h27,h28,h7,h2⟩ := stage_regs s
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact h10.trans hs.x10
  · exact h11.trans hs.x11
  · rw [h13, hs.x12]
    simpa only [← BitVec.ofNat_add]
  · rw [h14, hs.x11]
    exact BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk
  · exact h27.trans hs.x27
  · exact h28.trans hs.x28
  · exact h7.trans hs.x7
  · exact h2.trans hs.x2
  · exact h30
  · intro i hi
    rw [stage_mem]
    exact hs.table i hi

theorem stage_search (s : MachineState) (k rank bound : Nat)
    (hs : Input s k rank bound)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hfloor : k - 1 ≤ bound)
    (hbound : bound ≤ 384)
    (hrank : rank < 2 ^ 64)
    (hcap : rank < Nat.choose (bound + 1) k) :
    ∃ u n c, Steps expandImage s n c u ∧
      n ≤ stage.res.steps + 117 ∧ c ≤ stage.res.cycles + 144 ∧
      Core u k rank
        (Radix12FixedPair.fixedPair k rank (k - 1) (bound + 1) 9).1
        (Radix12FixedPair.fixedPair k rank (k - 1) (bound + 1) 9).2 0 ∧
      u.pc = BitVec.ofNat 64 4324 ∧
      u.getReg .x14 = BitVec.ofNat 64 (Radix12.highChooseMax k bound rank) ∧
      (∀ a, u.getMem a = s.getMem a) := by
  let t := stage.res.toState s
  have htpc : t.pc = BitVec.ofNat 64 4268 := stage_pc s
  have htcore : Core t k rank (k - 1) (bound + 1) 9 :=
    stage_core s k rank bound hs hk hk5 hbound
  have hlohi : k - 1 < bound + 1 := by omega
  have hlo : Nat.choose (k - 1) k ≤ rank := by
    rw [Nat.choose_eq_zero_of_lt (by omega)]
    omega
  obtain ⟨u, n, c, hsearch, hn, hc, hcore, hpc, hbar, hmem⟩ :=
    search9_bar t k rank (k - 1) (bound + 1)
      htpc htcore hk hk5 hlohi (by omega) hlo hcap hrank
  refine ⟨u, stage.res.steps + n, stage.res.cycles + c, ?_, ?_, ?_,
    hcore, hpc, ?_, ?_⟩
  · exact (stage_steps s hs.pc).trans hsearch
  · omega
  · omega
  · simpa only [Radix12.highChooseMax] using hbar
  · intro a
    rw [hmem, stage_mem]

theorem stage_full (s : MachineState) (k rank bound : Nat)
    (hs : Input s k rank bound)
    (hk : 1 ≤ k) (hk5 : k ≤ 5) (hfloor : k - 1 ≤ bound)
    (hbound : bound ≤ 384)
    (hrank : rank < 2 ^ 64)
    (hcap : rank < Nat.choose (bound + 1) k) :
    let bar := Radix12.highChooseMax k bound rank
    let residual := rank - Nat.choose bar k
    ∃ v n c, Steps expandImage s n c v ∧
      n ≤ stage.res.steps + 117 + post.res.steps ∧
      c ≤ stage.res.cycles + 144 + post.res.cycles ∧
      v.pc = (if 1 < k then BitVec.ofNat 64 4252 else BitVec.ofNat 64 4380) ∧
      v.getReg .x11 = BitVec.ofNat 64 (k - 1) ∧
      v.getReg .x12 = BitVec.ofNat 64 bar ∧
      v.getReg .x10 = BitVec.ofNat 64 residual ∧
      v.getReg .x27 = BitVec.ofNat 64 385 ∧
      v.getReg .x28 = BitVec.ofNat 64 0x4000 ∧
      v.getReg .x7 = BitVec.ofNat 64 0x20F0 ∧
      v.getReg .x2 = BitVec.ofNat 64 0xffc3d0 ∧
      (∀ i < 5 * 385,
        v.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
          BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) ∧
      v.getMem (BitVec.ofNat 64 (0x4000 + 8 * (k - 1))) =
        BitVec.ofNat 64 bar ∧
      (∀ a, v.getMem a =
        if a = BitVec.ofNat 64 (0x4000 + 8 * (k - 1)) then
          BitVec.ofNat 64 bar else s.getMem a) := by
  let bar := Radix12.highChooseMax k bound rank
  let residual := rank - Nat.choose bar k
  have hlohi : k - 1 < bound + 1 := by omega
  have hlo : Nat.choose (k - 1) k ≤ rank := by
    rw [Nat.choose_eq_zero_of_lt (by omega)]
    omega
  have hgap : (bound + 1) - (k - 1) ≤ 2 ^ 9 := by omega
  have hbspec := Radix12.bisectChoose_spec k rank 9
    (k - 1) (bound + 1) hlo hcap hlohi hgap
  have hbarlt : bar < 385 := by
    dsimp [bar, Radix12.highChooseMax]
    omega
  have hchoose : Nat.choose bar k ≤ rank := by
    simpa only [bar, Radix12.highChooseMax] using hbspec.1
  obtain ⟨u, n, c, hsearch, hn, hc, hcore, hpc, hbar, hframe⟩ :=
    stage_search s k rank bound hs hk hk5 hfloor hbound hrank hcap
  let v := post.res.toState u
  have hpost : Steps expandImage u post.res.steps post.res.cycles v :=
    post_steps_bounded u k bar hpc hcore.x11 hbar hcore.x28
      hcore.x27 hcore.x2 hk hk5 hbarlt
  obtain ⟨hx11, hx12, hx14, hx27, hx28, hx7, hx2⟩ := post_regs u
  refine ⟨v, n + post.res.steps, c + post.res.cycles,
    hsearch.trans hpost, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · omega
  · omega
  · exact post_pc u k hcore.x11 hk hk5
  · rw [hx11, hcore.x11]
    exact BitVec.ofNat_sub_ofNat_of_le k 1 (by decide) hk
  · exact hx12.trans hbar
  · exact post_rank u k bar rank hcore.x11 hbar hcore.x10 hcore.x27
      hcore.x2 hk hk5 hbarlt hchoose hcore.table
  · exact hx27.trans hcore.x27
  · exact hx28.trans hcore.x28
  · exact hx7.trans hcore.x7
  · exact hx2.trans hcore.x2
  · intro i hi
    rw [post_table_frame u k i hcore.x11 hcore.x28 hk hk5 hi]
    exact hcore.table i hi
  · exact (post_scratch u k hcore.x11 hcore.x28 hk hk5).trans hbar
  · intro a
    rw [post_mem, scratch_addr u k hcore.x11 hcore.x28 hk hk5]
    by_cases ha : a = BitVec.ofNat 64 (0x4000 + 8 * (k - 1))
    · simp [ha, hbar]
    · simp [ha, hframe]

theorem next_cap (k rank bound : Nat)
    (hk : 1 ≤ k) (hfloor : k - 1 ≤ bound)
    (hcap : rank < Nat.choose (bound + 1) k)
    (hbound : bound ≤ 384) :
    let bar := Radix12.highChooseMax k bound rank
    (k - 1 ≤ bar ∧ bar ≤ bound) ∧
      rank - Nat.choose bar k < Nat.choose bar (k - 1) := by
  have hlo : Nat.choose (k - 1) k ≤ rank := by
    rw [Nat.choose_eq_zero_of_lt (by omega)]
    omega
  have hs := Radix12.bisectChoose_spec k rank 9 (k - 1) (bound + 1)
    hlo hcap (by omega) (by omega)
  change (k - 1 ≤ Radix12.bisectChoose k rank (k - 1) (bound + 1) 9 ∧
    Radix12.bisectChoose k rank (k - 1) (bound + 1) 9 ≤ bound) ∧
    rank - Nat.choose
      (Radix12.bisectChoose k rank (k - 1) (bound + 1) 9) k <
      Nat.choose (Radix12.bisectChoose k rank (k - 1) (bound + 1) 9) (k - 1)
  constructor
  · exact ⟨hs.2.2.1, by omega⟩
  · let bar := Radix12.bisectChoose k rank (k - 1) (bound + 1) 9
    have hpascal : Nat.choose (bar + 1) k =
        Nat.choose bar (k - 1) + Nat.choose bar k := by
      have hh := Nat.choose_succ_succ' bar (k - 1)
      simpa only [Nat.sub_add_cancel hk] using hh
    have hlt : rank < Nat.choose (bar + 1) k := hs.2.1
    have hle : Nat.choose bar k ≤ rank := hs.1
    change rank - Nat.choose bar k < Nat.choose bar (k - 1)
    omega

theorem stage_next (s : MachineState) (k rank bound : Nat)
    (hs : Input s k rank bound)
    (hk : 1 < k) (hk5 : k ≤ 5) (hfloor : k - 1 ≤ bound)
    (hbound : bound ≤ 384) (hrank : rank < 2 ^ 64)
    (hcap : rank < Nat.choose (bound + 1) k) :
    let bar := Radix12.highChooseMax k bound rank
    let residual := rank - Nat.choose bar k
    ∃ v n c, Steps expandImage s n c v ∧
      n ≤ stage.res.steps + 117 + post.res.steps ∧
      c ≤ stage.res.cycles + 144 + post.res.cycles ∧
      Input v (k - 1) residual bar ∧
      (k - 1) - 1 ≤ bar ∧ bar ≤ 384 ∧
      residual < 2 ^ 64 ∧
      residual < Nat.choose (bar + 1) (k - 1) ∧
      v.getMem (BitVec.ofNat 64 (0x4000 + 8 * (k - 1))) =
        BitVec.ofNat 64 bar ∧
      (∀ a, v.getMem a =
        if a = BitVec.ofNat 64 (0x4000 + 8 * (k - 1)) then
          BitVec.ofNat 64 bar else s.getMem a) := by
  let bar := Radix12.highChooseMax k bound rank
  let residual := rank - Nat.choose bar k
  obtain ⟨v,n,c,hsteps,hn,hc,hpc,h11,h12,h10,h27,h28,h7,h2,htable,
    hslot,hframe⟩ :=
    stage_full s k rank bound hs (by omega) hk5 hfloor hbound hrank hcap
  obtain ⟨hbarbounds,hrescap⟩ :=
    next_cap k rank bound (by omega) hfloor hcap hbound
  refine ⟨v,n,c,hsteps,hn,hc,?_,?_,?_,?_,?_,hslot,hframe⟩
  · refine ⟨?_,h10,h11,h12,h27,h28,h7,h2,htable⟩
    simpa [show 1 < k by omega] using hpc
  · omega
  · omega
  · omega
  · have hchoose : Nat.choose bar (k - 1) ≤
        Nat.choose (bar + 1) (k - 1) :=
      Nat.choose_le_choose (k - 1) (by omega)
    exact lt_of_lt_of_le hrescap hchoose

#print axioms stage_core
#print axioms stage_search
#print axioms stage_full
#print axioms next_cap
#print axioms stage_next
end Radix12SplitOneStageSD
end
-- END Radix12SplitOneStageSD

-- BEGIN Radix12SplitFiveStageSD from /tmp/Radix12SplitFiveStageSD.lean
section
namespace Radix12SplitFiveStageSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
  Radix12SplitOneStageSD Radix12SplitStageStartSD Radix12SplitStagePostSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def slot (i : Nat) : Word := BitVec.ofNat 64 (0x4000 + 8 * i)

theorem slot_ne (i j : Nat) (hi : i < 5) (hj : j < 5) (hij : i ≠ j) :
    slot i ≠ slot j := by
  intro heq
  have hn := congrArg BitVec.toNat heq
  simp only [slot, BitVec.toNat_ofNat,
    Nat.mod_eq_of_lt (show 0x4000 + 8 * i < 2 ^ 64 by omega),
    Nat.mod_eq_of_lt (show 0x4000 + 8 * j < 2 ^ 64 by omega)] at hn
  omega

theorem frame_other {s t : MachineState} (i j : Nat) (hi : i < 5)
    (hj : j < 5) (hij : i ≠ j) (bar : Nat)
    (hframe : ∀ a, t.getMem a =
      if a = slot i then BitVec.ofNat 64 bar else s.getMem a) :
    t.getMem (slot j) = s.getMem (slot j) := by
  rw [hframe]
  simp [ne_comm.mp (slot_ne i j hi hj hij)]

theorem five_stages (s : MachineState) (code : Nat)
    (hs : Input s 5 code 384)
    (hcode : code < Nat.choose 385 5) :
    let b4 := Radix12.highChooseMax 5 384 code
    let r4 := code - Nat.choose b4 5
    let b3 := Radix12.highChooseMax 4 b4 r4
    let r3 := r4 - Nat.choose b3 4
    let b2 := Radix12.highChooseMax 3 b3 r3
    let r2 := r3 - Nat.choose b2 3
    let b1 := Radix12.highChooseMax 2 b2 r2
    let r1 := r2 - Nat.choose b1 2
    let b0 := Radix12.highChooseMax 1 b1 r1
    ∃ t n c, Steps expandImage s n c t ∧
      t.pc = BitVec.ofNat 64 4380 ∧
      t.getReg .x10 = 0#64 ∧
      t.getReg .x7 = BitVec.ofNat 64 0x20F0 ∧
      t.getReg .x28 = BitVec.ofNat 64 0x4000 ∧
      t.getMem (slot 0) = BitVec.ofNat 64 b0 ∧
      t.getMem (slot 1) = BitVec.ofNat 64 b1 ∧
      t.getMem (slot 2) = BitVec.ofNat 64 b2 ∧
      t.getMem (slot 3) = BitVec.ofNat 64 b3 ∧
      t.getMem (slot 4) = BitVec.ofNat 64 b4 ∧
      n ≤ 5 * (stage.res.steps + 117 + post.res.steps) ∧
      c ≤ 5 * (stage.res.cycles + 144 + post.res.cycles) ∧
      (∀ a, (∀ i < 5, a ≠ slot i) → t.getMem a = s.getMem a) := by
  let b4 := Radix12.highChooseMax 5 384 code
  let r4 := code - Nat.choose b4 5
  let b3 := Radix12.highChooseMax 4 b4 r4
  let r3 := r4 - Nat.choose b3 4
  let b2 := Radix12.highChooseMax 3 b3 r3
  let r2 := r3 - Nat.choose b2 3
  let b1 := Radix12.highChooseMax 2 b2 r2
  let r1 := r2 - Nat.choose b1 2
  let b0 := Radix12.highChooseMax 1 b1 r1
  have h64 : code < 2 ^ 64 :=
    lt_trans hcode (lt_trans Radix12Split.capacity_core (by norm_num))
  obtain ⟨s4,n5,c5,hstep5,hn5,hc5,hin4,hfloor4,hbound4,hrank4,hcap4,
    hslot4,hframe4⟩ :=
    stage_next s 5 code 384 hs (by decide) (by decide) (by decide)
      (by decide) h64 hcode
  obtain ⟨s3,n4,c4,hstep4,hn4,hc4,hin3,hfloor3,hbound3,hrank3,hcap3,
    hslot3,hframe3⟩ :=
    stage_next s4 4 r4 b4 hin4 (by decide) (by decide) hfloor4
      hbound4 hrank4 hcap4
  obtain ⟨s2,n3,c3,hstep3,hn3,hc3,hin2,hfloor2,hbound2,hrank2,hcap2,
    hslot2,hframe2⟩ :=
    stage_next s3 3 r3 b3 hin3 (by decide) (by decide) hfloor3
      hbound3 hrank3 hcap3
  obtain ⟨s1,n2,c2,hstep2,hn2,hc2,hin1,hfloor1,hbound1,hrank1,hcap1,
    hslot1,hframe1⟩ :=
    stage_next s2 2 r2 b2 hin2 (by decide) (by decide) hfloor2
      hbound2 hrank2 hcap2
  obtain ⟨t,n1,c1,hstep1,hn1,hc1,hpc,h11,h12,h10,h27,h28,h7,h2,htable,
    hslot0,hframe0⟩ :=
    stage_full s1 1 r1 b1 hin1 (by decide) (by decide) hfloor1
      hbound1 hrank1 hcap1
  have hzero : r1 - Nat.choose b0 1 = 0 := by
    have h := (next_cap 1 r1 b1 (by decide) hfloor1 hcap1 hbound1).2
    norm_num at h
    change r1 - b0 = 0 at h
    simpa only [Nat.choose_one_right] using h
  have hmem1 : t.getMem (slot 1) = BitVec.ofNat 64 b1 :=
    (frame_other 0 1 (by decide) (by decide) (by decide) b0 hframe0).trans hslot1
  have hmem2 : t.getMem (slot 2) = BitVec.ofNat 64 b2 :=
    (frame_other 0 2 (by decide) (by decide) (by decide) b0 hframe0).trans
      ((frame_other 1 2 (by decide) (by decide) (by decide) b1 hframe1).trans hslot2)
  have hmem3 : t.getMem (slot 3) = BitVec.ofNat 64 b3 :=
    (frame_other 0 3 (by decide) (by decide) (by decide) b0 hframe0).trans
      ((frame_other 1 3 (by decide) (by decide) (by decide) b1 hframe1).trans
        ((frame_other 2 3 (by decide) (by decide) (by decide) b2 hframe2).trans hslot3))
  have hmem4 : t.getMem (slot 4) = BitVec.ofNat 64 b4 :=
    (frame_other 0 4 (by decide) (by decide) (by decide) b0 hframe0).trans
      ((frame_other 1 4 (by decide) (by decide) (by decide) b1 hframe1).trans
        ((frame_other 2 4 (by decide) (by decide) (by decide) b2 hframe2).trans
          ((frame_other 3 4 (by decide) (by decide) (by decide) b3 hframe3).trans
            hslot4)))
  refine ⟨t, n5+n4+n3+n2+n1, c5+c4+c3+c2+c1, ?_, ?_, ?_, h7,
    h28,hslot0,hmem1,hmem2,hmem3,hmem4,?_,?_,?_⟩
  · exact ((((hstep5.trans hstep4).trans hstep3).trans hstep2).trans hstep1)
  · simpa using hpc
  · change t.getReg .x10 = BitVec.ofNat 64 (r1 - Nat.choose b0 1) at h10
    simpa only [hzero] using h10
  · omega
  · omega
  · intro a ha
    have h0 : a ≠ BitVec.ofNat 64 (0x4000 + 8 * (1 - 1)) := by
      simpa only [slot, Nat.reduceSub] using ha 0 (by decide)
    have h1 : a ≠ BitVec.ofNat 64 (0x4000 + 8 * (2 - 1)) := by
      simpa only [slot, Nat.reduceSub] using ha 1 (by decide)
    have h2 : a ≠ BitVec.ofNat 64 (0x4000 + 8 * (3 - 1)) := by
      simpa only [slot, Nat.reduceSub] using ha 2 (by decide)
    have h3 : a ≠ BitVec.ofNat 64 (0x4000 + 8 * (4 - 1)) := by
      simpa only [slot, Nat.reduceSub] using ha 3 (by decide)
    have h4 : a ≠ BitVec.ofNat 64 (0x4000 + 8 * (5 - 1)) := by
      simpa only [slot, Nat.reduceSub] using ha 4 (by decide)
    rw [hframe0 a, if_neg h0, hframe1 a, if_neg h1,
      hframe2 a, if_neg h2, hframe3 a, if_neg h3,
      hframe4 a, if_neg h4]

#print axioms frame_other
#print axioms five_stages
end Radix12SplitFiveStageSD
end
-- END Radix12SplitFiveStageSD

-- BEGIN Radix12SplitSetupSD from /tmp/Radix12SplitSetupSD.lean
section
namespace Radix12SplitSetupSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 7)),
   (15 + 7, (expandTail.drop 7).take 16),
   (15 + 23, (expandTail.drop 23).take 1),
   (15 + 24, expandTail.drop 24)]
theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel
theorem codeAt_setup :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 7)))
      ((expandTail.drop 7).take 16) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_mask :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 23)))
      ((expandTail.drop 23).take 1) :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)

sym_block setup := symRun {} ((expandTail.drop 7).take 16)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 7))) 30
sym_block mask := symRun {} ((expandTail.drop 23).take 1)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 23))) 3

theorem setup_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 7))) :
    Steps expandImage s setup.res.steps setup.res.cycles
      (setup.res.toState s) := by
  have ho : setup.res.obligs s := by simp only [setup.res, rv_simp]
  exact symRun_sound setup codeAt_setup s hpc ho

theorem mask_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 23))) :
    Steps expandImage s mask.res.steps mask.res.cycles
      (mask.res.toState s) := by
  have ho : mask.res.obligs s := by simp only [mask.res, rv_simp]
  exact symRun_sound mask codeAt_mask s hpc ho

theorem setup_regs (s : MachineState) :
    (setup.res.toState s).getReg .x11 = BitVec.ofNat 64 5 ∧
    (setup.res.toState s).getReg .x12 = BitVec.ofNat 64 384 ∧
    (setup.res.toState s).getReg .x27 = BitVec.ofNat 64 385 ∧
    (setup.res.toState s).getReg .x28 = BitVec.ofNat 64 0x4000 ∧
    (setup.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (setup.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (setup.res.toState s).getReg .x2 = s.getReg .x2 ∧
    (setup.res.toState s).getReg .x20 = BitVec.ofNat 64 68674865952 := by
  simp only [Result.toState_getReg, setup.res, rv_simp]
  simp

theorem choose3855_eq : Nat.choose 385 5 = 68674865952 := by
  rw [Nat.choose_eq_descFactorial_div_factorial]
  norm_num [Nat.descFactorial]

theorem setup_pc (s : MachineState) (code : Nat)
    (h10 : s.getReg .x10 = BitVec.ofNat 64 code)
    (hcap : code < Nat.choose 385 5) :
    (setup.res.toState s).pc = BitVec.ofNat 64 4248 := by
  simp only [Result.toState_pc, setup.res, rv_simp]
  simp only [h10]
  rw [choose3855_eq] at hcap
  have hcode64 : code < 2 ^ 64 := by omega
  have htest : (BitVec.ofNat 64 code).ult (BitVec.ofNat 64 68674865952) = true := by
    simp only [BitVec.ult_eq_decide_lt, decide_eq_true_eq,
      BitVec.lt_def, BitVec.toNat_ofNat,
      Nat.mod_eq_of_lt hcode64,
      Nat.mod_eq_of_lt (show 68674865952 < 2 ^ 64 by decide)]
    exact hcap
  simp [htest]

theorem setup_mem (s : MachineState) (a : Word) :
    (setup.res.toState s).getMem a = s.getMem a := by
  simp only [Result.toState_getMem, setup.res, memEval]

theorem mask_regs (s : MachineState) :
    (mask.res.toState s).getReg .x11 = s.getReg .x11 ∧
    (mask.res.toState s).getReg .x12 = s.getReg .x12 ∧
    (mask.res.toState s).getReg .x27 = s.getReg .x27 ∧
    (mask.res.toState s).getReg .x28 = s.getReg .x28 ∧
    (mask.res.toState s).getReg .x10 = s.getReg .x10 ∧
    (mask.res.toState s).getReg .x7 = s.getReg .x7 ∧
    (mask.res.toState s).getReg .x2 = s.getReg .x2 := by
  simp only [Result.toState_getReg, mask.res, rv_simp]
  simp

theorem mask_pc (s : MachineState) :
    (mask.res.toState s).pc = BitVec.ofNat 64 4252 := by
  simp only [Result.toState_pc, mask.res, rv_simp]

theorem mask_mem (s : MachineState) (a : Word) :
    (mask.res.toState s).getMem a = s.getMem a := by
  simp only [Result.toState_getMem, mask.res, memEval]

theorem setup_to_stage (s : MachineState) (code : Nat)
    (hpc : s.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 7)))
    (h10 : s.getReg .x10 = BitVec.ofNat 64 code)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0)
    (h2 : s.getReg .x2 = BitVec.ofNat 64 0xffc3d0)
    (hcap : code < Nat.choose 385 5)
    (htable : ∀ i < 5 * 385,
      s.getMem (BitVec.ofNat 64 (0xffc3d0 + 8 * i)) =
        BitVec.ofNat 64 (Nat.choose (i % 385) (i / 385 + 1))) :
    ∃ v, Steps expandImage s
        (setup.res.steps + mask.res.steps)
        (setup.res.cycles + mask.res.cycles) v ∧
      Radix12SplitOneStageSD.Input v 5 code 384 := by
  let u := setup.res.toState s
  let v := mask.res.toState u
  have hu : Steps expandImage s setup.res.steps setup.res.cycles u :=
    setup_steps s hpc
  have hupc : u.pc = BitVec.ofNat 64 (0x1000 + 4 * (15 + 23)) :=
    setup_pc s code h10 hcap
  have hv : Steps expandImage u mask.res.steps mask.res.cycles v :=
    mask_steps u hupc
  obtain ⟨hu11,hu12,hu27,hu28,hu10,hu7,hu2,_⟩ := setup_regs s
  obtain ⟨hv11,hv12,hv27,hv28,hv10,hv7,hv2⟩ := mask_regs u
  refine ⟨v, hu.trans hv, ?_⟩
  refine ⟨mask_pc u, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · exact hv10.trans (hu10.trans h10)
  · exact hv11.trans hu11
  · exact hv12.trans hu12
  · exact hv27.trans hu27
  · exact hv28.trans hu28
  · exact hv7.trans (hu7.trans h7)
  · exact hv2.trans (hu2.trans h2)
  · intro i hi
    rw [mask_mem, setup_mem]
    exact htable i hi

#print axioms setup_steps
#print axioms mask_steps
#print axioms setup_regs
#print axioms setup_pc
#print axioms setup_to_stage
end Radix12SplitSetupSD
end
-- END Radix12SplitSetupSD

-- BEGIN Radix12SplitFinalSD from /tmp/Radix12SplitFinalSD.lean
section
namespace Radix12SplitFinalSD
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def L : SigGolfCandidate.Rv.Layout :=
  [(0, expandCode.take (15 + 56)),
   (15 + 56, (expandTail.drop 56).take 1),
   (15 + 57, (expandTail.drop 57).take 40),
   (15 + 97, (expandTail.drop 97).take 9),
   (15 + 106, expandTail.drop 106)]
theorem layout_ok : layoutOk 0 L = true := by decide +kernel
theorem code_eq : expandImage.code = layoutCode L := by decide +kernel
theorem codeAt_check :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 56)))
      ((expandTail.drop 56).take 1) :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_write :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 57)))
      ((expandTail.drop 57).take 40) :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_fallback :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 97)))
      ((expandTail.drop 97).take 9) :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_done :
    CodeAt expandImage (BitVec.ofNat 64 (0x1000 + 4 * (15 + 106)))
      (expandTail.drop 106) :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)

sym_block check := symRun {} ((expandTail.drop 56).take 1)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 56))) 3
sym_block write := symRun {noAlias := true} ((expandTail.drop 57).take 40)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 57))) 50
sym_block fallback := symRun {noAlias := true} ((expandTail.drop 97).take 9)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 97))) 20
sym_block done := symRun {} (expandTail.drop 106)
  (BitVec.ofNat 64 (0x1000 + 4 * (15 + 106))) 5

theorem check_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 4380) :
    Steps expandImage s check.res.steps check.res.cycles
      (check.res.toState s) := by
  have ho : check.res.obligs s := by simp only [check.res, rv_simp]
  exact symRun_sound check codeAt_check s hpc ho

theorem check_pc (s : MachineState) (h10 : s.getReg .x10 = 0#64) :
    (check.res.toState s).pc = BitVec.ofNat 64 4384 := by
  simp only [Result.toState_pc, check.res, rv_simp, h10]
  decide

theorem write_obligs (s : MachineState)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000) :
    write.res.obligs s := by
  simp only [Result.obligs, write.res, rv_simp]
  rw [h7, h28]
  decide

theorem write_steps (s : MachineState)
    (hpc : s.pc = BitVec.ofNat 64 4384)
    (h7 : s.getReg .x7 = BitVec.ofNat 64 0x20F0)
    (h28 : s.getReg .x28 = BitVec.ofNat 64 0x4000) :
    Steps expandImage s write.res.steps write.res.cycles
      (write.res.toState s) :=
  symRun_sound write codeAt_write s hpc (write_obligs s h7 h28)

#print axioms codeAt_write
#print axioms write_steps
end Radix12SplitFinalSD
end
-- END Radix12SplitFinalSD

-- BEGIN Radix12SplitFrameX2 from /tmp/Radix12SplitFrameX2.lean
section
namespace Radix12SplitFrameX2
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

def SafeX2 : SigGolfCandidate.Rv.Micro → Prop
  | .alu rd _ _ _ | .load _ rd _ _ | .jal rd _ | .jalr rd _ _ => rd ≠ .x2
  | .store .. | .branch .. => True
instance (m : SigGolfCandidate.Rv.Micro) : Decidable (SafeX2 m) := by
  cases m <;> simp [SafeX2] <;> infer_instance

def safeMicroB : SigGolfCandidate.Rv.Micro → Bool
  | .alu rd _ _ _ | .load _ rd _ _ | .jal rd _ | .jalr rd _ _ => rd != .x2
  | .store .. | .branch .. => true

def safeWordB (w : BitVec 32) : Bool :=
  match decodeInstruction w with
  | some i =>
      match SigGolfCandidate.Rv.classify i with
      | some m => safeMicroB m
      | none => w == 0x00000073
  | none => true

theorem code_safe :
    expandCode.all safeWordB = true := by
  decide +kernel

theorem micro_frame (m : SigGolfCandidate.Rv.Micro) (s t : MachineState)
    (hm : safeMicroB m = true)
    (hs : m.exec s = some t) :
    t.getReg .x2 = s.getReg .x2 := by
  cases m with
  | alu rd op a b =>
      simp only [safeMicroB, bne_iff_ne] at hm
      simp only [SigGolfCandidate.Rv.Micro.exec, Option.some.injEq] at hs
      subst t
      simp only [MachineState.getReg_setPC]
      exact MachineState.getReg_setReg_ne s rd .x2 _ hm

  | load k rd rs off =>
      simp only [safeMicroB, bne_iff_ne] at hm
      simp only [SigGolfCandidate.Rv.Micro.exec] at hs
      split_ifs at hs
      cases hs
      simp only [MachineState.getReg_setPC]
      exact MachineState.getReg_setReg_ne s rd .x2 _ hm
  | store k rs1 rs2 off =>
      simp only [SigGolfCandidate.Rv.Micro.exec] at hs
      split_ifs at hs
      cases hs
      cases k <;> rfl
  | branch op rs1 rs2 off =>
      simp only [SigGolfCandidate.Rv.Micro.exec] at hs
      split_ifs at hs <;> cases hs <;> rfl
  | jal rd off =>
      simp only [safeMicroB, bne_iff_ne] at hm
      simp only [SigGolfCandidate.Rv.Micro.exec, Option.some.injEq] at hs
      subst t
      simp only [MachineState.getReg_setPC]
      exact MachineState.getReg_setReg_ne s rd .x2 _ hm
  | jalr rd rs off =>
      simp only [safeMicroB, bne_iff_ne] at hm
      simp only [SigGolfCandidate.Rv.Micro.exec, Option.some.injEq] at hs
      subst t
      simp only [MachineState.getReg_setPC]
      exact MachineState.getReg_setReg_ne s rd .x2 _ hm

theorem fetch_safe (s : MachineState) (i : Instruction)
    (hf : fetch expandImage s = some i) :
    (∃ m, SigGolfCandidate.Rv.classify i = some m ∧ safeMicroB m = true) ∨
      i = .base .ECALL := by
  unfold fetch at hf
  split_ifs at hf with hpc
  · obtain ⟨w, hw, hdecode⟩ := Option.bind_eq_some_iff.mp hf
    have hmem : w ∈ expandCode := List.mem_of_getElem? hw
    have hsafe := (List.all_eq_true.mp code_safe) w hmem
    simp only [safeWordB, hdecode] at hsafe
    cases hc : SigGolfCandidate.Rv.classify i with
    | none =>
        simp only [hc, beq_iff_eq] at hsafe
        subst w
        have hd : decodeInstruction (0x00000073 : BitVec 32) =
            some (.base .ECALL) := by rfl
        rw [hd] at hdecode
        exact Or.inr (Option.some.inj hdecode).symm
    | some m =>
        simp only [hc] at hsafe
        exact Or.inl ⟨m, rfl, hsafe⟩

theorem steps_x2 {s t : MachineState} {n c : Nat}
    (h : Steps expandImage s n c t) :
    t.getReg .x2 = s.getReg .x2 := by
  induction h with
  | refl => rfl
  | @step s t u i k c hf hs tail ih =>
      rcases fetch_safe s i hf with ⟨m, hclass, hsafe⟩ | hecall
      · rw [SigGolfCandidate.Rv.classify_sound hclass s] at hs
        exact ih.trans (micro_frame m s t hsafe hs)
      · subst i
        simp [ordinaryStep] at hs
#print axioms code_safe
#print axioms micro_frame
#print axioms fetch_safe
#print axioms steps_x2
end Radix12SplitFrameX2
end
-- END Radix12SplitFrameX2

-- BEGIN Radix12SplitStepsDet from /tmp/Radix12SplitStepsDet.lean
section
namespace Radix12SplitStepsDet
open RiscvZkvm.Rv64 SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv
  SigGolfCandidate.Rv Radix12SplitExpandImageSD
set_option maxRecDepth 100000
set_option maxHeartbeats 1000000

theorem steps_det {s t u : MachineState} {n c c' : Nat}
    (h : Steps expandImage s n c t)
    (h' : Steps expandImage s n c' u) : t = u := by
  induction h generalizing u c' with
  | refl s =>
      cases h'
      rfl
  | @step s t v i k c hf hs tail ih =>
      cases h' with
      | step hf' hs' tail' =>
          have hi : i = _ := Option.some.inj (hf.symm.trans hf')
          subst hi
          have ht : t = _ := Option.some.inj (hs.symm.trans hs')
          subst ht
          exact ih tail'

#print axioms steps_det
end Radix12SplitStepsDet
end
-- END Radix12SplitStepsDet
