-- Generated by SigGolfCandidate/Expand/gen_code.py from work/py-pors/out/expand.lst. Do not edit.
import SigGolfCandidate.Expand.Base
import SigGolfCandidate.Submission

namespace SigGolfCandidate.Expand
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

set_option maxRecDepth 16384

/-- instructions 0 .. 13 -/
def seg0 : List (BitVec 32) := [0x000011b7#32, 0xc0118193#32, 0x02303023#32, 0x02003423#32, 0x00003cb7#32, 0x300c8c93#32, 0x000cb083#32, 0x008cb103#32, 0x02103823#32, 0x02203c23#32, 0x02000513#32, 0x04000593#32, 0x16000613#32, 0x00000073#32]
/-- instructions 14 .. 17 -/
def seg14 : List (BitVec 32) := [0x00400237#32, 0x74403c23#32, 0x00000413#32, 0x02200813#32]
/-- instructions 18 .. 24 -/
def seg18 : List (BitVec 32) := [0x00685693#32, 0x00369693#32, 0x1606b483#32, 0x0104d4b3#32, 0x03f87213#32, 0x03200893#32, 0x0048dc63#32]
/-- instructions 25 .. 29 -/
def seg25 : List (BitVec 32) := [0x1686b703#32, 0x04000893#32, 0x404888b3#32, 0x01171733#32, 0x00e4e4b3#32]
/-- instructions 30 .. 39 -/
def seg30 : List (BitVec 32) := [0x03249493#32, 0x0324d493#32, 0x00849493#32, 0x00341193#32, 0x0034e4b3#32, 0x6e91b023#32, 0x00e80813#32, 0x00140413#32, 0x00f00893#32, 0xfb1416e3#32]
/-- instructions 40 .. 40 -/
def seg40 : List (BitVec 32) := [0x00100413#32]
/-- instructions 41 .. 43 -/
def seg41 : List (BitVec 32) := [0x00341713#32, 0x6e070713#32, 0x00073483#32]
/-- instructions 44 .. 45 -/
def seg44 : List (BitVec 32) := [0x6e000893#32, 0x01170c63#32]
/-- instructions 46 .. 47 -/
def seg46 : List (BitVec 32) := [0xff873683#32, 0x00d4f863#32]
/-- instructions 48 .. 50 -/
def seg48 : List (BitVec 32) := [0x00d73023#32, 0xff870713#32, 0xfe9ff06f#32]
/-- instructions 51 .. 54 -/
def seg51 : List (BitVec 32) := [0x00973023#32, 0x00140413#32, 0x00f00893#32, 0xfd1416e3#32]
/-- instructions 55 .. 56 -/
def seg55 : List (BitVec 32) := [0x00000413#32, 0x00000793#32]
/-- instructions 57 .. 63 -/
def seg57 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x00d4c4b3#32, 0x32048063#32]
/-- instructions 64 .. 66 -/
def seg64 : List (BitVec 32) := [0x0014d493#32, 0x00178793#32, 0xfe049ce3#32]
/-- instructions 67 .. 69 -/
def seg67 : List (BitVec 32) := [0x00140413#32, 0x00e00893#32, 0xfd1418e3#32]
/-- instructions 70 .. 71 -/
def seg70 : List (BitVec 32) := [0x08600893#32, 0x30f8c063#32]
/-- instructions 72 .. 80 -/
def seg72 : List (BitVec 32) := [0x00003eb7#32, 0x400e8e93#32, 0x00001f37#32, 0x910f0f13#32, 0x008f0f93#32, 0x76003023#32, 0x76000b93#32, 0x00004c37#32, 0x00000413#32]
/-- instructions 81 .. 87 -/
def seg81 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x0096c6b3#32, 0xfff00a13#32]
/-- instructions 88 .. 90 -/
def seg88 : List (BitVec 32) := [0x0016d693#32, 0x001a0a13#32, 0xfe069ce3#32]
/-- instructions 91 .. 94 -/
def seg91 : List (BitVec 32) := [0x0184e933#32, 0x00197793#32, 0x00000993#32, 0x00000a93#32]
/-- instructions 95 .. 95 -/
def seg95 : List (BitVec 32) := [0x0749d063#32]
/-- instructions 96 .. 97 -/
def seg96 : List (BitVec 32) := [0x000bb183#32, 0x03219863#32]
/-- instructions 98 .. 108 -/
def seg98 : List (BitVec 32) := [0x00579c93#32, 0x015cecb3#32, 0x010cec93#32, 0x019f0023#32, 0x000f8f13#32, 0x008f8f93#32, 0x00000a93#32, 0xff8b8b93#32, 0x00195913#32, 0x00197793#32, 0x0240006f#32]
/-- instructions 109 .. 116 -/
def seg109 : List (BitVec 32) := [0x000eb083#32, 0x008eb103#32, 0x001fb023#32, 0x002fb423#32, 0x010e8e93#32, 0x010f8f93#32, 0x001a8a93#32, 0x00195913#32]
/-- instructions 117 .. 118 -/
def seg117 : List (BitVec 32) := [0x00198993#32, 0xfa5ff06f#32]
/-- instructions 119 .. 125 -/
def seg119 : List (BitVec 32) := [0x00579c93#32, 0x015cecb3#32, 0x019f0023#32, 0x000f8f13#32, 0x008f8f93#32, 0x00e00893#32, 0x01140863#32]
/-- instructions 126 .. 128 -/
def seg126 : List (BitVec 32) := [0x00194193#32, 0x008b8b93#32, 0x003bb023#32]
/-- instructions 129 .. 131 -/
def seg129 : List (BitVec 32) := [0x00140413#32, 0x00f00893#32, 0xf3141ce3#32]
/-- instructions 132 .. 133 -/
def seg132 : List (BitVec 32) := [0x00004cb7#32, 0xb80c8c93#32]
/-- instructions 134 .. 134 -/
def seg134 : List (BitVec 32) := [0x019e8a63#32]
/-- instructions 135 .. 136 -/
def seg135 : List (BitVec 32) := [0x000eb183#32, 0x1e019e63#32]
/-- instructions 137 .. 138 -/
def seg137 : List (BitVec 32) := [0x008e8e93#32, 0xff1ff06f#32]
/-- instructions 139 .. 144 -/
def seg139 : List (BitVec 32) := [0x00005eb7#32, 0xac0e8e93#32, 0x008eb583#32, 0x02e5d813#32, 0x00387813#32, 0x1c081e63#32]
/-- instructions 145 .. 149 -/
def seg145 : List (BitVec 32) := [0x00003337#32, 0x30030313#32, 0x000013b7#32, 0x80038393#32, 0x00400b13#32]
/-- instructions 150 .. 155 -/
def seg150 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 156 .. 158 -/
def seg156 : List (BitVec 32) := [0x00001cb7#32, 0x810c8c93#32, 0x00000413#32]
/-- instructions 159 .. 165 -/
def seg159 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x008c81b3#32, 0x00918023#32, 0x00140413#32, 0x00f00893#32, 0xff1414e3#32]
/-- instructions 166 .. 170 -/
def seg166 : List (BitVec 32) := [0x00003337#32, 0x31030313#32, 0x000013b7#32, 0x82038393#32, 0x03c00b13#32]
/-- instructions 171 .. 176 -/
def seg171 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 177 .. 181 -/
def seg177 : List (BitVec 32) := [0x00004337#32, 0xb8030313#32, 0x000013b7#32, 0x17838393#32, 0x0d400b13#32]
/-- instructions 182 .. 187 -/
def seg182 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 188 .. 192 -/
def seg188 : List (BitVec 32) := [0x00004337#32, 0xed030313#32, 0x000013b7#32, 0x4c838393#32, 0x0c000b13#32]
/-- instructions 193 .. 198 -/
def seg193 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 199 .. 203 -/
def seg199 : List (BitVec 32) := [0x00004337#32, 0x1d030313#32, 0x000013b7#32, 0x7c838393#32, 0x0c000b13#32]
/-- instructions 204 .. 209 -/
def seg204 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 210 .. 214 -/
def seg210 : List (BitVec 32) := [0x00004337#32, 0x4d030313#32, 0x000023b7#32, 0xac838393#32, 0x0c000b13#32]
/-- instructions 215 .. 220 -/
def seg215 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 221 .. 225 -/
def seg221 : List (BitVec 32) := [0x00004337#32, 0x7d030313#32, 0x000023b7#32, 0xdc838393#32, 0x0bc00b13#32]
/-- instructions 226 .. 231 -/
def seg226 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 232 .. 259 -/
def seg232 : List (BitVec 32) := [0x00005eb7#32, 0xac0e8e93#32, 0x000023b7#32, 0x0b838393#32, 0x000eb503#32, 0x008eb583#32, 0x02a51613#32, 0x02a65613#32, 0x01655693#32, 0x02a69693#32, 0x02a6d693#32, 0x02c55713#32, 0x0035f893#32, 0x01489893#32, 0x01170733#32, 0x0025d793#32, 0x02a79793#32, 0x02a7d793#32, 0x0185d813#32, 0x02a81813#32, 0x02a85813#32, 0x02069693#32, 0x00d60633#32, 0x00c3b023#32, 0x02079793#32, 0x00f70733#32, 0x00e3b423#32, 0x0103b823#32]
/-- instructions 260 .. 262 -/
def seg260 : List (BitVec 32) := [0x00100293#32, 0x00000513#32, 0x00000073#32]
/-- instructions 263 .. 265 -/
def seg263 : List (BitVec 32) := [0x00100293#32, 0x00100513#32, 0x00000073#32]

/-- Segment table of the expand image. -/
def L : Rv.Layout := [(0, seg0), (14, seg14), (18, seg18), (25, seg25), (30, seg30), (40, seg40), (41, seg41), (44, seg44), (46, seg46), (48, seg48), (51, seg51), (55, seg55), (57, seg57), (64, seg64), (67, seg67), (70, seg70), (72, seg72), (81, seg81), (88, seg88), (91, seg91), (95, seg95), (96, seg96), (98, seg98), (109, seg109), (117, seg117), (119, seg119), (126, seg126), (129, seg129), (132, seg132), (134, seg134), (135, seg135), (137, seg137), (139, seg139), (145, seg145), (150, seg150), (156, seg156), (159, seg159), (166, seg166), (171, seg171), (177, seg177), (182, seg182), (188, seg188), (193, seg193), (199, seg199), (204, seg204), (210, seg210), (215, seg215), (221, seg221), (226, seg226), (232, seg232), (260, seg260), (263, seg263)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The expand image. -/
abbrev image : Image := Images.expandImage

theorem image_eq : submission.image .expand = image := rfl

theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (pcOf 0) seg0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_14 : CodeAt image (pcOf 14) seg14 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_18 : CodeAt image (pcOf 18) seg18 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_25 : CodeAt image (pcOf 25) seg25 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_30 : CodeAt image (pcOf 30) seg30 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_40 : CodeAt image (pcOf 40) seg40 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_41 : CodeAt image (pcOf 41) seg41 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_44 : CodeAt image (pcOf 44) seg44 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_46 : CodeAt image (pcOf 46) seg46 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_48 : CodeAt image (pcOf 48) seg48 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_51 : CodeAt image (pcOf 51) seg51 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_55 : CodeAt image (pcOf 55) seg55 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (pcOf 57) seg57 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_64 : CodeAt image (pcOf 64) seg64 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_67 : CodeAt image (pcOf 67) seg67 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (pcOf 70) seg70 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_72 : CodeAt image (pcOf 72) seg72 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_81 : CodeAt image (pcOf 81) seg81 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_88 : CodeAt image (pcOf 88) seg88 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_91 : CodeAt image (pcOf 91) seg91 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_95 : CodeAt image (pcOf 95) seg95 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_96 : CodeAt image (pcOf 96) seg96 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_98 : CodeAt image (pcOf 98) seg98 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_109 : CodeAt image (pcOf 109) seg109 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_117 : CodeAt image (pcOf 117) seg117 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_119 : CodeAt image (pcOf 119) seg119 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_126 : CodeAt image (pcOf 126) seg126 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_129 : CodeAt image (pcOf 129) seg129 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_132 : CodeAt image (pcOf 132) seg132 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_134 : CodeAt image (pcOf 134) seg134 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_135 : CodeAt image (pcOf 135) seg135 :=
  codeAt_layout code_eq layout_ok (i := 30) (by kernel_rfl) (by decide)
theorem codeAt_137 : CodeAt image (pcOf 137) seg137 :=
  codeAt_layout code_eq layout_ok (i := 31) (by kernel_rfl) (by decide)
theorem codeAt_139 : CodeAt image (pcOf 139) seg139 :=
  codeAt_layout code_eq layout_ok (i := 32) (by kernel_rfl) (by decide)
theorem codeAt_145 : CodeAt image (pcOf 145) seg145 :=
  codeAt_layout code_eq layout_ok (i := 33) (by kernel_rfl) (by decide)
theorem codeAt_150 : CodeAt image (pcOf 150) seg150 :=
  codeAt_layout code_eq layout_ok (i := 34) (by kernel_rfl) (by decide)
theorem codeAt_156 : CodeAt image (pcOf 156) seg156 :=
  codeAt_layout code_eq layout_ok (i := 35) (by kernel_rfl) (by decide)
theorem codeAt_159 : CodeAt image (pcOf 159) seg159 :=
  codeAt_layout code_eq layout_ok (i := 36) (by kernel_rfl) (by decide)
theorem codeAt_166 : CodeAt image (pcOf 166) seg166 :=
  codeAt_layout code_eq layout_ok (i := 37) (by kernel_rfl) (by decide)
theorem codeAt_171 : CodeAt image (pcOf 171) seg171 :=
  codeAt_layout code_eq layout_ok (i := 38) (by kernel_rfl) (by decide)
theorem codeAt_177 : CodeAt image (pcOf 177) seg177 :=
  codeAt_layout code_eq layout_ok (i := 39) (by kernel_rfl) (by decide)
theorem codeAt_182 : CodeAt image (pcOf 182) seg182 :=
  codeAt_layout code_eq layout_ok (i := 40) (by kernel_rfl) (by decide)
theorem codeAt_188 : CodeAt image (pcOf 188) seg188 :=
  codeAt_layout code_eq layout_ok (i := 41) (by kernel_rfl) (by decide)
theorem codeAt_193 : CodeAt image (pcOf 193) seg193 :=
  codeAt_layout code_eq layout_ok (i := 42) (by kernel_rfl) (by decide)
theorem codeAt_199 : CodeAt image (pcOf 199) seg199 :=
  codeAt_layout code_eq layout_ok (i := 43) (by kernel_rfl) (by decide)
theorem codeAt_204 : CodeAt image (pcOf 204) seg204 :=
  codeAt_layout code_eq layout_ok (i := 44) (by kernel_rfl) (by decide)
theorem codeAt_210 : CodeAt image (pcOf 210) seg210 :=
  codeAt_layout code_eq layout_ok (i := 45) (by kernel_rfl) (by decide)
theorem codeAt_215 : CodeAt image (pcOf 215) seg215 :=
  codeAt_layout code_eq layout_ok (i := 46) (by kernel_rfl) (by decide)
theorem codeAt_221 : CodeAt image (pcOf 221) seg221 :=
  codeAt_layout code_eq layout_ok (i := 47) (by kernel_rfl) (by decide)
theorem codeAt_226 : CodeAt image (pcOf 226) seg226 :=
  codeAt_layout code_eq layout_ok (i := 48) (by kernel_rfl) (by decide)
theorem codeAt_232 : CodeAt image (pcOf 232) seg232 :=
  codeAt_layout code_eq layout_ok (i := 49) (by kernel_rfl) (by decide)
theorem codeAt_260 : CodeAt image (pcOf 260) seg260 :=
  codeAt_layout code_eq layout_ok (i := 50) (by kernel_rfl) (by decide)
theorem codeAt_263 : CodeAt image (pcOf 263) seg263 :=
  codeAt_layout code_eq layout_ok (i := 51) (by kernel_rfl) (by decide)

end SigGolfCandidate.Expand
