-- Generated by the isolated counterpack RV64 design script.
import SigGolfCandidate.Expand.CounterUnpackLayout

namespace SigGolfCandidate.Expand

set_option maxRecDepth 16384

/-- Packed-tail expander segment at instruction 171, 5 words. -/
def seg171Packed : List (BitVec 32) := [
  0x00004337#32, 0xb6030313#32, 0x000013b7#32, 0x17838393#32, 0x0d400b13#32
]
/-- Packed-tail expander segment at instruction 176, 6 words. -/
def seg176Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 182, 5 words. -/
def seg182Packed : List (BitVec 32) := [
  0x00004337#32, 0xeb030313#32, 0x000013b7#32, 0x4c838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 187, 6 words. -/
def seg187Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 193, 5 words. -/
def seg193Packed : List (BitVec 32) := [
  0x00004337#32, 0x1b030313#32, 0x000013b7#32, 0x7c838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 198, 6 words. -/
def seg198Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 204, 5 words. -/
def seg204Packed : List (BitVec 32) := [
  0x00004337#32, 0x4b030313#32, 0x000023b7#32, 0xac838393#32, 0x0c000b13#32
]
/-- Packed-tail expander segment at instruction 209, 6 words. -/
def seg209Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 215, 5 words. -/
def seg215Packed : List (BitVec 32) := [
  0x00004337#32, 0x7b030313#32, 0x000023b7#32, 0xdc838393#32, 0x0bc00b13#32
]
/-- Packed-tail expander segment at instruction 220, 6 words. -/
def seg220Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]
/-- Packed-tail expander segment at instruction 226, 55 words. -/
def seg226Packed : List (BitVec 32) := [
  0x00033583#32, 0x00836603#32, 0x00c35683#32, 0x00e6d713#32, 0x0c071c63#32, 0x02069693#32, 0x00d66633#32, 0x02a59713#32,
  0x02a75713#32, 0x00e3a023#32, 0x0165d713#32, 0x02a71713#32, 0x02a75713#32, 0x00e3a223#32, 0x02c5d713#32, 0x00367793#32,
  0x01479793#32, 0x00f76733#32, 0x00e3a423#32, 0x00265713#32, 0x02a71713#32, 0x02a75713#32, 0x00e3a623#32, 0x01865713#32,
  0x00e3a823#32, 0x0780006f#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32,
  0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32, 0x00000013#32
]
end SigGolfCandidate.Expand
