import SigGolfCandidate.Packed.SignClone.PackStep

/-! ### cloned PackC0 -/
-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.

namespace SigGolfCandidate.Packed.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 0: instructions 675 .. 1113, signature dwords 0 .. 79. -/

set_option maxRecDepth 100000

sym_block blk675 := symRun { noAlias := true } seg675 (pcOf 675) 440

kernel_theorem blk675_pc : ∀ t : MachineState, (blk675.res.toState t).pc = pcOf 1114
kernel_theorem blk675_addrs : ∀ t : MachineState, blk675.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 0 + 8 * i))).reverse
kernel_theorem blk675_words : ∀ t : MachineState,
    (blk675.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 0)) 80 =
      ((packTab.drop 0).take 80).map (packDW t)

theorem packStep_675 : PackStep 675 1114 0 80 439 :=
  packStep_of blk675 codeAt_675 rfl blk675_pc rfl rfl blk675_words blk675_addrs (by norm_num)

end SigGolfCandidate.Packed.Sign

/-! ### cloned PackC1 -/
-- Generated by SigGolfCandidate/Sign/gen_code.py. Do not edit.

namespace SigGolfCandidate.Packed.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 1: instructions 1114 .. 1394, signature dwords 80 .. 159. -/

set_option maxRecDepth 100000

sym_block blk1114 := symRun { noAlias := true } seg1114 (pcOf 1114) 282

kernel_theorem blk1114_pc : ∀ t : MachineState, (blk1114.res.toState t).pc = pcOf 1395
kernel_theorem blk1114_addrs : ∀ t : MachineState, blk1114.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 80).map (fun i => BitVec.ofNat 64 (packD + 8 * 80 + 8 * i))).reverse
kernel_theorem blk1114_words : ∀ t : MachineState,
    (blk1114.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 80)) 80 =
      ((packTab.drop 80).take 80).map (packDW t)

theorem packStep_1114 : PackStep 1114 1395 80 80 281 :=
  packStep_of blk1114 codeAt_1114 rfl blk1114_pc rfl rfl blk1114_words blk1114_addrs (by norm_num)

end SigGolfCandidate.Packed.Sign

