-- Generated by w4sign/gen_code.py from w4img/sign.lst. Do not edit.
import SigGolfCandidate.Sign.Base
import SigGolfCandidate.Submission

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

set_option maxRecDepth 16384

/-- instructions 0 .. 54: ld ra, 128(x0); sd ra, 1728(x0); sd ra, 1600(x0); ld ra, 64(x0); sd ra, 1632(x0); ld ra, 136(x0) ... -/
def seg0 : List (BitVec 32) := [0x08003083#32, 0x6c103023#32, 0x64103023#32, 0x04003083#32, 0x66103023#32, 0x08803083#32, 0x6c103423#32, 0x64103423#32, 0x04803083#32, 0x66103423#32, 0x09003083#32, 0x6c103823#32, 0x64103823#32, 0x05003083#32, 0x66103823#32, 0x09803083#32, 0x6c103c23#32, 0x64103c23#32, 0x05803083#32, 0x66103c23#32, 0x70100193#32, 0x62302023#32, 0x000011b7#32, 0xc0118193#32, 0x02303023#32, 0x00005eb7#32, 0xb00e8e93#32, 0x000eb683#32, 0x008eb703#32, 0x010eb783#32, 0x018eb803#32, 0x00005eb7#32, 0xb00e8e93#32, 0x000011b7#32, 0xe0118193#32, 0xfe3eb023#32, 0x08003083#32, 0x001eb023#32, 0x08803083#32, 0x001eb423#32, 0x09003083#32, 0x001eb823#32, 0x09803083#32, 0x001ebc23#32, 0x000151b7#32, 0xb0018193#32, 0x0001b023#32, 0x0001b423#32, 0x0001b823#32, 0x0001bc23#32, 0xfe0e8513#32, 0x000105b7#32, 0x04058593#32, 0x16000613#32, 0x00000073#32]
/-- instructions 55 .. 56: ld ra, 352(x0); bne ra, a3, +344 -/
def seg55 : List (BitVec 32) := [0x16003083#32, 0x14d09c63#32]
/-- instructions 57 .. 58: ld ra, 360(x0); bne ra, a4, +336 -/
def seg57 : List (BitVec 32) := [0x16803083#32, 0x14e09863#32]
/-- instructions 59 .. 60: ld ra, 368(x0); bne ra, a5, +328 -/
def seg59 : List (BitVec 32) := [0x17003083#32, 0x14f09463#32]
/-- instructions 61 .. 62: ld ra, 376(x0); bne ra, a6, +320 -/
def seg61 : List (BitVec 32) := [0x17803083#32, 0x15009063#32]
/-- instructions 63 .. 64: load the trial limit and jump to the randomizer packer (754). -/
def seg63 : List (BitVec 32) := [0x001003b7#32, 0x2c90006f#32]
/-- instructions 65 .. 69 (dig_loop): store the trial at 0x7bc, then hash 64 bytes at 0x780. -/
def seg65 : List (BitVec 32) := [0x7a602e23#32, 0x78000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 70 .. 77: ld ra, 320(x0); ld sp, 328(x0); sd ra, 48(x0); sd sp, 56(x0); addi a0, x0, 32; addi a1, x0, 64 ... -/
def seg70 : List (BitVec 32) := [0x14003083#32, 0x14803103#32, 0x02103823#32, 0x02203c23#32, 0x02000513#32, 0x04000593#32, 0x16000613#32, 0x00000073#32]
/-- instructions 78 .. 81: lui tp, 0x400; sd tp, 1880(x0); addi s0, x0, 0; addi a6, x0, 34 -/
def seg78 : List (BitVec 32) := [0x00400237#32, 0x74403c23#32, 0x00000413#32, 0x02200813#32]
/-- instructions 82 .. 88: srli a3, a6, 6; slli a3, a3, 3; ld s1, 352(a3); srl s1, s1, a6; andi tp, a6, 63; addi a7, x0, 50 ... -/
def seg82 : List (BitVec 32) := [0x00685693#32, 0x00369693#32, 0x1606b483#32, 0x0104d4b3#32, 0x03f87213#32, 0x03200893#32, 0x0048dc63#32]
/-- instructions 89 .. 93: ld a4, 360(a3); addi a7, x0, 64; sub a7, a7, tp; sll a4, a4, a7; or s1, s1, a4 -/
def seg89 : List (BitVec 32) := [0x1686b703#32, 0x04000893#32, 0x404888b3#32, 0x01171733#32, 0x00e4e4b3#32]
/-- instructions 94 .. 103: slli s1, s1, 50; srli s1, s1, 50; slli s1, s1, 8; slli gp, s0, 3; or s1, s1, gp; sd s1, 1760(gp) ... -/
def seg94 : List (BitVec 32) := [0x03249493#32, 0x0324d493#32, 0x00849493#32, 0x00341193#32, 0x0034e4b3#32, 0x6e91b023#32, 0x00e80813#32, 0x00140413#32, 0x00f00893#32, 0xfb1416e3#32]
/-- instructions 104 .. 104: addi s0, x0, 1 -/
def seg104 : List (BitVec 32) := [0x00100413#32]
/-- instructions 105 .. 107: slli a4, s0, 3; addi a4, a4, 1760; ld s1, 0(a4) -/
def seg105 : List (BitVec 32) := [0x00341713#32, 0x6e070713#32, 0x00073483#32]
/-- instructions 108 .. 109: addi a7, x0, 1760; beq a4, a7, +24 -/
def seg108 : List (BitVec 32) := [0x6e000893#32, 0x01170c63#32]
/-- instructions 110 .. 111: ld a3, -8(a4); bgeu s1, a3, +16 -/
def seg110 : List (BitVec 32) := [0xff873683#32, 0x00d4f863#32]
/-- instructions 112 .. 114: sd a3, 0(a4); addi a4, a4, -8; jal x0, -24 -/
def seg112 : List (BitVec 32) := [0x00d73023#32, 0xff870713#32, 0xfe9ff06f#32]
/-- instructions 115 .. 118: sd s1, 0(a4); addi s0, s0, 1; addi a7, x0, 15; bne s0, a7, -52 -/
def seg115 : List (BitVec 32) := [0x00973023#32, 0x00140413#32, 0x00f00893#32, 0xfd1416e3#32]
/-- instructions 119 .. 120: addi s0, x0, 0; addi a5, x0, 0 -/
def seg119 : List (BitVec 32) := [0x00000413#32, 0x00000793#32]
/-- instructions 121 .. 127: slli gp, s0, 3; ld s1, 1760(gp); srli s1, s1, 8; ld a3, 1768(gp); srli a3, a3, 8; xor s1, s1, a3 ... -/
def seg121 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x00d4c4b3#32, 0x02048463#32]
/-- instructions 128 .. 130: srli s1, s1, 1; addi a5, a5, 1; bne s1, x0, -8 -/
def seg128 : List (BitVec 32) := [0x0014d493#32, 0x00178793#32, 0xfe049ce3#32]
/-- instructions 131 .. 133: addi s0, s0, 1; addi a7, x0, 14; bne s0, a7, -48 -/
def seg131 : List (BitVec 32) := [0x00140413#32, 0x00e00893#32, 0xfd1418e3#32]
/-- instructions 134 .. 135: addi a7, x0, 132; blt a7, a5, +8 -/
def seg134 : List (BitVec 32) := [0x08400893#32, 0x00f8c463#32]
/-- instructions 136 .. 136: jal x0, +36 -/
def seg136 : List (BitVec 32) := [0x0240006f#32]
/-- instructions 137 .. 138: addi t1, t1, 1; bne t1, t2, -292 -/
def seg137 : List (BitVec 32) := [0x00130313#32, 0xec731ee3#32]
/-- instructions 139 .. 141: addi t0, x0, 1; addi a0, x0, 1; ecall -/
def seg139 : List (BitVec 32) := [0x00100293#32, 0x00100513#32, 0x00000073#32]
/-- instructions 142 .. 144: addi t0, x0, 1; addi a0, x0, 1; ecall -/
def seg142 : List (BitVec 32) := [0x00100293#32, 0x00100513#32, 0x00000073#32]
/-- instructions 145 .. 178: lui s2, 0x3; addi s2, s2, 768; ld ra, 48(x0); ld sp, 56(x0); sd ra, 0(s2); sd sp, 8(s2) ... -/
def seg145 : List (BitVec 32) := [0x00003937#32, 0x30090913#32, 0x03003083#32, 0x03803103#32, 0x00193023#32, 0x00293423#32, 0x16003b03#32, 0x01eb1b13#32, 0x01eb5b13#32, 0x020b5193#32, 0x01819193#32, 0x00001eb7#32, 0x801e8e93#32, 0x003eeeb3#32, 0x6bd03023#32, 0x6b602423#32, 0x00001eb7#32, 0x901e8e93#32, 0x003eeeb3#32, 0x0dd03023#32, 0x0d602423#32, 0x00001eb7#32, 0xa01e8e93#32, 0x003eeeb3#32, 0x1dd03023#32, 0x1d602423#32, 0x000309b7#32, 0x000048b7#32, 0x00003937#32, 0x31090913#32, 0x6e000a13#32, 0x000a3683#32, 0x0086d693#32, 0x00000493#32]
/-- instructions 179 .. 180: andi gp, s1, 1; bne gp, x0, +28 -/
def seg179 : List (BitVec 32) := [0x0014f193#32, 0x00019e63#32]
/-- instructions 181 .. 186: srli gp, s1, 1; sw gp, 1708(x0); addi a0, x0, 1696; addi a1, x0, 64; addi a2, x0, 320; ecall -/
def seg181 : List (BitVec 32) := [0x0014d193#32, 0x6a302623#32, 0x6a000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 187 .. 193: andi gp, s1, 1; slli gp, gp, 4; ld ra, 320(gp); ld sp, 328(gp); sd ra, 224(x0); sd sp, 232(x0) ... -/
def seg187 : List (BitVec 32) := [0x0014f193#32, 0x00419193#32, 0x1401b083#32, 0x1481b103#32, 0x0e103023#32, 0x0e203423#32, 0x02d49263#32]
/-- instructions 194 .. 201: ld ra, 224(x0); ld sp, 232(x0); sd ra, 0(s2); sd sp, 8(s2); addi s2, s2, 16; addi s4, s4, 8 ... -/
def seg194 : List (BitVec 32) := [0x0e003083#32, 0x0e803103#32, 0x00193023#32, 0x00293423#32, 0x01090913#32, 0x008a0a13#32, 0x000a3683#32, 0x0086d693#32]
/-- instructions 202 .. 207: sw s1, 204(x0); addi a0, x0, 192; addi a1, x0, 64; slli gp, s1, 4; add a2, s3, gp; ecall -/
def seg202 : List (BitVec 32) := [0x0c902623#32, 0x0c000513#32, 0x04000593#32, 0x00449193#32, 0x00398633#32, 0x00000073#32]
/-- instructions 208 .. 209: addi s1, s1, 1; bne s1, a7, -120 -/
def seg208 : List (BitVec 32) := [0x00148493#32, 0xf91494e3#32]
/-- instructions 210 .. 210: addi a5, x0, 1 -/
def seg210 : List (BitVec 32) := [0x00100793#32]
/-- instructions 211 .. 214: slli gp, a7, 4; add s9, s3, gp; srli a7, a7, 1; addi a6, x0, 0 -/
def seg211 : List (BitVec 32) := [0x00489193#32, 0x00398cb3#32, 0x0018d893#32, 0x00000813#32]
/-- instructions 215 .. 231: add sp, a6, a7; sw sp, 460(x0); slli gp, a6, 5; add gp, gp, s3; ld ra, 0(gp); sd ra, 480(x0) ... -/
def seg215 : List (BitVec 32) := [0x01180133#32, 0x1c202623#32, 0x00581193#32, 0x013181b3#32, 0x0001b083#32, 0x1e103023#32, 0x0081b083#32, 0x1e103423#32, 0x0101b083#32, 0x1e103823#32, 0x0181b083#32, 0x1e103c23#32, 0x1c000513#32, 0x04000593#32, 0x00481193#32, 0x003c8633#32, 0x00000073#32]
/-- instructions 232 .. 233: addi a6, a6, 1; bne a6, a7, -72 -/
def seg232 : List (BitVec 32) := [0x00180813#32, 0xfb181ce3#32]
/-- instructions 234 .. 237: addi s3, s9, 0; addi a5, a5, 1; addi gp, x0, 15; bne a5, gp, -104 -/
def seg234 : List (BitVec 32) := [0x000c8993#32, 0x00178793#32, 0x00f00193#32, 0xf8379ce3#32]
/-- instructions 238 .. 248: ld ra, 0(s3); ld sp, 8(s3); sd ra, 288(x0); sd sp, 296(x0); lui t4, 0x3; addi t4, t4, 1024 ... -/
def seg238 : List (BitVec 32) := [0x0009b083#32, 0x0089b103#32, 0x12103023#32, 0x12203423#32, 0x00003eb7#32, 0x400e8e93#32, 0x000b0f37#32, 0x76003023#32, 0x76000b93#32, 0x00004c37#32, 0x00000413#32]
/-- instructions 249 .. 255: slli gp, s0, 3; ld s1, 1760(gp); srli s1, s1, 8; ld a3, 1768(gp); srli a3, a3, 8; xor a3, a3, s1 ... -/
def seg249 : List (BitVec 32) := [0x00341193#32, 0x6e01b483#32, 0x0084d493#32, 0x6e81b683#32, 0x0086d693#32, 0x0096c6b3#32, 0xfff00a13#32]
/-- instructions 256 .. 258: srli a3, a3, 1; addi s4, s4, 1; bne a3, x0, -8 -/
def seg256 : List (BitVec 32) := [0x0016d693#32, 0x001a0a13#32, 0xfe069ce3#32]
/-- instructions 259 .. 262: or s2, s1, s8; andi a5, s2, 1; addi s3, x0, 0; addi s5, x0, 0 -/
def seg259 : List (BitVec 32) := [0x0184e933#32, 0x00197793#32, 0x00000993#32, 0x00000a93#32]
/-- instructions 263 .. 263: bge s3, s4, +100 -/
def seg263 : List (BitVec 32) := [0x0749d263#32]
/-- instructions 264 .. 265: ld gp, 0(s7); bne gp, s2, +24 -/
def seg264 : List (BitVec 32) := [0x000bb183#32, 0x01219c63#32]
/-- instructions 266 .. 270: addi s5, x0, 0; addi s7, s7, -8; srli s2, s2, 1; andi a5, s2, 1; jal x0, +64 -/
def seg266 : List (BitVec 32) := [0x00000a93#32, 0xff8b8b93#32, 0x00195913#32, 0x00197793#32, 0x0400006f#32]
/-- instructions 271 .. 285: addi s9, x0, 14; sub s9, s9, s3; addi s10, x0, 3; sll s10, s10, s9; xori s9, s2, 1; sub s9, s9, s10 ... -/
def seg271 : List (BitVec 32) := [0x00e00c93#32, 0x413c8cb3#32, 0x00300d13#32, 0x019d1d33#32, 0x00194c93#32, 0x41ac8cb3#32, 0x004c9c93#32, 0x01ec8cb3#32, 0x000cb083#32, 0x008cb103#32, 0x001eb023#32, 0x002eb423#32, 0x010e8e93#32, 0x001a8a93#32, 0x00195913#32]
/-- instructions 286 .. 287: addi s3, s3, 1; jal x0, -96 -/
def seg286 : List (BitVec 32) := [0x00198993#32, 0xfa1ff06f#32]
/-- instructions 288 .. 289: addi a7, x0, 14; beq s0, a7, +16 -/
def seg288 : List (BitVec 32) := [0x00e00893#32, 0x01140863#32]
/-- instructions 290 .. 292: xori gp, s2, 1; addi s7, s7, 8; sd gp, 0(s7) -/
def seg290 : List (BitVec 32) := [0x00194193#32, 0x008b8b93#32, 0x003bb023#32]
/-- instructions 293 .. 295: addi s0, s0, 1; addi a7, x0, 15; bne s0, a7, -184 -/
def seg293 : List (BitVec 32) := [0x00140413#32, 0x00f00893#32, 0xf51414e3#32]
/-- instructions 296 .. 314 (layer_consts): lui t2, 0x400; lui s10, 0xf0f; addi s10, s10, 241; slli s10, s10, 12; addi s10, s10, -241; slli s10, s10, 12 ... -/
def seg296 : List (BitVec 32) := [0x004003b7#32, 0x00f0fd37#32, 0x0f1d0d13#32, 0x00cd1d13#32, 0xf0fd0d13#32, 0x00cd1d13#32, 0x0f1d0d13#32, 0x00cd1d13#32, 0xf0fd0d13#32, 0x0ff01db7#32, 0xff0d8d93#32, 0x00cd9d93#32, 0x0ffd8d93#32, 0x004d9d93#32, 0x00cd9d93#32, 0x0ffd8d93#32, 0x00500413#32, 0x00001937#32, 0x69890913#32]
/-- instructions 315 .. 316 (layer_loop): addi gp, x0, 4; blt s0, gp, +24 -/
def seg315 : List (BitVec 32) := [0x00400193#32, 0x00344c63#32]
/-- instructions 317 .. 321: slli gp, s0, 2; addi t3, x0, 20; sub t3, t3, gp; addi s1, x0, 4; jal x0, +40 -/
def seg317 : List (BitVec 32) := [0x00241193#32, 0x01400e13#32, 0x403e0e33#32, 0x00400493#32, 0x0280006f#32]
/-- instructions 322 .. 322 (layer_h5): beq s0, x0, +28 -/
def seg322 : List (BitVec 32) := [0x00040e63#32]
/-- instructions 323 .. 328: slli gp, s0, 2; add gp, gp, s0; addi t3, x0, 23; sub t3, t3, gp; addi s1, x0, 5; jal x0, +12 -/
def seg323 : List (BitVec 32) := [0x00241193#32, 0x008181b3#32, 0x01700e13#32, 0x403e0e33#32, 0x00500493#32, 0x00c0006f#32]
/-- instructions 329 .. 330 (layer_h11): addi t3, x0, 23; addi s1, x0, 11 -/
def seg329 : List (BitVec 32) := [0x01700e13#32, 0x00b00493#32]
/-- instructions 331 .. 345 (layer_route): srl a3, s6, t3; addi gp, x0, 1; sll gp, gp, s1; addi gp, gp, -1; and a3, a3, gp; add t4, t3, s1 ... -/
def seg331 : List (BitVec 32) := [0x01cb56b3#32, 0x00100193#32, 0x009191b3#32, 0xfff18193#32, 0x0036f6b3#32, 0x009e0eb3#32, 0x01db5f33#32, 0x02069193#32, 0x003f0fb3#32, 0x01041193#32, 0x40118193#32, 0x10303023#32, 0x11f03423#32, 0x12003c23#32, 0x00000313#32]
/-- instructions 346 .. 350 (enc_loop): sd t1, 304(x0); addi a0, x0, 256; addi a1, x0, 64; addi a2, x0, 320; ecall -/
def seg346 : List (BitVec 32) := [0x12603823#32, 0x10000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 351 .. 371: ld ra, 320(x0); ld sp, 328(x0); srli t3, ra, 4; and t3, t3, s10; and t4, ra, s10; add t3, t3, t4 ... -/
def seg351 : List (BitVec 32) := [0x14003083#32, 0x14803103#32, 0x0040de13#32, 0x01ae7e33#32, 0x01a0feb3#32, 0x01de0e33#32, 0x00415e93#32, 0x01aefeb3#32, 0x01de0e33#32, 0x01a17eb3#32, 0x01de0e33#32, 0x008e5e93#32, 0x01de0e33#32, 0x01be7e33#32, 0x010e5e93#32, 0x01de0e33#32, 0x020e5e93#32, 0x01de0e33#32, 0x3ffe7e13#32, 0xec8e0e13#32, 0x000e1463#32]
/-- instructions 372 .. 372: jal x0, +24 -/
def seg372 : List (BitVec 32) := [0x0180006f#32]
/-- instructions 373 .. 374 (enc_next): addi t1, t1, 1; bne t1, t2, -112 -/
def seg373 : List (BitVec 32) := [0x00130313#32, 0xf87318e3#32]
/-- instructions 375 .. 377 (fail_enc): addi t0, x0, 1; addi a0, x0, 1; ecall -/
def seg375 : List (BitVec 32) := [0x00100293#32, 0x00100513#32, 0x00000073#32]
/-- instructions 378 .. 474 (enc_ok): sw t1, 4(s2); addi a4, x0, 1920; andi gp, ra, 15; sd gp, 0(a4); srli gp, ra, 4; andi gp, gp, 15 ... -/
def seg378 : List (BitVec 32) := [0x00692223#32, 0x78000713#32, 0x00f0f193#32, 0x00373023#32, 0x0040d193#32, 0x00f1f193#32, 0x00373423#32, 0x0080d193#32, 0x00f1f193#32, 0x00373823#32, 0x00c0d193#32, 0x00f1f193#32, 0x00373c23#32, 0x0100d193#32, 0x00f1f193#32, 0x02373023#32, 0x0140d193#32, 0x00f1f193#32, 0x02373423#32, 0x0180d193#32, 0x00f1f193#32, 0x02373823#32, 0x01c0d193#32, 0x00f1f193#32, 0x02373c23#32, 0x0200d193#32, 0x00f1f193#32, 0x04373023#32, 0x0240d193#32, 0x00f1f193#32, 0x04373423#32, 0x0280d193#32, 0x00f1f193#32, 0x04373823#32, 0x02c0d193#32, 0x00f1f193#32, 0x04373c23#32, 0x0300d193#32, 0x00f1f193#32, 0x06373023#32, 0x0340d193#32, 0x00f1f193#32, 0x06373423#32, 0x0380d193#32, 0x00f1f193#32, 0x06373823#32, 0x03c0d193#32, 0x00f1f193#32, 0x06373c23#32, 0x00f17193#32, 0x08373023#32, 0x00415193#32, 0x00f1f193#32, 0x08373423#32, 0x00815193#32, 0x00f1f193#32, 0x08373823#32, 0x00c15193#32, 0x00f1f193#32, 0x08373c23#32, 0x01015193#32, 0x00f1f193#32, 0x0a373023#32, 0x01415193#32, 0x00f1f193#32, 0x0a373423#32, 0x01815193#32, 0x00f1f193#32, 0x0a373823#32, 0x01c15193#32, 0x00f1f193#32, 0x0a373c23#32, 0x02015193#32, 0x00f1f193#32, 0x0c373023#32, 0x02415193#32, 0x00f1f193#32, 0x0c373423#32, 0x02815193#32, 0x00f1f193#32, 0x0c373823#32, 0x02c15193#32, 0x00f1f193#32, 0x0c373c23#32, 0x03015193#32, 0x00f1f193#32, 0x0e373023#32, 0x03415193#32, 0x00f1f193#32, 0x0e373423#32, 0x03815193#32, 0x00f1f193#32, 0x0e373823#32, 0x03c15193#32, 0x00f1f193#32, 0x0e373c23#32, 0x20040263#32]
/-- instructions 475 .. 487: lui s3, 0xb0; slli gp, s0, 16; ori t4, gp, 1; sw t4, 1696(x0); ori t4, gp, 257; sw t4, 192(x0) ... -/
def seg475 : List (BitVec 32) := [0x000b09b7#32, 0x01041193#32, 0x0011ee93#32, 0x6bd02023#32, 0x1011ee93#32, 0x0dd02023#32, 0x2011ee93#32, 0x35d03023#32, 0x00100193#32, 0x009198b3#32, 0x00000a13#32, 0x0e003023#32, 0x0e003423#32]
/-- instructions 488 .. 494 (tb_leaf_loop): slli gp, s4, 32; or gp, gp, t5; sd gp, 1704(x0); sd gp, 200(x0); sd gp, 840(x0); addi s5, x0, 0 ... -/
def seg488 : List (BitVec 32) := [0x020a1193#32, 0x01e1e1b3#32, 0x6a303423#32, 0x0c303423#32, 0x34303423#32, 0x00000a93#32, 0x00000c13#32]
/-- instructions 495 .. 496 (tb_chain_loop): andi gp, s5, 1; bne gp, x0, +28 -/
def seg495 : List (BitVec 32) := [0x001af193#32, 0x00019e63#32]
/-- instructions 497 .. 502: srli gp, s5, 1; sw gp, 1700(x0); addi a0, x0, 1696; addi a1, x0, 64; addi a2, x0, 320; ecall -/
def seg497 : List (BitVec 32) := [0x001ad193#32, 0x6a302223#32, 0x6a000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 503 .. 514 (prf_have_4): andi gp, s5, 1; slli gp, gp, 4; ld ra, 320(gp); ld sp, 328(gp); sd ra, 240(x0); sd sp, 248(x0) ... -/
def seg503 : List (BitVec 32) := [0x001af193#32, 0x00419193#32, 0x1401b083#32, 0x1481b103#32, 0x0e103823#32, 0x0e203c23#32, 0x0c000513#32, 0x0f000613#32, 0x00000b93#32, 0x003a9193#32, 0x7801bc83#32, 0x02da1063#32]
/-- instructions 515 .. 515: bne s7, s9, +28 -/
def seg515 : List (BitVec 32) := [0x019b9e63#32]
/-- instructions 516 .. 521: slli gp, s5, 4; add gp, gp, s2; ld ra, 240(x0); ld sp, 248(x0); sd ra, 8(gp); sd sp, 16(gp) -/
def seg516 : List (BitVec 32) := [0x004a9193#32, 0x012181b3#32, 0x0f003083#32, 0x0f803103#32, 0x0011b423#32, 0x0021b823#32]
/-- instructions 522 .. 529 (tb_cap0,tb_step_loop): addi s7, s7, 1; srli gp, s8, 4; slli gp, gp, 8; andi t4, s8, 15; or gp, gp, t4; sw gp, 196(x0) ... -/
def seg522 : List (BitVec 32) := [0x001b8b93#32, 0x004c5193#32, 0x00819193#32, 0x00fc7e93#32, 0x01d1e1b3#32, 0x0c302223#32, 0x0c000513#32, 0x00000073#32]
/-- instructions 530 .. 531: addi s8, s8, 1; bne s4, a3, +32 -/
def seg530 : List (BitVec 32) := [0x001c0c13#32, 0x02da1063#32]
/-- instructions 532 .. 532: bne s7, s9, +28 -/
def seg532 : List (BitVec 32) := [0x019b9e63#32]
/-- instructions 533 .. 538: slli gp, s5, 4; add gp, gp, s2; ld ra, 240(x0); ld sp, 248(x0); sd ra, 8(gp); sd sp, 16(gp) -/
def seg533 : List (BitVec 32) := [0x004a9193#32, 0x012181b3#32, 0x0f003083#32, 0x0f803103#32, 0x0011b423#32, 0x0021b823#32]
/-- instructions 539 .. 540 (tb_cap1): addi gp, x0, 15; bne s7, gp, -72 -/
def seg539 : List (BitVec 32) := [0x00f00193#32, 0xfa3b9ce3#32]
/-- instructions 541 .. 549: addi s8, s8, 1; slli gp, s5, 4; ld ra, 240(x0); ld sp, 248(x0); sd ra, 864(gp); sd sp, 872(gp) ... -/
def seg541 : List (BitVec 32) := [0x001c0c13#32, 0x004a9193#32, 0x0f003083#32, 0x0f803103#32, 0x3611b023#32, 0x3621b423#32, 0x001a8a93#32, 0x02000193#32, 0xf23a94e3#32]
/-- instructions 550 .. 554: addi a0, x0, 832; addi a1, x0, 576; slli gp, s4, 4; add a2, s3, gp; ecall -/
def seg550 : List (BitVec 32) := [0x34000513#32, 0x24000593#32, 0x004a1193#32, 0x00398633#32, 0x00000073#32]
/-- instructions 555 .. 556: addi s4, s4, 1; bne s4, a7, -272 -/
def seg555 : List (BitVec 32) := [0x001a0a13#32, 0xef1a18e3#32]
/-- instructions 557 .. 557: addi a5, x0, 1 -/
def seg557 : List (BitVec 32) := [0x00100793#32]
/-- instructions 558 .. 574 (tb_level_loop): addi gp, a5, -1; srl gp, a3, gp; xori gp, gp, 1; slli gp, gp, 4; add gp, gp, s3; ld ra, 0(gp) ... -/
def seg558 : List (BitVec 32) := [0xfff78193#32, 0x0036d1b3#32, 0x0011c193#32, 0x00419193#32, 0x013181b3#32, 0x0001b083#32, 0x0081b103#32, 0x00479e93#32, 0x012e8eb3#32, 0x1e1ebc23#32, 0x202eb023#32, 0x01041193#32, 0x3011e193#32, 0x1c303023#32, 0x1de02423#32, 0x0018d893#32, 0x00000813#32]
/-- instructions 575 .. 591 (tb_node_loop): add sp, a6, a7; sw sp, 460(x0); slli gp, a6, 5; add gp, gp, s3; ld ra, 0(gp); sd ra, 480(x0) ... -/
def seg575 : List (BitVec 32) := [0x01180133#32, 0x1c202623#32, 0x00581193#32, 0x013181b3#32, 0x0001b083#32, 0x1e103023#32, 0x0081b083#32, 0x1e103423#32, 0x0101b083#32, 0x1e103823#32, 0x0181b083#32, 0x1e103c23#32, 0x1c000513#32, 0x04000593#32, 0x00481193#32, 0x00398633#32, 0x00000073#32]
/-- instructions 592 .. 593: addi a6, a6, 1; bne a6, a7, -72 -/
def seg592 : List (BitVec 32) := [0x00180813#32, 0xfb181ce3#32]
/-- instructions 594 .. 595: addi a5, a5, 1; bge s1, a5, -148 -/
def seg594 : List (BitVec 32) := [0x00178793#32, 0xf6f4d6e3#32]
/-- instructions 596 .. 602: ld ra, 0(s3); ld sp, 8(s3); sd ra, 288(x0); sd sp, 296(x0); addi s2, s2, -696; addi s0, s0, -1 ... -/
def seg596 : List (BitVec 32) := [0x0009b083#32, 0x0089b103#32, 0x12103023#32, 0x12203423#32, 0xd4890913#32, 0xfff40413#32, 0xb85ff06f#32]
/-- instructions 603 .. 611 (top_layer): addi gp, x0, 1; sd gp, 1696(x0); sd t6, 1704(x0); addi gp, x0, 257; sw gp, 192(x0); sd t6, 200(x0) ... -/
def seg603 : List (BitVec 32) := [0x00100193#32, 0x6a303023#32, 0x6bf03423#32, 0x10100193#32, 0x0c302023#32, 0x0df03423#32, 0x0e003023#32, 0x0e003423#32, 0x00000a93#32]
/-- instructions 612 .. 613 (top_chain_loop): andi gp, s5, 1; bne gp, x0, +28 -/
def seg612 : List (BitVec 32) := [0x001af193#32, 0x00019e63#32]
/-- instructions 614 .. 619: srli gp, s5, 1; sw gp, 1700(x0); addi a0, x0, 1696; addi a1, x0, 64; addi a2, x0, 320; ecall -/
def seg614 : List (BitVec 32) := [0x001ad193#32, 0x6a302223#32, 0x6a000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 620 .. 631 (prf_have_7): andi gp, s5, 1; slli gp, gp, 4; ld ra, 320(gp); ld sp, 328(gp); sd ra, 240(x0); sd sp, 248(x0) ... -/
def seg620 : List (BitVec 32) := [0x001af193#32, 0x00419193#32, 0x1401b083#32, 0x1481b103#32, 0x0e103823#32, 0x0e203c23#32, 0x0c000513#32, 0x0f000613#32, 0x003a9193#32, 0x7801bc83#32, 0x004a9c13#32, 0x00000b93#32]
/-- instructions 632 .. 632 (top_step_loop): beq s7, s9, +44 -/
def seg632 : List (BitVec 32) := [0x039b8663#32]
/-- instructions 633 .. 639: srli gp, s8, 4; slli gp, gp, 8; andi t4, s8, 15; or gp, gp, t4; sw gp, 196(x0); addi a0, x0, 192 ... -/
def seg633 : List (BitVec 32) := [0x004c5193#32, 0x00819193#32, 0x00fc7e93#32, 0x01d1e1b3#32, 0x0c302223#32, 0x0c000513#32, 0x00000073#32]
/-- instructions 640 .. 642: addi s8, s8, 1; addi s7, s7, 1; jal x0, -40 -/
def seg640 : List (BitVec 32) := [0x001c0c13#32, 0x001b8b93#32, 0xfd9ff06f#32]
/-- instructions 643 .. 651 (top_step_done): slli gp, s5, 4; add gp, gp, s2; ld ra, 240(x0); ld sp, 248(x0); sd ra, 8(gp); sd sp, 16(gp) ... -/
def seg643 : List (BitVec 32) := [0x004a9193#32, 0x012181b3#32, 0x0f003083#32, 0x0f803103#32, 0x0011b423#32, 0x0021b823#32, 0x001a8a93#32, 0x02000193#32, 0xf63a92e3#32]
/-- instructions 652 .. 655: lui s3, 0x5; addi s3, s3, -1248; lui a7, 0x8; addi a5, x0, 0 -/
def seg652 : List (BitVec 32) := [0x000059b7#32, 0xb2098993#32, 0x000088b7#32, 0x00000793#32]
/-- instructions 656 .. 667 (top_path_loop): srl a6, a3, a5; xori a6, a6, 1; slli gp, a5, 32; addi gp, gp, 1665; addi gp, gp, 1664; sd gp, 1696(x0) ... -/
def seg656 : List (BitVec 32) := [0x00f6d833#32, 0x00184813#32, 0x02079193#32, 0x68118193#32, 0x68018193#32, 0x6a303023#32, 0x02081193#32, 0x6a303423#32, 0x6a000513#32, 0x04000593#32, 0x14000613#32, 0x00000073#32]
/-- instructions 668 .. 684: slli gp, a6, 4; add gp, gp, s3; slli t4, a5, 4; add t4, t4, s2; ld ra, 0(gp); ld sp, 320(x0) ... -/
def seg668 : List (BitVec 32) := [0x00481193#32, 0x013181b3#32, 0x00479e93#32, 0x012e8eb3#32, 0x0001b083#32, 0x14003103#32, 0x0020c0b3#32, 0x201eb423#32, 0x0081b083#32, 0x14803103#32, 0x0020c0b3#32, 0x201eb823#32, 0x011989b3#32, 0x0018d893#32, 0x00178793#32, 0x00b00193#32, 0xf83798e3#32]
/-- instructions 685 .. 689 (pack_0): lui t1, 0x1; addi t1, t1, -1788; lui t2, 0x4; addi t2, t2, -1184; addi s6, x0, 173 -/
def seg685 : List (BitVec 32) := [0x00001337#32, 0x90430313#32, 0x000043b7#32, 0xb6038393#32, 0x0ad00b13#32]
/-- instructions 690 .. 695 (copy_loop_0): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg690 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 696 .. 700 (pack_1): lui t1, 0x1; addi t1, t1, -1092; lui t2, 0x4; addi t2, t2, -492; addi s6, x0, 149 -/
def seg696 : List (BitVec 32) := [0x00001337#32, 0xbbc30313#32, 0x000043b7#32, 0xe1438393#32, 0x09500b13#32]
/-- instructions 701 .. 706 (copy_loop_1): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg701 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 707 .. 711 (pack_2): lui t1, 0x1; addi t1, t1, -396; lui t2, 0x4; addi t2, t2, 104; addi s6, x0, 149 -/
def seg707 : List (BitVec 32) := [0x00001337#32, 0xe7430313#32, 0x000043b7#32, 0x06838393#32, 0x09500b13#32]
/-- instructions 712 .. 717 (copy_loop_2): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg712 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 718 .. 722 (pack_3): lui t1, 0x1; addi t1, t1, 300; lui t2, 0x4; addi t2, t2, 700; addi s6, x0, 149 -/
def seg718 : List (BitVec 32) := [0x00001337#32, 0x12c30313#32, 0x000043b7#32, 0x2bc38393#32, 0x09500b13#32]
/-- instructions 723 .. 728 (copy_loop_3): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg723 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 729 .. 733 (pack_4): lui t1, 0x1; addi t1, t1, 996; lui t2, 0x4; addi t2, t2, 1296; addi s6, x0, 145 -/
def seg729 : List (BitVec 32) := [0x00001337#32, 0x3e430313#32, 0x000043b7#32, 0x51038393#32, 0x09100b13#32]
/-- instructions 734 .. 739 (copy_loop_4): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg734 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 740 .. 744 (pack_5): lui t1, 0x1; addi t1, t1, 1692; lui t2, 0x4; addi t2, t2, 1876; addi s6, x0, 145 -/
def seg740 : List (BitVec 32) := [0x00001337#32, 0x69c30313#32, 0x000043b7#32, 0x75438393#32, 0x09100b13#32]
/-- instructions 745 .. 750 (copy_loop_5): lwu gp, 0(t1); sw gp, 0(t2); addi t1, t1, 4; addi t2, t2, 4; addi s6, s6, -1; bne s6, x0, -20 -/
def seg745 : List (BitVec 32) := [0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32]
/-- instructions 751 .. 753 (success): addi t0, x0, 1; addi a0, x0, 0; ecall -/
def seg751 : List (BitVec 32) := [0x00100293#32, 0x00000513#32, 0x00000073#32]
/-- instructions 754 .. 796: pack one-block randomizer input in 0x780..0x7bf, back to `dig_loop`. -/
def seg754 : List (BitVec 32) := [0x64003083#32, 0x64803103#32, 0x65003183#32, 0x65803203#32, 0x66003403#32, 0x66803483#32, 0x67003503#32, 0x67803583#32, 0x01009613#32, 0x70166613#32, 0x78c03023#32, 0x0300d613#32, 0x01011693#32, 0x00d66633#32, 0x78c03423#32, 0x03015613#32, 0x01019693#32, 0x00d66633#32, 0x78c03823#32, 0x0301d613#32, 0x01021693#32, 0x02069693#32, 0x0206d693#32, 0x00d66633#32, 0x02041693#32, 0x00d66633#32, 0x78c03c23#32, 0x02045613#32, 0x02049693#32, 0x00d66633#32, 0x7ac03023#32, 0x0204d613#32, 0x02051693#32, 0x00d66633#32, 0x7ac03423#32, 0x02055613#32, 0x02059693#32, 0x00d66633#32, 0x7ac03823#32, 0x0205d613#32, 0x7ac03c23#32, 0x00000313#32, 0xc94ff06f#32]

/-- Segment table of the sign image. -/
def L : Rv.Layout := [(0, seg0), (55, seg55), (57, seg57), (59, seg59), (61, seg61), (63, seg63), (65, seg65), (70, seg70), (78, seg78), (82, seg82), (89, seg89), (94, seg94), (104, seg104), (105, seg105), (108, seg108), (110, seg110), (112, seg112), (115, seg115), (119, seg119), (121, seg121), (128, seg128), (131, seg131), (134, seg134), (136, seg136), (137, seg137), (139, seg139), (142, seg142), (145, seg145), (179, seg179), (181, seg181), (187, seg187), (194, seg194), (202, seg202), (208, seg208), (210, seg210), (211, seg211), (215, seg215), (232, seg232), (234, seg234), (238, seg238), (249, seg249), (256, seg256), (259, seg259), (263, seg263), (264, seg264), (266, seg266), (271, seg271), (286, seg286), (288, seg288), (290, seg290), (293, seg293), (296, seg296), (315, seg315), (317, seg317), (322, seg322), (323, seg323), (329, seg329), (331, seg331), (346, seg346), (351, seg351), (372, seg372), (373, seg373), (375, seg375), (378, seg378), (475, seg475), (488, seg488), (495, seg495), (497, seg497), (503, seg503), (515, seg515), (516, seg516), (522, seg522), (530, seg530), (532, seg532), (533, seg533), (539, seg539), (541, seg541), (550, seg550), (555, seg555), (557, seg557), (558, seg558), (575, seg575), (592, seg592), (594, seg594), (596, seg596), (603, seg603), (612, seg612), (614, seg614), (620, seg620), (632, seg632), (633, seg633), (640, seg640), (643, seg643), (652, seg652), (656, seg656), (668, seg668), (685, seg685), (690, seg690), (696, seg696), (701, seg701), (707, seg707), (712, seg712), (718, seg718), (723, seg723), (729, seg729), (734, seg734), (740, seg740), (745, seg745), (751, seg751), (754, seg754)]

theorem layout_ok : layoutOk 0 L = true := by decide +kernel

/-- The sign image. -/
abbrev image : Image := Images.signImage

theorem image_eq : submission.image .sign = image := rfl

set_option maxHeartbeats 4000000 in
theorem code_eq : image.code = layoutCode L := by decide +kernel

theorem codeAt_0 : CodeAt image (pcOf 0) seg0 :=
  codeAt_layout code_eq layout_ok (i := 0) (by kernel_rfl) (by decide)
theorem codeAt_55 : CodeAt image (pcOf 55) seg55 :=
  codeAt_layout code_eq layout_ok (i := 1) (by kernel_rfl) (by decide)
theorem codeAt_57 : CodeAt image (pcOf 57) seg57 :=
  codeAt_layout code_eq layout_ok (i := 2) (by kernel_rfl) (by decide)
theorem codeAt_59 : CodeAt image (pcOf 59) seg59 :=
  codeAt_layout code_eq layout_ok (i := 3) (by kernel_rfl) (by decide)
theorem codeAt_61 : CodeAt image (pcOf 61) seg61 :=
  codeAt_layout code_eq layout_ok (i := 4) (by kernel_rfl) (by decide)
theorem codeAt_63 : CodeAt image (pcOf 63) seg63 :=
  codeAt_layout code_eq layout_ok (i := 5) (by kernel_rfl) (by decide)
theorem codeAt_65 : CodeAt image (pcOf 65) seg65 :=
  codeAt_layout code_eq layout_ok (i := 6) (by kernel_rfl) (by decide)
theorem codeAt_70 : CodeAt image (pcOf 70) seg70 :=
  codeAt_layout code_eq layout_ok (i := 7) (by kernel_rfl) (by decide)
theorem codeAt_78 : CodeAt image (pcOf 78) seg78 :=
  codeAt_layout code_eq layout_ok (i := 8) (by kernel_rfl) (by decide)
theorem codeAt_82 : CodeAt image (pcOf 82) seg82 :=
  codeAt_layout code_eq layout_ok (i := 9) (by kernel_rfl) (by decide)
theorem codeAt_89 : CodeAt image (pcOf 89) seg89 :=
  codeAt_layout code_eq layout_ok (i := 10) (by kernel_rfl) (by decide)
theorem codeAt_94 : CodeAt image (pcOf 94) seg94 :=
  codeAt_layout code_eq layout_ok (i := 11) (by kernel_rfl) (by decide)
theorem codeAt_104 : CodeAt image (pcOf 104) seg104 :=
  codeAt_layout code_eq layout_ok (i := 12) (by kernel_rfl) (by decide)
theorem codeAt_105 : CodeAt image (pcOf 105) seg105 :=
  codeAt_layout code_eq layout_ok (i := 13) (by kernel_rfl) (by decide)
theorem codeAt_108 : CodeAt image (pcOf 108) seg108 :=
  codeAt_layout code_eq layout_ok (i := 14) (by kernel_rfl) (by decide)
theorem codeAt_110 : CodeAt image (pcOf 110) seg110 :=
  codeAt_layout code_eq layout_ok (i := 15) (by kernel_rfl) (by decide)
theorem codeAt_112 : CodeAt image (pcOf 112) seg112 :=
  codeAt_layout code_eq layout_ok (i := 16) (by kernel_rfl) (by decide)
theorem codeAt_115 : CodeAt image (pcOf 115) seg115 :=
  codeAt_layout code_eq layout_ok (i := 17) (by kernel_rfl) (by decide)
theorem codeAt_119 : CodeAt image (pcOf 119) seg119 :=
  codeAt_layout code_eq layout_ok (i := 18) (by kernel_rfl) (by decide)
theorem codeAt_121 : CodeAt image (pcOf 121) seg121 :=
  codeAt_layout code_eq layout_ok (i := 19) (by kernel_rfl) (by decide)
theorem codeAt_128 : CodeAt image (pcOf 128) seg128 :=
  codeAt_layout code_eq layout_ok (i := 20) (by kernel_rfl) (by decide)
theorem codeAt_131 : CodeAt image (pcOf 131) seg131 :=
  codeAt_layout code_eq layout_ok (i := 21) (by kernel_rfl) (by decide)
theorem codeAt_134 : CodeAt image (pcOf 134) seg134 :=
  codeAt_layout code_eq layout_ok (i := 22) (by kernel_rfl) (by decide)
theorem codeAt_136 : CodeAt image (pcOf 136) seg136 :=
  codeAt_layout code_eq layout_ok (i := 23) (by kernel_rfl) (by decide)
theorem codeAt_137 : CodeAt image (pcOf 137) seg137 :=
  codeAt_layout code_eq layout_ok (i := 24) (by kernel_rfl) (by decide)
theorem codeAt_139 : CodeAt image (pcOf 139) seg139 :=
  codeAt_layout code_eq layout_ok (i := 25) (by kernel_rfl) (by decide)
theorem codeAt_142 : CodeAt image (pcOf 142) seg142 :=
  codeAt_layout code_eq layout_ok (i := 26) (by kernel_rfl) (by decide)
theorem codeAt_145 : CodeAt image (pcOf 145) seg145 :=
  codeAt_layout code_eq layout_ok (i := 27) (by kernel_rfl) (by decide)
theorem codeAt_179 : CodeAt image (pcOf 179) seg179 :=
  codeAt_layout code_eq layout_ok (i := 28) (by kernel_rfl) (by decide)
theorem codeAt_181 : CodeAt image (pcOf 181) seg181 :=
  codeAt_layout code_eq layout_ok (i := 29) (by kernel_rfl) (by decide)
theorem codeAt_187 : CodeAt image (pcOf 187) seg187 :=
  codeAt_layout code_eq layout_ok (i := 30) (by kernel_rfl) (by decide)
theorem codeAt_194 : CodeAt image (pcOf 194) seg194 :=
  codeAt_layout code_eq layout_ok (i := 31) (by kernel_rfl) (by decide)
theorem codeAt_202 : CodeAt image (pcOf 202) seg202 :=
  codeAt_layout code_eq layout_ok (i := 32) (by kernel_rfl) (by decide)
theorem codeAt_208 : CodeAt image (pcOf 208) seg208 :=
  codeAt_layout code_eq layout_ok (i := 33) (by kernel_rfl) (by decide)
theorem codeAt_210 : CodeAt image (pcOf 210) seg210 :=
  codeAt_layout code_eq layout_ok (i := 34) (by kernel_rfl) (by decide)
theorem codeAt_211 : CodeAt image (pcOf 211) seg211 :=
  codeAt_layout code_eq layout_ok (i := 35) (by kernel_rfl) (by decide)
theorem codeAt_215 : CodeAt image (pcOf 215) seg215 :=
  codeAt_layout code_eq layout_ok (i := 36) (by kernel_rfl) (by decide)
theorem codeAt_232 : CodeAt image (pcOf 232) seg232 :=
  codeAt_layout code_eq layout_ok (i := 37) (by kernel_rfl) (by decide)
theorem codeAt_234 : CodeAt image (pcOf 234) seg234 :=
  codeAt_layout code_eq layout_ok (i := 38) (by kernel_rfl) (by decide)
theorem codeAt_238 : CodeAt image (pcOf 238) seg238 :=
  codeAt_layout code_eq layout_ok (i := 39) (by kernel_rfl) (by decide)
theorem codeAt_249 : CodeAt image (pcOf 249) seg249 :=
  codeAt_layout code_eq layout_ok (i := 40) (by kernel_rfl) (by decide)
theorem codeAt_256 : CodeAt image (pcOf 256) seg256 :=
  codeAt_layout code_eq layout_ok (i := 41) (by kernel_rfl) (by decide)
theorem codeAt_259 : CodeAt image (pcOf 259) seg259 :=
  codeAt_layout code_eq layout_ok (i := 42) (by kernel_rfl) (by decide)
theorem codeAt_263 : CodeAt image (pcOf 263) seg263 :=
  codeAt_layout code_eq layout_ok (i := 43) (by kernel_rfl) (by decide)
theorem codeAt_264 : CodeAt image (pcOf 264) seg264 :=
  codeAt_layout code_eq layout_ok (i := 44) (by kernel_rfl) (by decide)
theorem codeAt_266 : CodeAt image (pcOf 266) seg266 :=
  codeAt_layout code_eq layout_ok (i := 45) (by kernel_rfl) (by decide)
theorem codeAt_271 : CodeAt image (pcOf 271) seg271 :=
  codeAt_layout code_eq layout_ok (i := 46) (by kernel_rfl) (by decide)
theorem codeAt_286 : CodeAt image (pcOf 286) seg286 :=
  codeAt_layout code_eq layout_ok (i := 47) (by kernel_rfl) (by decide)
theorem codeAt_288 : CodeAt image (pcOf 288) seg288 :=
  codeAt_layout code_eq layout_ok (i := 48) (by kernel_rfl) (by decide)
theorem codeAt_290 : CodeAt image (pcOf 290) seg290 :=
  codeAt_layout code_eq layout_ok (i := 49) (by kernel_rfl) (by decide)
theorem codeAt_293 : CodeAt image (pcOf 293) seg293 :=
  codeAt_layout code_eq layout_ok (i := 50) (by kernel_rfl) (by decide)
theorem codeAt_296 : CodeAt image (pcOf 296) seg296 :=
  codeAt_layout code_eq layout_ok (i := 51) (by kernel_rfl) (by decide)
theorem codeAt_315 : CodeAt image (pcOf 315) seg315 :=
  codeAt_layout code_eq layout_ok (i := 52) (by kernel_rfl) (by decide)
theorem codeAt_317 : CodeAt image (pcOf 317) seg317 :=
  codeAt_layout code_eq layout_ok (i := 53) (by kernel_rfl) (by decide)
theorem codeAt_322 : CodeAt image (pcOf 322) seg322 :=
  codeAt_layout code_eq layout_ok (i := 54) (by kernel_rfl) (by decide)
theorem codeAt_323 : CodeAt image (pcOf 323) seg323 :=
  codeAt_layout code_eq layout_ok (i := 55) (by kernel_rfl) (by decide)
theorem codeAt_329 : CodeAt image (pcOf 329) seg329 :=
  codeAt_layout code_eq layout_ok (i := 56) (by kernel_rfl) (by decide)
theorem codeAt_331 : CodeAt image (pcOf 331) seg331 :=
  codeAt_layout code_eq layout_ok (i := 57) (by kernel_rfl) (by decide)
theorem codeAt_346 : CodeAt image (pcOf 346) seg346 :=
  codeAt_layout code_eq layout_ok (i := 58) (by kernel_rfl) (by decide)
theorem codeAt_351 : CodeAt image (pcOf 351) seg351 :=
  codeAt_layout code_eq layout_ok (i := 59) (by kernel_rfl) (by decide)
theorem codeAt_372 : CodeAt image (pcOf 372) seg372 :=
  codeAt_layout code_eq layout_ok (i := 60) (by kernel_rfl) (by decide)
theorem codeAt_373 : CodeAt image (pcOf 373) seg373 :=
  codeAt_layout code_eq layout_ok (i := 61) (by kernel_rfl) (by decide)
theorem codeAt_375 : CodeAt image (pcOf 375) seg375 :=
  codeAt_layout code_eq layout_ok (i := 62) (by kernel_rfl) (by decide)
theorem codeAt_378 : CodeAt image (pcOf 378) seg378 :=
  codeAt_layout code_eq layout_ok (i := 63) (by kernel_rfl) (by decide)
theorem codeAt_475 : CodeAt image (pcOf 475) seg475 :=
  codeAt_layout code_eq layout_ok (i := 64) (by kernel_rfl) (by decide)
theorem codeAt_488 : CodeAt image (pcOf 488) seg488 :=
  codeAt_layout code_eq layout_ok (i := 65) (by kernel_rfl) (by decide)
theorem codeAt_495 : CodeAt image (pcOf 495) seg495 :=
  codeAt_layout code_eq layout_ok (i := 66) (by kernel_rfl) (by decide)
theorem codeAt_497 : CodeAt image (pcOf 497) seg497 :=
  codeAt_layout code_eq layout_ok (i := 67) (by kernel_rfl) (by decide)
theorem codeAt_503 : CodeAt image (pcOf 503) seg503 :=
  codeAt_layout code_eq layout_ok (i := 68) (by kernel_rfl) (by decide)
theorem codeAt_515 : CodeAt image (pcOf 515) seg515 :=
  codeAt_layout code_eq layout_ok (i := 69) (by kernel_rfl) (by decide)
theorem codeAt_516 : CodeAt image (pcOf 516) seg516 :=
  codeAt_layout code_eq layout_ok (i := 70) (by kernel_rfl) (by decide)
theorem codeAt_522 : CodeAt image (pcOf 522) seg522 :=
  codeAt_layout code_eq layout_ok (i := 71) (by kernel_rfl) (by decide)
theorem codeAt_530 : CodeAt image (pcOf 530) seg530 :=
  codeAt_layout code_eq layout_ok (i := 72) (by kernel_rfl) (by decide)
theorem codeAt_532 : CodeAt image (pcOf 532) seg532 :=
  codeAt_layout code_eq layout_ok (i := 73) (by kernel_rfl) (by decide)
theorem codeAt_533 : CodeAt image (pcOf 533) seg533 :=
  codeAt_layout code_eq layout_ok (i := 74) (by kernel_rfl) (by decide)
theorem codeAt_539 : CodeAt image (pcOf 539) seg539 :=
  codeAt_layout code_eq layout_ok (i := 75) (by kernel_rfl) (by decide)
theorem codeAt_541 : CodeAt image (pcOf 541) seg541 :=
  codeAt_layout code_eq layout_ok (i := 76) (by kernel_rfl) (by decide)
theorem codeAt_550 : CodeAt image (pcOf 550) seg550 :=
  codeAt_layout code_eq layout_ok (i := 77) (by kernel_rfl) (by decide)
theorem codeAt_555 : CodeAt image (pcOf 555) seg555 :=
  codeAt_layout code_eq layout_ok (i := 78) (by kernel_rfl) (by decide)
theorem codeAt_557 : CodeAt image (pcOf 557) seg557 :=
  codeAt_layout code_eq layout_ok (i := 79) (by kernel_rfl) (by decide)
theorem codeAt_558 : CodeAt image (pcOf 558) seg558 :=
  codeAt_layout code_eq layout_ok (i := 80) (by kernel_rfl) (by decide)
theorem codeAt_575 : CodeAt image (pcOf 575) seg575 :=
  codeAt_layout code_eq layout_ok (i := 81) (by kernel_rfl) (by decide)
theorem codeAt_592 : CodeAt image (pcOf 592) seg592 :=
  codeAt_layout code_eq layout_ok (i := 82) (by kernel_rfl) (by decide)
theorem codeAt_594 : CodeAt image (pcOf 594) seg594 :=
  codeAt_layout code_eq layout_ok (i := 83) (by kernel_rfl) (by decide)
theorem codeAt_596 : CodeAt image (pcOf 596) seg596 :=
  codeAt_layout code_eq layout_ok (i := 84) (by kernel_rfl) (by decide)
theorem codeAt_603 : CodeAt image (pcOf 603) seg603 :=
  codeAt_layout code_eq layout_ok (i := 85) (by kernel_rfl) (by decide)
theorem codeAt_612 : CodeAt image (pcOf 612) seg612 :=
  codeAt_layout code_eq layout_ok (i := 86) (by kernel_rfl) (by decide)
theorem codeAt_614 : CodeAt image (pcOf 614) seg614 :=
  codeAt_layout code_eq layout_ok (i := 87) (by kernel_rfl) (by decide)
theorem codeAt_620 : CodeAt image (pcOf 620) seg620 :=
  codeAt_layout code_eq layout_ok (i := 88) (by kernel_rfl) (by decide)
theorem codeAt_632 : CodeAt image (pcOf 632) seg632 :=
  codeAt_layout code_eq layout_ok (i := 89) (by kernel_rfl) (by decide)
theorem codeAt_633 : CodeAt image (pcOf 633) seg633 :=
  codeAt_layout code_eq layout_ok (i := 90) (by kernel_rfl) (by decide)
theorem codeAt_640 : CodeAt image (pcOf 640) seg640 :=
  codeAt_layout code_eq layout_ok (i := 91) (by kernel_rfl) (by decide)
theorem codeAt_643 : CodeAt image (pcOf 643) seg643 :=
  codeAt_layout code_eq layout_ok (i := 92) (by kernel_rfl) (by decide)
theorem codeAt_652 : CodeAt image (pcOf 652) seg652 :=
  codeAt_layout code_eq layout_ok (i := 93) (by kernel_rfl) (by decide)
theorem codeAt_656 : CodeAt image (pcOf 656) seg656 :=
  codeAt_layout code_eq layout_ok (i := 94) (by kernel_rfl) (by decide)
theorem codeAt_668 : CodeAt image (pcOf 668) seg668 :=
  codeAt_layout code_eq layout_ok (i := 95) (by kernel_rfl) (by decide)
theorem codeAt_685 : CodeAt image (pcOf 685) seg685 :=
  codeAt_layout code_eq layout_ok (i := 96) (by kernel_rfl) (by decide)
theorem codeAt_690 : CodeAt image (pcOf 690) seg690 :=
  codeAt_layout code_eq layout_ok (i := 97) (by kernel_rfl) (by decide)
theorem codeAt_696 : CodeAt image (pcOf 696) seg696 :=
  codeAt_layout code_eq layout_ok (i := 98) (by kernel_rfl) (by decide)
theorem codeAt_701 : CodeAt image (pcOf 701) seg701 :=
  codeAt_layout code_eq layout_ok (i := 99) (by kernel_rfl) (by decide)
theorem codeAt_707 : CodeAt image (pcOf 707) seg707 :=
  codeAt_layout code_eq layout_ok (i := 100) (by kernel_rfl) (by decide)
theorem codeAt_712 : CodeAt image (pcOf 712) seg712 :=
  codeAt_layout code_eq layout_ok (i := 101) (by kernel_rfl) (by decide)
theorem codeAt_718 : CodeAt image (pcOf 718) seg718 :=
  codeAt_layout code_eq layout_ok (i := 102) (by kernel_rfl) (by decide)
theorem codeAt_723 : CodeAt image (pcOf 723) seg723 :=
  codeAt_layout code_eq layout_ok (i := 103) (by kernel_rfl) (by decide)
theorem codeAt_729 : CodeAt image (pcOf 729) seg729 :=
  codeAt_layout code_eq layout_ok (i := 104) (by kernel_rfl) (by decide)
theorem codeAt_734 : CodeAt image (pcOf 734) seg734 :=
  codeAt_layout code_eq layout_ok (i := 105) (by kernel_rfl) (by decide)
theorem codeAt_740 : CodeAt image (pcOf 740) seg740 :=
  codeAt_layout code_eq layout_ok (i := 106) (by kernel_rfl) (by decide)
theorem codeAt_745 : CodeAt image (pcOf 745) seg745 :=
  codeAt_layout code_eq layout_ok (i := 107) (by kernel_rfl) (by decide)
theorem codeAt_751 : CodeAt image (pcOf 751) seg751 :=
  codeAt_layout code_eq layout_ok (i := 108) (by kernel_rfl) (by decide)
theorem codeAt_754 : CodeAt image (pcOf 754) seg754 :=
  codeAt_layout code_eq layout_ok (i := 109) (by kernel_rfl) (by decide)

end SigGolfCandidate.Sign
