-- Generated by the isolated counterpack RV64 design script.
import SigGolfCandidate.Sign.CounterPackLayout

namespace SigGolfCandidate.Sign

set_option maxRecDepth 16384

/-- Redirect the old proven pack to the aligned body/tail appendix; PCs 2844..2886 remain unchanged. -/
def seg2841Packed : List (BitVec 32) := [0x0b80006f#32, 0x00000013#32, 0x00000013#32]

/-- Packed-tail signer body setup at instruction 2887, 5 words. -/
def seg2887Packed : List (BitVec 32) := [
  0x00001337#32, 0x90830313#32, 0x000043b7#32, 0xb6038393#32, 0x0d400b13#32
]

/-- Packed-tail signer body loop at instruction 2892, 6 words. -/
def seg2892Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2898, 5 words. -/
def seg2898Packed : List (BitVec 32) := [
  0x00001337#32, 0xc6030313#32, 0x000043b7#32, 0xeb038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2903, 6 words. -/
def seg2903Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2909, 5 words. -/
def seg2909Packed : List (BitVec 32) := [
  0x00001337#32, 0xfb830313#32, 0x000043b7#32, 0x1b038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2914, 6 words. -/
def seg2914Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2920, 5 words. -/
def seg2920Packed : List (BitVec 32) := [
  0x00001337#32, 0x31030313#32, 0x000043b7#32, 0x4b038393#32, 0x0c000b13#32
]

/-- Packed-tail signer body loop at instruction 2925, 6 words. -/
def seg2925Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer body setup at instruction 2931, 5 words. -/
def seg2931Packed : List (BitVec 32) := [
  0x00001337#32, 0x66830313#32, 0x000043b7#32, 0x7b038393#32, 0x0bc00b13#32
]

/-- Packed-tail signer body loop at instruction 2936, 6 words. -/
def seg2936Packed : List (BitVec 32) := [
  0x00036183#32, 0x0033a023#32, 0x00430313#32, 0x00438393#32, 0xfffb0b13#32, 0xfe0b16e3#32
]

/-- Packed-tail signer tail and HALT at instruction 2942, 25 words. -/
def seg2942Packed : List (BitVec 32) := [
  0x00001e37#32, 0x900e0e13#32, 0x000e6583#32, 0x358e6603#32, 0x6b0e6683#32, 0x00001e37#32, 0x308e0e13#32, 0x000e6703#32,
  0x358e6783#32, 0x00005eb7#32, 0xaa0e8e93#32, 0x01661813#32, 0x00b86833#32, 0x02c69913#32, 0x01286833#32, 0x0146d893#32,
  0x00271913#32, 0x0128e8b3#32, 0x01879913#32, 0x0128e8b3#32, 0x010eb023#32, 0x011eb423#32, 0x00100293#32, 0x00000513#32,
  0x00000073#32
]
end SigGolfCandidate.Sign
