-- Generated by gen_sign.py. Do not edit.
import SigGolfCandidate.Sign.PackC0
import SigGolfCandidate.Sign.PackC1
import SigGolfCandidate.Sign.PackC2
import SigGolfCandidate.Sign.PackC3
import SigGolfCandidate.Sign.PackC4
import SigGolfCandidate.Sign.PackC5

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-- The whole pack (instructions 718 .. 1735). -/
theorem pack_run : PackStep 718 1736 0 490 1018 :=
  (((((packStep_718.comp packStep_934 (by norm_num)).comp packStep_1130 (by norm_num)).comp packStep_1326 (by norm_num)).comp packStep_1522 (by norm_num)).comp packStep_1714 (by norm_num))

-- The final HALT.
sym_block blk1736 := symRun { noAlias := true } seg1736 (pcOf 1736) 4

end SigGolfCandidate.Sign
