-- Generated by gen_sign.py. Do not edit.
import SigGolfCandidate.Sign.PackStep

namespace SigGolfCandidate.Sign
open SigGolfCandidate.Legacy SigGolfCandidate.Legacy.Riscv RiscvZkvm.Rv64 SigGolfCandidate.Rv

/-! Pack chunk 4: instructions 1522 .. 1713, signature dwords 394 .. 487. -/

set_option maxRecDepth 100000

sym_block blk1522 := symRun { noAlias := true } seg1522 (pcOf 1522) 193

kernel_theorem blk1522_pc : ∀ t : MachineState, (blk1522.res.toState t).pc = pcOf 1714
kernel_theorem blk1522_addrs : ∀ t : MachineState, blk1522.res.st.mem.map (fun p => p.1.eval t) =
    ((List.range 94).map (fun i => BitVec.ofNat 64 (packD + 8 * 394 + 8 * i))).reverse
kernel_theorem blk1522_words : ∀ t : MachineState,
    (blk1522.res.toState t).readWords (BitVec.ofNat 64 (packD + 8 * 394)) 94 =
      ((packTab.drop 394).take 94).map (packDW t)

theorem packStep_1522 : PackStep 1522 1714 394 94 192 :=
  packStep_of blk1522 codeAt_1522 rfl blk1522_pc rfl rfl blk1522_words blk1522_addrs (by norm_num)

end SigGolfCandidate.Sign
